"*.text.scrollHorizontal:			WhenNeeded",
"*.text.scrollVertical:				WhenNeeded",
"*.text.displayCaret:				False",
"*.left:						ChainLeft",
"*.right:					ChainRight",
"*.top:						ChainTop",
"*.bottom:					ChainBottom",
"*.internalBorderWidth:				0",
"*.helpshell.rootpane.textform.text.height:	300",
"*.helpshell.rootpane.textform.text.width:	560",
"*.about.label:					About me",
"*.fileinfo.label:				Fileinfo",
"*.grab.label:					Grab color",
"*.reverse.label:				Reverse",
"*.defaults.label:				Default colors",
"*.quit.label:					Quit",
"*.display.label:				Display format",
"*.comma.label:					C-Style",
"*.realized.label:				Show real server values",
"*.best.label:					Best match",
"*.prev.label:					Previous",
"*.next.label:					Next",
"*.setfore.label:				Set foreground",
"*.setback.label:				Set background",
"*.close.label:					Dismiss",
"*.input.label:					Values from input file",
"*.rgb4.label:					4 bit scaled rgb",
"*.rgb8.label:					8 bit scaled rgb",
"*.rgb12.label:					12 bit scaled rgb",
"*.rgb16.label:					16 bit scaled rgb",
"*.rgbi.label:					Float scaled rgb",
"*.ciexyz.label:					CIEXYZ",
"*.cieuvy.label:					CIEuvY",
"*.ciexyy.label:					CIExyY",
"*.cielab.label:					CIELab",
"*.cieluv.label:					CIELuv",
"*.tekhvc.label:					TekHVC (converts slowly)",
"*.srgb4.label:					4 bit truncated rgb",
"*.srgb8.label:					8 bit truncated rgb",
"*.srgb12.label:					12 bit truncated rgb",
"*.srgb16.label:					16 bit truncated rgb",
"*.helpshell.title:				About Xcolorsel",
