.\"	$Id: afack.man,v 1.7 1997/02/15 12:45:29 malc Exp $
.TH AFACK %SEC1%
.SH NAME
Afack \- alias file checker for af.
.SH SYNOPSIS
.B afack
[
.B -v
] file ..
.SH DESCRIPTION
.I Afack\^
reports erroneous alias lines in each file to standard error.
If there are no errors,
.I Afack
exits silently.
.SH OPTIONS
If the
.B -v
(verbose) flag is specified,
the validated and canonicalised
aliases are also written to standard output in human-readable form.
.SH AUTHOR
Malc Arnold.
.SH SEE ALSO
af(%SEC1%), afalias(%SEC5%), ``The Af Reference Manual''.
