#
# This Makefile is specially tailored for use on a Deckstation 3100
# (used by H.J. at WSU).  Everyone else should probably leave it alone.
#
XCFLAGS=-DPREFIX=\"/local/i386-linux/bin/\" # -DUSE_VARARGS
# Define DLL if you are building tools for dynamic linking libraries.
#CFLAGS = -g -O -Wall
CC=gcc
HOST_CC=gcc
CFLAGS = -O3 -Wall -I. 
CFLAGS = -O3 -Wall -I. $(XCFLAGS)
LIBS=-liberty -shlib

#MISC_OBJS=system.o

BINDIR=/local/i386-linux/bin

include Makerules
