.TH "ObjPak" 3 "Oct 30, 1996"
.SH CLASS
.B
ObjPak
.SH SUPERCLASS
Object
.SH DESCRIPTION
.PP

.B
ObjPak 
is the superclass of all classes in ObjectPak.  Methods implemented here are inherited by all ObjectPak classes.
.SH METHOD TYPES
.PP
.B
Class Methods
.RS 3
objpakRevision
.br
.RE
.PP
.B
Copying
.RS 3
deepCopy
.br
.RE
.PP
.B
Comparing
.RS 3
isEqual:
.br
notEqual:
.br
compare:
.br
.RE
.PP
.B
Printing
.RS 3
printToFile:
.br
printOn:
.br
printToStream:
.br
printForDebugger:
.br
.RE
.SH METHODS
.PP
.B
objpakRevision
.RS 1
+ (STR)
.B
objpakRevision
.RE
.PP

Returns the version string of the ObjectPak being used.
.PP
.B
deepCopy
.RS 1
-
.B
deepCopy
.RE
.PP

Should return a 
.I
deep copy 
of the object.  Usually this means a copy that doesn\&'t share objects with the original object and that can be 
.B
free
\&'ed independently.  By default, sends 
.B
copy 
to 
.B
super.
.PP
.B
isEqual:
.RS 1
- (BOOL)
.B
isEqual:
.I
anObject
.RE
.PP

Should return YES if the receiver is equal to 
.I
anObject.
.PP
.B
notEqual:
.RS 1
- (BOOL)
.B
notEqual:
.I
anObject
.RE
.PP

Whether 
.B
isEqual: 
returns NO.
.PP
.B
compare:
.RS 1
- (int)
.B
compare:
.I
anObject
.RE
.PP

Should return an integer which is less than, equal to, or greater than zero, if the receiver is less than, equal to, or greater than 
.I
anObject.  
The return value is called the method\&'s comparison value.
.PP
.B
printToFile:
.RS 1
-
.B
printToFile:
(FILE *)
.I
aFile
.RE
.PP

Should print the contents of the object to 
.I
aFile.  
Should return the receiver.
.PP
.B
printOn:
.RS 1
-
.B
printOn:
(IOD)
.I
anIOD
.RE
.PP

For compatibility with the Stepstone runtime.  Invokes 
.B
printToFile: 
and returns the receiver.
.PP
.B
printToStream:
.RS 1
-
.B
printToStream:
(NXStream *)
.I
aStream
.RE
.PP

For compatibility with the NextStep runtime.  Invokes 
.B
printToFile: 
and returns the receiver.
.PP
.B
printForDebugger:
.RS 1
- (void)
.B
printForDebugger:
(NXStream *)
.I
aStream
.RE
.PP

To support the enhanced GNU debugger under NextStep.
