.TH MKTIME 1 "15 March 1994" "Version 1.0"
.SH NAME
.B mktime
\- create time information file
.SH SYNOPSIS
.B mktime
[
.B \-o
.I output_file_name
]
[
.I filename
]
.SH DESCRIPTION
.B mktime
is used to create binary file,
describing time information
for
.BR setlocale (3)
and
.BR localeinfo (3).
.I filename
is the name of input file.
If none given,
.I stdin
used.
.SH OPTIONS
.TP
.RI \-o\  output_file_name
Write the output on
.IR output_file_name ;
otherwise,
write the output on a file
named LC_TIME.
.SH INPUT FILE FORMAT
Empty lines and lines beginning with # are ignored.
The backslash character,
\\,
is used for continuation.
No characters are permitted after it.
The following statements are recognized:
.sp
.B codeset
.I codename
.sp
.RS
.I Codename
is the name of codeset. This statement is required.
.RE
.sp
Rest of the lines
taken as contents of structure
.IR time_info .
.SH EXAMPLE
.RS
.nf
codeset dummy

Sun
Mon
Tue
Wed
Thu
Fri
Sat

Sunday
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday

Jan
Feb
Mar
Apr
May
Jun
Jul
Aug
Sep
Oct
Nov
Dec

January
February
March
April
May
June
July
August
September
October
November
December

AM
PM

%a %b %d %H:%M:%S %Y
%d/%m/%y
%H:%M:%S

GMT
+0000
.fi
.RE
.SH BUGS
None are know at the moment.
If you find any,
feel free to fix.
.SH AUTHOR
Nickolay Saukh - <nms@ussr.EU.net>
.SH FILES
/usr/lib/locale/\fIlocale\fR/LC_TIME
\- LC_TIME database for
.br
/usr/include/localeinfo.h
.I locale
.SH SEE ALSO
.BR setlocale (3),
.BR localeconv (3),
.BR mkcollate (1),
.BR mkctype (1),
.BR mkmonetary (1),
.BR mknumeric (1),
.BR mkresponse (1)
