.\"
.\" Traduzione in italiano di Giovanni Bortolozzo <borto@dei.unipd.it>
.\" Agosto 1996
.\"
.\" " for hilit19
.TH CHGRP 1L "GNU File Utilities" "FSF" "" -*- nroff -*-
.SH NOME
chgrp \- cambia il gruppo proprietario dei file
.SH SINTASSI
.B chgrp
[\-Rcfv] [\-\-recursive] [\-\-changes]
[\-\-silent] [\-\-quiet] [\-\-verbose] [\-\-help] [\-\-version] gruppo file...
.SH DESCRIZIONE
Questa pagina di manuale descrive la versione GNU di
.BR chgrp .
.B chgrp
imposta il gruppo proprietario di ognuno dei file forniti al gruppo dato,
il quale può essere sia un nome di gruppo che un group ID numerico.
.SS OPZIONI
.TP
.I "\-c, \-\-changes"
Mostra le informazioni solo sui file la cui proprietà viene cambiata.
.TP
.I "\-f, \-\-silent, \-\-quiet"
Non mostra messaggi d'errore sui file la cui proprietà non può essere 
cambiata.
.TP
.I "\-v, \-\-verbose"
Mostra le informazioni sui cambi di proprietà.
.TP
.I "\-R, \-\-recursive"
Cambia ricorsivamente la proprietà delle directory e dei file contenuti.
.TP
.I "\-\-help"
Stampa un messaggio di aiuto sullo standard output ed esce (con successo).
.TP
.I "\-\-version"
Stampa informazioni sulla versione sullo standard output ed esce (con
successo).

