.\"
.\" Traduzione in italiano di Giovanni Bortolozzo <borto@dei.unipd.it>
.\" Agosto 1996
.\"
.\" " for hilit19
.TH GZEXE 1
.SH NOME
gzexe \- comprime i file eseguibili sul posto
.SH SINTASSI
.B gzexe
[ nome ...  ]
.SH DESCRIZIONE
L'utility 
.I  gzexe
permette di comprimere gli eseguibili sul posto, far sì che questi siano
automaticamente decompressi ed eseguiti quando li si lancia (penalizzando
le prestazioni). Per esempio se si esegue ``gzexe /bin/cat'' saranno creati
i due file seguenti:
.nf
.br
    -r-xr-xr-x  1 root  bin   9644 Feb 11 11:16 /bin/cat
    -r-xr-xr-x  1 bin   bin  24576 Nov 23 13:21 /bin/cat~
.fi
/bin/cat~ è il file originale e /bin/cat è il file eseguibile 
auto-scompattante. Il file /bin/cat~ può essere rimosso una volta che sì è
sicuri che /bin/cat funzioni propriamente.
.PP
Questa utility è molto utile su sistemi con dischi molto piccoli.
.SH OPZIONI
.TP
.B \-d
Decomprime gli eseguibili invece di comprimerli.
.SH "VEDERE ANCHE"
gzip(1), znew(1), zmore(1), zcmp(1), zforce(1)
.SH AVVERTIMENTI
L'eseguibile compresso è uno shell script. Ciò potrebbe creare alcuni buchi 
di sicurezza. In particolare, gli eseguibili compressi si rifanno alla 
variabile d'ambiente PATH per trovare
.I gzip
e qualche altra utility
.I (tail, chmod, ln, sleep).
.SH "PROBLEMI"
.I gzexe 
prova a conservare gli attributi originali del file sul file compresso, ma
in qualche caso dovranno essere sistemati a mano, usando 
.I chmod
o
.IR chown .
