'\" t
.\" Note: this must be run through tbl before nroff.
.\" The magic cookie on the first line triggers this under some man program
.\"
.\" Traduzione in italiano di Giovanni Bortolozzo <borto@dei.unipd.it>
.\" Agosto 1996
.\"
.\" " for hilit19
.TH MKMANIFEST 1 local
.SH NOME
mkmanifest \- crea uno shell script per ripristinare il nomi di file Unix
.SH SINTASSI
.B mkmanifest
[ lista_di_file ]
.SH DESCRIZIONE
.I Mkmanifest
crea uno shell script che sarà d'aiuto nel rispristino dei nomi di file Unix
che sono stati ``rovinati'' dalle restrizioni MSDOS sui nomi di file. I nomi 
di file MSDOS sono ristretti a nomi di 8 caratteri, estensioni di 3 caratteri,
solo lettere minuscole, niente nomi di dispositivi e nessun carattere illegale.
.PP
Il programma mkmanifest è compatibile con i metodi usati da
.IR pcomm ", " arc 
e
.I mtools
per far si che i nomi di file Unix si adattino nelle restrizioni MSDOS.
.SH ESEMPIO
Si vogliono copiare i seguenti file Unix in un dischetto MSDOS (usando il
comando
.IR mcopy ).
.PP
.in +0.5i
.nf
very_long_name
2.many.dots
illegal:
good.c
prn.dev
Capital
.fi
.in
.PP
.I Mcopy
convertirà i nomi in:
.PP
.in +0.5i
.nf
very_lon
2xmany.dot
illegalx
good.c
xprn.dev
capital
.fi
.in
.PP
Il comando:
.PP
mkmanifest very_long_name 2.many.dots illegal: good.c prn.dev Capital >
manifest
.PP
produrrà il seguente output:
.PP
.in +0.5i
.nf
mv very_lon very_long_name
mv 2xmany.dot 2.many.dots
mv illegalx illegal:
mv xprn.dev prn.dev
mv capital Capital
.fi
.in
.PP
Si noti che "good.c" non necessita di alcuna conversione, e perciò non
compare nell'output.
.PP
Supposto di aver copiato questi file da un dischetto in un sistema Unix,
si vuole che i file abbiano i loro nomi originali. Se il file "manifest" 
(l'output catturato sopra) è assieme con questi file, può essere usato
per convertire i nomi dei file.
.SH PROBLEMI
I nomi corti generati da 
.B mkmanifest
seguono la vecchia convenzione (degli mtools-2.0.7) e non quella di 
Windows 95 e degli mtools-3.0.
.SH VEDERE ANCHE
arc(1), pcomm(1), mtools(1)
