'\" t
.\" Note: this must be run through tbl before nroff.
.\" The magic cookie on the first line triggers this under some man program
.\"
.\" Traduzione in italiano di Giovanni Bortolozzo <borto@dei.unipd.it>
.\" Agosto 1996
.\"
.\" " for hilit19
.TH MLABEL 1 local
.SH NOME
mlabel \- crea l'etichetta su un disco MSDOS
.SH SINTASSI
.B mlabel
[
.B -v
] drive: [
.I nuova_etichetta
]
.SH DESCRIZIONE
.B Mlabel
mostra, se è presente, l'etichetta corrente del disco. Se non è data la
.IR nuova_etichetta ,
e non sono settate neppure le opzioni 
.B c
o
.BR s ,
chiede all'utente una nuova etichetta. Per cancellare un'etichetta esistente,
si prema return al prompt. 
.PP
.B Mlabel
accetta le seguenti opzioni:
.TP
.B v
Verbose mode.  Mostra la nuova etichetta se l'etichetta fornita non è valida.
.TP
.B c
Cancella un'etichetta esistente, senza chiedere all'utente.
.TP
.B s
Mostra l'etichetta esistente, senza chiedere all'utente.
.PP
Sono prese particolari attenzioni nel creare una etichetta MSDOS valida. Se è
specificata un'etichetta non valida,
.B mlabel
la cambierà (e mostrerà la nuova etichetta se è settato il verbose mode).
.PP
.B Mlabel
restituisce 0 in caso di successo o 1 in caso di errore.
.SH VEDERE ANCHE
mformat(1)
