'\" t
.\" Note: this must be run through tbl before nroff.
.\" The magic cookie on the first line triggers this under some man program
.\"
.\" Traduzione in italiano di Giovanni Bortolozzo <borto@dei.unipd.it>
.\" Agosto 1996
.\"
.\" " for hilit19
.TH MMOVE 1 local
.SH NOME
mmove \- sposta o rinomina un file o una subdirectory MSDOS esistente
.SH SINTASSI
.B mmove
[
.B -voOsSrRA
] file_sorgente file_destinazione
.PP
.B mmove
[
.B -voOsSrRA
] file_sorgente [ lista_di_file... ] directory_destinazione
.PP
.SH DESCRIZIONE
.I Mmove
sposta o rinomina un file o una subdirectory MSDOS esistente.
.PP
.I Mmove
accetta la seguente opzione:
.TP
.B v
Verbose mode.  Mostra il nuovo nome di file se il nome fornito non è valido.
.PP
Inoltre accetta le opzioni per il trattamento delle collisioni descritte
nella pagina di guida di mtools.
.PP
I nomi delle subdirectory MSDOS sono accettati sia con il separatore '/' che
con '\e'. L'uso di '\e' o di wildcard potrebbe richiedere che i nomi siano 
racchiusi tra virgolette per proteggerli dalla shell.
Diversamente dalla versione MSDOS di MOVE,
.I mmove
è in grado di spostare subdirectory.
.SH VEDERE ANCHE
mren(1) mtools(1)
