'\" t
.\" Note: this must be run through tbl before nroff.
.\" The magic cookie on the first line triggers this under some man program
.\"
.\" Traduzione in italiano di Giovanni Bortolozzo <borto@dei.unipd.it>
.\" Agosto 1996
.\"
.\" " for hilit19
.TH MWRITE 1 local
.SH NOME
mwrite \- scrive (copia) a basso livello un file Unix in MSDOS
.SH SINTASSI
.B mwrite
[
.B -tnvmoOsSrRA
] file_unix file_msdos
.PP
.B mwrite
[
.B -tnvmoOsSrRA
] file_unix [ lista_file_unix... ] directory_msdos
.SH DESCRIZIONE
Questo comando è obsoleto, ed è fornito solo per ragioni di compatibilità
con i vecchi script. Si usi invece mcopy.
.SH VEDERE ANCHE
mcopy(1), mtools(1)
