.\" Traduzione Augusto Leonardi <augusto@comune.modena.it>
.\" luglio 1996
.TH RMDIR 1L "GNU File Utilities" "FSF" \" -*- nroff -*-
.SH NOME
rmdir \- rimuove directory vuote
.SH SINTASSI
.B rmdir
[\-p] [\-\-parents] [\-\-help] [\-\-version] dir...
.SH DESCRIZIONE
Questa pagina di manuale
documenta la versione GNU di
.BR rmdir .
.B rmdir
rimuove ogni directory vuota indicata. Se un qualsiasi argomento, non
opzione, non si riferisce a una directory vuota esistente, si ha un errore.
.SS OPZIONI
.TP
.I "\-p, \-\-parents"
Rimuove ogni directory genitrice che sia esplicitamente menzionata in un
argomento, se questa diventa vuota dopo che file in argomento è rimosso.
.TP
.I "\-\-help"
Stampa una indicazione di uso sullo standard output e termina con successo.
.TP
.I "\-\-version"
Stampa le informazioni sulla versione sullo standard output e termina
con successo.
