.\" @(#)tar.1 1.11.1 93/19/22 PJV;
.\" Traduzione di Tommaso Schiavinotto - tommaso@cln.it
.\" Luglio 1996
.TH TAR 1 "22 September 1993"
.SH NOME
tar \- La versione GNU del programma di utilità tar 
.SH SINTASSI
.B tar
[
.B \-
]
.B A --catenate --concatenate \||\| c --create \||\| d --diff --compare \||\| r --append \||\| t --list \||\| u --update \||\| x -extract --get
[
.B --atime-preserve
]
[
.B -b, --block-size N
]
[
.B -B, --read-full-blocks
]
[
.B -C, --directory DIR
]
[
.B --checkpoint	
]
[
.B -f, --file [NOME_HOST:]F
]
[
.B --force-local	
]
[
.B -F, --info-script F --new-volume-script F
]
[
.B -G, --incremental
]
[
.B -g, --listed-incremental F
]
[
.B -h, --dereference
]
[
.B -i, --ignore-zeros
]
[
.B --ignore-failed-read
]
[
.B -k, --keep-old-files
]
[
.B -K, --starting-file F
]
[
.B -l, --one-file-system
]
[
.B -L, --tape-length N
]
[
.B -m, --modification-time
]
[
.B -M, --multi-volume
]
[
.B -N, --after-date DATA, --newer DATA
]
[
.B -o, --old-archive, --portability
]
[
.B -O, --to-stdout
]
[
.B -p, --same-permissions, --preserve-permissions
]
[
.B -P, --absolute-paths
]
[
.B --preserve	
]
[
.B -R, --record-number
]
[
.B --remove-files
]
[
.B -s, --same-order, --preserve-order
]
[
.B --same-owner
]
[
.B -S, --sparse
]
[
.B -T, --files-from F
]
[
.B --null	
]
[
.B --totals	
]
[
.B -v, --verbose
]
[
.B -V, --label NAME
]
[
.B --version	
]
[
.B -w, --interactive, --confirmation
]
[
.B -W, --verify	
]
[
.B --exclude FILE
]
[
.B -X, --exclude-from FILE
]
[
.B -Z, --compress, --uncompress
]
[
.B -z, --gzip, --ungzip	
]
[
.B --use-compress-program PROG
]
[
.B --block-compress
]
[
.B -[0-7][lmh]	
]
.TP
.I nomefile1 [ nomefile2, ... nomefileN ] 
.TP
.I directory1 [ directory2, ...directoryN ]
.SH DESCRIZIONE
.LP
Questa pagina del manuale documenta la versione GNU di  
.BR tar ,
un programma di archiviazione progettato per immagazzinare ed estrarre file da 
un archivio conosciuto come un 
.IR tarfile .
Un 
.I tarfile 
può  essere  fatto  su  un'unità  a 
nastro magnetico, comunque è anche comune
scrivere un
.IR tarfile
su un file normale. 
Il primo argomento del 
.B tar
deve essere una delle opzioni:
.BR Acdrtux ,
seguita da una qualsiasi funzione facoltativa.
L'argomento finale del 
.B tar
sono i nomi dei file o delle directory che devono essere archiviate. L'uso
del nome di una directory implica sempre che le sotto directory che si trovano
all'interno debbano essere incluse nell'archivo.
.SH "LE FUNZIONI DELLE LETTERE"
.TP
.B Deve essere usata almeno una delle seguenti opzioni:
.TP
.B -A, --catenate, --concatenate
aggiunge i file ad un archivio
.TP
.B -c, --create	
crea un nuovo archivio
.TP
.B -d, --diff, --compare
trova la differenza tra l'archivio e il file system 
.TP
.B --delete		
elimina dall'archivio  (da  non  usare  sui  nastri magnetici!)
.TP
.B -r, --append		
aggiunge i file alla fine di un archivio
.TP
.B -t, --list		
elenca il contenuto di un archivio
.TP
.B -u, --update		
aggiunge solamente i file che sono più recenti della copia nell'archivio
.TP
.B -x, --extract, --get		
estrae i file da un archivio
.SH "ALTRE OPZIONI"
.TP
.B --atime-preserve	
non cambia i tempi di accesso dei file che sono stati estratti
.TP
.B -b, --block-size N	
il blocco assume la dimensione di Nx512 byte (default N=20)
.TP
.B -B, --read-full-blocks	
reblocca appena è stato letto (per i pipe in lettura in 4.2BSD) 
.TP 
.B -C, --directory DIR	
cambia la directory in DIR 
.TP 
.B --checkpoint		
stampa i nomi delle directory mentre legge l'archivio
.TP
.B -f, --file [NOME_HOST:]F	
usa il file di archivo o dispostivo F (default /dev/rmt0)
.TP
.B --force-local		
il file di archivo è locale anche se contiene un 'due punti' (:)
.TP 
.B -F, --info-script F --new-volume-script F 
esegue lo script alla fine di ogni nastro (implica -M)
.TP
.B -G, --incremental	
crea/elenca/estrae un backup incrementale nel vecchio formato GNU 
.TP
.B -g, --listed-incremental F 
crea/elenca/estrae un backup incrementale nel nuovo formato GNU
.TP 
.B -h, --dereference	
non scarica link simbolici ma i file ai quali sono collegati
.TP
.B -i, --ignore-zeros	
ignora i blocchi formati da soli zero nell'archivio (normalmente significa EOF)
.TP
.B --ignore-failed-read	
non esce con uno stato diverso da zero sui file illeggibili
.TP
.B -k, --keep-old-files	
mantieni i file esistenti; non sovrascriverli dall'archivio
.TP
.B -K, --starting-file F	
inizia dal file F nell'archivio
.TP
.B -l, --one-file-system	
resta nel file system locale durante la creazione di un archivio
.TP
.B -L, --tape-length N	
cambia il nastro dopo aver scritto N*1024 byte
.TP
.B -m, --modification-time	
non estrae il tempo di modifica del file
.TP
.B -M, --multi-volume	
crea/elenca/estrae archivi su più volumi
.TP
.B -N, --after-date DATA, --newer DATA	
archivia solamente i file più recenti della DATA
.TP
.B -o, --old-archive, --portability	
scrive un archivio nel format V7, invece che nel formato ANSI
.TP
.B -O, --to-stdout		
estrae i file  sull'uscita  standard  (standard output)
.TP
.B -p, --same-permissions, --preserve-permissions 
estrae tutte le informazioni relative ai permessi
.TP
.B -P, --absolute-paths	
non toglie i '/' all'inizio del nome dei file
.TP
.B --preserve		
come -p -s
.TP
.B -R, --record-number	
mostra il numero dei record all'interno dell'archivio con ogni messaggio
.TP 
.B --remove-files		
elimina i file dopo averli aggiunti all'archivio
.TP
.B -s, --same-order, --preserve-order	
l'elenco con i nomi da estrarre è ordinato per l'archivio corrispondente
.TP
.B --same-owner		
crea i file estratti con la stessa proprietà
.TP
.B -S, --sparse		
gestisci i file frammentati efficientemente 
.TP 
.B -T, --files-from F	
prendi i nomi dei file da estrarre o creare dal file F
.TP
.B --null			
-T legge i file che terminano con un null, disabilita -C
.TP
.B --totals		
stampa il numero totale di byte scritti con --create
.TP
.B -v, --verbose		
elenco minuzioso dei file elaborati
.TP
.B -V, --label NOME
crea un archivio con il nome del volume NOME
.TP 
.B --version		
stampa la versione del programma tar
.TP
.B -w, --interactive, --confirmation	
chiede la conferma per ogni azione
.TP
.B -W, --verify		
prova a fare una verifica dell'archivio dopo ogni scrittura
.TP
.B --exclude FILE		
esclude il file FILE
.TP
.B -X, --exclude-from FILE	
esclude i file elencati in FILE
.TP
.B -Z, --compress, --uncompress      	
filtra l'archivio attraverso compress
.TP 
.B -z, --gzip, --ungzip		
filtra l'archivio attraverso gzip 
.TP
.B --use-compress-program PROG
filtra l'archivio attraverso PROG (che deve accettare -d)
.TP
.B --block-compress	
blocca l'uscita del programma di compressione per i nastri
.TP
.B -[0-7][lmh]		
specifica l'unità e la densità
