\input texinfo
@c -*-texinfo-*-
@c %**start of header
@setfilename guile-programmer.info
@settitle Guile Programmers Manual
@c %**end of header

@c @include version.texi

@c I combine the type and variable indices
@syncodeindex vr tp

@c @iftex
@c @cropmarks
@c @end iftex

@dircategory Guile -- GNU extension language
@direntry
* guile-programmer: (guile-programmer).         The Guile Programmer's Manual.
@end direntry

@setchapternewpage on

@ifinfo
Guile Programmer's Manual
Copyright (C) 1996 Cygnus Support

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).
@end ignore

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the Free Software Foundation.
@end ifinfo

@titlepage
@sp 10
@comment The title is printed in a large font.
@title Guile Programmer's Manual
@subtitle For use with Guile @value{VERSION}
@subtitle Last updated @value{UPDATED}
@author Mark Galassi
@author Los Alamos National Laboratory
@author @code{rosalia@@nis.lanl.gov}

@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@vskip 0pt plus 1filll
Copyright @copyright{} 1996 Cygnus Support

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by Free Software Foundation.
@end titlepage

@c @smallbook
@finalout
@headings double

@ifinfo
@node Top, What goes in this manual, (dir), (dir)
@top The Guile Programmers Manual
@end ifinfo

@menu
* What goes in this manual::    
* Guile Tk reference::          
* Guile Posix reference::       
* Guile threads reference::     
* Libguile -- high level interface reference::  
* Libguile -- low level interface reference::  
* Where to find more Guile/Scheme resources::  
* Concept Index::               
* Procedure Index::             
* Types Variables Constants::  

 --- The Detailed Node Listing ---

What goes in this manual

* What does NOT go in this manual::  
* Other notes::                 

Guile Tk reference

* Guile Tk reference


Guile Posix reference

* Posix preliminaries::         
* I/O extensions to standard Scheme::  
* Posix system and library calls::  
* UNIX system and library calls::  

Guile threads reference

* Low level thread primitives::  
* Higher level thread procedures::  

Libguile -- high level interface reference

* gh preliminaries::            
* Data types and constants defined by gh::  
* Starting and controlling the interpreter::  
* Error messages::              
* Executing Scheme code::       
* Defining new Scheme procedures in C::  
* Converting data between C and Scheme::  
* Type predicates::             
* Equality predicates::         
* Memory allocation and garbage collection::  
* Calling Scheme procedures from C::  
* Mixing gh and scm APIs::      

Converting data between C and Scheme

* C to Scheme::                 
* Scheme to C::                 

Libguile -- low level interface reference

* Organization and paradigms::  
* Data types::                  
* Starting the interpreter::    

Where to find more Guile/Scheme resources

* Online resources::            
* Books and papers::            
* Other documents shipped with Guile::  
@end menu

@include what-goes.texi
@c @include tk.texi
@include tk-new.texi
@include goonix.texi
@include threads.texi
@c @include applet-ref.texi
@include gh-ref.texi
@include scm-ref.texi
@include more-resources.texi

@include ci.texi
@include pi.texi
@include ti.texi

@c @summarycontents
@contents

@bye
