@node Libguile -- low level interface reference
@chapter Libguile -- low level interface reference
@cindex libguile
@cindex scm
@cindex scm - reference manual

This chapter documents the lower-level interface to libguile, also
called the @code{scm_} interface.  It has evolved from Aubrey Jaffer's
SCM interpreter (@pxref{Overview, SCM: a portable scheme interpreter,
Overview, scm, SCM: a portable scheme interpreter}), but has now
divered, so the Guile API has to be documented separately.

The place for the @code{scm_} interface is when the @code{gh_} interface
is not sufficient bla...


@menu
* Organization and paradigms::  
* Data types::                  
* Starting the interpreter::    
@end menu

@node Organization and paradigms
@section Organization and paradigms

@node Data types
@section Data types

@node Starting the interpreter
@section Starting the interpreter

[I just put in one function to sort get it going and get something in
the function index.]

@deftypefun {static int} scm_boot_guile (SCM_STACKITEM *base, char **result, int argc, char **argv, FILE *in, FILE *out, FILE *err, void (*init_func)(), char *boot_cmd)
Starts up a Scheme interpterter ... bla ... meaning of arguments ... all
the work is really done by scm_boot_guile_1()...
@end deftypefun
