#! /bin/sh

set -e

if [ ! -d /var/log/net-acct ]; then
  mkdir /var/log/net-acct
  chmod 755 /var/log/net-acct
  chown root.root /var/log/net-acct
fi

if [ "$1" = "configure" ]
then

  update-rc.d net-acct defaults >/dev/null

cat<<EOT

Don't forget to make changes to /etc/naccttab and read the documentation
and examples in /usr/doc/net-acct/ and /usr/dec/examples/net-acct/.

EOT

  # restarting daemon
  #
  /etc/init.d/net-acct start
fi

exit 0
