.\"  This page Copyright (C) 1996 Christian Schwarz, C.Schwarz@monet.m.isar.de
.\"  Freely distributable under the terms of the GPL
.TH ANACRONTAB 5 "22 August 1996"
.SH NAME
anacrontab \- tables for driving anacron
.SH DESCRIPTION
The
.I anacrontab
file contains instructions for the anacron(8) program about how often
specific jobs should be executed. It also contains information about
environment variables.
.PP
Blank lines, leading spaces, and tabs are ignored.
Text following a hash-sign (#) up to the end-of-line character are
also ignored.
.PP
An  active line in the anacrontab will be either an environment
setting or an anacron command.  An environment setting  is  of
the form,
.PP
    VAR=VALUE
.PP
where spaces around the equal-sign (=) are not allowed.
.PP
Every other non-empty line must have the following format:
.PP
    period delay jobname job
.PP
The
.I period
is specified in days, the
.I delay
in minutes. The
.I jobname
is used for the temporary files, that tell anacron when a job was run
the last time.
The
.I job
parameter itself tells anacron which command to run.
.SH "SEE ALSO"
anacron(8)
.SH AUTHOR
.nf
Christian Schwarz <C.Schwarz@monet.m.isar.de>
