echo Cleaning up V hierarchy
del draw\*.bak
del drawex\*.bak
del srcwin\*.bak
del bmp2vbm\*.bak
del bmp2vbm\*.mk1
del bmp2vbm\*.lk1
del bccide\*.~de
del bccide\*.dsw
del bccide\*.csm
del bccide\*.rws
del bccide\*.res
del bccide\*.obr
del bccide\*.tr
del bccide\*.mrt
del bccide\*.mbt
del bccide\*.r$p
echo Cleaning Watcom
del watcom\win32\*.obj
del watcom\win32\*.bak
del watcom\win32\*.map
del watcom\win32\*.mk1
del watcom\win32\*.lk1
del watcom\win32\*.lib
del watcom\win32\*.sym
del watcom\win32\*.exe
del watcom\win32db\*.obj
del watcom\win32db\*.bak
del watcom\win32db\*.map
del watcom\win32db\*.mk1
del watcom\win32db\*.lk1
del watcom\win32db\*.lib
del watcom\win32db\*.exe
del watcom\win32db\*.sym
del watcom\win16\*.obj
del watcom\win16\*.bak
del watcom\win16\*.map
del watcom\win16\*.mk1
del watcom\win16\*.lk1
del watcom\win16\*.lib
del watcom\win16\*.exe
del watcom\win16db\*.sym
del watcom\win16db\*.obj
del watcom\win16db\*.bak
del watcom\win16db\*.map
del watcom\win16db\*.mk1
del watcom\win16db\*.lk1
del watcom\win16db\*.lib
del watcom\win16db\*.exe
echo cleaning regular files.
del includew\v\*.bak
del examp\*.bak
del tutor\*.bak
del test\*.bak
del iconed\*.bak
rem
del lib\win\*.lib
del bin\win\*.exe
del obj\win16\*.obj
del obj\win16\*.res
del obj\win32\*.obj
del obj\win32\*.res
del obj\win32db\*.obj
del obj\win32db\*.res
rem
mkdir obj\win32db
mkdir obj\win32
mkdir obj\win16
mkdir bin\win
mkdir lib\win
touch bin\win
touch lib\win
touch obj\win16\ThisIs
touch obj\win32\ThisIs
touch obj\win32db\ThisIs
