#! /bin/sh

###############################################################################
###									    ###
###		GNU Interactive Tools 4.3.16 recursive grep script          ###
###		Copyright (C) 1994, 1996 Free Software Foundation, Inc.     ###
###		    Written by Tudor Hulubei and Andrei Pitis.              ###
###									    ###
###############################################################################

grep="grep"
name=`basename "$0"`

# Start grep/egrep/fgrep depending on argv[0]

case $name in
gitrgrep)	grep="grep";;
gitregrep)	grep="egrep";;
gitrfgrep)	grep="fgrep";;
esac

find . -follow -type d -exec gitxgrep '{}' $grep "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" ';'
