\input texinfo        @c                    -*- Texinfo -*-
@setfilename xconq-x11.info
@settitle Playing and Designing with X11 Xconq

@finalout
@setchapternewpage off
@iftex
@raggedbottom
@global@parindent=0pt
@end iftex

@titlepage
@title X11 Xconq Interface
@subtitle Playing and Designing with X11 Xconq
@subtitle April 1996
@author Stanley T. Shebs

@page

@vskip 0pt plus 1filll
Copyright @copyright{} 1995, 1996 Stanley T. Shebs

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided also that
the entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions.
@end titlepage

@ifinfo
@format
START-INFO-DIR-ENTRY
* X11 Xconq: (xconq-x11.info).       Playing and Designing with X11 Xconq
END-INFO-DIR-ENTRY
@end format

Copyright (c) 1995, 1996 Stanley T. Shebs

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided also that
the entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions.

@node Top
@top X11 Xconq

@display
@strong{Stanley T. Shebs}
April, 1996
@end display

This document is X11-specific info about Xconq.

@end ifinfo

@chapter Playing

@c Include sections from the main manual.

@include x11-sect.texi

@chapter Designing

@c Include sections from the main manual.

@include x11-dsect.texi

@section Beyond Designer Mode

The designer popup and privileges just scratch the surface of what you
can do with @i{Xconq}.
You can define your own complete games with @i{Xconq}
using its Game Design Language (GDL), a declarative Lisp-like language
with many more capabilities than could be provided interactively.
The @i{Xconq} manual chapter ``Designing Games with @i{Xconq}'' goes into
much more detail about @i{Xconq}'s programmability,
and the chapter ``Reference Manual''
is the complete description of GDL's abilities.

@page
@w{ }

@contents
@c second page break makes sure right-left page alignment works right
@c with a one-page toc, even though we don't have setchapternewpage odd.
@page
@w{ }

@bye
