.\" (C) 1993 Peter Orbaek <poe@daimi.aau.dk>
.\" this man-page is freely distributable
.TH MESG 1 "30 Jul 93" "Linux 0.99" "Linux Programmer's Manual"
.SH NAME
megs \- allow/disallow others to write to ones terminal
.SH SYNOPSIS
.B mesg [ n | y ]
.SH DESCRIPTION
Without argument
.B mesg
prints 'mesg is y' if others are allowed to write to ones terminal with,
for example,
.BR write (1).
It prints 'mesg is n' otherwise.

The command
.B mesg y
changes the status of the current tty to allow others to write to it.
Likewise, the command 
.B mesg n
changes the status of the current tty to disallow other from writing to
one.

.SH FILES
.I /dev/tty
.SH "SEE ALSO"
.BR chmod (1),
.BR tty(1).
.SH AUTHOR
Peter Orbaek <poe@daimi.aau.dk>

