.\" Copyright 1994 Peter Orbaek
.\" May be distributed under the GNU General Public License
.TH WALL 1 "10 May 1994" "Linux 1.1.9" "Linux Programmer's Manual"
.SH NAME
wall \- broadcast a message to all users logged in
.SH SYNOPSIS
.BR wall " [" message "]"
.SH DESCRIPTION
.B wall
writes a message to all users currently logged in, just like 
.IR write (1)
writes a message to a number of specific users.

If no message is given on the commandline, 
.I wall
will expect a message on standard input. 
.I Wall
uses
.I /var/run/utmp
to decide which users are logged in and where.
.SH FILES
.I /var/run/utmp
.SH "SEE ALSO"
.BR write (1),
.BR mesg (1),
.BR talk (1)
.SH AUTHOR
Peter Orbaek (poe@daimi.aau.dk)
.SH NOTE
Deprecated, use the GNU version.

