.\" Copyright 1994 Peter Orbaek
.\" May be distributed under the GNU General Public License
.TH WHO 1 "10 May 1994" "Linux 1.1.9" "Linux Programmer's Manual"
.SH NAME
who \- see who are logged in
.SH SYNOPSIS
.B who
.br
.B who am i
.SH DESCRIPTION
.B who
prints a list of all users logged in, according to the data in
.I /var/run/utmp.

The
.B "who am i"
variant is for schizophrenic people, who after 
.IR su 'ing
a lot forget their real identity. This command looks up a username
in the
.I /var/run/utmp
file according to the tty line where the command is given.
.SH FILES
.I /var/run/utmp
.SH "SEE ALSO"
.BR users(1)
.BR w(1)
.SH AUTHOR
Peter Orbaek (poe@daimi.aau.dk)
.SH NOTE
Deprecated, use the GNU version.

