@ifclear FPKONLY
@node FPK Pascal
@chapter FPK Pascal and GNU Pascal---a comparision
@cindex FPK Pascal
@end ifclear

@ifset FPKONLY
@settitle FPK Pascal and GNU Pascal---a comparision
@node Top
@chapter FPK Pascal and GNU Pascal---a comparision
@end ifset

by Florian Klaempfl <fnklaem@@cip.ft.uni-erlangen.de> @*
and Peter Gerwinski <peter.gerwinski@@uni-essen.de> @*
22 September 1996

@example
             FPK Pascal                        GNU Pascal
             ----------                        ----------

aim:         free Borland compatible           free portable
             32-bit Pascal compiler            32-bit Pascal compiler

version:     0.6.4                             2.0 (corresp. to GCC 2.7.2.1)

operating    DOS (DJGPP), OS/2, Linux          DOS (DJGPP), DOS (EMX),
systems:                                       OS/2 (EMX), Win95/NT (CygWin),
                                               arbitrary UNIX systems

written in:  Pascal, TP Syntax                 C
             (compiles itself)

source:      900 kB                            6.4 MB plus source of GCC (27 MB)
                                               (including documentation etc.)
 
language     Borland Pascal 7.0,               ISO 7185, ISO 10206,
standard:    (parts of) Delphi II              (most of) Borland Pascal 7.0

extensions:  function overloading              user-definable operators

home server: http://home.pages.de/~FPK-Pascal/ http://home.pages.de/~GNU-Pascal/
                                               ftp://kampi.hut.fi/jtv/gnu-pascal/

license:     FreeWare (GPL)                    FreeWare (GPL)

author:      Florian Klaempfl, Germany         Jukka Virtanen, Finland
             fnklaem@@cip.ft.uni-erlangen.de    jtv@@hut.fi 
@end example
