@node Support
@chapter Where to get support for GNU Pascal

GPC is free software and comes @strong{without any warranty}.  You have
not paid to get a license to use GNU Pascal so you cannot expect to get
phone support etc. unless a company provides such a service for a fee
(which is allowed and welcome, by the way).

However there is de-facto support in the Internet.  The first address is
the GNU Pascal mailing list, @code{gpc@@hut.fi}.  To join the list,
please send e-mail to

@smallexample
  gpc-request@@hut.fi
@end smallexample

You can also ask the Internet NewsGroups for help.  There is no
specialized NewsGroup for GNU Pascal, so use that one which is most
appropriate for your problem.  When in doubt, we recommend
@code{comp.lang.pascal.misc}.

@strong{Never forget:} Everybody who is working on GNU Pascal and
answering your questions is doing that in his free time without getting
any salery for this.  Please honor our work by contributing yours.  When
somebody has solved your problems in a NewsGroup, watch out for other
people's problems you can help to solve.

