#! /bin/sh -e
###############################################################################
#
# Postinst for mime-support to add useful MIME utility programs
#
###############################################################################


# Support installation of debian packages
install-mime	--install --package=mime-support --content=application/x-debian-package \
		--description="Debian GNU/Linux Package" --nametemplate="%s.deb" \
		--view="/usr/lib/mime/debian-view %s" --needsterminal=t \
		--comment="This entry should probably appear after any entries with test conditions."


# Support basic audio files
install-mime	--install --package=mime-support --content=audio/basic \
		--description="Basic uLaw Audio" --nametemplate="%s.au" \
		--view="/usr/lib/mime/playaudio %s"


# Remove test-hack directory
rm -rf /var/lib/mime/tests
