.\" Someone tell emacs that this is an -*- nroff -*- source file.
.\" Copyright 1997 Guy Maor.
.\" Adduser and this manpage are copyright 1995 by Ted Hajek,
.\" With much borrowing from the original adduser copyright 1994 by
.\" Ian Murdock.
.\" 
.\" This is free software; see the GNU General Public License version
.\" 2 or later for copying conditions.  There is NO warranty.
.TH ADDUSER 8 "Version VERSION" "Debian GNU/Linux"
.SH NAME
adduser, addgroup \- add a user or group to the system
.SH SYNOPSIS
.BR adduser " [options] [\-\-home dir] [\-\-uid id] [\-\-ingroup group | \-\-gid id] [--disabled-password] [--gecos gecos] user"
.PP
.BR adduser " \-\-system [options] [\-\-home dir] [\-\-uid id] [\-\-group | \-\-ingroup group | \-\-gid id] [--disabled-password] [--gecos gecos] user"
.PP
.BR adduser " \-\-group [options] [--gid id] group"
.br
.BR addgroup " [options] [--gid id] group"
.PP
.BR adduser " [options] user group"
.SS COMMON OPTIONS
.br
[\-\-quiet] [\-\-force-badname] [\-\-help] [\-\-version]
.SH DESCRIPTION
.PP
.B adduser
and
.B addgroup
add users and groups to the system according to command line options
and configuration information in
.IR /etc/adduser.conf .
The programs can be run in one of four modes:
.SS "Add a normal user"
If called with one non-option argument and without the
.BR \-\-system " or " \-\-group " options, " adduser
will add a normal user.

.B adduser
will choose the first available UID from the range specified for
normal users in the configuration file.  The UID can be overridden
with the
.B \-\-uid
option.

By default, each user in Debian GNU/Linux is given a corresponding
group with the same name and id, allowing users to easily give access
to their home directories to others.  If this option is turned off by
setting
.B USERGROUPS
to
.IR no ,
all users' GIDs are set to
.BR USERS_GID .
Users' groups can also be overridden from the command line with the
.BR \-\-gid " or " \-\-ingroup
options to set the group by id or name, respectively.

.B adduser
will create a home directory subject to
.BR DHOME ", " GROUPHOMES ", and " LETTERHOMES .
The home directory can be overridden from the command line with the
.B \-\-home
option.  The home directory's set-group-ID bit is set if
.B USERGROUPS
is
.I yes
so that any files created in the user's home directory will
have the correct group.

.B adduser
will copy files from
.B SKEL
into the home directory and prompt for finger (gecos) information and
a password.  The gecos may also be set with the
.B \-\-gecos
option.  With the
.B \-\-disabled-password
option, the account will be created but will be disabled until a
password is set.

If the file
.B /usr/local/sbin/adduser.local
exists, it will be executed after the user account has been set
up in order to do any local setup.  The arguments passed to
.B adduser.local
are:
.br
username uid gid home-directory
.SS "Add a system user"
If called with one non-option argument and the
.BR \-\-system " option, " adduser
will add a system user.

.B adduser
will choose the first available UID from the range specified for
system users in the configuration file.  The UID can be overridden with the
.B \-\-uid
option.

By default, system users are placed in the
.B nogroup
group.  To place the new system user in an already existing group, use
the
.BR \-\-gid " or " \-\-ingroup
options.  To place the new system user in a new group with the same ID, use
the
.B \-\-group
option.

A home directory is created by the same rules as for normal users.
The new system user will have the shell
.I /bin/false
and have a disabled password.  Skeletal configuration files are not copied.
If
.B adduser
created the home directory and a new group for the system user, it will set
suid group permissions on the directory.
.SS "Add a system group"
If 
.BR adduser " is called with the " \-\-group " option, or " addgroup
is called, a system group will be added.

A GID will be chosen from the range specified for system UIDS in the
configuration file.  The GID can be overridden with the
.B \-\-gid
option.

The group is created with no users.
.SS "Add an existing user to an existing group"
If called with two non-option arguments,
.B adduser
will add an existing user to an existing group.
.SH OPTIONS
.TP
.B \-\-disabled-password
Do not run passwd to set the password.  The user won't be able to use
her account until the password is set.
.TP
.B \-\-force\-badname
2By default, user and group names are required to consist of a
lowercase letter followed by one or more lowercase letters or numbers.
This option forces
.B adduser
and 
.B addgroup
to be more lenient.
.TP
.B \-\-gecos name
Set the gecos field for the new entry generated.  adduser will not ask
for finger information if this option is given.
.TP
.B \-\-gid id
When creating a group, this option forces the new groupid to be the
given number.  When creating a user, this option will put the user in
that group.
.TP
.B \-\-group
When combined with 
.BR \-\-system ,
a group with the same name and ID as the system user is created.
If not combined with
.BR \-\-system ,
a group with the given name is created.  This is the default action if
the program is invoked as
.BR addgroup .
.TP
.B \-\-help
Display brief instructions.
.TP
.BI "\-\-home " "directory"
Use
.I directory 
as the user's home directory, rather than the default specified by the
configuration file.  If the directory does not exist, it is created
and skeleton files are copied.
.TP
.BI "\-\-ingroup" " group"
Add the new user to
.I group
instead of a usergroup or the default group defined by USERS_GID
in the adduser.conf file.
.TP
.B \-\-quiet
Suppress progress messages.
.TP
.B \-\-system
Create a system user.
.TP
.B \-\-uid id
Force the new userid to be the given number.  adduser will fail if the userid
is already taken.
.TP
.B \-\-version
Display version and copyright information.
.SH FILES
/etc/adduser.conf
.SH "SEE ALSO"
adduser.conf(5)

.SH COPYRIGHT
Copyright (C) 1997 Guy Maor.
.br
Copyright (C) 1995 Ted Hajek, with a great deal borrowed from the original
Debian 
.B adduser
.br
Copyright (C) 1994 Ian Murdock.
.B adduser
is free software; see the GNU General Public Licence version 2 or
later for copying conditions.  There is
.I no
warranty.
