.TH UUTRAF 5 "September 22, 1996" "Debian" "User's Reference Manual" \" -*- nroff -*-
.SH NAME
uutraf.cf \- UUCP traffic analyzator configuration file
.PP
.SH DESCRIPTION
The
.I uutraf.cf
describes the various
.B cost parameters
per site.
Hash signs introduce comment lines; 
data lines consists of the following 6 fields:
.br 
1) remote host name,
.br
2) provider connection fee per minute,
.br
3) fee per mail,
.br
4) fee per transferred mail-kB,
.br
5) telephone company cost per call,
.br
6) telephone company cost per minute.
.PP 
.SH EXAMPLE
.PP
.nf
.ta 3i
.ft CW
# uutraf configuration file
#
#        [-----------provider----------] [-------PTT------]
#host    cost/min fee/mail fee/(mail*kB) cost/call cost/min
scsing   0.1      0.15     0.1           0.1       0.12
obastrlx 0.0      0.0      0.0           0.1       0.12
luna     0.0      0.0      0.0           0         0.0
.fi
.ft R
.PP
Note that the local host 
.I luna 
has an entry too (filled with zeroes); this prevents 
.IR uutraf (1) 
to issue an warning message about an unknown host. 
The cost figure is in local currency (eg. Dollars);
.IR uutraf (1)
assumes that calls are only done during one tariffary period
(eg. all low rate calls).
.PP
.SH FILE
.I /etc/uucp/uutraf.cf
.PP
.SH SEE ALSO
.BR uutraf "(1), " uucp "(1)."
.PP
.SH AUTHOR
David Frey
