#!/bin/sh

# You will not be able to write to the filesystem until you comment out this next line.
LDE_DEFINES=--paranoid

# Print help message
if [ "$1" = "" ] ; then
	echo This script will run lde from this directory without installing anything.
	echo If you\'re going to keep lde, you should think about installing it in
	echo /sbin \(see INSTALL and README for more info\).
	echo
	echo Re-run this script with arguments to invoke lde
	echo \(i.e. $0 --paranoid /dev/hda1\).
	echo
	echo If you want to access a partition, you must be root.

else
	# Export terminfo location
	export TERMINFO=./terminfo

	# Invoke lde
	./lde $LDE_DEFINES $*

fi
