.\" -*- nroff -*-
.\" Copyright 1995 Brian Cully (shmit@kublai.com).
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\"
.TH FLIN 1 "13-Jul-95"
.SH NAME
flin \- \fBF\fPlin's a \fBL\fPearners \fBI\fPnterface to '\fBN\fPix \fBS\fPystems.

.SH SYNOPSIS
.B flin [\-hV] [\-d delimiter] [\-e escape] [\-c comment] [menu file]

.SH DESCRIPTION
\fBflin\fP loads \fImenu file\fP and displays it. The menu is made up of any combination of
\fItoken structures\fP seperated by line breaks.

.SH OPTIONS
.TP
.I "\-h"
Print a help message and usage information.
.TP
.I "-V"
Print version information and compile\-time defaults.
.TP
.I "-d delimiter"
Set the delimiter character to \fIdelimiter\fP.
.TP
.I "-e escape"
Set the escape character to \fIescape\fP.
.TP
.I "-c comment"
Set the comment character to \fIcomment\fP.
.TP
.I "menu file"
Load menu from \fImenu file\fP.

.SH FILE FORMAT
\fINote: I will be using `:' as the token delimiter,
`\\' as the escape character, and `#' as the
comment character throughout this document.\fP

Flin files are made up of a series of \fItoken structures\fP and \fIdirectives\fP. There is a
limit of one token structure or directive per line.

Lines beginning with `#' will be ignored by \fBflin\fP.
.br
Characters preceded by `\\' will be treated literally by \fBflin\fP.

.SH Directives
Directives tell \fBflin\fP how to interperet text. Currently \fBflin\fP only understands the
\fIMenu\fP directive. Directives may not be nested.
.TP
.I "Menu name"
Starts a menu named \fIname\fP, all following lines will be interpereted as \fItoken structures\fP
until \fIEndMenu\fP is read.

.SH Token Structures
.PP
Token structures are enclosed within a \fIMenu directive\fP, with one structure per line.
A token structure is made up of at least two fields separated by delimiters. The last field
\fBmust\fP end with a delimiter.
The format of the token structure is:

.RS
.LP
Token:Name:Args:
.RE

Where \fIToken\fP is the type of item to display, \fIName\fP is the name of the item, and
\fIArgs\fP is the argument field. Not all tokens require the argument field, see the \fBTokens\fP
section for details.

.B Tokens
.RS
.TP
.I "Title"
Title inserts a non-selectable title line in the menu.
.RS
.RS
Title:Name:
.RE
.RE

.TP
.I "Nop"
Nop inserts a non-selectable line in the menu, when blank will display a line.
.RS
.RS
Nop:Name:
.br
or
.br
Nop::
.RE
.RE

.TP
.I "SubMenu"
SubMenu creates a link to another menu named in the \fIArgs\fP field.
.RS
.RS
SubMenu:Name:Args:
.RE
.RE

.TP
.I "Exec"
Exec executes the \fIArgs\fP field.
.RS
.RS
Exec:Name:Args:
.RE
.RE

.TP
.I "Args"
Args executes the \fIArgs\fP field with user inputted command-line arguments.
The optional \fIPrompt\fP field contains the prompt for the dialog box.
\fIUse with care!\fP If you use this improperly, you could open up a big security whole on your
system.
.RS
.RS
Args:Name:Args:\fIPrompt:\fP
.RE
.RE

.TP
.I "Exit"
Exit exits the current menu, returning to the previous menu. If Exit is executed in the first menu
loaded Flin will quit.
.RS
.RS
Exit:Name:
.RE
.RE

.TP
.I "Quit"
Exits flin.
.RS
.RS
Quit:Name:
.RE
.RE
.RE

.SH EXAMPLE MENU
Here is an example menu (comment character is `#', delimiter is `:'):

.RS
.nf
#
#	test.menu - A sample menu for `flin'
#		    to try it out type:
#		    flin test.menu
#

# Startup Menu
Menu Main
    Title:Main Menu:
    Nop::
    SubMenu:File Utitities:File-Util:
    SubMenu:Surf the 'Net:InterNet:
    Exit:Logout:
EndMenu

# File utilities
Menu File-Util
    Title:File Menu:
    Nop::
    Exec:Directory listing:ls -F:
    Exit:Back to Main Menu:
EndMenu

# Net `Surfing'
Menu InterNet
    Title:Internet:
    Nop::
    Exec:CyberMail:pine:
    Nop:Anything's cooler if you prepend it with `cyber':
    Exec:Telnet:telnet:
    Exec:Ftp:ftp:
    Exit:Back to Main Menu:
EndMenu
.fi
.RP

.SH BUGS
No! No! Never! Yes. A bit. She has got a wart.

.SH AUTHOR
Brian Cully (shmit@kublai.com)
