.\" =()<.ds a @<NEWSARTS>@>()=
.ds a /var/news
.\" =()<.ds b @<NEWSBIN>@>()=
.ds b /usr/libexec/news
.\" =()<.ds c @<NEWSCTL>@>()=
.ds c /etc/news
.\"
.\"
.\"
.TH CHECKACTIVE 8CN "5 Feb 1995"
.BY "C News"
.SH NAME
checkactive \- check format of news active file
.SH SYNOPSIS
.B checkactive
[
.B \-q
] [
.B \-n
] [
.B \-i
] [ file ]
.SH DESCRIPTION
.I Checkactive
checks the format of news's
.I active
file
(or the named
.IR file ,
if specified),
and also checks the file for consistency with the
.I sys
file.
Complaints, if any, are produced on standard output.
.PP
The
.B \-n
(numeric fields okay)
option suppresses checking of the relationship between the two middle
(numeric) fields,
for the case where they are about to be rebuilt.
.PP
The
.B \-q
(quick) option suppresses one test,
precise checking of the format of newsgroup names,
which is relatively slow for a large
.I active
file.
.PP
The
.B \-i
(incomplete) option indicates that the input is only part of an
.I active
file and might be incomplete,
e.g. it might not have entries for the
``control'' and ``junk''
pseudo-newsgroups.
.SH SEE ALSO
newsdb(5)
.SH HISTORY
Written at U of Toronto by Henry Spencer.
.SH BUGS
There's no good reason why name-format checking
.I has
to be so slow.
