all: newfaq.dvi letterfaq.dvi
newfaq.dvi: newfaq.tex
	latex newfaq.tex
	latex newfaq.tex
	latex newfaq.tex
letterfaq.dvi: letterfaq.tex
	latex letterfaq.tex
	latex letterfaq.tex
	latex letterfaq.tex
clean:
	rm -f *.dvi *.aux *.log *.toc
