#!/bin/sh
# postremoval file for httpd package
set -e

# remove the server startup, configuration, and files:
if [ $1 = purge ]
then
  update-rc.d cern-httpd remove >/dev/null
  rm -f /etc/cern-httpd.conf.old*
  rm -f /var/run/cern-httpd.pid
  conffile=/etc/cern-httpd.conf
  acclog=`grep -Ei '^\W*accesslog\W+' $conffile | awk '{print $2}'` 
  errlog=`grep -Ei '^\W*errorlog\W+' $conffile | awk '{print $2}'` 
  rm -f ${errlog}*
  rm -f ${acclog}*
  rm -f $conffile
fi
