.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified 21 Aug 1994 by Michael Chastain (mec@shell.portal.com):
.\"   Removed note about old libc (pre-4.5.26) translating to 'sync'.
.\" Modified 15 Apr 1995 by Michael Chastain (mec@shell.portal.com):
.\"   Added 'see also' section.
.\" Translated 25 Dec 1995 Miguel A. Sepulveda (miguel@typhoon.harvard.edu)
.\" Modified 1 Jul 1996 Miguel A. Sepulveda (angel@vivaldi.princeton.edu)
.TH FSYNC 2 "1 Jul 1996" "Linux 1.2.4" "Manual del Programador"
.SH NOMBRE 
fsync \- sincroniza el estado de un fichero in-core
con aquel del disco.
.SH SINOPSIS
.B #include <unistd.h>
.sp
.BI "int fsync(int " fd );
.SH DESCRIPCIÓN
.B fsync
copia todas las partes in-core de un fichero en el disco.
.SH "VALOR REGRESADO"
En caso de éxito regresa 0. En caso de error \-1, y la variable
.I errno
es asignada apropiadamente.
.SH ERRORES
.TP 0.8i
.B EBADF
.B fd
no es un descriptor de fichero válido.
.TP
.B EROFS
.B EINVAL
.B fd
está enlazado con un fichero especial que no sabe acerca de sincronización.
.TP
.B EIO
Ha ocurrido un error durante sincronización.
.SH "VÉASE"
.BR bdflush "(2), " fsync "(2), " update "(8), " sync "(8)"
