#define __CRACK_VOID_F(fn,args) (void)(fn args)
#define __CRACK_BOOL_F(fn,args) (BOOL)(fn args)
#define __CRACK_HMENU_F(fn,args) (HMENU)(fn args)
#define __CRACK_HWND_F(fn,args) (HWND)(fn args)
#define __CRACK_LONG_F(fn, args) (LRESULT)(fn args)
#define __CRACK_ZERO_F(fn, args)  (fn args,0)

/* Totally disgusting ! we get wParam and lParam from the environment ! */
#define HANDLE_MSG(h, message, fn)  case message: return HANDLE_##message(h, wParam, lParam, fn)

#define GetFirstChild(h) GetTopWindow(h)
#define GetNextSibling(h) GetWindow(h, GW_HWNDNEXT)
#define GetWindowID(h) GetDlgCtrlID(h)
#define SubclassWindow(h, p) (SetWindowLong(h, GWL_WNDPROC, p))

#define GET_WM_COMMAND_CMD(w, l) 	HIWORD(w)
#define GET_WM_COMMAND_ID(w, l) 	LOWORD(w)
#define GET_WM_CTLCOLOR_HDC(w, l, msg) 	(HDC)(w)
#define GET_WM_CTLCOLOR_HWND(w, l, msg) (HWND)(l)
#define GET_WM_HSCROLL_CODE(w, l) 	LOWORD(w)
#define GET_WM_HSCROLL_HWND(w, l) 	(HWND)(l)
#define GET_WM_HSCROLL_POS(w, l) 	HIWORD(w)
#define GET_WM_MDIACTIVATE_FACTIVATE(h, a, b) 	 (b == (LONG)h)
#define GET_WM_MDIACTIVATE_HWNDACTIVATE(a, b) (HWND)(b)
#define GET_WM_MDIACTIVATE_HWNDDEACT(a, b) 	(HWND)(a)
#define GET_WM_VSCROLL_CODE(w, l)	 LOWORD(w)
#define GET_WM_VSCROLL_HWND(w, l)	(HWND)(l)
#define GET_WM_VSCROLL_POS(w, l) 	HIWORD(w)

#define FORWARD_WM_CLOSE(h, fn)  		__CRACK_VOID_F(fn,(h, WM_CLOSE, 0, 0))
#define FORWARD_WM_COMMAND(h, id, c, n, fn)  	__CRACK_VOID_F(fn,(h, WM_COMMAND, MAKEWPARAM(id,n), (LPARAM)c))
#define FORWARD_WM_CREATE(h, p, fn)  		__CRACK_BOOL_F(fn,(h, WM_CREATE, 0, (LPARAM)p))
#define FORWARD_WM_DESTROY(h, fn)  		__CRACK_VOID_F(fn,(h, WM_DESTROY, 0, 0))
#define FORWARD_WM_ENABLE(h, e, fn)  		__CRACK_VOID_F(fn,(h, WM_ENABLE, (WPARAM)e, 0))
#define FORWARD_WM_INITDIALOG(h, c, l, fn) 	__CRACK_BOOL_F(fn,(h, WM_INITDIALOG, (WPARAM)c, l))
#define FORWARD_WM_MDICASCADE(h, c, fn)  	__CRACK_BOOL_F(fn,(h, WM_MDICASCADE, (WPARAM)c, 0))
#define FORWARD_WM_MDIDESTROY(h, d, fn)  	__CRACK_VOID_F(fn,(h, WM_MDIDESTROY, (WPARAM)d, 0))
#define FORWARD_WM_MDIGETACTIVE(h, fn)  	__CRACK_HWND_F(fn,(h, WM_MDIGETACTIVE, 0, 0))
#define FORWARD_WM_MDIICONARRANGE(h, fn)  	__CRACK_VOID_F(fn,(h, WM_MDIICONARRANGE, 0, 0))
#define FORWARD_WM_MDISETMENU(h, fr, hf, hw, fn) __CRACK_HMENU_F(fn,(h, WM_MDISETMENU, (WPARAM)((fr) ? (hf) : 0), (LPARAM)(hw)))
#define FORWARD_WM_MDITILE(h, c, fn)  		__CRACK_BOOL_F(fn,(h, WM_MDITILE, (WPARAM)(c), 0))
#define FORWARD_WM_PAINT(h, fn)  		__CRACK_VOID_F(fn,(h, WM_PAINT, 0, 0))
#define FORWARD_WM_QUERYENDSESSION(h, fn)  	__CRACK_BOOL_F(fn,(h, WM_QUERYENDSESSION, 0, 0))
#define FORWARD_WM_SIZE(h, state, cx, cy, fn)  	__CRACK_VOID_F(fn,(h, WM_SIZE, (WPARAM)state, MAKELPARAM(cx, cy)))
#define FORWARD_WM_SYSCOMMAND(h, c, x, y, fn)  	__CRACK_VOID_F(fn,(h, WM_SYSCOMMAND, (WPARAM)c, MAKELPARAM(x, y)))

#define HANDLE_WM_CLOSE(h, w, l, fn) 		__CRACK_ZERO_F(fn,(h));
#define HANDLE_WM_COMMAND(h, w, l, fn)  	__CRACK_ZERO_F(fn,(h, SEXT_LOWORD(w), (HWND)l, HIWORD(w)))
#define HANDLE_WM_CREATE(h, w, l, fn)   	(LRESULT)((fn(h, (CREATESTRUCT *)l)) ? 0 : -1)
#define HANDLE_WM_DESTROY(h, w, l, fn)  	__CRACK_ZERO_F(fn,(h))
#define HANDLE_WM_ENABLE(h, w, l, fn)  		__CRACK_ZERO_F(fn,(h, (BOOL)w))
#define HANDLE_WM_INITDIALOG(h, w, l, fn)  	__CRACK_LONG_F(fn,(h, (HWND)w, l))
#define HANDLE_WM_MDICASCADE(h, w, l, fn) 	__CRACK_LONG_F(fn, (h, (UINT)w)
#define HANDLE_WM_MDIDESTROY(h, w, l, fn) 	__CRACK_ZERO_F(fn,(h, (HWND)w))
#define HANDLE_WM_MDIGETACTIVE(h, w, l, fn)  	__CRACK_LONG_F(fn,(h))
#define HANDLE_WM_MDIICONARRANGE(h, w, l, fn)  	__CRACK_ZERO_F(fn,(h))
#define HANDLE_WM_MDISETMENU(h, w, l, fn)  	__CRACK_LONG_F(fn,(h, (BOOL)w, (HMENU)w, (HMENU)l)
#define HANDLE_WM_MDITILE(h, w, l, fn)  	__CRACK_LONG_F(fn,(h, (UINT)w))
#define HANDLE_WM_PAINT(h, w, l, fn)  		__CRACK_ZERO_F(fn,(h))
#define HANDLE_WM_QUERYENDSESSION(h, w, l, fn)  MAKELRESULT(fn(h), 0)
#define HANDLE_WM_SIZE(h, w, l, fn)  		__CRACK_ZERO_F(fn,(h, (UINT)w, SEXT_LOWORD(l), SEXT_HIWORD(l)))
#define HANDLE_WM_SYSCOMMAND(h, w, l, fn)  	__CRACK_ZERO_F(fn,(h, (UINT)w, SEXT_LOWORD(l), SEXT_HIWORD(l)))



