.\" -*- nroff -*-
.TH UPDATE-MENUS 1L "Debian Utilities" "DEBIAN"
.SH NAME
update-menus \- generate debian menu system
.SH SYNOPSIS
.B update-menus [\-v] [\-d] [\-h]
.SH DESCRIPTION
Before the advent of \fIupdate-menus\fP, when the sysadmin installed a 
package onto a debian system, they would need to edit various window 
manager config files to make the new program show up on, for example, 
fvwm's menus. The menus could easily become out of sync with what programs
were actually available, with some menu items that didn't work, and other
programs that lacked a menu entry.
.I update-menus
and debian's menu package aim to solve this problem.
.PP
.I update-menus 
automatically generates menus of installed programs for window 
managers and other menu programs. It should be run whenever a
.BR menufile (5)
or menu-method file is changed.
.I update-menus
will be ran automatically when debian packages that contain menu 
files are installed or removed from the system.
.SH OPTIONS
.IP "-v"
Verbose output. Shows all arguments to the /etc/menu-methods programs.
.IP "-d"
Debug output. Generates loads of unintelligible output.
.IP "-h"
Display usage help and exit.
.SH CONFIGURATION
There are several ways to tune the operation of update-menus:
.PP
.I per menuentry, in /etc/menu/$package
.RS
In these directory the system admin or user can override the default
menufiles. (if a file /etc/menu/$package exists, than the
corresponding /usr/lib/menu/$package file isn't read any more). Users
who want to override the system wide defaults put their files in
~/.menu. See also 
.BR menufile(5)
.RE	
.I per window-manager in /etc/menu-methods/$wm
.RS
In these config files, one can tune generated "system.rc" files for
each individual window manager. For example, one can specify that the
wm should ignore any icons that the packages may supply, or set the
default wrapper for text-only apps (usually, an xterm is started to
run a text-only app like vi). Users who want to override the system
wide defaults put their files in ~/.menu-methds. For more info, see
/usr/doc/menu/README. 
.RE
.I globally, in /etc/menu-methods/translate_menus
.RS
This file contains translations that will be performed for all
menuentries and all window managers. You can specify things like:
`All sections that start with "Apps/Games" should be mapped to "Games"',
or `menuentryid "gnuplot" should have a title of "GnuTeken" (to
translate titles into other other languages)'. Look at the default
/etc/menu-methods/translate_menus for an example. Users who want to
override the systemdefault translate file, put one in
~/.menu-methods/translate_menus.
.RE
.SH FILES
Menu files: (Earlier listed directories override those listed later.)
.RS
.I ~/.menu/*
.RS
Menu files added by the user. (Isn't read if root runs update-menus)
.RE
.I /etc/menu/*
.RS
Menu files added by the sysadmin.
.RE
.I /usr/lib/menu/*
.RS
Menu files provided by other debian packages.
.RE
.I /usr/lib/menu/default/*
.RS
Menu files provided by the menu package. (These are for packages that
don't provide menuentries yet. If you see (or maintain) a package that
supplies a menufile in /usr/lib/menu/, please email me and I'll remove
that menufile from /usr/lib/menu/default/).
.RE
.RE
Menu methods:
.RS
.I /etc/menu-methods/
.RS
Executable config files that are added by window managers and other menu
programs, these files are run by
.I update-menus
to generate menus for the different programs. Also in this directory
is the translate file, used for local configuration of the shape of the
menu trees.
.RE
.RE
.RS
.I ~/menu-methods/
.RS
For users to override the system-defaults of /etc/menu-methods.
If this directory exists, no files in /etc/menu-methods are read
any more.
.RE
.RE
.SH DISTRIBUTION
Distribution is subject to the GNU public license.
.SH BUGS
.I update-menus
may not work properly when run by a normal user, to generate menus for that
user. This is usually because the window manager doesn't expect the
system."$wm"rc files in the directory (usually ~/."$wm", configurable
in /etc/menu-methods). If you see such a thing, and you find a
solution, please mail me (joostje@debian.org). It should work OK for
fvwm and fvwm2: I usually test the package first ordinary user.
.PP
.SH AUTHOR 
Joost Witteveen <joostje@debian.org>, original idea by
Lars Wirzenius <liw@iki.fi>
.SH THANKS
To Joey Hess, for a lot of good ideas and pre-release testing, and to
Tom Lees for a update-menus in pure C (of which I only used one
function, but that's life).
.PP
(Man page by Joey Hess, <joey@kite.ml.org>)
.SH "SEE ALSO"
.BR menufile (5),
.BR /usr/doc/menu/README
