.ll 6i
.pl 10.5i
.\"	@(#)keysu.1	1.0 (Bellcore) 12/2/91
.\"
.lt 6.0i
.TH KEYSU 1 "2 December 1991"
.AT 3
.SH NAME
keysu \-  Switch user program for use with the S/Key one time password system.
.SH SYNOPSIS
.B keysu   [<user ID >] 
.SH DESCRIPTION
.I keysu
.SH OPTIONS
.B <user ID>
the ID for the user to become.
The defalt is root.
.SH DIAGNOSTICS
.SH FILES
.TP
/etc/skeykeys data base of information for S/Key system.
.SH BUGS
.LP
.SH SEE ALSO
.BR su(1),
.BR key(1),
.BR skey(1),
.BR keyinfo(1),
.BR keyinit(1),
.BR keylogin(1)
.SH AUTHOR
Command by Phil Karn, Neil M. Haller, John S. Walden
.SH CONTACT
staff@thumper.bellcore.com
