/* ==> Do not modify this file!!  It is created automatically
   by copying.awk.  Modify copying.awk instead.  <== */

#include "conq.h"

void
describe_copyright(arg, key, buf)
int arg;
char *key, *buf;
{
    strcat(buf, "		    GNU GENERAL PUBLIC LICENSE\n");
    strcat(buf, "		       Version 2, June 1991\n");
    strcat(buf, "\n");
    strcat(buf, " Copyright (C) 1989, 1991 Free Software Foundation, Inc.\n");
    strcat(buf, "                          675 Mass Ave, Cambridge, MA 02139, USA\n");
    strcat(buf, " Everyone is permitted to copy and distribute verbatim copies\n");
    strcat(buf, " of this license document, but changing it is not allowed.\n");
    strcat(buf, "\n");
    strcat(buf, "			    Preamble\n");
    strcat(buf, "\n");
    strcat(buf, "  The licenses for most software are designed to take away your\n");
    strcat(buf, "freedom to share and change it.  By contrast, the GNU General Public\n");
    strcat(buf, "License is intended to guarantee your freedom to share and change free\n");
    strcat(buf, "software--to make sure the software is free for all its users.  This\n");
    strcat(buf, "General Public License applies to most of the Free Software\n");
    strcat(buf, "Foundation's software and to any other program whose authors commit to\n");
    strcat(buf, "using it.  (Some other Free Software Foundation software is covered by\n");
    strcat(buf, "the GNU Library General Public License instead.)  You can apply it to\n");
    strcat(buf, "your programs, too.\n");
    strcat(buf, "\n");
    strcat(buf, "  When we speak of free software, we are referring to freedom, not\n");
    strcat(buf, "price.  Our General Public Licenses are designed to make sure that you\n");
    strcat(buf, "have the freedom to distribute copies of free software (and charge for\n");
    strcat(buf, "this service if you wish), that you receive source code or can get it\n");
    strcat(buf, "if you want it, that you can change the software or use pieces of it\n");
    strcat(buf, "in new free programs; and that you know you can do these things.\n");
    strcat(buf, "\n");
    strcat(buf, "  To protect your rights, we need to make restrictions that forbid\n");
    strcat(buf, "anyone to deny you these rights or to ask you to surrender the rights.\n");
    strcat(buf, "These restrictions translate to certain responsibilities for you if you\n");
    strcat(buf, "distribute copies of the software, or if you modify it.\n");
    strcat(buf, "\n");
    strcat(buf, "  For example, if you distribute copies of such a program, whether\n");
    strcat(buf, "gratis or for a fee, you must give the recipients all the rights that\n");
    strcat(buf, "you have.  You must make sure that they, too, receive or can get the\n");
    strcat(buf, "source code.  And you must show them these terms so they know their\n");
    strcat(buf, "rights.\n");
    strcat(buf, "\n");
    strcat(buf, "  We protect your rights with two steps: (1) copyright the software, and\n");
    strcat(buf, "(2) offer you this license which gives you legal permission to copy,\n");
    strcat(buf, "distribute and/or modify the software.\n");
    strcat(buf, "\n");
    strcat(buf, "  Also, for each author's protection and ours, we want to make certain\n");
    strcat(buf, "that everyone understands that there is no warranty for this free\n");
    strcat(buf, "software.  If the software is modified by someone else and passed on, we\n");
    strcat(buf, "want its recipients to know that what they have is not the original, so\n");
    strcat(buf, "that any problems introduced by others will not reflect on the original\n");
    strcat(buf, "authors' reputations.\n");
    strcat(buf, "\n");
    strcat(buf, "  Finally, any free program is threatened constantly by software\n");
    strcat(buf, "patents.  We wish to avoid the danger that redistributors of a free\n");
    strcat(buf, "program will individually obtain patent licenses, in effect making the\n");
    strcat(buf, "program proprietary.  To prevent this, we have made it clear that any\n");
    strcat(buf, "patent must be licensed for everyone's free use or not licensed at all.\n");
    strcat(buf, "\n");
    strcat(buf, "  The precise terms and conditions for copying, distribution and\n");
    strcat(buf, "modification follow.\n");
    strcat(buf, "\n");
    strcat(buf, "		    GNU GENERAL PUBLIC LICENSE\n");
    strcat(buf, "   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n");
    strcat(buf, "\n");
    strcat(buf, "  0. This License applies to any program or other work which contains\n");
    strcat(buf, "a notice placed by the copyright holder saying it may be distributed\n");
    strcat(buf, "under the terms of this General Public License.  The \"Program\", below,\n");
    strcat(buf, "refers to any such program or work, and a \"work based on the Program\"\n");
    strcat(buf, "means either the Program or any derivative work under copyright law:\n");
    strcat(buf, "that is to say, a work containing the Program or a portion of it,\n");
    strcat(buf, "either verbatim or with modifications and/or translated into another\n");
    strcat(buf, "language.  (Hereinafter, translation is included without limitation in\n");
    strcat(buf, "the term \"modification\".)  Each licensee is addressed as \"you\".\n");
    strcat(buf, "\n");
    strcat(buf, "Activities other than copying, distribution and modification are not\n");
    strcat(buf, "covered by this License; they are outside its scope.  The act of\n");
    strcat(buf, "running the Program is not restricted, and the output from the Program\n");
    strcat(buf, "is covered only if its contents constitute a work based on the\n");
    strcat(buf, "Program (independent of having been made by running the Program).\n");
    strcat(buf, "Whether that is true depends on what the Program does.\n");
    strcat(buf, "\n");
    strcat(buf, "  1. You may copy and distribute verbatim copies of the Program's\n");
    strcat(buf, "source code as you receive it, in any medium, provided that you\n");
    strcat(buf, "conspicuously and appropriately publish on each copy an appropriate\n");
    strcat(buf, "copyright notice and disclaimer of warranty; keep intact all the\n");
    strcat(buf, "notices that refer to this License and to the absence of any warranty;\n");
    strcat(buf, "and give any other recipients of the Program a copy of this License\n");
    strcat(buf, "along with the Program.\n");
    strcat(buf, "\n");
    strcat(buf, "You may charge a fee for the physical act of transferring a copy, and\n");
    strcat(buf, "you may at your option offer warranty protection in exchange for a fee.\n");
    strcat(buf, "\n");
    strcat(buf, "  2. You may modify your copy or copies of the Program or any portion\n");
    strcat(buf, "of it, thus forming a work based on the Program, and copy and\n");
    strcat(buf, "distribute such modifications or work under the terms of Section 1\n");
    strcat(buf, "above, provided that you also meet all of these conditions:\n");
    strcat(buf, "\n");
    strcat(buf, "    a) You must cause the modified files to carry prominent notices\n");
    strcat(buf, "    stating that you changed the files and the date of any change.\n");
    strcat(buf, "\n");
    strcat(buf, "    b) You must cause any work that you distribute or publish, that in\n");
    strcat(buf, "    whole or in part contains or is derived from the Program or any\n");
    strcat(buf, "    part thereof, to be licensed as a whole at no charge to all third\n");
    strcat(buf, "    parties under the terms of this License.\n");
    strcat(buf, "\n");
    strcat(buf, "    c) If the modified program normally reads commands interactively\n");
    strcat(buf, "    when run, you must cause it, when started running for such\n");
    strcat(buf, "    interactive use in the most ordinary way, to print or display an\n");
    strcat(buf, "    announcement including an appropriate copyright notice and a\n");
    strcat(buf, "    notice that there is no warranty (or else, saying that you provide\n");
    strcat(buf, "    a warranty) and that users may redistribute the program under\n");
    strcat(buf, "    these conditions, and telling the user how to view a copy of this\n");
    strcat(buf, "    License.  (Exception: if the Program itself is interactive but\n");
    strcat(buf, "    does not normally print such an announcement, your work based on\n");
    strcat(buf, "    the Program is not required to print an announcement.)\n");
    strcat(buf, "\n");
    strcat(buf, "These requirements apply to the modified work as a whole.  If\n");
    strcat(buf, "identifiable sections of that work are not derived from the Program,\n");
    strcat(buf, "and can be reasonably considered independent and separate works in\n");
    strcat(buf, "themselves, then this License, and its terms, do not apply to those\n");
    strcat(buf, "sections when you distribute them as separate works.  But when you\n");
    strcat(buf, "distribute the same sections as part of a whole which is a work based\n");
    strcat(buf, "on the Program, the distribution of the whole must be on the terms of\n");
    strcat(buf, "this License, whose permissions for other licensees extend to the\n");
    strcat(buf, "entire whole, and thus to each and every part regardless of who wrote it.\n");
    strcat(buf, "\n");
    strcat(buf, "Thus, it is not the intent of this section to claim rights or contest\n");
    strcat(buf, "your rights to work written entirely by you; rather, the intent is to\n");
    strcat(buf, "exercise the right to control the distribution of derivative or\n");
    strcat(buf, "collective works based on the Program.\n");
    strcat(buf, "\n");
    strcat(buf, "In addition, mere aggregation of another work not based on the Program\n");
    strcat(buf, "with the Program (or with a work based on the Program) on a volume of\n");
    strcat(buf, "a storage or distribution medium does not bring the other work under\n");
    strcat(buf, "the scope of this License.\n");
    strcat(buf, "\n");
    strcat(buf, "  3. You may copy and distribute the Program (or a work based on it,\n");
    strcat(buf, "under Section 2) in object code or executable form under the terms of\n");
    strcat(buf, "Sections 1 and 2 above provided that you also do one of the following:\n");
    strcat(buf, "\n");
    strcat(buf, "    a) Accompany it with the complete corresponding machine-readable\n");
    strcat(buf, "    source code, which must be distributed under the terms of Sections\n");
    strcat(buf, "    1 and 2 above on a medium customarily used for software interchange; or,\n");
    strcat(buf, "\n");
    strcat(buf, "    b) Accompany it with a written offer, valid for at least three\n");
    strcat(buf, "    years, to give any third party, for a charge no more than your\n");
    strcat(buf, "    cost of physically performing source distribution, a complete\n");
    strcat(buf, "    machine-readable copy of the corresponding source code, to be\n");
    strcat(buf, "    distributed under the terms of Sections 1 and 2 above on a medium\n");
    strcat(buf, "    customarily used for software interchange; or,\n");
    strcat(buf, "\n");
    strcat(buf, "    c) Accompany it with the information you received as to the offer\n");
    strcat(buf, "    to distribute corresponding source code.  (This alternative is\n");
    strcat(buf, "    allowed only for noncommercial distribution and only if you\n");
    strcat(buf, "    received the program in object code or executable form with such\n");
    strcat(buf, "    an offer, in accord with Subsection b above.)\n");
    strcat(buf, "\n");
    strcat(buf, "The source code for a work means the preferred form of the work for\n");
    strcat(buf, "making modifications to it.  For an executable work, complete source\n");
    strcat(buf, "code means all the source code for all modules it contains, plus any\n");
    strcat(buf, "associated interface definition files, plus the scripts used to\n");
    strcat(buf, "control compilation and installation of the executable.  However, as a\n");
    strcat(buf, "special exception, the source code distributed need not include\n");
    strcat(buf, "anything that is normally distributed (in either source or binary\n");
    strcat(buf, "form) with the major components (compiler, kernel, and so on) of the\n");
    strcat(buf, "operating system on which the executable runs, unless that component\n");
    strcat(buf, "itself accompanies the executable.\n");
    strcat(buf, "\n");
    strcat(buf, "If distribution of executable or object code is made by offering\n");
    strcat(buf, "access to copy from a designated place, then offering equivalent\n");
    strcat(buf, "access to copy the source code from the same place counts as\n");
    strcat(buf, "distribution of the source code, even though third parties are not\n");
    strcat(buf, "compelled to copy the source along with the object code.\n");
    strcat(buf, "\n");
    strcat(buf, "  4. You may not copy, modify, sublicense, or distribute the Program\n");
    strcat(buf, "except as expressly provided under this License.  Any attempt\n");
    strcat(buf, "otherwise to copy, modify, sublicense or distribute the Program is\n");
    strcat(buf, "void, and will automatically terminate your rights under this License.\n");
    strcat(buf, "However, parties who have received copies, or rights, from you under\n");
    strcat(buf, "this License will not have their licenses terminated so long as such\n");
    strcat(buf, "parties remain in full compliance.\n");
    strcat(buf, "\n");
    strcat(buf, "  5. You are not required to accept this License, since you have not\n");
    strcat(buf, "signed it.  However, nothing else grants you permission to modify or\n");
    strcat(buf, "distribute the Program or its derivative works.  These actions are\n");
    strcat(buf, "prohibited by law if you do not accept this License.  Therefore, by\n");
    strcat(buf, "modifying or distributing the Program (or any work based on the\n");
    strcat(buf, "Program), you indicate your acceptance of this License to do so, and\n");
    strcat(buf, "all its terms and conditions for copying, distributing or modifying\n");
    strcat(buf, "the Program or works based on it.\n");
    strcat(buf, "\n");
    strcat(buf, "  6. Each time you redistribute the Program (or any work based on the\n");
    strcat(buf, "Program), the recipient automatically receives a license from the\n");
    strcat(buf, "original licensor to copy, distribute or modify the Program subject to\n");
    strcat(buf, "these terms and conditions.  You may not impose any further\n");
    strcat(buf, "restrictions on the recipients' exercise of the rights granted herein.\n");
    strcat(buf, "You are not responsible for enforcing compliance by third parties to\n");
    strcat(buf, "this License.\n");
    strcat(buf, "\n");
    strcat(buf, "  7. If, as a consequence of a court judgment or allegation of patent\n");
    strcat(buf, "infringement or for any other reason (not limited to patent issues),\n");
    strcat(buf, "conditions are imposed on you (whether by court order, agreement or\n");
    strcat(buf, "otherwise) that contradict the conditions of this License, they do not\n");
    strcat(buf, "excuse you from the conditions of this License.  If you cannot\n");
    strcat(buf, "distribute so as to satisfy simultaneously your obligations under this\n");
    strcat(buf, "License and any other pertinent obligations, then as a consequence you\n");
    strcat(buf, "may not distribute the Program at all.  For example, if a patent\n");
    strcat(buf, "license would not permit royalty-free redistribution of the Program by\n");
    strcat(buf, "all those who receive copies directly or indirectly through you, then\n");
    strcat(buf, "the only way you could satisfy both it and this License would be to\n");
    strcat(buf, "refrain entirely from distribution of the Program.\n");
    strcat(buf, "\n");
    strcat(buf, "If any portion of this section is held invalid or unenforceable under\n");
    strcat(buf, "any particular circumstance, the balance of the section is intended to\n");
    strcat(buf, "apply and the section as a whole is intended to apply in other\n");
    strcat(buf, "circumstances.\n");
    strcat(buf, "\n");
    strcat(buf, "It is not the purpose of this section to induce you to infringe any\n");
    strcat(buf, "patents or other property right claims or to contest validity of any\n");
    strcat(buf, "such claims; this section has the sole purpose of protecting the\n");
    strcat(buf, "integrity of the free software distribution system, which is\n");
    strcat(buf, "implemented by public license practices.  Many people have made\n");
    strcat(buf, "generous contributions to the wide range of software distributed\n");
    strcat(buf, "through that system in reliance on consistent application of that\n");
    strcat(buf, "system; it is up to the author/donor to decide if he or she is willing\n");
    strcat(buf, "to distribute software through any other system and a licensee cannot\n");
    strcat(buf, "impose that choice.\n");
    strcat(buf, "\n");
    strcat(buf, "This section is intended to make thoroughly clear what is believed to\n");
    strcat(buf, "be a consequence of the rest of this License.\n");
    strcat(buf, "\n");
    strcat(buf, "  8. If the distribution and/or use of the Program is restricted in\n");
    strcat(buf, "certain countries either by patents or by copyrighted interfaces, the\n");
    strcat(buf, "original copyright holder who places the Program under this License\n");
    strcat(buf, "may add an explicit geographical distribution limitation excluding\n");
    strcat(buf, "those countries, so that distribution is permitted only in or among\n");
    strcat(buf, "countries not thus excluded.  In such case, this License incorporates\n");
    strcat(buf, "the limitation as if written in the body of this License.\n");
    strcat(buf, "\n");
    strcat(buf, "  9. The Free Software Foundation may publish revised and/or new versions\n");
    strcat(buf, "of the General Public License from time to time.  Such new versions will\n");
    strcat(buf, "be similar in spirit to the present version, but may differ in detail to\n");
    strcat(buf, "address new problems or concerns.\n");
    strcat(buf, "\n");
    strcat(buf, "Each version is given a distinguishing version number.  If the Program\n");
    strcat(buf, "specifies a version number of this License which applies to it and \"any\n");
    strcat(buf, "later version\", you have the option of following the terms and conditions\n");
    strcat(buf, "either of that version or of any later version published by the Free\n");
    strcat(buf, "Software Foundation.  If the Program does not specify a version number of\n");
    strcat(buf, "this License, you may choose any version ever published by the Free Software\n");
    strcat(buf, "Foundation.\n");
    strcat(buf, "\n");
    strcat(buf, "  10. If you wish to incorporate parts of the Program into other free\n");
    strcat(buf, "programs whose distribution conditions are different, write to the author\n");
    strcat(buf, "to ask for permission.  For software which is copyrighted by the Free\n");
    strcat(buf, "Software Foundation, write to the Free Software Foundation; we sometimes\n");
    strcat(buf, "make exceptions for this.  Our decision will be guided by the two goals\n");
    strcat(buf, "of preserving the free status of all derivatives of our free software and\n");
    strcat(buf, "of promoting the sharing and reuse of software generally.\n");
    strcat(buf, "\n");
}

void
describe_warranty(arg, key, buf)
int arg;
char *key, *buf;
{
    strcat(buf, "			    NO WARRANTY\n");
    strcat(buf, "\n");
    strcat(buf, "  11. BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY\n");
    strcat(buf, "FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.  EXCEPT WHEN\n");
    strcat(buf, "OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES\n");
    strcat(buf, "PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED\n");
    strcat(buf, "OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\n");
    strcat(buf, "MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS\n");
    strcat(buf, "TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD THE\n");
    strcat(buf, "PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING,\n");
    strcat(buf, "REPAIR OR CORRECTION.\n");
    strcat(buf, "\n");
    strcat(buf, "  12. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING\n");
    strcat(buf, "WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR\n");
    strcat(buf, "REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES,\n");
    strcat(buf, "INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING\n");
    strcat(buf, "OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED\n");
    strcat(buf, "TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY\n");
    strcat(buf, "YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER\n");
    strcat(buf, "PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE\n");
    strcat(buf, "POSSIBILITY OF SUCH DAMAGES.\n");
    strcat(buf, "\n");
}
