.TH SYSTAT 1 "7 August 1994" "Linux" "Linux Programmer's Manual"
.SH NAME
systat \- show the system/network status of a remote host
.SH SYNOPSIS
.B systat
.RB [ \-n ]
.RB [ \-\-netstat ]
.RB [ \-p\ port ]
.RB [ \-\-port\ port ]
.RB [ \-s ]
.RB [ \-\-systat ]
.RB [ \-t ]
.RB [ \-\-time ]
.RB [ \-h ]
.RB [ \-\-help ]
.RB [ \-v ]
.RB [ \-\-version ]
.RB host
.SH DESCRIPTION
.B Systat
allows you to get system informations from remote hosts using their
.B netstat,
.B systat
or
.B daytime
service. By default it will use the
.B systat
service.
.LP
The only mandatory parameter is the destination host name or IP number.  
.SH OPTIONS
.TP
.I "\-n, \-\-netstat"
Query the
.B netstat
service of the remote host
.TP
.I "\-p, \-\-port port"
Use a different tcp port
.TP
.I "\-s, \-\-systat"
Query the
.B systat
service of the remote host
.TP
.I "\-t, \-\-time"
Query the
.B daytime
service of the remote host
.TP
.I "\-h, \-\-help"
Print a usage message on standard output and exit successfully.
.TP
.I "\-v, \-\-version"
Print version information on standard output and exit successfully.
.SH AUTHOR
Peter Tobias, <tobias@et-inf.fho-emden.de>

