.\" Traducción al Español por Simon Mudd <sjmudd@redestb.es>
.\" 27 de nombiembre de 1996 - Ultima modificación: 27 de novembre de 1996
.\" $Revision: 1.3 $
.TH LPOST 1
.SH NOMBRE
lpost - envia un artículo al servidor local usando rnews.
.SH SINOPSIS
.I lpost
[
.BI
-v
]
.SH OPCIONES
-v     verbose, muestra cada artículo al subirlo al servidor.
.SH NOTA
Usa el modo batch de suck y evita lpost, esto no es el mecanismo
más eficaz de hacer estas cosas.  Se mantiene solamente por razones
históricas y porque todavía hay alguna gente que lo sigue usando. 
.SH DESCRIPCION
.I lpost
(local post) lee de stdin y envia el artículo vía un "pipe" a
.I rnews,
que normalmente se encuentra en /usr/lib/news. Si
.I rnews
se encuentra en otro directorio, cambia
.I #define RNEWS
en
.I config.h.
Un uso típico de lpost es:

.RS
zcat output.gz | lpost
.RE

Esto puede tardar bastante tiempo, así que sea paciente.
.SH VALORES DE RETORNO
0 éxito, -1 fallo.
.de R$
Revisione \\$$3, \\$$4
..
.SH "VER TAMBIEN"
suck(1), rpost(1), testhost(1).

