.\" $Revision: 1.2 $
.TH TESTHOST 1
.SH NOMBRE
testhost - verifica el estado de un servidor NNTP de news.
.SH SINTAXIS
.I testhost
.BI hostname
[
.BI -a | -n
fecha hora
]
[
.BI -s | -S
archivo
]
[
.BI -e | -E
archivo
]
[
.BI -N
número de puerto
]
[
.BI -U
id_usuario
]
[
.BI -P
clave
]
[
.BI -l
archivo_de_frases
]

.SH OPCIONES
-a     Obtiene la lista activa del servidor

-n fecha hora     

Obtiene los grupos creados en el servidor desde la fecha y hora
especificadas. La fecha ha de estar en el formato AAMMDD (Año mes día)
y la hora en HHMMSS (horas minutos segundos).

-s | -S archivo

Estas opciones enviarán todos los mensajes de estado (normalemente
escritos a stdout) a un archivo alternativo.  La opción en minúsculas,
-s, enviará los mensajes de estado al archivo compilado por defecto en
suck_config.h.  Por defecto es /dev/null, por eso no será escrito ningún
mensaje en pantalla.  La opción en mayúsculas, -S, requiere el parámetro
de archivo. Todos los mensajes de estado serán enviados a ese archivo.

-e | -E archivo

Estas opciones enviarán todos los mensajes de error (normalmente escritas
a stderr) a un archivo alternativo. La opción en minúsculas, -e, enviará
los mensajes de error al archivo compilado por defecto en suck_config.h.
Por defecto suck.errlog.  La opción en mayúsculas, -E, requiere el
parámetro de archivo.  Todos los mensajes de error serán enviados a
ese archivo.

-N número_puerto

Esta opción indica a testhost un número de puerto NNRP cuando se conecta
al host, en lugar de usar el predeterminado, 119.

-U userid

-P clave

Estas dos opciones te permiten especificar una identificación de usuario
y una clave, si tu servidor NNTP las requiere.

-l archivo_de_frases

Esta opción le indica a testhost a cargar un archivo alternativo de frases,
en vez de usar las frases compilados por defecto.  Esto permite el uso de
testhost con frases en otros idiomas o con mensajes especiales sin tener
que recompilarlo.  VER "FRASES EN IDIOMAS EXTRANJEROS" en suck.1 para más
detalles.

.SH DESCRIPCION
.I Testhost
informará sobre el NNTP servidor de noticias, especificado por
.I hostname.
La acción por defecto es pedir el comando 
.I help
al servidor, para ver que software está ejecutando y qué comandos acepta.
.PP
Si la opción
.I -a
es usada, testhost mostrará la activa history list del servidor. Si la
opción 
.I -n fecha hora
es usada, testhost mostrará todos los nuevos grupos creados en el servidor 
desde la fecha y hora especificadas.
.SH VALORES DE SALIDA
0 satisfactorio, -1 fallo.
.de R$
Esta versión \\$3, \\$4.
..
.SH "VER TAMBIEN"
suck(1), rpost(1), lpost(1).
