.TH scwish 1 "04 Dec 1994" "tkined" "tkined Reference Manual"

.SH NAME
scwish \- a tcl wish interpreter with the scotty extensions

.SH SYNOPSIS
.B scwish
[
.B options
]

.SH DESCRIPTION

scwish is an extended wish(1) interpreter supporting the scotty tcl
extensions. Read the documentation of wish(1) for a description of
options and the documentation of scotty(1) for a description of
tcl extensions provided by scotty.

.SH SEE ALSO
scotty(1), wish(1), Tcl(3)

.SH FILES
$HOME/.scwishrc              	startup commands for scotty

.SH AUTHORS
Juergen Schoenwaelder (schoenw@ibr.cs.tu-bs.de).