.TH STRAPS 8 "Sep 94"
.SH NAME
straps \- a simple SNMP trap-sink
.SH SYNOPSIS
.B straps
.SH DESCRIPTION
The
.B straps
trap demon listens to the snmp-trap port 162/udp (or to the port your
snmp-trap entry in your services map tells it) and forwards the
received events to connected clients (like
.B scotty
).

Because the port 162 needs root access and the port can be opend only
one time, the use of a simple forwarding demon is a good choice.

The 
.B straps
demon is installed with suid root and can therefore started by any
application and user and does not need run at boot time (but may be).

The client can connect to the AF_UNIX domain stream socket
/tmp/.straps and will get the trap-packets in raw binary form: 4 bytes
senders ip address (in network-byte-order), 2 bytes senders port
number (in network-byte-order), 4 bytes data-length (in
host-byte-order) followed by the data-bytes of the packet.

.SH SEE ALSO
scotty(1),tkined(1)
.SH BUGS
The client descriptor should be checked about writability.
.SH AUTHORS
Kaept'n Koerg and Bert Nase (schoenw@ibr.cs.tu-bs.de and
schoenfr@ibr.cs.tu-bs.de).
