'\" t
.\" Man page by Dale Scheetz
.TH SEESAT5.INI 5 "30 March 96" "Debian Linux"
.SH NAME
SEESAT5.INI \- operations control file for seesat5.

.SH DESCRIPTION

.LP
This file is used to automate the operation of seesat5 in a way that reduces
the amount of command line instructions. A sample example file can be found
in /usr/doc/SEESAT5.INI.example. A complete list and description of the
commands that may appear in this init file can be found in seesat5(7).

.SH "SEE ALSO"
seesat5(1), seesat5(7), tle(5), cr(1)
