.\" Copyright 1996 Helmut Geyer <Helmut.Geyer@iwr.uni-heidelberg.de>
.\" 
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.TH LIBPROC_PW 3 "20 October 1996" "Linux Manpage" "Linux Programmer's Manual"
.SH NAME 
user_from_uid, group_from_gid \- lookup ids in /etc/passwd and /etc/group

.SH SYNOPSIS
.nf
.B #include <proc/ps.h>
.sp 
.BI "char *user_from_uid(uid_t " uid ");"
.br
.BI "char *group_from_gid(gid_t " gid ");"

.SH DESCRIPTION
Both functions look up the numeric id and return a pointer to the name
corresponding to the id. If they cannot find an entry matching id,
they return a pointer to a string containing the id with a leading #.

.SH AUTHOR

This manpage was written by Helmut Geyer
<Helmut.Geyer@iwr.uni-heidelberg.de>.