.\" Copyright 1996 Helmut Geyer <Helmut.Geyer@iwr.uni-heidelberg.de>
.\" 
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.TH LIBPROC_DEV 3 "20 October 1996" "Linux Manpage" "Linux Programmer's Manual"
.SH NAME 
name_to_dev, dev_to_name \- lookup device names and numbers
tty_to_dev, dev_to_tty \- lookup tty names and numbers
.SH SYNOPSIS
.nf
.B #include <proc/devname.h>
.sp 
.BI "dev_t name_to_dev(char* " name ");"
.br
.BI "char* dev_to_name(dev_t " num ");"
.br
.BI "dev_t tty_to_dev(char *" tty ");"
.br
.BI "void  dev_to_tty(char *" tty ", dev_t " dev ");"

.SH DESCRIPTION
Using (and updating, if possible) one of the 
.I psdevtab
files (see section FILES) these functions convert device names (names
of special files in /dev/) to device numbers and back. 
.B tty 
functions may use short forms for tty names (i.e. without leading 
.B tty
or 
.BR cu ).
.br
.B dev_to_tty 
will always return the abbreviated name and wants to have a string of
length 4 as argument. Use 
.B dev_to_name
to get the full name.

.SH FILES
.BR /etc/psdevtab ,
.BR /tmp/psdevtab ,
.BR $HOME/psdevtab .

.SH AUTHOR

The device lookup code in libproc was written by Charles L. Blake
(cblake@bbn.com), this manpage was written by Helmut Geyer
(Helmut.Geyer@iwr.uni-heidelberg.de).