.\" Copyright 1996 Helmut Geyer <Helmut.Geyer@iwr.uni-heidelberg.de>
.\" 
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.TH  3 "20 October 1996" "Linux Manpage" "Linux Programmer's Manual"
.SH NAME 

.SH SYNOPSIS
.nf
.B #include <proc/ps.h>
.sp 
.BI
.SH AUTHOR

This manpage was written by Helmut Geyer
<Helmut.Geyer@iwr.uni-heidelberg.de>.