#================================================================
# Makefile for MIDI plug-in for Linux/AWE32 (w/o contorl panel)
# written by Takashi Iwai
#================================================================

#----------------------------------------------------------------
# plug-in destination directory
# /usr/local/lib/netscape/plugins or ~/.netscape/plugins
#----------------------------------------------------------------

PLUGIN_DIR=$(HOME)/.netscape/plugins
# PLUGIN_DIR = /usr/local/lib/netscape/plugins

#----------------------------------------------------------------
# plugin definitions
#----------------------------------------------------------------

# debug flag
# PLUGIN_DEBUG=-DDEBUG_ON

PLUGIN_DEFINES= -DXP_UNIX $(PLUGIN_DEBUG) -DNO_CONPANEL

#----------------------------------------------------------------
# compiler definitions
#----------------------------------------------------------------

CC= gcc
#OPTIMIZER= -g
OPTIMIZER= -O
CFLAGS=  -Wall $(OPTIMIZER) $(PLUGIN_DEFINES)

#----------------------------------------------------------------
# shared object targets
#----------------------------------------------------------------

TARGET=npmidi-nopanel.so

# SHLIBDIR = /usr/X11R6/lib
# EXTRA_LOAD_FLAGS = -Wl,-rpath,$(SHLIBDIR)
# LDFLAGS=-L/usr/X11R6/lib -lXaw -lXt -lX11 -lSM -lICE $(EXTRA_LOAD_FLAGS)

all: $(TARGET)

$(TARGET): midiplg.o npunix.o
	$(CC) -shared -o $@ midiplg.o npunix.o $(LDFLAGS)
	strip $(TARGET)

#----------------------------------------------------------------
# install & clean
#----------------------------------------------------------------

install: $(TARGET)
	mkdir -p $(PLUGIN_DIR)
	cp $(TARGET) $(PLUGIN_DIR)

clean:
	$(RM) *.o *.so


# end of file
