#! /bin/sh
# Feed input to inews, for ihave/sendme mostly.
# ignores arguments

# =()<. ${NEWSCONFIG-@<NEWSCONFIG>@}>()=
. ${NEWSCONFIG-/etc/news/bin/config}

HOME=/dev/null ; export HOME	# suppress signatures, .name, etc.
exec $NEWSBIN/inject/inews -h -W -A
