.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" 
.\" Traduction  10/10/1996 Christophe BLAESS (ccb@club-internet.fr)
.\" 
.TH GETDTABLESIZE 2 "10 Octobre 1996" "Linux 0.99.11" "Manuel du programmeur Linux"
.SH NOM
getdtablesize \- Lire la taille de la table des descripteurs.
.SH SYNOPSIS
.B #include <unistd.h>
.sp
.B int getdtablesize(void);
.SH DESCRIPTION
.B getdtablesize
retourne le nombre maximal de fichiers qu'un processus puisse ouvrir 
simultanement.
.SH NOTES
.B getdtablesize
est implementee comme fonction de bibliotheque DLL 4.4.1.

Cette fonction renvoie
.B OPEN_MAX
(valant 256 sous Linux 0.99.11) si
.B OPEN_MAX
etait defini quand la bibliotheque a ete compilee. 

Sinon \-1 est renvoye,
et
.I errno
contient l'erreur
.BR ENOSYS .
.SH "VOIR AUSSI"
.BR close "(2), " dup "(2), " open (2)
