.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Traduction 15/10/1996 par Christophe Blaess (ccb@club-internet.fr)
.\"
.TH VHANGUP 2 "15 Octobre 1996" Linux "Manuel du programmeur Linux"
.SH NOM
vhangup \- Deconnecte virtuellement un terminal.
.SH SYNOPSIS
.B #include <unistd.h>
.sp
.B int vhangup(void);
.SH DESCRIPTION
.B vhangup
simule une deconnexion du terminal courant.
Cet appel systeme est utilise pour que les autres
utilisateurs aient un ecran de connexion
\*(lqpropre\*(rq.
.SH "VALEUR RENVOYEE"
.B vhangup
renvoie zero s'il reussit, ou \-1 s'il echoue auquel cas
.I errno
contient le code d'erreur.
.SH ERREURS
.TP 0.8i
.B EPERM
L'utilisateur n'est pas Super\-User
.SH "VOIR AUSSI"
.BR init (8)
