#!/bin/sh

set -e

UUTRAFCF=/etc/uucp/uutraf.cf

if [ ! -e ${UUTRAFCF}.dpkg-dist ]
then
    echo ""
    echo "You must tailor your $UUTRAFCF file to your local installation."
    echo "Read the uutraf(5) manual page for explanations about the file format."
fi

exit 0

