.\" Copyright (c) 1995 Frank McIngvale
.\" May be freely distributed in any form.
.TH LuxMan 6 "24 Mar 1995" "LuxMan version 0.41" "Games"
.SH NAME
LuxMan \- A maze game for Linux
.SH SYNOPSIS
.B luxman
[
.B \-r rate
] [
.B \-f file
] [
.B \-8hn
]
.SH DESCRIPTION
.B luxman
is a maze game for Linux, similar to the
.RI ` Pac
.IR Man '
arcade game. It uses SVGAlib, so it runs in a console (as opposed
to running under X).
.LP
.B Some features:
.LP
.TP
\fB* Customizable\fP
You can change the playing order, create new levels, edit
the bitmaps, change colors, change sounds, etc., 
without recompiling the source. See the file
.B HOWTO.Modify
for details.
.TP
\fB* Multiple skill levels\fP
Four to be exact, ranging from pitifully easy
to nearly impossible (well, as far as *I* can tell :).
.TP
\fB* VT Switching\fP
You can switch to/from the game at any time.
.TP
\fB* Digitized sound\fP
Just listen, you'll hear what I mean.
.SH OPTIONS
.TP
\fB\-f\fP \fIname\fP, \fB\-\-file\fP \fIname\fP
Set scenarios filename to \fIname\fP. The default name
is
.B scenarios.
This file may be located either in the current directory
or in
.B /usr/games/lib/luxman.
.TP
\fB\-r\fP \fIrate\fP, \fB\-\-fps\fP \fIrate\fP
Set frame rate to \fIrate\fP.
.TP
\fB\-8\fP, \fB\-\-8k\fP
Use 8kHz sound playback. The default is 11kHz.
This option is considered \fBOBSOLETE\fP. If you
really need this feature, or find it useful, please
e-mail
.B frankm@nuance.com
and tell me.
.TP
\fB-n\fP, \fB\-\-nosnd\fP
Do not use sound. This is on by default if you do not
have a soundcard.
.TP
\fB-h\fP, \fB\-\-help\fP
Show a summary of command line options.
.SH FILES
/usr/games/lib/luxman/scenarios
/usr/games/lib/luxman/modern/levels.def
/usr/games/lib/luxman/oldscen/old.def
.SH BUGS
Please report any bugs to
.B frankm@nuance.com
.SH "SEE ALSO"
.BR
.BR luxchk ( 6 ).
.SH COPYING
Copyright (c) 1995 Frank McIngvale (frankm@nuance.com)
.PP
This manpage may be freely distributed in any form.
