.TH MKNUMERIC 1 "15 March 1994" "Version 1.0"
.SH NAME
.B mknumeric
\- create numeric information file
.SH SYNOPSIS
.B mknumeric
[
.B \-o
.I output_file_name
]
[
.I filename
]
.SH DESCRIPTION
.B mknumeric
is used to create binary file,
describing numeric information
for
.BR setlocale (3).
.I filename
is the name of input file.
If none given,
.I stdin
used.
.SH OPTIONS
.TP
.RI \-o\  output_file_name
Write the output on
.IR output_file_name ;
otherwise,
write the output on a file
named LC_NUMERIC.
.SH INPUT FILE FORMAT
Empty lines and lines beginning with # are ignored.
The backslash character,
\\,
is used for continuation.
No characters are permitted after it.
The following statements are recognized:
.sp
.B codeset
.I codename
.sp
.RS
.I Codename
is the name of codeset. This statement is required.
.RE
.sp
The rest of statements is just the field names of structure
.IR numeric_info .
.SH EXAMPLE
.nf
codeset dummy

decimal_point		"."
thousands_sep		""
grouping		""
.fi
.SH BUGS
None are know at the moment.
If you find any,
feel free to fix.
.SH AUTHOR
Nickolay Saukh - <nms@ussr.EU.net>
.SH ACKNOWLEDGEMENTS
Input language of
.B mknumeric
is based on manual pages of SVR4.0.
.SH FILES
/usr/lib/locale/\fIlocale\fR/LC_NUMERIC
\- LC_NUMERIC database for
.br
/usr/include/localeinfo.h
.I locale
.SH SEE ALSO
.BR setlocale (3),
.BR localeconv (3),
.BR mkcollate (1),
.BR mkctype (1),
.BR mkmonetary (1),
.BR mkresponse (1),
.BR mktime (1)
