.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 18:59:02 1993 by Rik Faith (faith@cs.unc.edu)
.TH MBSTOWCS 3  "March 29, 1993" "GNU" "Linux Programmer's Manual"
.SH NAME
mbstowcs \- convert a multibyte string to a wide character string.
.SH SYNOPSIS
.nf
.B #include <stdlib.h>
.sp
.BI "size_t mbstowcs(wchar_t *" pwcs ", const char *" s ", size_t " n );
.fi
.SH DESCRIPTION
The \fBmbstowcs()\fP function converts a sequence of multibyte characters
from the array \fIs\fP into a sequence of wide characters and stores up
to \fIn\fP wide characters in the array \fIpwcs\fP.
.SH "RETURN VALUE"
\fBmbstowcs()\fP returns the number of wide characters stored or \-1 if
\fIs\fP contains an invalid multibyte character.
.SH "CONFORMING TO"
SVID 3, ISO 9899
.SH "SEE ALSO"
.BR mblen "(3), " mbtowc "(3), " wcstombs "(3), " wctomb (3) 
