.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Sat Jul 24 17:46:05 1993 by Rik Faith (faith@cs.unc.edu)
.TH TMPNAM 3  "April 3, 1993" "GNU" "Linux Programmer's Manual"
.SH NAME
tmpnam \- create a name for a temporary file
.SH SYNOPSIS
.nf
.B #include <stdio.h>
.sp
.BI "char *tmpnam(char *" s );
.fi
.SH DESCRIPTION
The \fBtmpnam()\fP function generates a unique temporary filename 
using the path prefix \fIP_tmpdir\fP defined in \fI<stdio.h>\fP.  
If the argument \fIs\fP is NULL, \fBtmpnam()\fP returns the address 
of an internal static area which holds the filename, which is 
overwritten by subsequent calls to \fBtmpnam()\fP.  If \fIs\fP is 
not NULL, the filename is returned in \fIs\fP.
.SH "RETURN VALUE"
The \fBtmpnam()\fP function returns a pointer to the unique temporary 
filename, or NULL if a unique name cannot be generated.
.SH "ERRORS"
.TP
.B EEXIST
Unable to generate a unique filename.
.SH "CONFORMING TO"
SVID 3, POSIX, BSD 4.3, ISO 9899
.SH "SEE ALSO"
.BR mktemp "(3), " mkstemp "(3), " tempnam "(3), " tmpfile (3)
