.TH sfxload 1 "March 17, 1997"
.LO 1
.SH NAME
sfxload \- load a SoundFont file on the AWE32 sound driver
.br
.SH SYNOPSIS
sfxload [\-IixBv] [\-m mode] [\-b bank] [\-c chorus] [\-r reverb]
[\-V volume] [\-P path1:path2:pathN] soundfile [datafile]
.SH DESCRIPTION
.B sfxload
transfers the sound wave and instruments data of SoundFont file
to the AWE32 sound driver.
.B sfxload
can read the original SoundFont (SF2 or SBK) file and
the converted SFX file
(see txt2sfx(1)).
If it reads an SFX file and no wave data is included in the file,
additional argument
.I datafile
must be specified for corresponding SoundFont file.
If the sound file is SF2 or SBK file,
or instruments in the SFX file use only ROM samples,
.I datafile
is not required.

The sound files are searched through the path list given by the
environment variable
.B SFBANKDIR
or the command line option
.I -P.
The file extension .sfx, .sf2, and .sbk can be abbreviated.

.SH OPTIONS
.TP
.B \-I
Initialize Emu8000 chip in AWE32.
This is occasionally necessary when sample tranfer fails frequently.
.TP
.B \-i
Clean up all samples on the driver before loading.
.TP
.B \-x
Remove only the last loaded samples.
Otherwise, samples are appended after the last sample.
.TP
.B \-c " chorus"
Specify the effects of chorus.
The value is in percent, from 0 to 100.  The default value is zero.
This value may be overwritten by MIDI control messages.
.TP
.B \-c " reverb"
Specify the effects of reverb.
The value is in percent, from 0 to 100.  The default value is zero.
This value may be overwritten by MIDI control messages.
.TP
.B \-B
Add 48 size of blank loop on each sample data.
To be compatible with the older sfxload, specify this option.
.TP
.B \-v
Increase verbosity level.
Many information like maximum number of samples and instruments using
this option can be checked.  More -v cause more verbose outputs.
.TP
.B \-m " mode"
Change the instrument search mode for multiple defined instruments:
0=first, 1=last, and 2=merge(default)
modes, respectively.  If this options is 0, only the first instrument
is used and other instruments in the same preset are ignored.
If this is 1, the last instrument is used instead.  Otherwise, all the
instruments in the preset are merged.
.br
The AWE driver v0.2 or older doesn't support the multiple instrument
layers, and may produce different sounds if using last or merge mode.
If you wan to keep the older sounds, use first (-m 0) mode.
.TP
.B \-b " bank"
Replace bank number of default bank samples (bank 0).
This option is necessary to load user bank, usually in bank one.
For example,
.in +1i
% sfxload -i -r 10 -c 10 gm.sfx
.br
% sfxload -b 1 surprise.sf2
.br
.in -1i
.TP
.B \-V " volume"
Specify the total volume of sounds, provided in percent.
The default volume is 70%.
.TP
.B \-P " path1:path2:pathN"
Specify the search path list.
The sound files are searched from
.I path1, path2,
and so on.
This overrides the environment variable
.B SFBANKDIR.

.SH ENVIRONMENT
.TP
.B SFBANKDIR
Search path for sound files.  The current directory is searched
at last if this variable is set.

.SH "SEE ALSO"
drvmidi(1)

.SH COPYRIGHT
Copyright (C) 1996,1997 Takashi Iwai.
.P
The AWE32 driver and utilties are free software; you can redistribute them
and/or modify them under the terms of the \fIGNU General Public
License\fP as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.
