.TH suidunregister 1L "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
suidunregister \- Remove special binary from the registry
.SH SYNOPSIS
\fBsuidunregister [ -s package ] file
.SH DESCRIPTION
Remove the file from the suid registry.
.SH EXAMPLE
suidunregister /usr/bin/sendmail
.SS AUTHOR
Christoph Lameter <clameter@debian.org>
