.TH suid.conf 1L "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
suid.conf \- Configuration file for files with special permissions
.SH DESCRIPTION
suid.conf contains lines describing the permissions for files on your system
and information about who (user or a package) is responsible for making this
binary so special.
.PP
suid.conf contains lines of the form
.PP
whodoneit file user group mode
.PP
Where "whodoneit" is either the package name responsible for installing the
settings or "user" for a user override. Lines beginning with # are comments
and empty lines are ignored.
.PP
Example line:
.PP
sendmail /usr/bin/sendmail root mail 2755
.PP
Example override:
.PP
user /usr/bin/sendmail root root 4755 
.PP
If a package has been prepared for suidmanager then that package will
generate lines in /etc/suid.conf on installation. The administrator can then
change those permissions and the permissions will be kept intact across
upgrades. You can change permission with the
.B suidregister
command. Please do not specify a package name with -s if you do local
customization so that you changes can be specially marked with "user" and
kept. If the whodoneit field is a package name then that package has
absolute authority over the binary and can change permissions at will.
.PP
If a package installs setgid/setsid binaries and does not implement
suidmanager then you have to run
.B suidregister
after each upgrade to reset the permissions after the package has
overwritten the binaries with your permissions.
.SH AUTHOR
Christoph Lameter <clameter@debian.org>
