
/*
    xskat - a card game for 1 to 3 players.
    Copyright (C) 1996  Gunter Gerhardt

    This program is free software; you can redistribute it freely.
    Use it at your own risk; there is NO WARRANTY.
*/

#undef EXTERN
#ifdef TEXT_C
#define EXTERN
#else
#define EXTERN extern
#endif

enum {
  TX_NULL,TX_KARO,TX_HERZ,TX_PIK,TX_KREUZ,TX_GRAND,
  TX_AS,TX_ZEHN,TX_KOENIG,TX_DAME,TX_BUBE,TX_NEUN,TX_ACHT,TX_SIEBEN,
  TX_A,TX_10,TX_K,TX_D,TX_B,TX_9,TX_8,TX_7,
  TX_HAND_GESP,TX_SCHN_ANGE,TX_SCHW_ANGE,
  TX_OUVE_GESP,TX_OUVE_HAND_GESP,
  TX_PASSE,TX_JA,TX_NEIN,TX_SPIELER,TX_COMPUTER,TX_LINKS,TX_RECHTS,
  TX_DRUECKEN,TX_SPIELT,TX_OUVE_HAND,TX_OUVE,TX_HAND,TX_OUVERT,
  TX_UEBERLEGT,TX_GEREIZT_BIS_N,TX_LOESCHEN,TX_SPIELTE,
  TX_GEWONNEN,TX_VERLOREN,TX_AUGEN,
  TX_UEBERREIZT,TX_SCHNEIDERFREI,TX_NICHT_SCHWARZ,
  TX_DER_A_GEWINNT,TX_DER_A_VERLIERT,
  TX_DAS_NULLSPIEL,TX_DAS_SPIEL_SCHWARZ,TX_MIT_AUGEN,
  TX_HAND_F,TX_SPIEL_BEENDEN,TX_SPIELENDE,TX_BEENDET_DAS_SPIEL,TX_AHA,
  TX_LOESCHEN_F,TX_SPIEL,TX_SCHNEIDER,TX_SCHWARZ,TX_ANSAGEN,TX_HINWEIS,
  TX_F1,
  TX_F2,
  TX_F3,
  TX_F4,
  TX_U1,
  TX_U2,
  TX_U3,
  TX_U4,
  TX_ANGESAGT_IST,TX_RESULTAT,TX_DER_SPIELWERT_IST,TX_ENDE,
  TX_PROTOKOLL,TX_WEITER,TX_PROTOKOLL_T,
  TX_IM_SKAT_IST,
  TX_IM_SKAT_WAR,
  TX_GEREIZT_BIS,
  TX_GEWO_MIT,
  TX_VERL_MIT,
  TX_SPIELLISTE,TX_SPIELLISTE_T,TX_XSKAT,
  TX_COPYRIGHT,TX_EMAIL,
  TX_SORTIEREN,TX_AUFWAERTS,TX_ABWAERTS,TX_ALTERNIEREND,TX_SEQUENTIELL,
  TX_NORMAL,
  TX_GEREIZT_BIS_L,TX_GESPIELT_WIRD,TX_LETZTER_STICH,TX_GEDRUECKT,
  TX_DU_BIST_DRAN,TX_VORDEFINIERTES_SPIEL,TX_SPEICHERN,
  TX_FR1,
  TX_FR2,
  TX_FR3,
  TX_FR4
};

EXTERN char **textarr;
EXTERN int lang;
