[netcom.com]
  User     Real Name                 Idle  TTY  Host      Console Location
aaronm   Aaron D. McClure            0:10   t2 netcom16 (NETCOM-pa11.netc)
aasmok   Kristian D. Aasmo                  q0 netcom7  (NETCOM-dc6-1.net)
achilles Who Cares?                  0:24  *p7 netcom22 (205.199.152.104)
acmorton Ann Morton                         pa netcom16 (NETCOM-wc1.netco)
acoustic Yee On Lo                          t2 netcom9  (NETCOM-pa1.netco)
action   Don Lawrence                       pb netcom12 (NETCOM-la19.netc)
addison  Michael Addison Reed               qb netcom17 (NETCOM-la19.netc)
agok     ali gok                            p6 netcom4  (NETCOM-sj19.netc)
akama    Tae Ho Kim                         qf netcom17 (NETCOM-sj10.netc)
albertc  Albert Cheng                       qf netcom19 (NETCOM-sj24.netc)
aldridge J Aldridge                         pb netcom6  (NETCOM-pl1.netco)
aldridge J Aldridge                         pd netcom3  (NETCOM-pl2.netco)
alegado  Eric F. Alegado                    q2 netcom13 (NETCOM-pas12.net)
alive    Singer of Songs                    q5 netcom11 (NETCOM-wc6.netco)
amaslam  Ahmed Aslam                        pf netcom20 (NETCOM-nyc14.net)
amethyst Gerrit Kruidhof             0:02   p4 netcom6  (NETCOM-pa6.netco)
amuro    Dickinson Lo                       qa netcom22 (NETCOM-ir15.netc)
amyn     Amy N.                             pb netcom2  (NETCOM-sj10.netc)
animale  *                                  r8 netcom10 (NETCOM-sd9.netco)
apn      Advanced Prion Nomostatics         t7 netcom17 (NETCOM-sj18.netc)
arbuss   Steve Arbuss                0:19   q1 netcom16 (NETCOM-la18.netc)
arithmos Arithmos Inc                       qb netcom4  (NETCOM-pa4.netco)
armyman  Umar I Mallic                      s2 netcom21 (NETCOM-lb8.netco)
ataru    Mark Bradley                       qb netcom23 (NETCOM-clv1.netc)
aturco   Art Turco                   0:01   q2 netcom10 (NETCOM-ir15.netc)
awells   Adam B. Wells                     *pa netcom9  (NETCOM-sj11.netc)
b222527  Kevin                              q4 netcom3  (NETCOM-lb5.netco)
babylon5 Richard Krider                     q3 netcom5  (NETCOM-sf13.netc)
badboy   Jay Keller                  1:09   q3 netcom23 (netcom12)
badboy   Jay Keller                         qf netcom12 (NETCOM-sj23.netc)
badkarma                                    q6 netcom14 (NETCOM-pl4.netco)
baily    Richard "Dr." Baily         0:06   p5 netcom3  (NETCOM-pas12.net)
banquo   sean stephens               1:09   q3 netcom19 (NETCOM-lb5.netco)
barce    James Barcelona                    p4 netcom2  (NETCOM-sf5.netco)
bartfai  Zsuzsanna Ba'rtfai                 r9 netcom5  (NETCOM-sj21.netc)
batesole UNIX System Administration         r0 netcom19 (NETCOM-sj13.netc)
bauman   Blake Bauman                       pf netcom17 (NETCOM-la20.netc)
bblp1    Big Bird                    0:11   p5 netcom7  (NETCOM-pas11.net)
bbs      berzinas                           q5 netcom9  (NETCOM-sac4.netc)
bc1      Bob Campbell                       s0 netcom13 (NETCOM-atl15.net)
bckdrmn  Dave Gotwisner                     q5 netcom15 (NETCOM-pl5.netco)
bcre8ive Alex Lam                    0:31   p5 netcom17 (NETCOM-sac5.netc)
beetle   Beetle                            *s7 netcom3  (NETCOM-pas10.net)
beker    Brian Beker                 2:10   pa netcom23 (NETCOM-la1.netco)
beoj     Joseph Embree                      q9 netcom13 (NETCOM-den10.net)
beowulfs michael ellis                      p2 netcom9  (NETCOM-cin1.netc)
besnode  Paul and Michele                   sd netcom3  (NETCOM-pas11.net)
betts    Jonathan Betts              3:02   p8 netcom15 (204.152.97.90)
bhayes   Bill Hayes                         r2 netcom4  (NETCOM-pl4.netco)
bilbo    HeAdChEesE                         p4 netcom14 (NETCOM-sj25.netc)
bishpnc  david shaffer               0:03   p9 netcom6  (netcom11)
bishpnc  david shaffer               0:06   p9 netcom11 (NETCOM-sd8.netco)
blade    Dwight Mcgowen/Tracy Brown         pf netcom2  (NETCOM-sj16.netc)
blair5   Blair Family                       r7 netcom13 (NETCOM-wc7.netco)
blamar   Blake and/or Marla          0:01   p3 netcom   (camad1.camosun.b)
blckflag Black Flag                         td netcom4  (NETCOM-aus2.netc)
blevin   Bryan Levin                       *qb netcom19 (NETCOM-pa9.netco)
bloke    Bloke                       1:16   sb netcom12 (NETCOM-den10.net)
bluejay  Thomas Burnfin              0:17   q4 netcom15 (NETCOM-sf6.netco)
bmf      Kenneth Lu                         pf netcom14 (NETCOM-al6.netco)
bmfrosty Bad Mr. Frosty                    *qc netcom5  (NETCOM-al2.netco)
bmfrosty Bad Mr. Frosty                    *p4 netcom7  (netcom5)
bnorvell Brock Norvell                      p7 netcom3  (NETCOM-den13.net)
bnunes   Brian Nunes                       *p1 netcom23 (NETCOM-la18.netc)
bobrow   Jordan Bobrow                      q6 netcom17 (NETCOM-pa6.netco)
bobster  Robert Mosher               0:04   p5 netcom9  (NETCOM-or10.netc)
bolan    Don Carroll                        s2 netcom19 (NETCOM-ir15.netc)
boojum   Jeffrey J. Mancebo                 rc netcom3  (NETCOM-sj22.netc)
bored    Atreides                           p4 netcom22 (NETCOM-lv6.netco)
boserj   Jeffrey Boser                     *qb netcom12 (NETCOM-lv3.netco)
bradleym Bradley                           *q4 netcom12 (NETCOM-pl8.netco)
bradleym Bradley                           *r6 netcom14 (netcom12)
breadstx Chris Ogle                         pa netcom5  (NETCOM-aus2.netc)
breon    breon moore                        q7 netcom17 (NETCOM-sf16.netc)
brg      Bruce R. Gilson                    r9 netcom17 (NETCOM-dc6-1.net)
briden   AMB                                qa netcom19 (NETCOM-den13.net)
browder  Dustin Browder                     p3 netcom3  (NETCOM-la3.netco)
bryant   Bryant                            *r7 netcom18 (NETCOM-sj28.netc)
bsanders Brian Sanders               0:02  *pd netcom16 (NETCOM-pl1.netco)
bstern   Betsy Stern                        p6 netcom8  (NETCOM-al3.netco)
btm      Brent Matthews                     q6 netcom7  (NETCOM-sj26.netc)
bub      Joseph Leigh                       p7 netcom23 (NETCOM-sj13.netc)
buffy    Cheryl Qualls                      p5 netcom11 (NETCOM-atl6.netc)
burnout  Cory Fasbender              1:30   u5 netcom6  (NETCOM-pa11.netc)
busgirl  Martha                            *p4 netcom13 (NETCOM-al3.netco)
bytelock todd k. kramer                     pe netcom6  (NETCOM-den10.net)
cajun    Seth Shealer                       r7 netcom7  (NETCOM-mia1.netc)
caliph   John Luzar                         qb netcom6  (NETCOM-pl2.netco)
carrs    Amethyst                          *q6 netcom8  (NETCOM-lv3.netco)
carterg  Gil Carter                         pc netcom   (129.72.60.2)
casas    Robert Casas                       q8 netcom11 (NETCOM-chi12-1.n)
caslis   Russell Caslis                     pe netcom20 (NETCOM-sj30.netc)
cass     Cassandra                   1:23   ra netcom13 (NETCOM-dc15-1.ne)
catshous Bob Walker                         p4 netcom19 (NETCOM-sd9.netco)
cawhite  Carl White                  0:04   p8 netcom21 (ottgate.bnr.ca)
cb12     Christopher Blome           0:05   p6 netcom2  (NETCOM-dfw9.netc)
cdavis   Chris Davis                        p5 netcom14 (NETCOM-aus2.netc)
cdavis   Chris Davis                        pa netcom8  (netcom14)
ceichert Carl J. Eichert             0:05   p5 netcom4  (NETCOM-lb8.netco)
cfr1     Christopher Randall                qb netcom2  (NETCOM-pa9.netco)
cfrancis Charles Francis             1:34   sc netcom4  (NETCOM-mia2.netc)
cfwong   Chun Wong                          qe netcom18 (NETCOM-sj10.netc)
chaglund Cat Haglund (ftoast)               q1 netcom3  (NETCOM-al2.netco)
chalky   John McCauley               7:58   t0 netcom19 (office2.netcom.c)
chamw    Chamindra Weerasinghe              q1 netcom   (netcom4)
chamw    Chamindra Weerasinghe              q1 netcom4  (NETCOM-sj21.netc)
chewy    Chewy                              pa netcom11 (NETCOM-dfw10.net)
chuckm   Charles Montague                   pe netcom14 (NETCOM-dc6-1.net)
ckerr    Chris Kerr                         qd netcom17 (NETCOM-sd6.netco)
clas     Charles L. Arnold                  pe netcom16 (NETCOM-sd8.netco)
clb      Charles L. Brost                   q1 netcom22 (NETCOM-sd8.netco)
cnishida Craig H. Nishida                   q8 netcom9  (NETCOM-sf17.netc)
cnwong   carolyn wong                       s4 netcom13 (NETCOM-pl3.netco)
coan     John Coan                          p5 netcom8  (NETCOM-rtp4.netc)
cobalt   Laura Torrano                      pb netcom21 (NETCOM-prn1.netc)
colinr   Colin Robertson             0:02   q2 netcom16 (NETCOM-sea5.netc)
comtec                                      sd netcom16 (NETCOM-ir15.netc)
consult  consult                            s9 netcom9  (NETCOM-pa9.netco)
coop     The Real Coop                     *q2 netcom20 (NETCOM-aus2.netc)
cosmos   Gerald Penaflor                    pc netcom11 (NETCOM-sj11.netc)
cptater  James Sucky                        r5 netcom18 (NETCOM-col1.netc)
cpugh    Chris Pugh                         rf netcom5  (NETCOM-sj13.netc)
creol    Fred Chavez                        s1 netcom6  (NETCOM-al11.netc)
cricket  Tod Owens                          s8 netcom6  (NETCOM-lv3.netco)
crincon  chris rincon                0:01   qa netcom14 (NETCOM-sj14.netc)
croyston Chris Royston               0:26   p4 netcom15 (NETCOM-sac10.net)
cst      Christian Tice                     r3 netcom3  (NETCOM-sj27.netc)
ctk      Chris Kaiser                       p9 netcom19 (NETCOM-dc7-1.net)
ctseitz  Christin Seitc                     qe netcom17 (NETCOM-sj34.netc)
cuehara  Christian Uehara                   rf netcom8  (NETCOM-sj24.netc)
cuffs    vanessa zenzmaier           4:04   q2 netcom17 (NETCOM-dfw9.netc)
cyrillv  Cyrill Vatomsky                   *td netcom13 (NETCOM-sc5.netco)
dabronx  Karen Greene                       p2 netcom13 (NETCOM-al6.netco)
dadams   Dean Adams                  0:02   s0 netcom16 (NETCOM-wh6.netco)
daemon9  Route                              q0 netcom10 (NETCOM-lv3.netco)
danhuver Dan Huver                          p1 netcom20 (NETCOM-sj13.netc)
danny7   Jeong-Gi Cho                       p3 netcom15 (NETCOM-ir14.netc)
danos    Dan Osterlund               0:08   s8 netcom12 (NETCOM-nyc5.netc)
daveap   David Peterson              0:03   pf netcom15 (NETCOM-sea7.netc)
daverich David Richards                     q6 netcom4  (NETCOM-ir14.netc)
davidher david her                          q3 netcom3  (NETCOM-pl4.netco)
davidsc  David S. Collett                   p2 netcom   (comnet.ksc.net.t)
daw      Daniel Weinstein                   p4 netcom10 (NETCOM-wc1.netco)
dbakin   David S. Bakin              0:01   t0 netcom15 (NETCOM-sf9.netco)
dbongard Dan Bongard                 0:01   p2 netcom18 (NETCOM-sd8.netco)
dcanada  BoYz FrOm Da HoOd!                 p8 netcom10 (NETCOM-pl1.netco)
dcoakley dorothy coakley                    pd netcom2  (NETCOM-al6.netco)
dcohen   David Cohen                        pd netcom4  (NETCOM-la21.netc)
ddavid   Dennis David               11:10   s2 netcom8  (dida.netcom.com)
deang    Dean Grandquist             4:02   qb netcom16 (NETCOM-pl5.netco)
debbie   debbie ann                         p2 netcom12 (NETCOM-sf5.netco)
del      David Whittemore            9:23   r8 netcom22 (vergiftung.netco)
del      David Whittemore            9:05   qd netcom   (vergiftung.netco)
demon666 666                                u1 netcom20 (NETCOM-bos9.netc)
derald   Derald Sue                         tc netcom15 (NETCOM-al12.netc)
design   Design and Delivery                r3 netcom15 (NETCOM-al3.netco)
despair  despair                            p9 netcom3  (NETCOM-den10.net)
devtrix  Matthew B. Wood             0:02   ra netcom21 (nyquist.noc.netc)
dewshine Sh'k'anna Korra'ti                 ra netcom18 (NETCOM-sea4.netc)
dfd      David Charlton                     q9 netcom14 (NETCOM-pas11.net)
dfwnero  Robert Shaun Bartoo         0:01   pd netcom15 (NETCOM-dfw12.net)
dhl1     David Hugh Lewis                   p8 netcom   (einstein.technet)
dimitri  Dimitri I. Rakitine                t3 netcom18 (NETCOM-sr3.netco)
diony    Ayse                               r9 netcom12 (office4.netcom.c)
dis      Kurt Jacobsen              12:24   r4 netcom3  (NETCOM-wh3.netco)
dizy     Major D                     0:02   q4 netcom2  (NETCOM-sd9.netco)
dkershaw Dan Kershaw                 8:25   ta netcom20 (NETCOM-sr3.netco)
dlam     The_Lonely_One                     qd netcom21 (NETCOM-sj35.netc)
dleong   David Leong                 0:02  *q5 netcom21 (NETCOM-sj34.netc)
dmessiah Evan Brewerr                      *ra netcom20 (NETCOM-wc1.netco)
dmp      D and M Products                   qf netcom14 (NETCOM-pl3.netco)
dna      David Altekruse                   *pd netcom5  (NETCOM-pa7.netco)
dobe     lynn petrangelo                    pf netcom22 (NETCOM-wc7.netco)
doccon   judi stutz                        *pd netcom7  (NETCOM-ir13.netc)
dorlic   Dan Orlic                          q4 netcom   (VMS1.TAMU.EDU)
douglasw Douglas Wallace             0:15   pc netcom18 (NETCOM-nyc11.net)
draperm  Rulon Anderson                     q0 netcom15 (NETCOM-pl1.netco)
drd3524  David Diaz                  0:01   p8 netcom20 (NETCOM-dfw10.net)
drdoom   Dr. DooM                          *qb netcom9  (netcom23)
drdoom   Dr. DooM                          *q5 netcom4  (NETCOM-lv6.netco)
drdoom   Dr. DooM                    0:08  *q7 netcom23 (netcom4)
dreed    David Reed                         qc netcom4  (NETCOM-sj12.netc)
dregg    Cyrus H. Lendvay                   q9 netcom6  (NETCOM-sac4.netc)
dricket  Doug Ricket                        t3 netcom21 (NETCOM-sj26.netc)
drkhoe   Dr. Mosh                           q9 netcom16 (NETCOM-lb6.netco)
dror     Oz Dror                     0:02  *p0 netcom15 (NETCOM-la21.netc)
dshih    David Shih (Shy)            0:04   r7 netcom12 (NETCOM-pa3.netco)
dsickler Doug Sickler                       p0 netcom8  (NETCOM-sac7.netc)
dsnakao  David                       0:04   q0 netcom5  (netcom11)
dsnakao  David                              p2 netcom11 (netcom4)
dsnakao  David                             *pa netcom4  (NETCOM-lb6.netco)
dynamic  John D. D. Keighley                qa netcom9  (NETCOM-la22.netc)
eamon    Chuck Taggart                      p3 netcom14 (NETCOM-wc3.netco)
eblade   Who the Hell are you?       0:02   q4 netcom5  (pm041-kz.mich.ne)
edry     Edward Dry                         q3 netcom9  (NETCOM-la2.netco)
edwink   Edwin Khachatourian                qc netcom2  (netcom2)
edwink   Edwin Khachatourian                p2 netcom21 (NETCOM-pas10.net)
elmopons Elmo Ponsdomenech           0:01   q9 netcom11 (NETCOM-la21.netc)
emegas   Megas of Vecanti                   p8 netcom19 (NETCOM-la3.netco)
emir     God is Awesome                    *r0 netcom14 (cyber.net)
emoor    Ernie Moor                         q9 netcom2  (NETCOM-pl2.netco)
epk      Edward P. Krauss            1:25  *p3 netcom20 (NETCOM-al6.netco)
equitz1  Will Equitz                 0:21   qe netcom15 (NETCOM-pa8.netco)
equitz1  Will Equitz                        p8 netcom4  (NETCOM-pa7.netco)
estero   Aura Herring                       q1 netcom15 (NETCOM-pas12.net)
eugenia  Peter Chen                         pe netcom17 (NETCOM-pl5.netco)
exeter   John Chernoff                      qb netcom22 (NETCOM-sj13.netc)
exorder  Wanna play }=>              0:05  *s1 netcom16 (NETCOM-sac4.netc)
factor   Robert Walsh                       q7 netcom10 (NETCOM-sf11.netc)
falstaff anthony m. vervoort         0:21   q8 netcom5  (NETCOM-sc5.netco)
farinaz  Farinaz Raissi                     q7 netcom15 (NETCOM-sj21.netc)
fariss   Gary B. Fariss                    *q1 netcom14 (NETCOM-sj24.netc)
farooq   Farooq S. Khan              0:11   pd netcom23 (paknet.vip.best.)
farrago  D'Maris D. Coffman          0:08   q7 netcom21 (SHDH116-W16.WHAR)
fdd      Ford Davies                        pa netcom18 (NETCOM-sac6.netc)
fdp      Ciccio                             qa netcom12 (NETCOM-wc6.netco)
feedee   Karen P. Jones                     pa netcom20 (NETCOM-den10.net)
ferrett  Rene Martinez                      pd netcom20 (NETCOM-mia1.netc)
firekat  Kathryn Hormann                    tc netcom22 (NETCOM-sf12.netc)
fizz     FIZZ                              *qf netcom13 (NETCOM-sj34.netc)
fizz     FIZZ                              *p8 netcom12 (netcom13)
flux9                                0:01   q9 netcom10 (NETCOM-or11.netc)
foont    Uber Fonken                        q5 netcom17 (NETCOM-atl10.net)
fopp     jeff lindsey                0:02  *p0 netcom16 (NETCOM-lv4.netco)
forever  Greenwood Forever!                 p1 netcom21 (NETCOM-nyc13.net)
fork     Foobar                             qd netcom7  (NETCOM-wp1.netco)
foxtx    Josh Busby                         pa netcom   (jbusby.ICSI.Net)
freedom  Steve Legasto                      pf netcom6  (NETCOM-al6.netco)
fritzy   Brent Whisenant                    pd netcom18 (NETCOM-atl6.netc)
fshmongr Jon Haug                    0:02   p7 netcom5  (NETCOM-al6.netco)
fstclair Frank St. Claire            0:01   p2 netcom22 (NETCOM-dfw9.netc)
fur      Peter Formica                      q0 netcom2  (NETCOM-sj29.netc)
fvlaming frank vlamings                     q7 netcom7  (NETCOM-pl3.netco)
galend   Galen Davis                 0:02   p0 netcom6  (NETCOM-aus3.netc)
gam      Gordon Moffett                     r0 netcom17 (NETCOM-or11.netc)
gasman   Daniel Kaminsky                   *p9 netcom15 (NETCOM-sf8.netco)
geeze    Kiley Clark                        pf netcom18 (NETCOM-sd10.netc)
genechen Gene Chen                          q5 netcom6  (NETCOM-pas10.net)
genj     rick aulp                          q5 netcom8  (NETCOM-sj26.netc)
gentile  Don Gentile                 0:01  *p4 netcom12 (NETCOM-sj13.netc)
george11 George Stamatopoulos               q4 netcom20 (NETCOM-sf7.netco)
gerber   Trevor Tarr                        pc netcom22 (NETCOM-pas11.net)
ghost16  Troy Jackson                       p3 netcom21 (NETCOM-phi3.netc)
gif      Gifka Sovereign                    r9 netcom14 (NETCOM-la21.netc)
gilles   Gilles  Bacon                      pc netcom13 (NETCOM-nyc9.netc)
gking    Stephen Clark                      p8 netcom14 (NETCOM-wc1.netco)
gmarquez Richard Marquez                    p7 netcom17 (NETCOM-sf10.netc)
gnas     Peter Gnas                         p1 netcom13 (NETCOM-lv4.netco)
gndrflx  Billie Jean                        p8 netcom16 (NETCOM-sac5.netc)
godfther godfather                   4:10   r3 netcom8  (netcom14)
godfther godfather                   4:15   qe netcom14 (NETCOM-dfw14.net)
goshen   Shmuel Goshen                      p4 netcom20 (NETCOM-pa1.netco)
gradubid Claire Normand                     q6 netcom5  (NETCOM-pa6.netco)
grain    Peter Ehrlich                      qf netcom4  (NETCOM-la19.netc)
greggwb  Gregory W. Blas                    qc netcom22 (greggwb.slip.net)
gregoire Greg B.                            q2 netcom15 (NETCOM-lb7.netco)
grey     Grey Death - Digital Targe         p8 netcom6  (NETCOM-mon5.netc)
grindoom Daryth Kendrickson          0:03   rf netcom14 (rocky.ucdavis.ed)
grip                                        pa netcom7  (NETCOM-sj21.netc)
groo     Kiran Wagle                        q4 netcom10 (NETCOM-dc7-1.net)
guardian Andrew Denton                      q2 netcom11 (NETCOM-sc6.netco)
guardian Andrew Denton                      qd netcom19 (netcom11)
gwolfe   Graham Wolfe                       q0 netcom3  (NETCOM-al11.netc)
haag     Stephanie Haag                     pc netcom4  (NETCOM-tam2.netc)
hager    Sean Hager                         s2 netcom15 (NETCOM-atl16.net)
haku     kevin Perreira                     qc netcom12 (NETCOM-wc1.netco)
halanker Hal Anker                          pb netcom3  (NETCOM-sd10.netc)
halex    Alexander Hurwitz                  p7 netcom10 (NETCOM-pa1.netco)
halo     Alex Huang                         r5 netcom5  (NETCOM-pa1.netco)
hammitt  James A. Hammitt                   t1 netcom12 (NETCOM-lb8.netco)
hammonds Kenneth Hammonds            0:11   p0 netcom10 (NETCOM-la19.netc)
hanagar  Dave Brombaugh                     r3 netcom12 (NETCOM-sea7.netc)
hanson   Hanson T.                          p5 netcom22 (werple.mira.net.)
harmony  Tara Lynch                         p9 netcom12 (NETCOM-pa4.netco)
haroon   Omar Haroon                        p4 netcom16 (NETCOM-la1.netco)
harta    Adam Hart                          pc netcom8  (NETCOM-wc7.netco)
hary     Jim Rhoads                         pb netcom9  (NETCOM-lv3.netco)
hausmanc TheFixer                           p5 netcom6  (NETCOM-pa4.netco)
hawk2    hawky                       0:40  *p6 netcom6  (somebody.punk.ne)
heathn   Heath Newburn                      s4 netcom4  (NETCOM-aus3.netc)
hhannam  holly hannam                       sf netcom2  (NETCOM-ir5.netco)
hogaboam Andrew Hogaboam             1:54   q2 netcom22 (ix-sj24-28.ix.ne)
holl     Ignatz the Horrible                s5 netcom15 (NETCOM-sj14.netc)
hoodr    Robert Hood                 0:02  *t6 netcom9  (admin.noc.netcom)
hozey    Howard Jones                       r7 netcom19 (NETCOM-sf6.netco)
hsing    johnny wang                        t3 netcom14 (NETCOM-sf17.netc)
htoo                                 0:03   q7 netcom6  (NETCOM-wc1.netco)
huangjac Jason Huang                        q8 netcom12 (NETCOM-la20.netc)
ia       Litton Industrial                  p1 netcom5  (NETCOM-pl8.netco)
igorg    Igor Gurovich               0:12   r9 netcom18 (NETCOM-sf17.netc)
imagine  Michael Tenery              7:55   s5 netcom7  (NETCOM-atl10.net)
ine      Emily Chhor                        p7 netcom20 (NETCOM-la20.netc)
ine      Emily Chhor                        pb netcom7  (NETCOM-la21.netc)
inf8ltd  Benjamin Wang                      p1 netcom15 (NETCOM-lb9.netco)
ironic   Fruits Of Nature...aka cIV         q3 netcom14 (NETCOM-lb5.netco)
jackkolb Jack Kolb                          q2 netcom2  (NETCOM-la1.netco)
jacobe   Gail Kenner                        p0 netcom18 (NETCOM-sac5.netc)
jaegerms jaegerms@netcom.com               *p4 netcom   (bighorn.accessnv)
jagatai  Lars Jagatai Bunch                 q0 netcom20 (NETCOM-pas12.net)
jakala   henry jakala                       pe netcom21 (NETCOM-chi13-1.n)
jamesbur Robert Burnett                     q4 netcom4  (NETCOM-sj16.netc)
jamwal   A J                                r1 netcom20 (NETCOM-sj12.netc)
jaraq    Brian Haines                       p9 netcom21 (NETCOM-cin4.netc)
jau      Jennifer Au                        s5 netcom11 (NETCOM-lb5.netco)
jaycheng SHOU-JEI CHENG                     p9 netcom7  (NETCOM-pl2.netco)
jbeheler Joey Beheler                0:10   pf netcom7  (NETCOM-pa4.netco)
jch      Chia-Hwong Hwang                   qa netcom3  (NETCOM-sj34.netc)
jchap    John Chappelear                   *t2 netcom3  (NETCOM-sac5.netc)
jconklin J.T. Conklin                      *q9 netcom4  (NETCOM-sf6.netco)
jeffml   Jeff Lightfoot                     p3 netcom17 (131.36.128.128)
jeffsyl  *Unknown*                          qd netcom5  (NETCOM-sea4.netc)
jeffx    Jeff Crilly                        q8 netcom19 (NETCOM-pa3.netco)
jend     Jennifer M. Douglas         1:43   r0 netcom   (ix-sc5-24.ix.net)
jerel    Jerel E. Ellison            0:54   p2 netcom19 (NETCOM-sj23.netc)
jermsnap Jermsnap                           rb netcom9  (NETCOM-pl10.netc)
jfbrewer jeremy brewer                      r1 netcom2  (NETCOM-sd10.netc)
jferra   JJ Ferra                           q7 netcom11 (NETCOM-pl3.netco)
jhoffman John Hoffman                0:02   pc netcom21 (office4.netcom.c)
jimlynch Jim Lynch                         *qc netcom20 (NETCOM-al6.netco)
jina     FireStorm/DarkStar2                qf netcom23 (lennon.pub.csufr)
jkabakov Joel Kabakov                9:10   ra netcom10 (NETCOM-ir6.netco)
jkumarr  Soulman                     0:01  *q7 netcom14 (leonis.nus.sg)
jliang   Jimmy Liang                       *p1 netcom19 (NETCOM-sj16.netc)
jlk      Gerald Koenig                      pb netcom13 (NETCOM-la21.netc)
jmclark  James M. Clark                     qa netcom11 (NETCOM-al3.netco)
jmv      John Maguire                0:01   r2 netcom14 (NETCOM-sj26.netc)
jnishina John Nishinaga                    *qb netcom13 (NETCOM-la2.netco)
joelyons Shibumi                     0:10   sb netcom19 (NETCOM-la20.netc)
joeshea  Joe Shea                    0:19   q7 netcom20 (NETCOM-pas10.net)
johne    john eisenberg                     p9 netcom17 (NETCOM-pas12.net)
jondr    Whatever makes you happy           p2 netcom14 (NETCOM-dfw11.net)
jony                                        pd netcom6  (NETCOM-lb8.netco)
jordan   Jordan Bortz                0:03   q5 netcom   (165.227.93.5)
joshk    joshk@netcom.com            2:41   t3 netcom2  (NETCOM-la20.netc)
jpdavid  John Kordic                        q3 netcom15 (NETCOM-la18.netc)
jpenrose James Penrose                      pa netcom17 (NETCOM-ir13.netc)
jpf      Jonathan P. Finnecy                q3 netcom10 (NETCOM-la18.netc)
jreque   Martin Won                         pb netcom14 (NETCOM-pa7.netco)
jthill   Jim Hill                    0:01  *q6 netcom2  (NETCOM-pa7.netco)
jthomps  Jeff Thompson                      q4 netcom13 (netcom15)
jthomps  Jeff Thompson                      pe netcom15 (NETCOM-den11.net)
jtthomas Janice T. Thomas                   r4 netcom10 (NETCOM-sj35.netc)
jules    SnowBuny--Southern Califor  4:51  *pf netcom9  (NETCOM-ir2.netco)
jurassic                             0:05   p2 netcom20 (NETCOM-pa7.netco)
jux      marcellus' wife                   *q7 netcom19 (NETCOM-al1.netco)
jwagner3 John Wagner                        q8 netcom4  (NETCOM-sf5.netco)
karlb    Karl Buiter                 0:23   pd netcom11 (NETCOM-al6.netco)
kaupe    Raelani! and Teri                  p3 netcom16 (NETCOM-sc5.netco)
kay      Karen Heyman                       rb netcom   (ix-wh6-26.ix.net)
keno     Ken O'Connor                      *s6 netcom11 (NETCOM-dfw11.net)
ker      Keith E. Rowland            0:01   p5 netcom2  (140.174.162.102)
kglady   Korene Geffen                      p2 netcom15 (NETCOM-den5.netc)
khkwong  Kelvin Kwong                0:03   re netcom20 (netcom23)
khkwong  Kelvin Kwong                0:03   pa netcom21 (NETCOM-sf14.netc)
khkwong  Kelvin Kwong                       q4 netcom23 (netcom20)
killer8  jong-il kin                        pa netcom2  (NETCOM-slc3.netc)
kilty    Kathleen Richards                  s9 netcom16 (NETCOM-ont4.netc)
kjames   Kevin R. James                     p0 netcom22 (NETCOM-sd9.netco)
kkrebs   Ken Krebs                   0:33   p0 netcom3  (NETCOM-sj18.netc)
klutz    Kenneth Lu                         ra netcom17 (NETCOM-sj22.netc)
kma      Kevin Archibald                    p2 netcom10 (NETCOM-pa7.netco)
kman     The_Multimedia_Maddman      1:30   r2 netcom15 (NETCOM-dfw9.netc)
kmg1                                        q8 netcom10 (NETCOM-har5.netc)
kmodemod .teklordZ.epinicion.               pb netcom11 (NETCOM-sac4.netc)
kmorgan  Kevin Morgan                       q5 netcom2  (NETCOM-sj18.netc)
kodiak   Chris D Koeberle                   p0 netcom9  (NETCOM-dfw10.net)
koster                                      q0 netcom17 (NETCOM-sj9.netco)
koz      cole maddox                       *pa netcom19 (NETCOM-atl6.netc)
krist    kristina 3.2                       p7 netcom12 (NETCOM-ir13.netc)
ksparger                                   *p4 netcom9  (NETCOM-hou5.netc)
ksparger                             0:03  *qf netcom21 (netcom9)
kutter   Joe Judd                           r1 netcom5  (NETCOM-den13.net)
kvie     KVIE                               p6 netcom   (ppp3.ns.net)
kylec    kyle cummings               0:21   qb netcom14 (NETCOM-sac4.netc)
kymer    J Kymer                            p6 netcom22 (NETCOM-la2.netco)
kyoshiro Salamandrina                       pe netcom9  (NETCOM-mon5.netc)
lament   Jason Ernsberger                   p1 netcom4  (NETCOM-sd9.netco)
lasher   James LLasher Suzanne C Cl         p2 netcom23 (NETCOM-sea6.netc)
lcypher  Louis Cypher                       p1 netcom3  (NETCOM-hou5.netc)
lda      Leonard D Atkinson II       0:08   qd netcom8  (NETCOM-wc1.netco)
lede     charles chapman                    p1 netcom11 (NETCOM-la2.netco)
lemming  Nathan Clark                       pf netcom21 (NETCOM-lv5.netco)
lenr     Leonard Rosenzweig          0:01   q6 netcom23 (NETCOM-la20.netc)
leper    Mortensen                          q5 netcom20 (NETCOM-or10.netc)
lestat25 Christian Dion                     qf netcom20 (NETCOM-sj10.netc)
lewiz    Lewis De Payne                     pb netcom16 (NETCOM-pas12.net)
lewrose  Lewis Rose                         p9 netcom14 (NETCOM-dc7-1.net)
licon    Lord Icon                          qc netcom14 (NETCOM-sj10.netc)
lii      Listen to Him                     *p1 netcom12 (cyber.net)
lim      Lonnie Itzkovich                   q7 netcom9  (NETCOM-nyc9.netc)
limj     Jack Lim                    0:02   qe netcom5  (NETCOM-al6.netco)
lincmad  Linc Madison                      *p2 netcom17 (NETCOM-sf17.netc)
ljp      Lee J. Papageorge           0:01   p4 netcom5  (NETCOM-la21.netc)
llarrow  Lynn Larrow                        q1 netcom18 (NETCOM-sf9.netco)
llm      Ajeh                        0:42   qd netcom12 (NETCOM-clv2.netc)
lmy      Leonid M. Yaroslavsky              pd netcom17 (NETCOM-sea4.netc)
longh    Hoang                              r1 netcom17 (NETCOM-sj10.netc)
looser   Sean Bettencourt            0:04   pf netcom4  (NETCOM-sj12.netc)
lordr    william woodburn jr.               q8 netcom7  (NETCOM-sea6.netc)
lorenz   John Lorenz                 0:01   p0 netcom14 (NETCOM-sea5.netc)
lorenz   John Lorenz                        r0 netcom9  (netcom14)
lorindel Lorindel                    1:18  *qc netcom23 (140.145.250.170)
lsaid    Loai Said                          qc netcom6  (NETCOM-la18.netc)
ltd      Larry Drebes                2:17   sb netcom22 (rush.drebes.com)
lynx     Conrad Wong                 0:01   pb netcom17 (NETCOM-pa7.netco)
machida  Eileen Machida                     r5 netcom16 (NETCOM-sf6.netco)
mackdaly Bill Daly                          q1 netcom8  (NETCOM-atl7.netc)
mackn    Mack Nagashima                     qe netcom11 (NETCOM-pas10.net)
macnevin Brian MacNevin                     pc netcom3  (NETCOM-ir16.netc)
macronix Macronix                           p3 netcom5  (NETCOM-sj16.netc)
mage     Krista Landon                      qb netcom18 (pm011-03.dialip.)
maggie   Maggie MacDonald                   t3 netcom19 (NETCOM-sd8.netco)
malakar  Gary Larsen                        pc netcom7  (NETCOM-atl8.netc)
manfred  John Slane                         q4 netcom18 (NETCOM-col3.netc)
mapenzi  Brett Stewart               0:01   p7 netcom13 (NETCOM-sf10.netc)
margali  Deird'Re M. Brooks                 q4 netcom19 (NETCOM-or11.netc)
margeb   CJB                         0:13   p2 netcom16 (NETCOM-orl1.netc)
martinak Martina Koldewey                   p3 netcom4  (NETCOM-sf11.netc)
masegian John Daniel Masegian               p5 netcom16 (NETCOM-sj25.netc)
mchoe    Michael Choe                0:03   q8 netcom14 (NETCOM-sac5.netc)
mcstout  Mark C. Stout                      ra netcom8  (NETCOM-sac4.netc)
mdavies  Mark Davies                        r4 netcom22 (NETCOM-sr4.netco)
medea    Medea                              p3 netcom6  (NETCOM-phx3.netc)
megans   gasp                        0:08   q2 netcom4  (203.12.112.4)
memcr                                       qb netcom5  (NETCOM-la18.netc)
metal69  Pramod Pottayil                    td netcom19 (NETCOM-nyc11.net)
mgong    Michael Gong                       p0 netcom   (netcom17)
mgong    Michael Gong                       r4 netcom17 (NETCOM-sd8.netco)
migrnd   MR                          0:01   p8 netcom22 (NETCOM-sj34.netc)
mikehell Kontrol Faktory                    q4 netcom21 (NETCOM-pas12.net)
mikeoo   Linda MacGowan                     q8 netcom22 (NETCOM-sea4.netc)
milkbone B Tunick                           r1 netcom8  (NETCOM-sj11.netc)
mingo    steven clark                0:06   pf netcom16 (NETCOM-al2.netco)
mirowall Andrew Hahn                        q0 netcom4  (NETCOM-lb5.netco)
mirsasha Miri                               p8 netcom17 (NETCOM-aus2.netc)
mister   Eben Ozen                         *qa netcom4  (NETCOM-lb5.netco)
mistyros Super Brat!!                0:09   r5 netcom12 (NETCOM-ir5.netco)
mizag    Manuel Izaguirre                   p8 netcom23 (NETCOM-ir16.netc)
mjclark  Sensei                             q1 netcom20 (NETCOM-sd10.netc)
mjimenez michael jimenez                    q6 netcom10 (NETCOM-pa6.netco)
mjn      Marc Neuberger                     p6 netcom16 (NETCOM-bos5.netc)
mmm3     Mark Mayeda                        r3 netcom9  (NETCOM-al3.netco)
mmosko   Marc E. Mosko                      q7 netcom8  (NETCOM-sf13.netc)
mmsiwest Bart Pinto                         q9 netcom20 (NETCOM-wc7.netco)
mnelson  Michael Nelson                     p1 netcom7  (NETCOM-sj12.netc)
modemboy MoDeMbOy                    0:12  *pe netcom18 (NETCOM-den10.net)
mont     Mont Pierce                        se netcom10 (NETCOM-pl10.netc)
monterey David Wong                         p6 netcom21 (localhost)
monty1   monty Kane                         q0 netcom12 (NETCOM-sf10.netc)
moredhel Duncan Idaho                0:13   p1 netcom   (wcsub.ctstateu.e)
moto     Moto                        0:03   pb netcom10 (NETCOM-aus3.netc)
motofuji Richard Motofuji                   q6 netcom9  (NETCOM-al3.netco)
moxie    subPerignon                 2:41   u4 netcom4  (NETCOM-phi1.netc)
mperez   Manuel Perez-Pabon          0:01   p6 netcom11 (NETCOM-ir13.netc)
mpr      MPR Associates Inc          0:02   p3 netcom7  (netcom15)
mpr      MPR Associates Inc          0:02   pc netcom15 (NETCOM-al6.netco)
mrclean  Thx1138                     0:01   q1 netcom5  (NETCOM-sj11.netc)
mre      john smith                  0:01   q5 netcom16 (NETCOM-nwk11.net)
mriddell mr                                 p8 netcom5  (NETCOM-sea4.netc)
mrmacky  John MacMaster                     p5 netcom20 (NETCOM-atl6.netc)
mrmarks  Henry Stauf                        p7 netcom16 (NETCOM-kc5.netco)
mrose    martin rosenberg            0:08   qd netcom9  (NETCOM-pl2.netco)
msako    Mitch Sako                         rb netcom18 (NETCOM-sj10.netc)
msamett  Michael Samett                     p0 netcom11 (NETCOM-la18.netc)
msilva   "Murder was the Case"              q3 netcom17 (NETCOM-sj13.netc)
mskathy  MsKathy                     0:57  *s6 netcom22 (office3)
mtuxford Mike Tuxford                       t2 netcom20 (NETCOM-phx3.netc)
mtuxford Mike Tuxford                       s9 netcom21 (netcom20)
multitek Daron J. Wilson                    r6 netcom9  (NETCOM-sea5.netc)
mundsack Jon Mundsack                1:19   p8 netcom11 (NETCOM-chi11-1.n)
munin                                       p4 netcom11 (NETCOM-sj13.netc)
murphyc  C. Murphy                          r7 netcom22 (NETCOM-la19.netc)
musicman Bruce Berns                        pd netcom14 (NETCOM-la18.netc)
mwalker  maria walker                       s0 netcom11 (NETCOM-wp1.netco)
n9s6m    sub numin viget                    r1 netcom9  (NETCOM-nyc14.net)
nancydrw Thaddeus R. Croyle (Girl S         q7 netcom16 (NETCOM-sf9.netco)
narwhal  Narwhal                            s7 netcom8  (NETCOM-la21.netc)
nc0015   John M. Wu                        *qe netcom20 (manofpower.netco)
nc0096                               0:02   pd netcom21 (madras.netcom.co)
nc0118                               0:03   u2 netcom16 (voyeur.noc.netco)
nc0147   nc0147                             p7 netcom15 (NETCOM-sj34.netc)
nc0147   nc0147                      0:02   p3 netcom22 (solar.netcom.com)
nc0150                                      q6 netcom20 (office3)
nc0150                               0:02   qc netcom21 (office3)
nc0150                               0:02   q0 netcom22 (office3)
nc0256   Tech Support -- Cera        0:09   q5 netcom5  (netcom16)
nc0256   Tech Support -- Cera               ra netcom16 (office4.netcom.c)
ncohen   Nicholas Cohen              0:02   qc netcom15 (NETCOM-lb5.netco)
necron99 Robert French                      p4 netcom23 (NETCOM-sf10.netc)
necron99 Robert French                      p7 netcom9  (NETCOM-sf5.netco)
nee      Cheng-Lee Nee               0:03   q8 netcom2  (NETCOM-sj30.netc)
neilt    Neil Taneja                        p3 netcom2  (NETCOM-pas11.net)
netnews  USENET Administration             *pe netcom19 (rancor)
nevers   Nick Evers                  0:14   r1 netcom4  (NETCOM-phx3.netc)
newsntwk MQM Information Services N         r0 netcom11 (NETCOM-sj26.netc)
nfe      Nathan Estey                       q0 netcom19 (NETCOM-dc10-1.ne)
nielsen  Dale Nielsen                       q5 netcom14 (NETCOM-wh6.netco)
nil      Neil T. Nakao                      q6 netcom12 (NETCOM-ir14.netc)
ninthwav Waves That Meet             0:01   s4 netcom11 (NETCOM-den14.net)
nmsison  Nina Sison                  0:16   p4 netcom18 (NETCOM-lv6.netco)
nont     Nont Chiranand                    *pb netcom19 (NETCOM-dfw10.net)
norinm   Michael P. Norin                   r3 netcom20 (NETCOM-la24.netc)
normedw  Norman Edwards                     pf netcom12 (NETCOM-atl6.netc)
ogre     Mr. Ogre                           p8 netcom2  (NETCOM-ir13.netc)
omen     Jr.                         0:03   p9 netcom13 (netcom17)
omen     Jr.                         0:06   rd netcom17 (NETCOM-sac5.netc)
orphy    A Retired Unix Sys. Admin.  0:01   r0 netcom16 (NETCOM-stl3.netc)
oscarc   The Doctor Is In                   pa netcom15 (NETCOM-pl4.netco)
pacifica Russell                            q5 netcom18 (NETCOM-pas12.net)
padma    Padma Rao                   0:31   r9 netcom15 (NETCOM-atl9.netc)
pagli    [flaco]                     5:24   ra netcom5  (NETCOM-dc6-1.net)
paranoia Tyler Walden                       p8 netcom18 (NETCOM-or10.netc)
park     Bill Park                          qa netcom6  (NETCOM-pa1.netco)
party    Rick                        0:09   r3 netcom21 (office4.netcom.c)
paseo    casey cho                          q4 netcom16 (NETCOM-la2.netco)
path     path                        0:01   qf netcom9  (NETCOM-pa6.netco)
pauley   Paul Willett                       v0 netcom8  (NETCOM-den7.netc)
pauljo   Paul Johnson                       q0 netcom13 (NETCOM-wh5.netco)
pch      peter hun                          sd netcom2  (NETCOM-lb8.netco)
pcheng01 Poyuan Cheng                       q6 netcom6  (NETCOM-sj11.netc)
pchin    Midknight                          pe netcom7  (NETCOM-nyc14.net)
pcspec   Elaine Sampson                     qc netcom13 (NETCOM-sd8.netco)
peachez  Life Is Just PeAcHy         0:06   p7 netcom2  (NETCOM-nyc5.netc)
pegges   Paul Egges                        *qa netcom10 (NETCOM-den6.netc)
pepsiman Pepsiman/of netcom.com            *qf netcom2  (NETCOM-nyc10.net)
perez    ralph perez                        r9 netcom6  (NETCOM-la21.netc)
pettefer Matt Pettefer                      p6 netcom15 (NETCOM-atl13.net)
pfarrell Pat Farrell                        q3 netcom18 (NETCOM-dc7-1.net)
pfisher  Paul Fisher                        q4 netcom22 (NETCOM-hou5.netc)
pfnguyen Perry F Nguyen                    *pb netcom4  (NETCOM-al6.netco)
pgraham  Paul Graham                        qe netcom12 (NETCOM-atl7.netc)
phao     David Emery                        r3 netcom2  (NETCOM-sea6.netc)
phylo    Olav Phillips                      p6 netcom18 (NETCOM-wc6.netco)
phylo    Olav Phillips                     *r1 netcom19 (netcom18)
pimentel Wide Awake                        *p5 netcom15 (NETCOM-la19.netc)
pjr      Paul Rank                          qc netcom11 (NETCOM-sj11.netc)
pleh     David Hopman                       q9 netcom12 (NETCOM-pa7.netco)
ponyboy  Bucky                              pa netcom3  (NETCOM-wc7.netco)
poyang   Po-Yang Shih                      *q5 netcom22 (stucco.cco.calte)
prburgos *umop-ap!sdn 6u!6uey*              rc netcom8  (NETCOM-nyc14.net)
preacher Paul                        0:06  *q1 netcom13 (NETCOM-la24.netc)
prefect  prefect                            s5 netcom16 (NETCOM-dc14-1.ne)
profile  Profile Software                   r3 netcom7  (NETCOM-sf5.netco)
pug      Charles Peri                       se netcom15 (NETCOM-sac8.netc)
puppy    W.E.L.T.                           p8 netcom3  (NETCOM-sea4.netc)
pwrbomb  VEE JAY                            pe netcom12 (NETCOM-sf5.netco)
pwt      Peter Thornton              3:34   r3 netcom   (maple.circa.ufl.)
question     ???                            pd netcom19 (NETCOM-la22.netc)
quintrel Fred Quintrell                     p6 netcom23 (NETCOM-pas10.net)
quozl    D.M. "Quozl" Falk                  p1 netcom17 (redwood.northcoa)
raheeb   Raheeb Rahman               1:52  *pf netcom   (ix-wh6-02.ix.net)
ralph    Ralph Warren Pearson        0:03   s0 netcom21 (mola.org)
ramia    Sean Ramia                         p9 netcom2  (NETCOM-pl4.netco)
ranmas   RuGal                              pc netcom12 (NETCOM-pl1.netco)
ransacks Maureen C. Blair                   q1 netcom17 (NETCOM-dfw10.net)
ratcat   Smitten                     0:01   p2 netcom8  (NETCOM-sf5.netco)
rattle   jack                        0:01   p0 netcom20 (NETCOM-sf10.netc)
ravenna  monique Saltik                     t1 netcom14 (163.179.12.14)
rbh00    Richard Hitt                       r0 netcom5  (NETCOM-pa7.netco)
rblees   robert blees                       qe netcom10 (NETCOM-sf6.netco)
realpro  Realpro BBS                 0:02   pa netcom14 (NETCOM-lv6.netco)
rei      Lupa                               p6 netcom20 (NETCOM-la19.netc)
rei      Lupa                               pe netcom3  (NETCOM-la19.netc)
rere     rere                               p2 netcom7  (NETCOM-dfw11.net)
reznor                                      r6 netcom7  (NETCOM-sf12.netc)
rhardin  richard hardin              0:03   qa netcom5  (NETCOM-sd8.netco)
rhardin  richard hardin              0:02   q3 netcom4  (NETCOM-sd8.netco)
rhiana   Ruth Gardner                       q5 netcom3  (NETCOM-dc10-1.ne)
rhinewhn Mr Self Destruction                u0 netcom11 (NETCOM-sac7.netc)
rhosono                              4:50  *qe netcom22 (NETCOM-sd10.netc)
ricep                                       q4 netcom14 (NETCOM-pa4.netco)
richardc Richard                    13:37  *q8 netcom6  (netcom5)
richgold Richard Goldstein           0:04   q0 netcom   (NETCOM-bos5.netc)
richh    richh                       0:08   p9 netcom8  (163.179.37.13)
richie   Richard Collins                    r5 netcom3  (NETCOM-wc1.netco)
rickynew Ricky New                          p3 netcom12 (NETCOM-sf9.netco)
rivethed Placebozoid                 0:06   q2 netcom5  (NETCOM-mon5.netc)
rlee     Robert Lee                         r2 netcom12 (NETCOM-ir15.netc)
rleung   Ryan                        0:09   rd netcom3  (NETCOM-pl8.netco)
rng      Ronald Ng                          p7 netcom11 (NETCOM-pas10.net)
robertle Leung                              re netcom5  (NETCOM-sj18.netc)
robertp  Flashback                          sc netcom2  (NETCOM-chi11-1.n)
robrt    Robert Eliason              0:16   t4 netcom19 (NETCOM-wc7.netco)
robwong  Robert Wong                 0:03   q2 netcom12 (NETCOM-dc7-1.net)
rodthomp Roderick Thompson                  r1 netcom13 (NETCOM-sac10.net)
roessler Robert Roessler                    r3 netcom13 (NETCOM-ir15.netc)
rogaine  Christopher Roe                    q1 netcom7  (NETCOM-pa6.netco)
rogeorge R. LaMont George                   p2 netcom6  (NETCOM-den12.net)
rosewood Shankar Khadye                     p5 netcom13 (NETCOM-sj24.netc)
rriggs   Robert Riggs                       sb netcom18 (NETCOM-den12.net)
rrward   Richard Ward                       p7 netcom21 (jdc-p1-30.alaska)
rsf      Raul Fernandez                     q6 netcom18 (NETCOM-la18.netc)
rsh      Roy Ho                             q7 netcom13 (NETCOM-sj14.netc)
rsummers ron summers                        p0 netcom7  (NETCOM-wc7.netco)
rune     Rune ShadowMaster                  pc netcom9  (NETCOM-nyc12.net)
rupa     Rupa Schomaker                    *pf netcom3  (NETCOM-la20.netc)
russh    russell hull                       p7 netcom14 (NETCOM-dfw9.netc)
rustman  Rusty H. Hodge                     ta netcom3  (NETCOM-sf13.netc)
rut      Ruth Caspary                0:06   q5 netcom10 (NETCOM-pas11.net)
rzs      Vlad Shmunis                       q8 netcom15 (NETCOM-sf10.netc)
rzussman Ronald Zussman                     q0 netcom21 (NETCOM-nyc14.net)
sabbat   Heidi Hill                  0:01   r5 netcom   (ix-fre-ca1-13.ix)
sabeena  Sabeena                            qd netcom20 (NETCOM-slc4.netc)
sacker   Charles M. Solen                   q0 netcom23 (NETCOM-lv5.netco)
sagent   For Your Eye's Only!        0:05   q8 netcom8  (NETCOM-lb6.netco)
samkho   Samuel P Kho                       pa netcom6  (NETCOM-pa7.netco)
sang     Lee Sang Jun                       p1 netcom10 (NETCOM-mon5.netc)
saotome  Toshiya Mogi Saotome        0:01   p3 netcom9  (NETCOM-phi2.netc)
sappel   Shannon Appel                      p4 netcom17 (soda.CSUA.Berkel)
sarajevo Miroslav Curac              2:07   qd netcom13 (NETCOM-lb6.netco)
savdrag  Raw Raw like I got Cerebal         q6 netcom11 (NETCOM-or11.netc)
sbrindle Stephen Thomas Brindle            *pe netcom11 (NETCOM-al11.netc)
scandal  Peace Frog...                      pe netcom13 (NETCOM-dfw11.net)
schizo                                      p9 netcom20 (NETCOM-sj34.netc)
schuyler Gabriel M. Schuyler                t2 netcom15 (NETCOM-sf17.netc)
schuyler Gabriel M. Schuyler                q5 netcom23 (netcom15)
sdabbs   Steve Dabbs                        rc netcom17 (NETCOM-atl14.net)
sdy      Shahrokh Yadegari                  p3 netcom18 (NETCOM-la19.netc)
select   The Unknown                        q4 netcom7  (NETCOM-al11.netc)
sergeyk  Sergey Kirshner                    qd netcom2  (NETCOM-sf10.netc)
sergiohv Sergio H. Villalba                 r8 netcom12 (NETCOM-la18.netc)
serpent  Pat Coleman                        p1 netcom2  (NETCOM-atl6.netc)
setsuna  Setsuna Meioh                      p0 netcom5  (NETCOM-lb6.netco)
sfb      sfb                                p1 netcom18 (NETCOM-hou5.netc)
sfd      Scott Drellishak                   q2 netcom21 (drellishak.com)
sharons                                    *p3 netcom23 (NETCOM-atl6.netc)
shaunski Shaun Leavold                      s1 netcom20 (NETCOM-sj19.netc)
shawn    Shawn Hayes                 0:28   q0 netcom18 (netcom17)
shawn    Shawn Hayes                 0:28   r8 netcom17 (NETCOM-atl9.netc)
sheri                                       q4 netcom6  (ferd.sco.COM)
shkim    Tony Sison                         r8 netcom5  (NETCOM-sj12.netc)
shoryken [PsYcHo CrUsHeR]                  *pd netcom10 (NETCOM-atl8.netc)
sima     Rikke Stanger                      tf netcom12 (kendaco.telebyte)
sjoboat  Gary Sjobakken                     pb netcom18 (NETCOM-lb6.netco)
sjohnson Rashama Johnson             0:01   p5 netcom   (netcom19)
sjohnson Rashama Johnson                    pc netcom19 (NETCOM-pas12.net)
skylar   mike atchley                       r3 netcom10 (NETCOM-dc14-1.ne)
slayer   Neil Stewart/Dayvid Iannac         q8 netcom13 (NETCOM-la23.netc)
slo      Stephen Lo                        *qe netcom13 (NETCOM-pas10.net)
small                                       q0 netcom14 (netcom18)
small                                       sf netcom18 (NETCOM-sf14.netc)
smithajj Aaron Smith                        r5 netcom6  (NETCOM-pa6.netco)
smithtom                                    p1 netcom14 (NETCOM-or10.netc)
smryan   Steven Ryan                        p2 netcom3  (NETCOM-sj19.netc)
smryan   Steven Ryan                 0:09   pf netcom10 (NETCOM-sj11.netc)
smutrbfn Jamie                              pc netcom10 (NETCOM-sj13.netc)
snakee   Jake the Snake              1:31  *sc netcom17 (NETCOM-ir6.netco)
snap                                        re netcom17 (NETCOM-mon5.netc)
snoddy   Robert Snodgrass                   p8 netcom9  (NETCOM-ir13.netc)
snoflo   Spencer Weise                      p3 netcom10 (NETCOM-dfw9.netc)
soong    soong park                         p0 netcom19 (NETCOM-sj10.netc)
source   David Harmon                       qe netcom21 (NETCOM-la3.netco)
spector  DH                                 rc netcom6  (NETCOM-sac10.net)
sphariss steve phariss                      re netcom15 (NETCOM-sac7.netc)
spond    Kurt Chirhart                      p1 netcom22 (NETCOM-atl6.netc)
spsycho  Satanic Psycho                     p5 netcom5  (NETCOM-atl7.netc)
spyrus   SPYRUS                             pc netcom2  (NETCOM-pl1.netco)
ssmith   Steve                              q4 netcom17 (NETCOM-la20.netc)
stangel                                     p3 netcom11 (NETCOM-wc2.netco)
starbrdg Sky Gifs                           qa netcom15 (NETCOM-sea4.netc)
stedman  Scrounger                          q5 netcom13 (NETCOM-la5.netco)
stefan   Kay Schmelzenbach                  p0 netcom12 (NETCOM-or11.netc)
steffen  David Steffen                      pe netcom10 (NETCOM-ir14.netc)
stellar  David Weinstein                    q9 netcom15 (NETCOM-wc7.netco)
stephg   Stephanie Grusch                   qe netcom16 (NETCOM-pa7.netco)
sternkin Mike Stern                         pf netcom11 (NETCOM-wh5.netco)
stonem   PWA '95                            t1 netcom6  (NETCOM-la24.netc)
stormk   Storm A. King                      r3 netcom16 (NETCOM-pa1.netco)
straedey Richard Straedey                   p4 netcom4  (NETCOM-la18.netc)
stripey  Stripey                            rc netcom5  (NETCOM-sj30.netc)
succeed  George Galustian                   p1 netcom8  (NETCOM-wh3.netco)
sulaco   Sulaco                             pc netcom16 (NETCOM-pas10.net)
sylys    Mark Merlino                       q9 netcom5  (NETCOM-ir16.netc)
tara     erin grady                         rd netcom5  (NETCOM-sd9.netco)
tarbush  Joe                         0:01   s9 netcom13 (NETCOM-lv4.netco)
taylorp  Patrick Taylor                     q2 netcom14 (NETCOM-pas10.net)
teac     Jason Jenkins                      p6 netcom13 (NETCOM-lv5.netco)
techknow Mark Goetze                 0:03   rf netcom3  (netcom8)
techknow Mark Goetze                 0:01   p4 netcom8  (NETCOM-sd10.netc)
tessien  Chris Kroninger                    pb netcom5  (NETCOM-sj34.netc)
thanos   Lupe God of Spam                   qb netcom15 (NETCOM-sac5.netc)
tharper  Tupshin Harper                     pb netcom23 (163.176.32.103)
thechous                                    q7 netcom2  (NETCOM-al6.netco)
therat   Wade P Evans                       q7 netcom12 (NETCOM-sc5.netco)
thwack   Chris Clarke                       p0 netcom17 (NETCOM-pas10.net)
thwack   Chris Clarke                       p9 netcom22 (NETCOM-pas12.net)
timbol   Mike Timbol                        p4 netcom3  (NETCOM-sc5.netco)
tismb    jason saliba                7:08   r9 netcom10 (NETCOM-clv2.netc)
tjmiles  Terry Miles                        r2 netcom17 (NETCOM-lv4.netco)
tnt      Terry Turner                       r2 netcom3  (NETCOM-pa3.netco)
tori     Paul Nagai                         pa netcom13 (NETCOM-sj34.netc)
totoro1  Totoro                             q1 netcom6  (NETCOM-sf4.netco)
tozun    orhan tozun                        q1 netcom2  (NETCOM-sj12.netc)
tpstrain Dan Caldwell                       pc netcom5  (NETCOM-la20.netc)
tristan  Turner Morgan                      q0 netcom6  (NETCOM-sf16.netc)
tsalagi                                    *q0 netcom11 (NETCOM-sac5.netc)
tsalagi                              0:01  *q6 netcom3  (netcom11)
tsn      Susan Bryant                       p9 netcom   (emerald.cybergat)
tspence  Ted Spence                         p7 netcom6  (NETCOM-pas10.net)
turk                                        pe netcom   (terminus.dcn.dav)
twfic    Ty Fairchild                0:03   p7 netcom18 (NETCOM-wh6.netco)
tygger   Tygger                      0:02   pa netcom12 (NETCOM-sd11.netc)
unicon   Roger Kuperways                    sb netcom4  (NETCOM-nyc11.net)
uptime   Uptime Computer Solutions          r3 netcom17 (NETCOM-sf14.netc)
vailikit Toma Vailikit                      p9 netcom9  (NETCOM-dc8-1.net)
victoria Victoria Vogt                      pe netcom4  (NETCOM-ont4.netc)
vinh     Vinh Luu                           p6 netcom10 (NETCOM-sf12.netc)
vinhle   Vinh Le                     0:02  *q1 netcom21 (NETCOM-la18.netc)
voyagers mike myers                        *p7 netcom4  (NETCOM-sc1.netco)
vrotney  William Paul Vrotney               qd netcom6  (NETCOM-sj28.netc)
vsclyne  V Shannon Clyne                    pd netcom9  (NETCOM-sc5.netco)
vvw      Ville V Walveranta                 p9 netcom5  (NETCOM-al3.netco)
vychin   Vincent Y. Chin                    r3 netcom11 (NETCOM-sf5.netco)
walkerk  Kent Walker                       *qe netcom6  (NETCOM-sf5.netco)
wanderer Todd Gionet                        tb netcom8  (NETCOM-ir13.netc)
warrior  Metallic Warrior            0:04   p3 netcom8  (NETCOM-sd9.netco)
warwick1 warwick1                    0:07   p6 netcom7  (NETCOM-lb6.netco)
wb6mlc   ken chong                          p2 netcom4  (NETCOM-pl1.netco)
wbacon   william bacon                      p9 netcom16 (NETCOM-or10.netc)
wbristow Walter Bristow                     p1 netcom6  (NETCOM-or10.netc)
wbuckley william buckley                    p5 netcom18 (NETCOM-ont3.netc)
weasle   G. Douglas Green                   q8 netcom   (205.162.63.245)
webbwj   William Webb                0:03   s9 netcom3  (NETCOM-clv1.netc)
webbwj   William Webb                0:01   q6 netcom   (netcom3)
werecat  WereCat                            p7 netcom19 (gumbo-ppp-e6.no.)
wgg      William Greathouse          0:03   p4 netcom21 (NETCOM-clv2.netc)
whome    wHoIZmE THa_FeLoN           0:01   p6 netcom12 (NETCOM-lb5.netco)
whytock  Donald Whytock                     r8 netcom3  (NETCOM-dc8-1.net)
williamb richard belcher                    q6 netcom15 (NETCOM-or11.netc)
wilweb   William Weber                      q0 netcom8  (NETCOM-sj35.netc)
wing     Benjamin P. Wing                   p3 netcom13 (NETCOM-al12.netc)
wjcandee William Candee              0:27   pf netcom19 (NETCOM-lb6.netco)
wje      William J. Evans                   p2 netcom2  (NETCOM-ir16.netc)
wkunz    William E. Kunz             0:03   pc netcom17 (NETCOM-pa1.netco)
wlmcgr   W.L. McGraw                 0:01   pc netcom14 (NETCOM-or11.netc)
wraveth  .oO Wraveth / The Sage Oo.  2:03   u1 netcom4  (NETCOM-den5.netc)
wtsui    Willie Tsui                        q1 netcom19 (NETCOM-lv4.netco)
xamfear  Dr. Nightmare               0:01   p0 netcom13 (NETCOM-atl7.netc)
xina     Christina                   0:08   rb netcom2  (NETCOM-al6.netco)
xyzom    Da Xyz                             u2 netcom17 (NETCOM-col1.netc)
yeehang  Anthony Chan                       q8 netcom3  (NETCOM-pl1.netco)
yokosima Wing H. Yi                         ub netcom14 (NETCOM-nyc5.netc)
yspark   Yongsik Park                       qd netcom4  (NETCOM-la1.netco)
yvette   blossom                     5:04  *qc netcom17 (NETCOM-har6.netc)
zaneb    Zane Brown                         p3 netcom19 (NETCOM-wc7.netco)
zap      Paul Eastham                       p6 netcom19 (NETCOM-pa1.netco)
zio      James Elkinton                     p6 netcom14 (NETCOM-sj11.netc)
zrath    Eric Alexander Bitton              s1 netcom21 (NETCOM-la21.netc)

748 active login sessions.
