.TH mailpgp 1
.SH NAME
mailpgp - PGP unix mail editor
.SH SYNOPSIS
mailpgp [file]
.SH DESCRIPTION
.B mailpgp
provides a simple and seemless interface to 
.B PGP
directly from a mail agent such as
.B pine
or 
.B elm
. Both 
.B pine
and 
.B elm
require special setup. It is nessecary to set the default editor path in
each mail agents.
.SH BUGS
There are likely to be a few lurking.
.SH ALSO SEE
pgp(1), pine(1), elm(1)
.SH AUTHORS
jason steiner (
.B jsteiner@anwsun.phya.utoledo.edu
)
.PP
Dave Arcuri (
.B tfff@grove.iup.edu
)
