.TH NNTPGET 1 local "Public Domain"
.DA 31 October 1992
.SH NAME
nntpget \- get news article batch via network news transfer protocol (NNTP)
.SH SYNOPSIS
.B nntpget
[
.B \-t
] [
.B \-d
] [
.B \-p
port ] [
.B \-D
debugfile ]
hostname [ message-id ... ]
.SH DESCRIPTION
.I Nntpget
takes a list of news article message-ids on the command line
or on stdin, contacts the NNTP daemon on 
.I hostname
and requests the news by the Network News Transfer Protocol
(RFC977).
It writes out the articles on stdout as a batch, which
can be fed to
.IR relaynews (8).
.SH OPTIONS
.TP 1i
.B \-t
.I nntpget
spools received articles as batches in 
.IB $NEWARTS /in.coming .
.TP
.B \-d
Turns on debugging.
Multiple
.B \-d
options may be given, each
increases the verbosity of the tracing.
.TP
.BR \-D " debugfile"
Directs debugging to the specified file.
.TP
.BR \-p " port"
Specifies the TCP port to use.
This may be either a port number
or a service name.
By default, it uses the service
.B nntp
(usually found on port 119).
.SH FILES
.PD 0
.TP 2.5i
.IB NEWSARTS /in.coming/nntp. XXXXXX
accumulating batch file
.TP
.IB NEWSARTS /in.coming/ NNNNNNNNN .t
completed batch file for
.I newsrun
.PD
.SH SEE ALSO
.IR news (5),
.IR newsaux (8),
.IR relaynews (8),
.IR rnews (8)
.br
Internet RFC 977
.\".SH DIAGNOSTICS
.SH HISTORY
Written at the University of Toronto by Mark Moraes.
.SH BUGS
Doesn't check if local site already has the articles by history file lookup.
