# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

set numeric
label A0 = "This spreadsheet illustrates the use of the "
label A1 = "@irr() function to calculate real-rate-of-return"
label A2 = "for a given cash flow.  That is, the percentage"
label A3 = "return which yields a certain cash flow or"
label A4 = "sequence of payments"
label A6 = "Example 1"
label A7 = "payments"
let B7 = -100
let C7 = 10
let D7 = 10
let E7 = 10
let F7 = 110
label A8 = "@irr()"
let B8 = @irr(B7:F7)
label A9 = "an investment of 100, yielding payments of 10"
label A10 = "with a final payoff of the principal and interest.  "
label A11 = "Clearly, 10% or 1.10"
label A12 = "Example 2"
let B13 = -103.15
label C13 = "l"
let D13 = 9.13
let E13 = 9.13
let F13 = 9.13
let G13 = 109.13
label A14 = "return"
let B14 = @irr(B13:G13)
fmt B14 "#.0000"
label A15 = "More realistic example, showing also that the formula"
label A16 = "will ignore text or non-numeric entries"
let F16 = -104
label A17 = "Example 3.  Vertical input works too."
label E17 = "return"
let F17 = 8.7
let E18 = @irr(F16:F21)
fmt E18 "#.0000"
let F18 = 3.2
let F19 = 9.3
let F20 = 8.7
let F21 = 109.3
label A22 = "Error testing"
let A23 = 100
let B23 = 1
let C23 = 2
let D23 = 3
let E23 = -105
let F23 = @irr(A23:E23)
label G23 = "invalid"
let A24 = 1
let F24 = @irr(A24:E24)
label G24 = "bad range"
label A25 = "a"
label B25 = "b"
let F25 = @irr(A25:E25)
goto A0
