# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

leftstring A0 = "now is the time when all cursors"
leftstring A1 = "now is the time when all cursors"
goto A1
