config.h:
	cp config.h-dist config.h
	cp /usr/include/curses.h local_curses.h
	patch -s -p0 < local_curses.h.diff

compile: config.h
	make

install:
	echo "Run ./inst manually and select 's', then 'q'.

