TARG=xaos
OFILES= autopilot.$O\
   drivers.$O\
   formulas.$O\
   gif.$O\
   gifcompr.$O\
   palette.$O\
   param.$O\
   plane.$O\
   ui.$O\
   ui_plan9.$O\
   zoom.$O

HFILES=aconfig.h config.h
BIN=$home/bin/$objtype # /$objtype/bin

</sys/src/cmd/mkone

CFLAGS=-w -D_plan9_

aconfig.h: aconfig.plan9
   cp aconfig.plan9 aconfig.h
config.h: config.plan9
   cp config.plan9 config.h
