.\" Copyright 1994 Jon Tombs (jon@gtex02.us.es, jon@robots.ox.ac.uk)
.\" May be distributed under the GNU General Public License
.TH SWITCHTO 1 V1.4 "19 Jul 1996" "Linux 1.x" "Linux users' Manual"
.SH NAME
switchto \- switch to a new virtual terminal (VT).
.SH SYNOPSIS
.B switchto vtnumber
.SH DESCRIPTION
.B switchto
will change the current VT to the vt specified. Useful to change VTs when the
hotkey sequence is unavailable for some reason, or from within scripts.

.SH "SEE ALSO"
.BR open (1),

.SH AUTHOR
Jon Tombs <jon@gtex02.us.es or jon@robots.ox.ac.uk>
