#! /bin/sh
rmflags=-i

if [ ! -x ./dist ]
 then
   echo 'You must be in the base directory'
   exit 1
fi

current_dir=`pwd`
dir=`basename $current_dir`
find . -name "*~" -exec rm $rmflags \{\} \;
find . -name "*.[as]" -exec rm $rmflags \{\} \;
find testsuite -type f -perm -500 -exec rm $rmflags \{\} \;
find testsuite -name "*.o" -exec rm $rmflags \{\} \;
find testsuite -name "*.log" -exec rm $rmflags \{\} \;
find testsuite -name "core" -exec rm $rmflags \{\} \;
cd ..
echo -n I am now in
pwd
echo tar zcvf $dir.tgz $dir
tar zcvf $dir.tgz $dir
