#!/bin/bash

source /etc/nfsroot/def

DD="dd if=$NFSROOTKERNEL of=/dev/fd0 && /usr/sbin/rdev /dev/fd0 /dev/boot255"
if test "$DISPLAY" = ":0.0" -o -z "$DISPLAY"; then
  sh -c "$DD"
else
  rem=`echo $DISPLAY | cut -d":" -f 1`
  rsh $rem "sh -c \"$DD\""
fi


