(defun iso-insert-no-break-space ()
   (interactive "*")
   (insert 160)
)

(defun iso-insert-inverted-exclamation-mark ()
   (interactive "*")
   (insert 161)
)

(defun iso-insert-cent-sign ()
   (interactive "*")
   (insert 162)
)

(defun iso-insert-pound-sign ()
   (interactive "*")
   (insert 163)
)

(defun iso-insert-general-currency-sign ()
   (interactive "*")
   (insert 164)
)

(defun iso-insert-yen-sign ()
   (interactive "*")
   (insert 165)
)

(defun iso-insert-broken-vertical-line ()
   (interactive "*")
   (insert 166)
)

(defun iso-insert-section-sign ()
   (interactive "*")
   (insert 167)
)

(defun iso-insert-diaeresis ()
   (interactive "*")
   (insert 168)
)

(defun iso-insert-copyright-sign ()
   (interactive "*")
   (insert 169)
)

(defun iso-insert-ordinal-indicator-feminine ()
   (interactive "*")
   (insert 170)
)

(defun iso-insert-angle-quotation-mark-left ()
   (interactive "*")
   (insert 171)
)

(defun iso-insert-not-sign ()
   (interactive "*")
   (insert 172)
)

(defun iso-insert-soft-hyphen ()
   (interactive "*")
   (insert 173)
)

(defun iso-insert-registered-sign ()
   (interactive "*")
   (insert 174)
)

(defun iso-insert-macron ()
   (interactive "*")
   (insert 175)
)

(defun iso-insert-degree-sign ()
   (interactive "*")
   (insert 176)
)

(defun iso-insert-plus-or-minus-sign ()
   (interactive "*")
   (insert 177)
)

(defun iso-insert-superscript-two ()
   (interactive "*")
   (insert 178)
)

(defun iso-insert-superscript-three ()
   (interactive "*")
   (insert 179)
)

(defun iso-insert-acute-accent ()
   (interactive "*")
   (insert 180)
)

(defun iso-insert-micro-sign ()
   (interactive "*")
   (insert 181)
)

(defun iso-insert-pilcrow ()
   (interactive "*")
   (insert 182)
)

(defun iso-insert-middle-dot ()
   (interactive "*")
   (insert 183)
)

(defun iso-insert-cedilla ()
   (interactive "*")
   (insert 184)
)

(defun iso-insert-superscript-one ()
   (interactive "*")
   (insert 185)
)

(defun iso-insert-ordinal-indicator-masculine ()
   (interactive "*")
   (insert 186)
)

(defun iso-insert-angle-quotation-mark-right ()
   (interactive "*")
   (insert 187)
)

(defun iso-insert-fraction-one-quarter ()
   (interactive "*")
   (insert 188)
)

(defun iso-insert-fraction-one-half ()
   (interactive "*")
   (insert 189)
)

(defun iso-insert-fraction-three-quarters ()
   (interactive "*")
   (insert 190)
)

(defun iso-insert-inverted-question-mark ()
   (interactive "*")
   (insert 191)
)

(defun iso-insert-A-grave ()
   (interactive "*")
   (insert 192)
)

(defun iso-insert-A-acute ()
   (interactive "*")
   (insert 193)
)

(defun iso-insert-A-circumflex ()
   (interactive "*")
   (insert 194)
)

(defun iso-insert-A-tilde ()
   (interactive "*")
   (insert 195)
)

(defun iso-insert-A-umlaut ()
   (interactive "*")
   (insert 196)
)

(defun iso-insert-A-ring ()
   (interactive "*")
   (insert 197)
)

(defun iso-insert-AE ()
   (interactive "*")
   (insert 198)
)

(defun iso-insert-C-cedilla ()
   (interactive "*")
   (insert 199)
)

(defun iso-insert-E-grave ()
   (interactive "*")
   (insert 200)
)

(defun iso-insert-E-acute ()
   (interactive "*")
   (insert 201)
)

(defun iso-insert-E-circumflex ()
   (interactive "*")
   (insert 202)
)

(defun iso-insert-E-umlaut ()
   (interactive "*")
   (insert 203)
)

(defun iso-insert-I-grave ()
   (interactive "*")
   (insert 204)
)

(defun iso-insert-I-acute ()
   (interactive "*")
   (insert 205)
)

(defun iso-insert-I-circumflex ()
   (interactive "*")
   (insert 206)
)

(defun iso-insert-I-umlaut ()
   (interactive "*")
   (insert 207)
)

(defun iso-insert-D-stroke ()
   (interactive "*")
   (insert 208)
)

(defun iso-insert-N-tilde ()
   (interactive "*")
   (insert 209)
)

(defun iso-insert-O-grave ()
   (interactive "*")
   (insert 210)
)

(defun iso-insert-O-acute ()
   (interactive "*")
   (insert 211)
)

(defun iso-insert-O-circumflex ()
   (interactive "*")
   (insert 212)
)

(defun iso-insert-O-tilde ()
   (interactive "*")
   (insert 213)
)

(defun iso-insert-O-umlaut ()
   (interactive "*")
   (insert 214)
)

(defun iso-insert-multiplication-sign ()
   (interactive "*")
   (insert 215)
)

(defun iso-insert-O-slash ()
   (interactive "*")
   (insert 216)
)

(defun iso-insert-U-grave ()
   (interactive "*")
   (insert 217)
)

(defun iso-insert-U-acute ()
   (interactive "*")
   (insert 218)
)

(defun iso-insert-U-circumflex ()
   (interactive "*")
   (insert 219)
)

(defun iso-insert-U-umlaut ()
   (interactive "*")
   (insert 220)
)

(defun iso-insert-Y-acute ()
   (interactive "*")
   (insert 221)
)

(defun iso-insert-THORN ()
   (interactive "*")
   (insert 222)
)

(defun iso-insert-ss ()
   (interactive "*")
   (insert 223)
)

(defun iso-insert-a-grave ()
   (interactive "*")
   (insert 224)
)

(defun iso-insert-a-acute ()
   (interactive "*")
   (insert 225)
)

(defun iso-insert-a-circumflex ()
   (interactive "*")
   (insert 226)
)

(defun iso-insert-a-tilde ()
   (interactive "*")
   (insert 227)
)

(defun iso-insert-a-umlaut ()
   (interactive "*")
   (insert 228)
)

(defun iso-insert-a-ring ()
   (interactive "*")
   (insert 229)
)

(defun iso-insert-ae ()
   (interactive "*")
   (insert 230)
)

(defun iso-insert-c-cedilla ()
   (interactive "*")
   (insert 231)
)

(defun iso-insert-e-grave ()
   (interactive "*")
   (insert 232)
)

(defun iso-insert-e-acute ()
   (interactive "*")
   (insert 233)
)

(defun iso-insert-e-circumflex ()
   (interactive "*")
   (insert 234)
)

(defun iso-insert-e-umlaut ()
   (interactive "*")
   (insert 235)
)

(defun iso-insert-i-grave ()
   (interactive "*")
   (insert 236)
)

(defun iso-insert-i-acute ()
   (interactive "*")
   (insert 237)
)

(defun iso-insert-i-circumflex ()
   (interactive "*")
   (insert 238)
)

(defun iso-insert-i-umlaut ()
   (interactive "*")
   (insert 239)
)

(defun iso-insert-d-stroke ()
   (interactive "*")
   (insert 240)
)

(defun iso-insert-n-tilde ()
   (interactive "*")
   (insert 241)
)

(defun iso-insert-o-grave ()
   (interactive "*")
   (insert 242)
)

(defun iso-insert-o-acute ()
   (interactive "*")
   (insert 243)
)

(defun iso-insert-o-circumflex ()
   (interactive "*")
   (insert 244)
)

(defun iso-insert-o-tilde ()
   (interactive "*")
   (insert 245)
)

(defun iso-insert-o-umlaut ()
   (interactive "*")
   (insert 246)
)

(defun iso-insert-division-sign ()
   (interactive "*")
   (insert 247)
)

(defun iso-insert-o-slash ()
   (interactive "*")
   (insert 248)
)

(defun iso-insert-u-grave ()
   (interactive "*")
   (insert 249)
)

(defun iso-insert-u-acute ()
   (interactive "*")
   (insert 250)
)

(defun iso-insert-u-circumflex ()
   (interactive "*")
   (insert 251)
)

(defun iso-insert-u-umlaut ()
   (interactive "*")
   (insert 252)
)

(defun iso-insert-y-acute ()
   (interactive "*")
   (insert 253)
)

(defun iso-insert-thorn ()
   (interactive "*")
   (insert 254)
)

(defun iso-insert-y-umlaut ()
   (interactive "*")
   (insert 255)
)

(defvar iso-map nil "Keymap for ISO 8859/1 character insertion.")
(if iso-map nil
   (setq iso-map (make-keymap))
   (define-key iso-map " "    'iso-insert-no-break-space)
   (define-key iso-map "!"    'iso-insert-inverted-exclamation-mark)
   (define-key iso-map "\""   (make-sparse-keymap))
   (define-key iso-map "\"\"" 'iso-insert-diaeresis)
   (define-key iso-map "\"A"  'iso-insert-A-umlaut)
   (define-key iso-map "\"E"  'iso-insert-E-umlaut)
   (define-key iso-map "\"I"  'iso-insert-I-umlaut)
   (define-key iso-map "\"O"  'iso-insert-O-umlaut)
   (define-key iso-map "\"U"  'iso-insert-U-umlaut)
   (define-key iso-map "\"a"  'iso-insert-a-umlaut)
   (define-key iso-map "\"e"  'iso-insert-e-umlaut)
   (define-key iso-map "\"i"  'iso-insert-i-umlaut)
   (define-key iso-map "\"o"  'iso-insert-o-umlaut)
   (define-key iso-map "\"u"  'iso-insert-u-umlaut)
   (define-key iso-map "\"y"  'iso-insert-y-umlaut)
   (define-key iso-map "'"    (make-sparse-keymap))
   (define-key iso-map "''"   'iso-insert-acute-accent)
   (define-key iso-map "'A"   'iso-insert-A-acute)
   (define-key iso-map "'E"   'iso-insert-E-acute)
   (define-key iso-map "'I"   'iso-insert-I-acute)
   (define-key iso-map "'O"   'iso-insert-O-acute)
   (define-key iso-map "'U"   'iso-insert-U-acute)
   (define-key iso-map "'Y"   'iso-insert-Y-acute)
   (define-key iso-map "'a"   'iso-insert-a-acute)
   (define-key iso-map "'e"   'iso-insert-e-acute)
   (define-key iso-map "'i"   'iso-insert-i-acute)
   (define-key iso-map "'o"   'iso-insert-o-acute)
   (define-key iso-map "'u"   'iso-insert-u-acute)
   (define-key iso-map "'y"   'iso-insert-y-acute)
   (define-key iso-map "$"    'iso-insert-general-currency-sign)
   (define-key iso-map "+"    'iso-insert-plus-or-minus-sign)
   (define-key iso-map ","    (make-sparse-keymap))
   (define-key iso-map ",,"   'iso-insert-cedilla)
   (define-key iso-map ",C"   'iso-insert-C-cedilla)
   (define-key iso-map ",c"   'iso-insert-c-cedilla)
   (define-key iso-map "-"    'iso-insert-soft-hyphen)
   (define-key iso-map "."    'iso-insert-middle-dot)
   (define-key iso-map "/"    (make-sparse-keymap))
   (define-key iso-map "//"   'iso-insert-division-sign)
   (define-key iso-map "/O"   'iso-insert-O-slash)
   (define-key iso-map "/o"   'iso-insert-o-slash)
   (define-key iso-map "1"    (make-sparse-keymap))
   (define-key iso-map "1/"   (make-sparse-keymap))
   (define-key iso-map "1/2"  'iso-insert-fraction-one-half)
   (define-key iso-map "1/4"  'iso-insert-fraction-one-quarter)
   (define-key iso-map "3"    (make-sparse-keymap))
   (define-key iso-map "3/"   (make-sparse-keymap))
   (define-key iso-map "3/4"  'iso-insert-fraction-three-quarters)
   (define-key iso-map "<"    'iso-insert-angle-quotation-mark-left)
   (define-key iso-map "="    'iso-insert-macron)
   (define-key iso-map ">"    'iso-insert-angle-quotation-mark-right)
   (define-key iso-map "?"    'iso-insert-inverted-question-mark)
   (define-key iso-map "A"    'iso-insert-A-ring)
   (define-key iso-map "E"    'iso-insert-AE)
   (define-key iso-map "C"    'iso-insert-copyright-sign)
   (define-key iso-map "D"    'iso-insert-D-stroke)
   (define-key iso-map "L"    'iso-insert-pound-sign)
   (define-key iso-map "P"    'iso-insert-pilcrow)
   (define-key iso-map "R"    'iso-insert-registered-sign)
   (define-key iso-map "S"    'iso-insert-section-sign)
   (define-key iso-map "T"    'iso-insert-THORN)
   (define-key iso-map "Y"    'iso-insert-yen-sign)
   (define-key iso-map "^"    (make-sparse-keymap))
   (define-key iso-map "^1"   'iso-insert-superscript-one)
   (define-key iso-map "^2"   'iso-insert-superscript-two)
   (define-key iso-map "^3"   'iso-insert-superscript-three)
   (define-key iso-map "^A"   'iso-insert-A-circumflex)
   (define-key iso-map "^E"   'iso-insert-E-circumflex)
   (define-key iso-map "^I"   'iso-insert-I-circumflex)
   (define-key iso-map "^O"   'iso-insert-O-circumflex)
   (define-key iso-map "^U"   'iso-insert-U-circumflex)
   (define-key iso-map "^a"   'iso-insert-a-circumflex)
   (define-key iso-map "^e"   'iso-insert-e-circumflex)
   (define-key iso-map "^i"   'iso-insert-i-circumflex)
   (define-key iso-map "^o"   'iso-insert-o-circumflex)
   (define-key iso-map "^u"   'iso-insert-u-circumflex)
   (define-key iso-map "_"    (make-sparse-keymap))
   (define-key iso-map "_a"   'iso-insert-ordinal-indicator-feminine)
   (define-key iso-map "_o"   'iso-insert-ordinal-indicator-masculine)
   (define-key iso-map "`"    (make-sparse-keymap))
   (define-key iso-map "`A"   'iso-insert-A-grave)
   (define-key iso-map "`E"   'iso-insert-E-grave)
   (define-key iso-map "`I"   'iso-insert-I-grave)
   (define-key iso-map "`O"   'iso-insert-O-grave)
   (define-key iso-map "`U"   'iso-insert-U-grave)
   (define-key iso-map "`a"   'iso-insert-a-grave)
   (define-key iso-map "`e"   'iso-insert-e-grave)
   (define-key iso-map "`i"   'iso-insert-i-grave)
   (define-key iso-map "`o"   'iso-insert-o-grave)
   (define-key iso-map "`u"   'iso-insert-u-grave)
   (define-key iso-map "a"    'iso-insert-a-ring)
   (define-key iso-map "e"    'iso-insert-ae)
   (define-key iso-map "c"    'iso-insert-cent-sign)
   (define-key iso-map "d"    'iso-insert-d-stroke)
   (define-key iso-map "o"    'iso-insert-degree-sign)
   (define-key iso-map "s"    'iso-insert-ss)
   (define-key iso-map "t"    'iso-insert-thorn)
   (define-key iso-map "u"    'iso-insert-micro-sign)
   (define-key iso-map "x"    'iso-insert-multiplication-sign)
   (define-key iso-map "|"    'iso-insert-broken-vertical-line)
   (define-key iso-map "~"    (make-sparse-keymap))
   (define-key iso-map "~A"   'iso-insert-A-tilde)
   (define-key iso-map "~N"   'iso-insert-N-tilde)
   (define-key iso-map "~O"   'iso-insert-O-tilde)
   (define-key iso-map "~a"   'iso-insert-a-tilde)
   (define-key iso-map "~n"   'iso-insert-n-tilde)
   (define-key iso-map "~o"   'iso-insert-o-tilde)
   (define-key iso-map "~~"   'iso-insert-not-sign)
   (if (not (lookup-key global-map "\C-x8"))
      (define-key global-map "\C-x8" iso-map))
)

