#
#  Copyright (c) 1993, Trusted Information Systems, Incorporated
#  All rights reserved.
# 
#  Redistribution and use are governed by the terms detailed in the
#  license document ("LICENSE") included with the toolkit.
#

#
#	Author: Marcus J. Ranum, Trusted Information Systems, Inc.
#
# RcsId: "Header: Makefile,v 1.2 94/05/27 14:10:39 mjr Exp "

include	../Makefile.config


# these are no-ops
all:
clean:

install:
# Senseless.  $(DEST) is /usr/local/sbin.  --Shields 1995-12-12
#
#		$(CP) netperm-table $(DEST); \
#		chmod 644 $(DEST)/netperm-table; \
#	fi
