.\" $Copyright: $
.\" Copyright (c) 1995, 1996 by Steve Baker (ice@mama.indstate.edu)
.\" All Rights reserved
.\"
.\" This software is provided as is without any express or implied
.\" warranties, including, without limitation, the implied warranties
.\" of merchant-ability and fitness for a particular purpose.
.\"
...
.V= $Header: sac.8 1.5 1995, 1996 $
.TH SAC 8 "\*(V)" "UNIX Manual"
.SH NAME
sac \- system accounting.
.SH SYNOPSIS
\fBsac\fP [\fB-acdfFhmoprt\fP] [\fB-w\fP [\fIwtmp-list\fP|\fB-\fP]] [\fB-b\fP \fIH\fP[\fI:M\fP[\fI:S\fP]]] [\fB-s\fP \fIstart\fP] [\fB-e\fP \fIend\fP] [\fB-X\fP[\fB3\fP|\fB4\fP]] [[\fB-u\fP] \fIuser-list\fP] [\fB-x\fP [\fIuser-list\fP]] [\fB-T\fP [\fItty-list\fP]] [\fB-H\fP [\fIhost-list\fP]] [\fB-M\fP \fIhour-range\fP[,...]] [\fB-R\fP [\fIportmaster-list\fP]] [\fB--help\fP] [\fB--version\fP]
.br
.SH DESCRIPTION
\fISac\fP is a system administration utility, based on the original BSD
\fIac\fP program, to read the wtmp log and produce more human readable system
usage information than provided by \fIlast\fP. Several features not found in
the BSD version of this program have been added.

\fISac\fP produces five different types of output:  Total usage in number of
login hours since wtmp was created (default), login usage per day (\fI-d\fP
option), total usage per user (\fI-p\fP option), usage per tty line
(\fI-t\fP option) and raw usage (\fI-r\fP option), which prints everything
sac knows about your accounting file(s). The output of these five are
modified by supplying either the average (\fI-a\fP) option, the hourly
profile (\fI-h\fP) option, and/or the clipping (\fI-c\fP) option.

The \fI-s\fP and \fI-e\fP options are used to select the starting date and
ending date, respectively, to report on. The format for the date is one of:
\fB+\fP\fIdays\fP (days since the beginning of the wtmp file) or
\fB-\fP\fIdays\fP (days before the end of the wtmp file) or in standard date
format: \fIMM/DD/YY\fP.

The \fI-M\fP option is used to select only specific hours in a day to perform
accounting on instead of all the hours in the day.  The \fIhour-range\fP
format is: (0-23)[-(0-23)[,\fIhour-range\fP[,...]]].  The hour given applies
to the whole hour, so a range of "5-6" is a time range from 5am to 6:59:59am.
This option is probably only usefull to those ISP providers that want to
charge a different rate for specific time periods.

Selecting the average option for total usage, gives an average number of
login hours per day since the creation of the wtmp file.  For the daily
option it prints the total # of logins for the day and the average login
time per login.  For the per person display it displays the total number of
logins the user has made and the average amount of time spent on each login.
For the TTY option, it prints the total number of logins on that TTY and the
average amount of time for each login.

Selecting the hourly profile option for total usage gives a visual display
of the percentage of login time spent per hour for all the logins on the
system.  For the daily option it prints the same visual display for each
day.  For the per person display it displays the hourly breakdown of login
time the user spends on the system (this can be pretty interesting).  For
the TTY option it breaks down hourly usage for each TTY.

Selecting the \fI-c\fP option performs clipping on the amount of login time
being used.  Multiple logins during the same time period will only count
once.  As a side effect (possibly a bug) clipping will affect the output of
the average option, reporting only the number of logins that uniquely apply
to the total login time. Logins that fall totally within the time span of
other logins will be totally clipped out, as if they did not occur.

If the optional user-list is given \fIsac\fP will only consider accounting
information from those users, discarding the rest.  The \fI-u\fP option can
be used to precede the optional user-list.  This option is useful to
terminate the \fI-x\fP, \fI-T\fP and \fI-H\fP options.

The \fI-x\fP option, has the reverse effect of the \fI-u\fP option, in that
it excludes the users specified from accounting.  This is useful for
removing users that are on a lot, which skew average usage results.

The \fI-T\fP option performs accounting for only the optionally specified
tty lines listed.  This is useful for determining modem usage, and who's
been using them the most.  The tty line may be given as a wildcard pattern,
using `*', `?', `[...]' and `[^...]' to easily select a given set of tty
lines (such as ttyC* to produce accounting on cyclades tty lines).  Wildcard
patterns should escaped or quoted to avoid having the shell process them.

The \fI-H\fP option performs accounting for only the optionally specified
hosts listed.  Since a host-name can only be up to 16 characters long in the
wtmp file, only the first 16 characters of a given host-name will be
considered for purposes of matches.  If a host-name given on the command line
does not contain any dots (\fB.\fP) or ends with a dot, it is taken to be a
substring and will match if the first part of the wtmp host-name matches the
substring.  Like with tty lines, the hostname may be given as a wildcard,
using `*', `?', `[...]' and `[^...]' to easily select a large number of
hosts at once (such as *.indstate.*).

The \fI-f\fP option makes sac perform accounting on both normal logins and
ftp logins. The \fI-F\fP option makes sac perform accounting on ftp logins,
normal logins are not considered.  Sac is only guaranteed to work with
wu-ftpd (wu-archive FTP daemon) style of utmp entry for ftp logins, denoted
by a line of "ftp#####" where "#####" is the process ID of the ftp process.
.br
.SH OPTIONS
\fISac\fP understands the following command line switches:
.TP
\fB--help\fP
Outputs a verbose usage listing.
.PP
.TP
\fB--verbose\fP
Outputs the version of sac.
.PP
.TP
\fB-w\fP [\fIwtmp-list\fP|\fB-\fP]
Select a different input file(s) instead of the default (\fI/var/log/wtmp\fP).
The accounting file type is determined by the options used before -w is reached.
.PP
.TP
\fB-d\fP
List login time per day instead of the default total time.
.PP
.TP
\fB-p\fP
List login time per user instead of the default total time.
.PP
.TP
\fB-t\fP
List login time per tty line instead of the default total time.
.PP
.TP
\fB-r\fP
Print almost everything that sac knows about your wtmp file. Time is
displayed in seconds.  The Hourmask is a 24 bit field representing which
hours accounting was performed on (zero for no mask used). The format is
fairly obvious.  Usefull for use as a backend to some accounting package or
for graphing usage. Quite verbose.
.PP
.TP
\fB-a\fP
Print average information.
.PP
.TP
\fB-h\fP
Print hourly profile information.
.PP
.TP
\fB-c\fP
Perform login "clipping".  Multiple logins during the same time period will
only count once.
.PP
.TP
\fB-o\fP
Read the wtmp file as if it were an old style BSD wtmp file (old utmp format
which does not use ut_type field).  Programs such as tacacs maintain a
wtmp file which does not use all the fields.
.PP
.TP
\fB-X\fP[\fB3\fP]
Read a wtmp file maintained by xtacacs, terminal server access control software,
versions 3.4 and 3.5.
.PP
.TP
\fB-X4\fP
Read a wtmp file maintained by xtacacs version 4.0.
.PP
.TP
\fB-R\fP \fIportmaster-list\fP
Read and process the detail files maintained by the Radius access control
software for Livingston(tm) portmaster terminal servers.  Sac will process
each detail file in /usr/adm/radacct/<portmaster-name>/detail each in
turn until all the detail files have been processed.  If no portmaster
name is given, a detail file must be specified with the `\fB-w\fP' option.
A detail file may be specified with the `\fB-w\fP' option in addition to
the `\fB-R\fP' option.
.PP
.TP
\fB-b\fP \fIhours\fP[\fI:minutes\fP[\fI:seconds\fP]]
Consider only those utmp entries that fall within the last few
hours/minutes/seconds from the current time, disregarding the rest.  This
option is useful for determining if someone has been on in the last few
hours.
.PP
.TP
\fB-s\fP \fIstart\fP
Selects the starting date of the report.
.PP
.TP
\fB-e\fP \fIend\fP
Selects the ending date of the report.
.PP
.TP
\fB-M\fP \fIhour-range\fP[,...]]
Select only specific hours in a day to perform accounting on instead of all
the hours in the day.  The \fIhour-range\fP format is:
(0-23)[-(0-23)[,\fIhour-range\fP[,...]]].  The hour given applies to the
whole hour, so a range of "5-6" is a time range from 5am to 6:59:59am.
.PP
.TP
\fB-f\fP
Perform ftp login accounting in addition to normal shell accounting.
.PP
.TP
\fB-F\fP
Perform ftp login accounting only.
.PP
.TP
\fB-m\fP
Show minimum and maximum number of concurrent logins over the total time
span or per day when used with the -d option.  \fB-m\fP is ignored when per
user accounting is selected.
.PP
.TP
\fB-u\fP \fIuser-list\fP
Selects only those users to perform accounting on.
.PP
.TP
\fB-x\fP \fIuser-list\fP
Selects those users to not perform accounting on.
.PP
.TP
\fB-T\fP \fItty-list\fP
Selects those ttys to perform accounting on.  Each tty specifier may be a
wildcard.
.PP
.TP
\fB-H\fP \fIhost-list\fP
Selects those hosts to perform accounting on.  Each host specifier may be
a wildcard.
.PP
.SH FILES
/var/log/wtmp                  login database
.br
/usr/adm/radacct/.../detail    Radius accounting logs
.SH AUTHOR
Steve Baker (ice@mama.indstate.edu)
.SH BUGS
The documentation for wtmp is lacking. It's not clear at all what all gets
put in wtmp or the significance of any of it.  Good luck getting this to
work on Solaris machines.

The -o and -X options handle what is a login and a logout differently than
normally (because there is no ut_type field), making sac incorrectly
identify \fIxterm\fP log-outs as a login (\fIxterm\fP does not write a
"login" entry, only a "logout" entry that looks just like a login in all
respects save the contents of the ut_type field).  It should also be noted
that \fIlast\fP incorrectly handles xterm log-outs as well.

The -f or -F options should not be used with -o -X[3|4] or -R options, as
sac will default back to a normal utmp format, or ignore the -f or -F
directives depending on where they occur on the command line.

Sac (probably) only handles changes in time logged in the wtmp file
made by netdate. Rdate does not log time changes.

Clipping can affect the output of the average option, as described above.

The ut_addr field doesn't seem to be consistently used by all programs, so
it cannot be used for exact host-name filtering.  Even if it were, it would
be too much work for this lazy programmer anyway.

Too much accounting results in big brother... citizen.
.SH SEE ALSO
.BR last (1),
.BR rawtmp (1)
