#!/bin/sh

set -e
echo ""
echo "BEWARE : Please know what you are doing here. Running"
echo "the bridge without knowing what is going on on your Network and this"
echo "Machine might spell desaster for the people hooked up to those networks"
echo "and might cause trouble for this machine connecting to the networks!"
echo ""
echo "You must have your kernel compiled for bridging operations!"
echo ""
echo "The DEFAULT CONFIGURATION is to bridge between eth0 and eth1."
echo ""
echo "Bridging is enabled on bootup. Edit /etc/init.d/bridgex to change it."

