#!/bin/sh
#ifhp -Fo -Tdebug=8 '-Tdev=/dev/ttyb,stty=38400 -echo -crmod -raw -oddp -evenp ixon pass8 -ixany cbreak' "$@" <<'EOF'
#ifhp '-Tdev=/dev/ttyb,stty=9600 -echo -crmod -raw -oddp -evenp ixon pass8 -ixany cbreak' "$@" <<'EOF'
ifhp -Fo '-Tdev=ecepr3%9100' "$@" <<'EOF'
test
This is a test
EOF
