#! /bin/sh
install-info --section Development Development --menuentry='Python Library' \
	--description='Runtime library for the Python programming language' \
	--quiet /usr/info/python-lib.info.gz
install-info --section Development Development --menuentry='Python X Library' \
	--description='X support for the Python programming language' \
	--quiet /usr/info/python-X-lib.info.gz
