#! /bin/sh

tail +2 /etc/shells |
while read shell
do
	dirname $shell
done |
sort -u |
while read dir
do
#
#	cd to lshells directory, note that /lshell may already be present in
#	/etc/shells
#
	if [ `basename $dir` = "lshells" ]
	then
		cd $dir
	else
		cd $dir/lshells
	fi
	tail +2 /etc/shells |
	grep ^$dir |
	while read shell
	do
#
#		finally remove the link
#
		/bin/rm -f `basename $shell`
	done
done
