.TH HATTRIB 1 13-Jan-1997 HFSUTILS
.SH NAME
hattrib \- change HFS file or directory attributes
.SH SYNOPSIS
hattrib
[-t
.IR TYPE ]
[-c
.IR CREA ]
[-|+i] [-|+l]
.I hfs-path
[...]
.SH DESCRIPTION
.B hattrib
permits the alteration of HFS file attributes. The MacOS-defined
.I type
and
.I creator
attributes can be set using the -t and -c flags, respectively. A file's
.I invisible
flag can be set or cleared with +i and -i, respectively. Finally, a file's
.I locked
flag can be set or cleared with +l and -l.
.PP
All files mentioned on the command line will receive the specified attributes,
regardless of the file's current attributes. Any attribute not mentioned in
the command line is left unchanged.
.PP
Note that the
.I invisible
and
.I locked
flags only have meaning to the Macintosh Finder.
.SH SEE ALSO
hfsutils(1), hls(1)
.SH FILES
$HOME/.hcwd
.SH AUTHOR
Robert Leslie <rob@mars.org>
