#!/bin/sh
#
# Invalidate /etc/rmtab entries for hosts named.
# Restart mountd for changes to take effect.
#
# usage: fixrmtab host1 host2 ...
#
# $Id: fixrmtab,v 1.1 1993/04/29 21:42:20 stolcke Exp $
#

#if [ $# = 0 ]; then
#	set -- defaulthost
#fi

RMTAB=/etc/rmtab
TMP=/tmp/rmtab.$$
if [ ! -f /etc/rmtab ]; then
	exit
fi

for host
do
	/bin/sed -e '/^'$host':/s/^./#/' $RMTAB > $TMP && \
	/bin/cp $TMP $RMTAB
done
/bin/rm -f $TMP

