.\" (c) 1993 by Thomas Koenig (ig25@rz.uni-karlsruhe.de)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"  
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" License.
.\" Modified Sun Jul 25 11:05:58 1993 by Rik Faith (faith@cs.unc.edu)
.\" Modified Sat Feb 10 16:18:03 1996 by Urs Thuermann (urs@isnogud.escape.de)
.\"
.\"Translated Sun 16 1996 by
.\"  Ignacio Arenaza Nuño (Ignacio.Arenaza@studi.epfl.ch) 
.\"Modified Sat 22 1996 by
.\"  Miguel Angel Sepulveda (angel@vivaldi.princeton.edu)
.TH HIER 7  "16 Julio 1996" "Linux" "Manual del programador"
.SH NOMBRE
hier \- Descripción de la jerarquía del sistema de ficheros.
.SH DESCRIPCIÓN
Un sistema Linux típico tiene, entre otros, los siguientes directorios:
.TP
.I /
Este es el directorio raiz. Aquí comienza todo el árbol de directorios.
.TP
.I /bin
Este directorio contiene programas ejecutables que son necesarios en
el modo monousuario y para el arranque o reparación del sistema.
.TP
.I /boot
Contiene ficheros estáticos para el cargador de arranque. Este
directorio contiene sólo los ficheros necesarios para el proceso de
arranque. El instalador del mapa de arranque y los ficheros de
configuracion deberian ir en
.I /sbin
y
.I /etc.
.TP
.I /dev
Ficheros especiales o de dispositivo, que se refieren a dispositivos
físicos. Ver mknod(1).
.TP
.I /dos
Si se utilizan tanto MS\-DOS como Linux en el mismo ordenador, éste es
el lugar típico para montar un sistema de ficheros DOS.
.TP
.I /etc
Contiene los ficheros de configuración locales a la máquina. Algunos
paquetes de programas más grandes, como X11, pueden tener sus propios
directorios bajo
.I /etc.
Los ficheros de configuración generales pueden colocarse aquí o en
.I /usr/etc.
No obstante, los programas siempre deben buscar estos ficheros en 
.I /etc
y se pueden tener enlaces para estos ficheros hacia
.I /usr/etc.
.TP
.I /etc/skel
Cuando se crea una nueva cuenta de usuario, normalmente se copian los
ficheros de este directorio al directorio raiz del usuario.
.TP
.I /etc/X11
Ficheros de configuración del sistema de ventanas X11.
.TP
.I /home
En las máquinas que poseen directorios raiz para usuarios, normalmente
éstos se hallan bajo este directorio, sea directa o indirectamente. La
estructura de este directorio depende de decisiones administrativas
locales.
.TP
.I /lib
Este directorio debe contener aquellas bibliotecas compartidas que son
necesarias para arrancar el sistema y para ejecutar los comandos en el
sistema de ficheros raiz.
.TP
.I /mnt
es un punto de monta para los sistemas de ficheros montados temporalmente.
.TP
.I /proc
Este es el punto de monta para el sistema de ficheros
.I proc,
que proporciona información acerca de los procesos en ejecución y el
núcleo. Este pseudo sistema de ficheros se describe con más detalle en
.I proc(5).
.TP
.I /sbin
Como
.I /bin,
este directorio contiene comandos necesarios para arrancar el sistema,
pero que habitualmente no son ejecutados por los usuarios normales.
.TP
.I /tmp
Este directorio contiene ficheros temporales que pueden borrarse sin
previo aviso, por ejemplo por un trabajo regular (regular job) o
durante el arranque del sistema.
.TP
.I /usr
Normalmente, este directorio se monta desde una partición
separada. Debería contener solamente datos compartibles de sólo
lectura, de forma que pueda ser montado por varias máquinas que usen
Linux.
.TP
.I /usr/X11R6
El sistema X-\Window, versión 11 distribución 6.
.TP
.I /usr/X11R6/bin
Ficheros binarios que pertenecen al sistema X\-Windows. A menudo existe un
enlace simbólico desde el más tradicional
.I /usr/bin/X11
hacia aquí.
.TP
.I /usr/X11R6/lib
Ficheros de datos associados con el sistema X\-Windows.
.TP
.I /usr/X11R6/lib/X11
Estos contienen ficheros variados necesarios para ejecutar X. A
menudo, existe un enlace simbólico desde
.I /usr/lib/X11
hacia este directorio.
.TP
.I /usr/X11R6/include/X11
Contiene ficheros de cabecera necesarios para compilar los programas
que usen el sistema de ventanas X11. A menudo, existe un enlace
simbólico desde
.I /usr/inlcude/X11
hacia este directorio.
.TP
.I /usr/bin
Este es el directorio primario para los programas ejecutables. Se
deberían colocar aquí la mayoría de los programas que van a ser
ejecutados por los usuarios normales, que ni son necesarios para
arrancar o reparar el sistema, ni están instalados localmente.
.TP
.I /usr/bin/X11
Es el lugar tradicional para buscar los ejecutables de X11. En Linux,
normalmente es un enlace simbólico hacia
.IR /usr/X11R6/bin .
.TP
.I /usr/dict
En este directorio se hallan los ficheros que contienen listas de
palabras para los correctores ortográficos.
.TP
.I /usr/etc
En este directorio se pueden almacenar los ficheros de configuración
globales a ser compartidos entre varias máquinas. Sin embargo, los
comandos siempre deben referenciar estos ficheros usando el directorio
.I /etc
Los enlaces desde los ficheros en
.I /etc
siempre deben apuntar a los ficheros apropiados en 
.I /usr/etc.
.TP
.I /usr/include
Ficheros de cabecera para el compilador C.
.TP
.I /usr/include/X11
Ficheros de cabecera para el compilador C y el sistema
X\-Windows. Normalmente es un enlace simbólico hacia
.I /usr/X11R6/include/X11.
.TP
.I /usr/include/asm
Ficheros de cabecera que declaran algunas funciones de
ensamblador. Debería ser un enlace simbólico hacia
.IR /usr/src/linux/include/asm .
.TP
.I /usr/include/linux
Contiene información que puede cambiar de versión en versión del
sistema y debería ser un enlace hacia
.I /usr/src/linux/include/linux
para obtener la información especfíca del sistema operativo.
.TP
.I /usr/include/g++
Ficheros de cabecera para usar con el compilador GNU C++.
.TP
.I /usr/lib
Bibliotecas objeto, que incluyen las bibliotecas dinámicas, más
algunos ejecutables que normalmente no se invocan directamente. Los
programas más complicados pueden tener aquí subdirectorios completos.
.TP
.I /usr/lib/X11
El lugar habitual para los ficheros de datos asociados con los
programas X, así como ficheros de configuración del propio X. En
Linux, normalmente es un enlace simbólico hacia
.IR /usr/X11R6/lib/X11 .
.TP
.I /usr/lib/gcc-lib
Contiene los ejecutables y ficheros de cabecera para el compilador
GNU C.
.BR gcc (1).
.TP
.I /usr/lib/groff
Ficheros para el sistema de formateo de documentos GNU groff.
.TP
.I /usr/lib/uucp
Ficheros para
.BR uucp (1).
.TP
.I /usr/lib/zoneinfo
Ficheros para la información de la zona horaria.
.TP
.I /usr/local
Aquí es donde van típicamente los programas que son locales a la
máquina.
.TP
.I /usr/local/bin
Aquí van los binarios de los programas locales a la máquina.
.TP
.I /usr/local/doc
Documentación local.
.TP
.I /usr/local/etc
Aquí van los ficheros de configuración asociados a los programas
instalados localmente.
.TP
.I /usr/local/lib
Aquí van los ficheros asociados a los programas instalados localmente.
.TP
.I /usr/local/info
Aquí van las páginas de info asociadas a los programas instalados
localmente.
.TP
.I /usr/local/man
Aquí van las páginas del manual asociadas a los programas instalados
localmente.
.TP
.I /usr/local/sbin
Programas de administración instalados localmente.
.TP
.I /usr/local/src
Código fuente para los programas instalados localmente.
.TP
.I /usr/man
Aquí van las páginas del manual, en sus subdirectorios.
.TP
.I /usr/man/cat[1-9]
Estos directorios contienen las páginas del manual preformateadas,
según su sección del manual.
.TP
.I /usr/man/<locale>/man[1-9]
Estos directorios contienen las páginas del manual que están en forma
de código fuente. Aquellos sistemas que utilicen un único lenguaje y
código de caracteres para todas las páginas del manual pueden omitir 
la cadena
.I <locale>.
.TP
.I /usr/sbin
Este directorio contiene los binarios de los programas de
administración del sistema que no son esenciales para el proceso de
arranque, para montar
.I /usr,
o para reparar el sistema.
.TP
.I /usr/src
Ficheros fuente para diferentes partes del sistema.
.TP
.I /usr/src/linux
Contiene las fuentes del núcleo del sistema operativo propiamente dicho.
.TP
.I /usr/tmp
Un sitio alternativo para colocar fichero temporales. Debería ser un
enlace hacia
.I /var/tmp.
.TP
.I /var
Este directorio contiene ficheros que pueden cambiar de tamaño, como
los ficheros de colas (de impresión y otros) y de registro.
.TP
.I /var/adm
Este directorio ha quedado obsoleto por 
.I /var/log
y debería ser un enlace simbólico hacia
.I /var/log.
.TP
.I /var/lock
En este directorio se crean los ficheros de bloqueo. La convención para
nombrar los ficheros de bloqueo es
.I LCK..<device>
donde
.I <device>
es el nombre del dispositivo en el sistema de ficheros.
El formato utilizado es el de los ficheros de bloqueo HDU UUCP, esto es,
ficheros de bloqueo que contienen un PID como un número decimal ASCII
de 10 bytes, seguido por un carácter de salto de línea.
.TP
.I /var/log
Ficheros de bitácora o "log" misceláneos.
.TP
.I /var/preserve
Aquí es donde
.BR vi (1)
guarda las sesiones de edición de forma que puedan ser restablecidas
más tarde.
.TP
.I /var/run
Ficheros de variables de ejecución, como los ficheros que contienen
los identificadores de proceso (PIDs) y la información de los usuarios
"logeados".
.I (utmp).
Los ficheros de este directorio se suelen borrar cuando se arranca el
sistema.
.TP
.I /var/spool
Ficheros en cola para varios programas.
.TP
.I /var/spool/at
Trabajos en cola para
.BR at (1).
.TP
.I /var/spool/cron
Trabajos en cola para
.BR cron (1).
.TP
.I /var/spool/lpd
Trabajos en cola para su impresión.
.TP
.I /var/spool/mail
Buzones de los usuarios.
.TP
.I /var/spool/smail
Ficheros en cola para el programa
.BR smail (1)
de distribución de correo.
.TP
.I /var/spool/news
Directorio de encolado para el subsistema de noticias.
.TP
.I /var/spool/uucp
Ficheros en cola para
.BR uucp (1).
.TP
.I /var/tmp
Como
.I /tmp,5
este directorio contiene ficheros temporales, almacenados durante un
tiempo no especificado.
.SH "CONFORMA CON"
El estándar de sistema de ficheros Linux, edición 1.2
.SH "ERRORES"
Esta lista no es exhaustiva. Diferentes sistemas puede estar
configurados de forma diferente.
.SH "VÉASE TAMBIÉN"
.BR find (1),
.BR ln (1),
.BR mount (1), 
.BR proc (5),
El Estándar del Sistema de Ficheros Linux.

