.TH DVISVGA 1 "1 April 1996"
.SH NAME
dvisvga \- view DVI files on SVGA displays
.SH SYNOPSIS
\fBdvisvga\fP 
[\fB\-?\fP] 
[\fB\-h\fP<\fImarg\fP>] 
[\fB\-v\fP<\fImarg\fP>]
[\fB\-p\fP<\fIwidth\fP>\fIx\fP<\fIheight\fP>]
[\fB-r\fP<\fIxres\fP>\fIx\fP<\fIyres\fP>] 
[\fB\-f\fP<\fIpath\fP>]
[\fB\-n\fP<\fIname\fP>] 
[\fB\-t\fP<\fIpath\fP>]
[\fB\-d\fP<\fIwidth\fP>\fIx\fP<\fIheight\fP>] 
[\fB\-m\fP<\fImag\fP>]
[\fB\-k\fP<\fIleftmarg\fP>\fI,\fP<\fIrightmarg\fP>\fI,\fP<\fIuppermarg\fP>\fI,\fP<\fIlowermarg\fP>]
[\fB\-s\fP<\fIstartup-file\fP>] 
[\fBfile\fP[\fB.dvi\fP]]
.SH DESCRIPTION
\fBdvisvga\fP is a screen-previewer for \fB.dvi\fP-files compiled by
\fBTeX\fP. It let's you see what your printed output will look like. You can
choose between a black-and-white representation and greyscaling. You can
choose an arbitrary zoomfactor (at some cost of performance). You can set
marks to measure distances. You can search for textstrings. \fBdvisvga\fP does
not support \fBpxl\fP-files since I think they are prehistoric. \fBdvisvga\fP
ignores all special-commands and has \fBno font-replacing\fP mechanism, sorry
lads.
\fBdvisvga\fP goes with
\fBlinux\fP, and needs \fBsvgalib v1.25\fP or higher to work. Try
\fBdvisvga -?\fP to get a complete list
of all possible command-line options and their default-values.
.SS IMPORTANT: 
All options have to be followed \fBIMMEDIATELY\fP by their arguments,
\fBNO spaces\fP must be inserted !!!
.SS OPTIONS
.TP
\fB-h\fP (\fBhorizontal-offset\fP)
A lot of printer drivers do a horizontal offset of 1 inch. If yours does as
well, you should use \fB-h25.4\fP. The length following \fB-h\fP must be
given in mm. Default: "25.4"
.TP
\fB-v\fP (\fBvertical-offset\fP)
A lot of printer drivers do a vertival offset of 1 inch. If yours does as
well, you should use \fB-v25.4\fP. The length following \fB-v\fP must be
given in mm. Default: "25.4"
.TP
\fB-p\fP (\fBPaper-size\fP)
Tells \fBdvisvga\fP width and height of the paper you are using. The width
is given first and both width and height are given in mm. Width and height
are seperated by an "x". Default: "210.0x297.0" (german DIN A4)
.TP
\fB-r\fP (\fBResolution\fP)
Tells \fBdvisvga\fP what kind of pk-files to use. The horizontal resolution
is given first and both horizontal and vertical resolution are given in dpi
(dots per inch). The two values are seperated by an "x". Saying
\fB-r600x600\fP means \fBdvisvga\fP will use fonts which were generated for a
600-dpi-printer. As \fBdvisvga\fP assumes that pixels on the screen are
square, different values for horizontal and vertical resolution will result
in a distorted image. Always make sure the desired pk-files are available.
The chosen resolution determines the (maximum) size of the representation.
Default: "300x300"
.TP
\fB-f\fP (\fBFont-path\fP)
A list of paths telling \fBdvisvga\fP where to look for the pk-files. The
items in this list have to be seperated by \fB:\fP's. The given list is
executed from left to right. If an item ends with \fB//\fP all
subdirectories will be scanned too. This is programed in a very odd way, so
it takes lots of time. You should place such items at the end of the list.
Defaults: "./:/usr/lib/texmf/fonts//".
.TP
\fB-n\fP (\fBName-of-the-font-file\fP)
If your dvi-file tells \fBdvisvga\fP to use a font called "thisnthatfont"
and \fBdvisvga\fP was told to use a resolution of "123" dpi, \fBdvisvga\fP
has to know how the desired file is named. In the string following "-n" the
following replacements are made: 
.PP
.PD 0
		xx	replaced by
.PP
		@N	thisnthatfont
.PP
		@K	thisntha
.PP
			(this is @N reduced to 8 char. (MS-DOG !))
.PP
		@M	123
.PP
			(the resolution)
.PP
		@R	615
.PP
			(this is @M*5, intended for magnified 200 
.PP
			 dpi fonts used instead of 300 dpi fonts)
.PD 1
.TP
	  Defaults: "@N.@Mpk"
.TP
\fB-t\fP (\fBtfm-path\fP)
A list of paths telling \fBdvisvga\fP where to look for the tfm-files. The
items in this list have to be separated by \fB;\fP's. The given list is
executed from left to right. tfm-files are only used, when \fBdvisvga\fP
can't find a font. Defaults: "./:usr/lib/texmf/fonts//".
.TP
\fB-d\fP (\fBDisplay\fP)
Tells \fBdvisvga\fP the desired resolution of your display. The width is
given first and both width and height are given in pixels. Width and height
are seperated by an "x". Using linux you may  choose a resulution
supported by your version of svgalib with respect to your hardware. Only
256-color-modes are allowed. That means to get more than 320x240 you must
have a svga chipset, standard vga wont do. Defaults: (linux) "640x480"
.TP
\fB-m\fP (\fBmagnification\fP)
If you want to magnify by a factor n you have to specify n*1000 as an
argument to \fB-m\fP, e.g. \fB-m2000\fP means all lengths will be doubled.
\fBNOTE: dvisvga\fP magnifies according to the origin of the dvi-coordinates,
which is -in most cases- NOT the upper left corner of the paper. Always make
sure the desired pk-files are available. \fB-m\fP doesn't magnify the paper,
so if you wish a larger image use the \fB+\fP and \fB-\fP keys or the
\fB-r\fP option. Default: get magnification from dvi-file.
.TP
\fB-k\fP (\fBkannot-print-any-further\fP)
Most printers stop printing if they are too close at the papers edge (some
might even do strange things). The \fB-k\fP option describes the printable
area, e.g. saying \fB-k1.0,2.0,3.0,4.0\fP means that your printer can print
as close as 1 mm to the left 2 mm to the right 3 mm to the upper 4 mm to the
lower edge of the paper. These values are used to draw a frame indicating
the printable area. All four values have to be given
and they have to be seperated by ",". All lengths are given in mm. Default:
"4.0,4.0,4.0,12.0"
.TP
\fB-s\fP (\fBstartup-file\fP)
The above options, a list of visited dvi-files and lots of other
interna may be loaded from the startup-file, specified directly after
the \fB-s\fP.  
When quitting \fBdvisvga\fP, the current options etc. will be saved in the
startup-file. \fBIf this is not desired, the startup-file has to
be set read-only !!\fP Default: "~/.dvisvga"

.SH ONLINEHELP

Pressing <\fB?\fP> twice shows the onlinehelp and gives a list of available
commands.

.SH COPYING 

The code of \fBdvisvga\fP uses some rather basic ideas stolen from
\fBxdvi\fP. This includes some few lines of code just copied. The author of
\fBxdvi\fP is \fBEric Cooper\fP. In a similar kind, \fBdvisvga\fP's code
depends on some lines of \fBdvidjc\fP, written by \fBWolfgang R.Mueller\fP.
The hyper-TeX related parts are taken from
\fBxhdvi\fP, written by \fBArthur Smith\fP. 
The sources of the above
can be found on the \fBCTAN\fP. So by having mentioned
the authors here, and giving a reference how to get the original sources,
this should not be a violation of their copyrights. 

As far as I am concerned, \fBdvisvga\fP may be modified or distributed
without any restrictions. \fBdvisvga\fP is distributed in the hope that it
will be useful, but without any warranty.
.SH AUTHOR
(C)opyright 1995 Thomas Moor (QElis@aol.com)













