.TH QUOTAON 8 "Tue Jun 8 1993"
.UC 4
.SH NAME
quotaon, quotaoff \- turn file system quotas on and off
.SH SYNOPSIS
.B /usr/etc/quotaon
[
.B \-vug
]
.IR filesystem .\|.\|.
.br
.B /usr/etc/quotaon
[
.B \-avug
]
.LP
.B /usr/etc/quotaoff
[
.B \-vug
]
.IR filesystem .\|.\|.
.br
.B /usr/etc/quotaoff
[
.B \-avug
]
.SH DESCRIPTION
.SS quotaon
.IX  "quotaon command"  ""  "\fLquotaon\fP \(em turn file system quotas on"
.IX  "user quotas"  "quotaon command"  ""  "\fLquotaon\fP \(em turn file system quotas on"
.IX  "disk quotas"  "quotaon command"  ""  "\fLquotaon\fP \(em turn file system quotas on"
.IX  "quotas"  "quotaon command"  ""  "\fLquotaon\fP \(em turn file system quotas on"
.IX  "file system"  "quotaon command"  ""  "\fLquotaon\fP \(em turn file system quotas on"
.LP
.B quotaon
announces to the system that disk quotas should be enabled on one or
more file systems. The file system quota files must be present in the root
directory of the specified file system and be named
.IR quota.user
for userquota or
.IR quota.group
for groupquota.
.SS quotaoff
.IX  "quotaoff command"  ""  "\fLquotaoff\fP \(em turn file system quotas off"
.IX  "user quotas"  "quotaoff command"  ""  "\fLquotaoff\fP \(em turn file system quotas off"
.IX  "disk quotas"  "quotaoff command"  ""  "\fLquotaoff\fP \(em turn file system quotas off"
.IX  "quotas"  "quotaoff command"  ""  "\fLquotaoff\fP \(em turn file system quotas off"
.IX  "file system"  "quotaoff command"  ""  "\fLquotaoff\fP \(em turn file system quotas off"
.LP
.B quotaoff
announces to the system that file systems specified should
have any disk quotas turned off.
.SH OPTIONS
.SS quotaon
.TP
.B \-a
All file systems in
.B /etc/fstab
marked read-write with quotas
will have their quotas turned on.  This is normally used at
boot time to enable quotas.
.TP
.B \-v
Display a message for each file system where quotas are turned on.
.TP
.B \-u
Manupulate user quotas. This is the default.
.TP
.B \-g
Manupulate group quotas.
.SS quotaoff
.TP
.B \-a
Force all file systems in
.B /etc/fstab
to have their quotas disabled.
.TP
.B \-v
Display a message for each file system affected.
.TP
.B \-u
Manupulate user quotas. This is the default.
.TP
.B \-g
Manupulate group quotas.
.LP
.SH FILES
.PD 0
.TP 20
.B quota.user
user quota file at the file system root
.TP
.B quota.group
group quota file at the file system root
.TP
.B /etc/fstab
default file systems
.PD
.SH "SEE ALSO"
.BR quotactl (2),
.BR fstab (5),
