load_lib mike-g++.exp
prebase

set src_code profile1.C
append CXXFLAGS " -pg"
set run yes
setup_xfail "*-*-pe*"
setup_xfail "alpha-*-*"
setup_xfail "a29k-*-*"
setup_xfail "hppa-*-*"
setup_xfail "i386-*-*"
setup_xfail "m68k-hp-hpux*"
setup_xfail "m68k-*-coff"
setup_xfail "mips-*-*"
setup_xfail "sh-*-*"
setup_xfail "sparc64-*-elf"
setup_xfail "z8k-*-*"

set groups {passed profiling}

postbase $src_code $run $groups
