.TH gkwish 1 "6 Jan 1995" "GroupKit"
.SH NAME
gkwish \- GroupKit interpreter
.SH SYNOPSIS
.TP 
\fBgkwish \fI?options? ?arg arg ...?\fR

.SH DESCRIPTION
Gkwish is the interpreter used for running GroupKit applications.
It consists of the Tcl command language, the Tk toolkit, the
Tcl-DP extension, and the GroupKit extensions.

Most of the GroupKit implementation is currently embedded in Tcl
scripts executed by gkwish, rather than embedded in the interpreter
itself.  As such, you will almost always use gkwish in the context
of either a conference application or a registrar client.  See
the manual entries for \fBgk_initConf\fR and \fBgk_initGenericRC\fR.

Besides the GroupKit extensions, the interpreter also includes
pieces of extensions found in the Extended Tcl (TclX) package.
Specifically, gkwish incorporates TclX's keyed lists and random
command.  

The full set of options available here are described in the manual
entry for \fdpwish\fR.

.SH "SEE ALSO"
.PP
gk_initConf(n), gk_initGenericRC(n), dpwish(1)

.SH AUTHOR
Mark Roseman (roseman@cpsc.ucalgary.ca)
