.TH open.reg 1 "6 Jan 1995" "GroupKit"
.SH NAME
open.reg \- GroupKit open policy registration interface
.SH SYNOPSIS
.TP 
\fBopen.reg ?-p\fIport\fR? ?-h\fIhost\fR?

.SH DESCRIPTION
Open.reg is a GroupKit registrar client used for creating and
joining GroupKit conferences using an "open registration"
policy.  Under this policy, any user can create a conference,
and users can join to any existing conference.

This registrar client connects to the central registrar,
which it locates by examining the "host" and "port" keys
in the "registrar" environment, which are usually specified
in the user's .groupkitrc file.  If the port is not specified,
it defaults to 9068.  The registrar's host and port can be
overridden on the command line by specifying the \fI-h\fR
or \fI-p\fR options.

The interface for this registrar client consists of two lists,
one showing all existing conferences and the other showing the
users in the selected conference.  A conference may be joined by
double-clicking on it in the left list.  New conferences can be
created by choosing a conference type from the "Conferences"
menu, and then naming the conference.  Conferences created by
this registrar client are automatically destroyed when the 
last user leaves the conference.

.SH "SEE ALSO"
.PP
registrar(1), gk_initGenericRC(n)

.SH AUTHOR
Mark Roseman (roseman@cpsc.ucalgary.ca)
