.TH registrar 1 "6 Jan 1995" "GroupKit"
.SH NAME
registrar \- GroupKit registration daemon
.SH SYNOPSIS
.TP 
\fBregistrar ?-p\fIport\fR?

.SH DESCRIPTION
This command is used to create a GroupKit registration daemon on
the local machine.  Registrar clients (such as \fIopen.reg\fR)
require this daemon to be running.  Normally the daemon is run
as a background process.

The daemon will listen for connections from registrar clients on
the port specified by the "port" key of the "registrar"
environment, which can be specified in the user's .groupkitrc
file.  If this is not present, the registrar will run on port
9068.  The port number can be overridden by specifying the
\fI-p\fR option on the command line.

The registrar command also creates two additional processes.
The first is a persistence server, used to hold the state of
persistent conferences after the last user leaves.  The second
is a server that supports the rooms based registrar client.

.SH LIMITATIONS
There is no way currently to set the port numbers for the 
persist and rooms processes from the command line.

.SH "SEE ALSO"
.PP
open.reg(1)

.SH AUTHOR
Mark Roseman (roseman@cpsc.ucalgary.ca)
