.TH rmconf.reg 1 "6 Jan 1995" "GroupKit"
.SH NAME
rmconf.reg \- GroupKit interface for deleting zombie conferences
.SH SYNOPSIS
.TP 
\fBrmconf.reg ?-p\fIport\fR? ?-h\fIhost\fR?

.SH DESCRIPTION
Rmconf.reg is a GroupKit registrar client used for deleting
"zombie" conferences, which are sometimes created when GroupKit
programs exit improperly.

This registrar client connects to the central registrar,
which it locates by examining the "host" and "port" keys
in the "registrar" environment, which are usually specified
in the user's .groupkitrc file.  If the port is not specified,
it defaults to 9068.  The registrar's host and port can be
overridden on the command line by specifying the \fI-h\fR
or \fI-p\fR options.

The interface for this registrar client consists of two lists,
one showing all existing conferences and the other showing the
users in the selected conference.  A conference can be deleted
by double clicking on its name.

.SH "SEE ALSO"
.PP
registrar(1), gk_initGenericRC(n), open.reg(1)

.SH AUTHOR
Mark Roseman (roseman@cpsc.ucalgary.ca)
