.TH rooms.reg 1 "1 May 1995" "GroupKit"
.SH NAME
rooms.reg \- GroupKit rooms-based registration interface
.SH SYNOPSIS
.TP 
\fBrooms.reg ?-p\fIport\fR? ?-h\fIhost\fR?

.SH DESCRIPTION
Rooms.reg is a GroupKit registrar client used for creating and
joining GroupKit conferences using a "rooms-based" metaphor.
Conferences are placed into rooms, and users can move between
rooms freely.  When entering a room with conferences in progress,
the user is automatically joined to those conferences; similarly,
leaving a room will exit the conferences contained in the room.

This registrar client connects to the central registrar,
which it locates by examining the "host" and "port" keys
in the "registrar" environment, which are usually specified
in the user's .groupkitrc file.  If the port is not specified,
it defaults to 9068.  The registrar's host and port can be
overridden on the command line by specifying the \fI-h\fR
or \fI-p\fR options.


.SH "SEE ALSO"
.PP
registrar(1), gk_initGenericRC(n), open.reg(1)

.SH AUTHOR
Mark Roseman (roseman@cpsc.ucalgary.ca)
