.\" Copyright (c) 1986 Torsten Poulin <torsten@diku.dk>
.\" May be distributed under the GNU General Public License
.TH UPDATE 8 "July 26, 1996" "Linux 2.0" "Linux Programmer's Manual"
.SH NAME
update \- periodically flush filesystem buffers.
.SH SYNOPSIS
.B update [ options ]
.SH DESCRIPTION
The
.B update
daemon flushes the filesystem buffers at a regular interval. It has
two modes of operation. By default it will wake up every 5 seconds and
flush some dirty buffers. If this is not possible, it will
automatically fall back to the traditional behavior of waking up every
30 seconds to call
.BR sync (2).
.PP
The following options are accepted by
.BR update :
.TP
.B \-S
Use the traditional behavior of calling
.BR sync (2)
even if the preferred method of flushing is possible.
.TP
.BI \-s " secs"
If using sync, wake up and call it every
.I secs
seconds. The default is every 30 seconds.
.TP
.BI \-f " secs"
Unless using sync, wake up and flush some buffers every
.I secs
seconds. The default is every 5 seconds.
.PP
.B update
should be started as early as possible during the boot process. If it
is invoked by a non\-privileged user, it calls sync and exits.
.SH "SEE ALSO"
.BR init (8),
.BR sync (2),
.BR sync (8)
.SH AUTHOR
Torsten Poulin (torsten@diku.dk)
