.TH append_db 1 "11/94" "teTeX" "teTeX"
.SH NAME
append_db \- add single entry to TeX\-inputfiles\-database
.SH SYNOPSIS
.B append_db filename location
.SH DESCRIPTION
The binaries of
.I teTeX
use the file
.B $TEXMF/ls\-R
as database for the locations of common input files.
.I append_db
is used internally by
.I MakeTeXTFM
and
.I MakeTeXPK
to add a freshly created font to the database.

The
.I teTeX
binaries will find files even if they are not in the database (as long as
they are in the standard search paths),
.B but it will need very much longer!!!

.SH "SEE ALSO"
.IR ls\-R (5),
.IR texhash (1).

.SH AUTHOR
Thomas Esser (te@informatik.uni\-hannover.de)
