.TH texhash 1 "09/94" "teTeX" "teTeX"
.SH NAME
texhash \- rebuild TeX\-inputfiles\-database
.SH SYNOPSIS
.B texhash
.SH DESCRIPTION
The binaries of
.I teTeX
use the file
.B $TEXMF/ls\-R
as database for the locations of common input files. After adding new
input files (fonts, style\-files etc.) it is strongly recommended to
run
.I texhash
to update the database.

The
.I teTeX
binaries may find files even if they are not in the database (as long as
the !!-prefix to inhibit disk searching is not given for the relevant path component),
.B but it will need very much longer!!!

Pixel fonts that are calculated during compilation of a tex or dvi file are
added automatically to the database if possible. Nevertheless, you should call
.I texhash
from time to time (e.g. through the
.IR cron -daemon
) to update the file completely.

.SH "SEE ALSO"
.IR ls\-R (5),
.IR append_db (1).

.SH AUTHOR
Thomas Esser (te@informatik.uni\-hannover.de)
