.TH CCMTCNVT 1
.SH NAME
ccmtcnvt \- convert C++ comments to C comments
.SH SYNOPSIS
ccmtcnvt [-hv] [--help] [--version] [file ...]
.SH "DESCRIPTION"
This program converts the C++ style comments into C style comments.
C++ allows comments of that begin with `//' and end with the next newline.
Some C compilers accept these as well, 
which lures people into using them, 
even though it is against the language definition,
and even though most C compilers will not accept such comments.
.SH BUGS
ccmtcnvt assumes that the input is syntactically correct C code (except for
the comments).
.SH AUTHOR
Lars Wirzenius, liw@iki.fi.
