.TH RMCCMT 1
.SH NAME
rmccmt \- remove comments from C programs
.SH SYNOPSIS
rmccmt [-n] [file ...]
.SH "DESCRIPTION"
This program removes comments from C source code.
Each comment is replaced with one space.
With the `-n' option, newlines inside comments are kept.
.SH AUTHOR
Lars Wirzenius, liw@iki.fi.
