.TH UNTRIGRAPH 1
.SH NAME
untrigraph \- remove trigraphs from C source code
.SH SYNOPSIS
untrigraph [file ...]
.SH "DESCRIPTION"
untrigraph converts trigraphs into their single character equivalents.
.PP
See the entrigraph(1) manual page for a description of trigraphs.
.SH "SEE ALSO"
entrigraph(1)
.SH AUTHOR
Lars Wirzenius, liw@iki.fi.
