.TH BUILD 1L "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
build \- Build a debian package
.SH SYNOPSIS
\fBbuild\fP [\fBbinary\fP|\fBclean\fP|\fBbinary-indep\fP|\fBbinary-arch\fP]
\fBbuild\fP [ dpkg-buildpackage-options ]
.br
.SH DESCRIPTION
.I build
completely builds all elements from a debian package that are necessary
to upload. It does a
.B dpkg-buildpackage
by default. If a parameter 
is given it then
.B debian/rules
will be invoked with that parameter
instead.
.PP
.B build
has to be invoked from within the sourcecode package.
.PP
If you find that
.B dpkg-buildpackage
is still prompting you for a pgp password then set the environent variable
.B PGPPASS
to the password you use and it will work completely without asking any
questions. Note that doing this on a multiuser system is a potential problem
since other users might find ways to have a look at your environment
settings in .profile, through the /proc interface, with ps or with some
other means. See the pgp documentation for more details on the issue.
.SH REQUIREMENTS
.B build
needs to be run as superuser to function properly. This can be done by
configuring some superuser access tool to invoke build (like sudo or super)
or by making build setsuid. For example the command:
.br
.B chmod 4750 /usr/bin/build
.br
would allow users of the group that owns build (default root) to have access
to build running as the superuser.
.PP
Note that setuid binaries might create a security problems on your system.
You need to set up the permissions again after each upgrade of debmake.
.SH AUTHOR
Christoph Lameter <clameter@debian.org>
