.TH debclean 1L "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
debclean \- Cleanup a sourcecode tree
.SH SYNOPSIS
\fBdebclean
.SH DESCRIPTION
debclean goes through the tree beneath the directory it was invoked in and
executes
.I debian/rules clean
for each debian sourcedirectory encountered.
.PP
In the directory level above a package where the released software files are
all *.deb, *.changes, *.dsc files are removed. The .diff.gz and the tar.gz
are not touched so that the release can be reconstructed if necessary.
.PP
.B debclean
uses
.B build(1)
to clean the sourcetree.
.SS AUTHOR
Christoph Lameter <clameter@debian.org>
