.TH DEBC 1L "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
debc \- View contents of generated debian package.
.SH SYNOPSIS
\fBdebc\fP
.br
.SH DESCRIPTION
.I debc
figures out the current version of a package and displays the contents
of it on stdout (dpkg -I, dpkg -c). It has to be called from within the sourcecode package.
.SH AUTHOR
Christoph Lameter <clameter@debian.org>
