.TH DEBCONF 1L "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
debsums \- Run the pre-installation configure script of a package
.SH SYNOPSIS
\fBdebconf\fP [package] ...
.br
.SH DESCRIPTION
.I debconf
will run the configure scripts of the indicated packages. Packages can
either refer to an already installed package then the configure script in
.I /var/lib/dpkg/info/package.configure
is executed or a package can be specified by giving the location of a binary
debian package. That package will be checked for a configure script and if a
configure script is present it will be executed.
.SH AUTHOR
Christoph Lameter <clameter@debian.org>
