.TH DEBSUMS 1L "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
debsums \- Check the md5sums of a package
.SH SYNOPSIS
\fBdebsums\fP [-a] [-s] [package] ...
.br
.SH DESCRIPTION
.I debsums
will check if the indicated packages were installed with checksums. If so
then the checksums will be compared against the currently installed files.
The package can either be a filename of a .deb archive in which case the
checksums are extracted from that package and compared or an installed
package name.
.PP
If no packages are specified then a scan of all installed packages with
checksums is performed. It is recommended to use the
.B -s
option to reduce output.
.PP
The configuration files of a package are exempt from the check performed
since they are supposed to be changed. A failure on a configfile is no
indication of a problem.
.PP
You might have to run debsums as the superuser if there are files not
readable by regular users installed by a package.
.SH OPTIONS
.TP
.B -a
Check all files including configuration files for matches to the checksum.
.TP
.B -s
Be silent. Just report problems.
.SH AUTHOR
Christoph Lameter <clameter@debian.org>
