.TH uupdate 1L "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
uupdate \- Upgrade a sourcecode package with material from upstream
.SH SYNOPSIS
\fBuupdate\fP [\fB\-v newversion\fP] [\fB\-p patchfile\fP] | sourcearchive
.SH DESCRIPTION
.B uupdate
modifies an existing sourcecode archive to reflect an upstream update with a
patch or from a wholly new sourcecode archive. The utility needs to be
invoked from inside the old sourcecode directory.
.PP
Usually
.B uupdate
will be able to deduce the version number from the sourcearchive name. If
that fails you need to specify the version number (without the debian
release which will always be initially 1!) with the -v option.
.SH ACTIONS TAKEN
.TP
.B Figure out new version.
The archivename is analyzed for a sequence of digits separated by dots. If
something like that is found its taken to be the new upstream version
number.
.TP
.B Unpacking.
The archive is unpacked renamed to the correct debian package name. The .orig directory is generated.
.TP
.B Patching.
The latest localizable diffs are applied to the unpackaged archive. 
The file
.B debian/rules
is made executable and eventual rejects are displayed.
.TP
.B Version.
A changelog entry with the version number is generated.
.SH AUTHOR
Christoph Lameter <clameter@debian.org>
