#
# Copyright (c) Mark J. Kilgard, 1995.
#
include $(ROOT)/usr/include/make/commondefs

TOP = ..

# $(TOP)/Fortran.mk should contain the line "FGLUT = fglut" if
# the Fortran GLUT API binding is to be built.  Note:  This requires
# IRIX 5.3 and the SGI Fortran compiler and OpenGL Fortran libraries
# installed.
sinclude $(TOP)/Fortran.mk

SUBDIRS = glut $(FGLUT)

default $(COMMONTARGS): $(_FORCE)
	$(SUBDIRS_MAKERULE)

$(SUBDIRS): $(_FORCE)
	cd $@; $(MAKE)

$(_FORCE):
