.\" Copyright (c) 1996, 1997 Peter Fox <fox@roestock.demon.co.uk>
.\" This program is distributed according to the Gnu General Public License.
.\" See the file COPYING in the isapnptools source distribution.
.\"
.\" $Id: isapnp.8,v 0.1 1997/01/14 21:46:57 fox Exp $
.\"
.TH ISAPNP 8 "14 Jan 1997" "isapnptools"
.SH NAME
isapnp \- Configure ISA Plug-and-Play devices.
.SH SYNOPSIS
\fBisapnp\fP \fIconffile\fP 
.SH DESCRIPTION
\fBisapnp\fP will carry out the instructions provided
in the \fIconffile\fP to configure ISA PnP cards.
\fBisapnp\fP must read in the entire configuration file
successfully before it will execute the commands: this
is to ensure the instructions are consistent and valid.

The format of the configuration file is described
in \fBisapnp.conf(5)\fP.

.SH FILES
.TP
\fC/sbin/isapnp\fR
The executable.
.TP
\fC/etc/isapnp.conf\fR
The standard place for the \fIconffile\fP.
.SH BUGS
Lines may not always be counted correctly. (For diagnostics).
If you think you have found any more, please send a report to
isapnp@roestock.demon.co.uk.
.SH WARNING
This program can reset all your Plug-and-Play devices.
Use at your own risk.
.SH AUTHOR
\fBisapnp\fP has been written by Peter Fox <fox@roestock.demon.co.uk>,
the creator and maintainer of isapnptools.
.SH AVAILABILITY
The latest version of the sources may be obtained by ftp from
ftp://ftp.demon.co.uk/pub/unix/linux/utils
.br
Or follow the pointer from my web page at
http://www.roestock.demon.co.uk/
.SH REFERENCES
Plug and Play ISA Specification, Version 1.0a, May 5, 1994.
Available from ftp://ftp.microsoft.com/developer/drg/Plug-and-Play/Pnpspecs
.SH "SEE ALSO"
pnpdump(8), isapnp.conf(5)
