.\" Traduzione italiana di Giuseppe De Marco <gdm@rebel.net>
.\" 4 Ottobre 1996 - Ultima modifica: 15 Marzo 1997

.\" $Revision: 1.1 $
.TH TESTHOST 1
.SH NOME
testhost - testa lo stato di un news server NNTP
.SH SINTASSI
.I testhost
.BI hostname
[
.BI -a | -n
date time
]
[
.BI -s | -S
filename
]
[
.BI -e | -E
filename
]
[
.BI -N
port_number
]
[
.BI -U
userid
]
[
.BI -P
password
]
[
.BI -l
phrase_file
]

.SH OPZIONI
-a     Prende la lista dei newsgroup attivi sull'hostname

-n date time     Prende i newsgroup creati sull'host dalla data ed
ora specificati in poi. La data dev'essere nel formato AAMMGG e l'ora dev'essere
nel formato OOMMSS.

-s | -S filename

Queste opzioni manderanno tutti i messaggi di stato (normalmente mostrati su
stdout) ad un file alternativo.  La versione minuscola, -s, manderà i messaggi
di stato al compiled-in default definito in suck_config.h.
Il default è /dev/null, in modo che non venga mostrato alcun messaggio di stato.
La versione maiuscola, -S, richiede il parametro filename.
Tutti i messaggi di stato verranno quindi mandati a tal file.

-e | -E filename

Queste opzioni manderanno tutti i messaggi di errore (normalmente mostrati su
stderr) ad un file alternativo.  La versione minuscola, -e, manderà tutti
i messaggi d'errore al compiled-in default definito in suck_config.h.
Il default è suck.errog.  La versione maiuscola, -E, richiede il parametro
filename.  Tutti i messaggi di errore verranno quindi mandati a tal file.

-N port_number

Questa opzione dirà a testhost di usare un numero di porta NNRP alternativo
al 119 di default, quando si connette all'host.

-U userid

-P password

Queste due opzioni permettono di specificare un userid ed una password, se
il server NNTP li richiede.

\-l phrase_file

Questa opzione dice a testhost di caricare un file delle frasi alternativo,
invece di usare i messaggi built-in.  Questo permette di far stampare a
testhost le frasi in un'altra lingua, o permette di customizzare i messaggi
senza ricompilare.
Vedere "FRASI IN UNA LINGUA STRANIERA" in suck.1 per ulteriori dettagli.


.SH DESCRIZIONE
.I Testhost
interrogherà un news server NNTP, specificato da
.I hostname.
L'azione di default è di emettere il comando
.I help
al server, per vedere che software sta usando
e che comandi accetta.
.PP
Se viene usata l'opzione
.I -a
, testhost mostrerà l'active history list del server.  Se l'opzione 
.I -n date time
viene usata, testhost mostrerà tutti i nuovi gruppi creati sul server
dalla data ed ora specificati.
.SH CODICI DI USCITA
0 in caso di successo, -1 in caso di fallimento.
.de R$
Questa revisione \\$3, \\$4.
..
.SH "VEDERE ANCHE"
suck(1), rpost(1), lpost(1).
