.TH gdbdump 1 "February 1996" "Steve Roth et.al." "HP100LX Tools"
.SH NAME
gdbdump \- dump HP 100LX database into ASCII format
.SH SYNOPSIS
.B gdbdump
.RB [ -noqswm ]
.I file
.SH DESCRIPTION
.B gdbdump
exports the contents of an HP 100LX database into an ASCII form.
.I file
is the name of the 100LX database to read; the results are written to
the terminal and can be redirected or piped as needed.
The output format is suitable for input to many database packages as
well as to
.IR gdbload (1).
.SS Options
.B gdbdump
recognizes the following options:
.RS
.TP
.B -n
Suppress the first line of the output, which normally contains the names
of all of the database fields.
Note that if this option is specified, the output is not compatible with
.IR gdbload (1).
However, this option may be needed for compatibility with other database
programs trying to read the output.
.TP
.B -o
Omit note fields from the output.
Note fields are included by default.
.TP
.B -q
Suppress warning messages.
.TP
.B -s
Write special characters (character codes 128-254, inclusive) directly
to the output.  The default is to represent such characters in \\nnn
notation.
.TP
.B -w
Wrap long lines.
For some databases, the output line length can be larger than some programs
(notably
.IR vi (1))
can handle, especially if records contain long notes.
This option wraps each output line at about 75 characters, marking the end
of lines to be continued with a backslash (\\).
.IR gdbload (1)
understands this format.
.TP
.B -m
Write multi-line string (i.e. note) fields on multiple lines. Thus the
quoted string will span newlines. Without this option, newlines in strings
will be output as \\r\\n sequences, and the complete string will be subject
to line wrapping if specified by the
.B -w 
option.
.RE
.SS "Output Format Description"
The output of this program is an ASCII text file which starts with a line
containing field names (unless
.B -n
was specified) and is followed by one line for each record of the database.
Note that any of these lines may be split into multiple lines if
.B -w
is specified, and that newlines in strings may cause further splitting if
specified by the
.B -m
option.
Each "logical" line contains all of the fields of the database, in the
same order in
which their field names appeared on the first line of the output.
The fields are separated by commas.
.PP
Exactly how each field appears in the output depends on its type.
Text fields, category fields, and note fields appear with the contents
inside quote marks (").  Quote marks and backslashes within the text
of the field are escaped by preceding them with a backslash (\\).
Newlines are printed as \\n and carriage returns as \\r, unless the
.B -m
option is used. Non-printing
or non-ASCII characters as \\nnn, where nnn is an octal character code.
(See the description of the
.B -s
flag, above.)
.PP
Number fields appear as they do in the database.  Date fields appear
in the format YYYYMMDD; for example, August 15, 1993 would appear as
19930815.  Time fields appear in the format HHMM, where HH is in the
range 00-23.
.PP
Radio buttons and check boxes appear as 1 if selected, 0 otherwise.
.PP
All other field types, including application-defined types, are omitted
from the output.
.PP
This output format can be used as input to
.IR gdbload (1).
.SH WARNINGS
.B gdbdump
cannot handle the application-defined records and fields in HP 100LX
Appointment Book and World Time databases.  Running this program on
such databases will give useful, but incomplete, output.
.PP
Records are printed in the order stored in the file, i.e., randomly.
.PP
This program cannot handle password-protected databases.  Attempts to
dump password-protected databases will have unpredictable results.
.SH AUTHOR
.B gdbdump
was written by Steven Roth, stever@cup.hp.com, and is being maintained
by Arne Christensen, arc@pine.dk.  Contact the latter
for bug reports, enhancement requests, or to get a copy of the source
code.
.SH DISCLAIMER
This program is released into the public domain and
neither the author nor the maintainer place any restrictions on its use.
We make no warranties or guarantees for this program and
you use it at your own risk.
This program is supplied by us personally and
not by Hewlett-Packard Co. or Pine Tree Systems, which incur no
obligations pertaining to it.
.SH ACKNOWLEDGEMENTS
Many thanks to Andy Gryc for publishing the details of the database file
formats!
.SH SEE ALSO
gdbload(1).
