#! /bin/sh
install-info --quiet --description="Debian GNU/Linux FAQ" \
 --section "Information" "Information" /usr/info/debian-faq.info.gz

# remove old 0.93R6 base disk leftover

rm -f /usr/doc/{bug-log-access.txt,bug-reporting.txt,mailing-lists.txt}