/*
 * vgrammar.c - includes and macros for building the parse tree
 */

#include "../h/define.h"
#include "../common/yacctok.h"

%{
/*
 * These commented directives are passed through the first application
 * of cpp, then turned into real includes in tgram.g by fixgram.icn.
 */
/*#include "../h/gsupport.h"*/
/*#include "../h/lexdef.h"*/
/*#include "tproto.h"*/
/*#include "tglobals.h"*/
/*#include "tsym.h"*/
/*#include "tree.h"*/
/*#include "keyword.h"*/
/*#undef YYSTYPE*/
/*#define YYSTYPE nodeptr*/
/*#define YYMAXDEPTH 500*/

extern int fncargs[];
int idflag;
int id_cnt;

nodeptr q();
nodeptr cat();
nodeptr quote();

#include "ident.h"
%}

%%
#include "../h/grammar.h"
%%

/*
 * xfree(p) -- used with free(p) macro to avoid compiler errors from
 *  miscast free calls generated by Yacc.
 */
static novalue xfree(p)
char *p;
{
   free(p);
}

/*#define free(p) xfree((char*)p)*/
