.ds f. http-gw.tbl
.\" Peter J. Churchyard, 1994
.\" Copyright (C) Trusted Information Systems, Inc.
.\" All rights reserved
.TH HTTP-GOPHER-PROXY 8 "26 September 1994"
.SH NAME
HTTP-GW - Gopher / HTTP proxy
.SH SYNOPSIS
.B http-gw [ options \]
- invoked from inetd
.SH DESCRIPTION
.IX  "HTTP-GW"  ""  "\(em Gopher/HTTP proxy server"
.LP
.B HTTP-GW
provides Gopher and HTTP proxy services with logging and
access control. It allows Gopher and Gopher+ client to access
Gopher, Gopher+, and FTP servers. It also allows WWW clients
such as Mosaic to access HTTP, Gopher and FTP servers. Both
standard and proxy aware WWW clients are supported. The proxy supports 
.B common use
of the Gopher, Gopher+ and HTTP protocols. Except where noted, 
.B client
means Gopher, Gopher+, WWW, or proxy aware WWW clients, 
.B server
means Gopher, Gopher+, HTTP, or FTP servers.
.LP
Proxy aware clients should be configured to use the proxy. Non proxy
aware clients should be setup so that their 
.B HOME PAGE
is the proxy. If you are installing a firewall where you already have
users using Gopher or WWW, then they need to edit their 
.B Hotlists
to route the requests through the proxy. 
.TP 5
.B WWW (URLs)
Insert the string 
.B http://firewall/
in front of the existing URL.
.TP 5
.B Gopher
Change the Gopher menu information from
.LP
.RS 10
Host=somehost
.br
Port=someport
.br
Path=somepath
.RS 5
.br
to
.RS -5
.br
Host=firewall
.br
Port=70
.br
Path=gopher://somehost:someport/somepath
.LP
.RS -10
Assuming that the proxy has been configured to be on the default HTTP and
Gopher ports (80 and 70 repectively)
.SH OPTIONS
.LP
.B \-d file
This option can only be used if the proxy was compiled with BINDDEBUG. It
allows debugging information to be written to the specified file.
.LP
.B \-D
This option turns on the debugging log if specified. The proxy must be
compiled with BINDDEBUG for the option to be recognised.
.LP
.SH OPERATION
.LP
.B HTTP-GW
is invoked from
.B inetd(8),
it reads its configuration and checks to see if the
system that has just connected is permitted to use the
proxy. If not, it returns a message/menu and logs
the connection. If the peer is permitted to use the
proxy,
.B HTTP-GW
reads in a single line request which it then decodes. 
If needed, more lines are read from
the client. Most requests carry the information that the proxy needs in the
first line.
.LP
When a user initiates a request, the client determines three pieces of 
information. These are 
.B host, port 
and a
.B selector.
The client then connects to the host on the port and sends the selector. When
using a proxy, the host and port refer to the proxy itself. The proxy has
to determine the host and port from information contained in the selector.
The proxy does this by re-writing the information it passes back to the client.
Both Gopher and WWW clients do none or only minimal processing on the selector.
If the proxy cannot find it's special information in the selector, it looks in
it's configuration file to see if a server has been defined that the request
can be handed off to.
.LP
There are three main types of information that the proxy has to process.
.TP 5
.B Gopher menus
.br
these contain a 
.B description
(to be displayed to the user), a
.B selector, 
a
.B host, 
and a
.B port.
The first character of the description is used to tell the client the sort of
information that the entry refers to.
.TP 5
.B HTML files
.br
contain Hypertext which can contain embedded 
.B links 
to other documents. The proxy has to parse the HTML file and re-write 
the links so that the client routes the request through the proxy.
.TP 5
.B other data files
.b
these can be roughly classified as 
.B text
or
.B binary
data. The proxy just passes the data through without changing it.
.LP
The proxy encodes the extra information into the selector by converting it
into a
.B URL
(Universal Resource Locator) This is also the form of selector that is used
in 
.B HTML
documents.
.LP
.ne 20
When building a Gopher Menu from an FTP directory list, the proxy has to 
guess what Gopher type to specify by looking at the file extension. 

.TS
.if \n+(b.=1 .nr d. \n(.c-\n(c.-1
.de 35
.ps \n(.s
.vs \n(.vu
.in \n(.iu
.if \n(.u .fi
.if \n(.j .ad
.if \n(.j=0 .na
..
.nf
.nr #~ 0
.if n .nr #~ 0.6n
.ds #d .d
.if \(ts\n(.z\(ts\(ts .ds #d nl
.fc
.nr 33 \n(.s
.rm 80 81 82
.nr 80 0
.nr 38 \wDescription
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \w 
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wGIF Image
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wDOS archives
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wDOS binaries
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wMisc Images
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wUnix binaries
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wMAC archives
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wMisc sounds
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wHTML Documents
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wMisc Documents
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \w 
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wDirectories
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \w 
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wPlain text
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \w 
.if \n(80<\n(38 .nr 80 \n(38
.80
.rm 80
.nr 81 0
.nr 38 \wGopher type
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wg
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \w5
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \w9
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wI
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \w9
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \w4
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \ws
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wh
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \w9
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \w1
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \w0
.if \n(81<\n(38 .nr 81 \n(38
.81
.rm 81
.nr 82 0
.nr 38 \wExtensions
.if \n(82<\n(38 .nr 82 \n(38
.nr 38 \w.gif
.if \n(82<\n(38 .nr 82 \n(38
.nr 38 \w.zip .zoo .arj .arc .lzh
.if \n(82<\n(38 .nr 82 \n(38
.nr 38 \w.exe .com .dll .lib .sys
.if \n(82<\n(38 .nr 82 \n(38
.nr 38 \w.jpg .jpeg .pict .pct .tiff 
.if \n(82<\n(38 .nr 82 \n(38
.nr 38 \w.tif .pcx
.if \n(82<\n(38 .nr 82 \n(38
.nr 38 \w.tar .z .gz
.if \n(82<\n(38 .nr 82 \n(38
.nr 38 \w.hqx
.if \n(82<\n(38 .nr 82 \n(38
.nr 38 \w.au .snd .wav 
.if \n(82<\n(38 .nr 82 \n(38
.nr 38 \w.html .htm 
.if \n(82<\n(38 .nr 82 \n(38
.nr 38 \w.doc .wri 
.if \n(82<\n(38 .nr 82 \n(38
.nr 38 \wFilenames that end in /
.if \n(82<\n(38 .nr 82 \n(38
.nr 38 \wAll other extensions.
.if \n(82<\n(38 .nr 82 \n(38
.82
.rm 82
.nr 38 1n
.nr 79 0
.nr 40 \n(79+(0*\n(38)
.nr 80 +\n(40
.nr 41 \n(80+(3*\n(38)
.nr 81 +\n(41
.nr 42 \n(81+(3*\n(38)
.nr 82 +\n(42
.nr TW \n(82
.if t .if \n(TW>\n(.li .tm Table at line 164 file http-gw.tbl is too wide - \n(TW units
.fc  
.nr #T 0-1
.nr #a 0-1
.eo
.de T#
.ds #d .d
.if \(ts\n(.z\(ts\(ts .ds #d nl
.mk ##
.nr ## -1v
.ls 1
.ls
..
.ec
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'Description\h'|\n(41u'Gopher type\h'|\n(42u'Extensions
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u' \h'|\n(41u'\h'|\n(42u'
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'GIF Image\h'|\n(41u'g\h'|\n(42u'.gif
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'DOS archives\h'|\n(41u'5\h'|\n(42u'.zip .zoo .arj .arc .lzh
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'DOS binaries\h'|\n(41u'9\h'|\n(42u'.exe .com .dll .lib .sys
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'Misc Images\h'|\n(41u'I\h'|\n(42u'.jpg .jpeg .pict .pct .tiff 
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'\h'|\n(41u'\h'|\n(42u'.tif .pcx
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'Unix binaries\h'|\n(41u'9\h'|\n(42u'.tar .z .gz
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'MAC archives\h'|\n(41u'4\h'|\n(42u'.hqx
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'Misc sounds\h'|\n(41u's\h'|\n(42u'.au .snd .wav 
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'HTML Documents\h'|\n(41u'h\h'|\n(42u'.html .htm 
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'Misc Documents\h'|\n(41u'9\h'|\n(42u'.doc .wri 
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u' \h'|\n(41u'\h'|\n(42u'
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'Directories\h'|\n(41u'1\h'|\n(42u'Filenames that end in /
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u' \h'|\n(41u'\h'|\n(42u'
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'Plain text\h'|\n(41u'0\h'|\n(42u'All other extensions.
.ta \n(80u \n(81u \n(82u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u' \h'|\n(41u'\h'|\n(42u'
.fc
.nr T. 1
.T# 1
.35
.TE
.if \n-(b.=0 .nr c. \n(.c-\n(d.-20
.LP
.ne 10
.SH CONFIGURATION
.LP
.B HTTP-GW
reads its configuration rules and permissions
information from the firewall configuration
table
.B netperm-table,
retrieving all rules specified for "http-gw". 
The "ftp-gw" rules are also retrieved. The "ftp-gw" rules are consulted when
looking for 
.B host
rules once the "http-gw" ones have been searched. 
The following configuration rules are recognized:
.TP 5
.B userid user
specify a numeric user-id or the name of a password file entry.
If this value is specified,
.B HTTP-GW
will set its user-id before providing service. Note that this
option is included mostly for completeness, as
.B HTTP-GW
performs no local operations that are likely to introduce a
security hole.
.TP 5
.B directory pathname
specifies a directory to which
.B HTTP-GW
will chroot(2) prior to providing service.
.TP 5
.B timeout secondsvalue
This value is used as a dead-watch timer when the proxy is
reading data from the net. Defaults to 60 minutes.
.TP 5
.B default-gopher server
define a gopher server to which requests can be handed off.
.TP 5
.B default-httpd server
define an HTTP server to which requests can be handed off if they came
from a WWW client using the HTTP protocol.
.TP 5
.B ftp-proxy server
define an 
.B ftp-gw
that should be used to access 
.B FTP
servers.
.B If not specified, 
.B the proxy will do the FTP 
.B transaction with the FTP server.
Since the ftp-gw rules will be used if there are no relevant HTTP-GW rules 
then this is not a major problem.
.TP 0
.B hosts host-pattern [host-pattern ...] [options]
.B permit-hosts host-pattern [host-pattern ...] [options]
.br
.B deny-hosts host-pattern [host-pattern ...] 
.RS 5
.br
rules specify host and access permissions. Typically, a
hosts rule will be in the form of:
.na
.sp 1
http-gw:	deny-hosts unknown
.br
http-gw:	hosts 192.33.112.* 192.94.214.*
.ad
.sp 1
There may be several host patterns following the "hosts"
keyword, ending with the first optional parameter beginning
with '-'. Optional parameters permit the selective enabling
or disabling of logging information, etc. 
.RS -5
.TP 5
.B permit-hosts options
.LP
permit-hosts rules may take options. Some of the options take parameters.
The functions are defined later (see 
.B gopher functions)
.RS 5
.ne 5
.TP 0
.B -permit function
.br
.B -permit { function [function ...] }
.RS 5
.br
Only the specified functions are permitted. Other functions will be
denyed. If this option is not specified then all functions are initially
permitted.
.RS -5
.ne 5
.TP 0
.B \-deny function
.br
.B \-deny { function [function ...] }
.RS 5
.br
specifies a list of Gopher/HTTP functions to deny. 
.RS -5
.ne 5
.TP 5
.B \-gopher server
Make 
.B server
the default server for this transaction.
.ne 5
.TP 5
.B \-httpd server
Make
.B server
the default HTTP server for this transaction. Will be used if the request came
in via the HTTP protocol.
.TP 0
.B \-filter function
.br
.B \-filter { function [function ...] }
.RS 5
.br
will remove the specified functions when re-writing selectors and URL's. Does
not stop the user from entering selectors that the client will execute locally
but can be used to remove them from retrieved documents.
.LP
.RS -10
The following options are also recognised and processed since they
may be specified on an ftp-gw config line.
.RS 5
.TP 5
.B \-noinput
Disables data read functions.
.TP 5
.B \-nooutput
Disables data write functions.
.TP 0
.B \-log function
.br
.B \-log { function [function ...] }
.RS 5
.br
specifies that a log entry to the system log should be made
whenever the listed functions are performed through the
proxy.
.RS -5
.TP 5
.B \-authall
specifies that all functions require the user to be authenticated.
.TP 0
.B \-auth function
.br
.B \-auth { function [function ...] }
.RS 5
.br
specifies that the functions listed require the user to be authenticated.
.RS -5
.TP 0
.B \-dest pattern
.br
.B \-dest { pattern [pattern ...] }
.RS 5
.br
specifies a list of valid destinations. If no list is specified,
all destinations are considered valid. The -dest list is processed
in order as it appears on the options line. -dest entries preceeded
with a '!' character are treated as negation entries. Therefore the
rule:
.sp
.nf
.na
-dest !*.mit.edu -dest *
.fi
.ad
.sp
will permit hosts that are not in the domain "mit.edu" to be
connected to.
.RS -5
.RE
.LP
.ne 30
.B gopher functions
.LP
The proxy characterizes each transaction as one of a number of functions. For
the 
.B deny
options it is the request that is used. For 
.B filter
options it is the returned selectors that are used.
.LP
.TS
.if \n+(b.=1 .nr d. \n(.c-\n(c.-1
.de 35
.ps \n(.s
.vs \n(.vu
.in \n(.iu
.if \n(.u .fi
.if \n(.j .ad
.if \n(.j=0 .na
..
.nf
.nr #~ 0
.if n .nr #~ 0.6n
.ds #d .d
.if \(ts\n(.z\(ts\(ts .ds #d nl
.fc
.nr 33 \n(.s
.rm 80 81
.nr 80 0
.nr 38 \wFunction
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \w 
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wdir
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \w 
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wread
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \w 
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wwrite
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \w 
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wftp
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \w 
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wplus
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \w 
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wwais
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \w 
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \wexec
.if \n(80<\n(38 .nr 80 \n(38
.nr 38 \w 
.if \n(80<\n(38 .nr 80 \n(38
.80
.rm 80
.nr 81 0
.nr 38 \wDescription
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wFetching Gopher Menus
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wGetting a directory listing via FTP
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wFetching an HTML document (This is being studied)
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wFetching a file of any type. 
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wHTML files are treated as \f3read\f1 even though 
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wthey are also \f3dir\f1
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wPutting a file of any type.
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wNeeds \f3plus\f1 since only available to Gopher+ 
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wand HTTP/1.x
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wAccessing an FTP server
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wGopher+ operations
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wHTTP methods other than GET
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wWAIS index operations
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \wOperations that require a program to be run, 
.if \n(81<\n(38 .nr 81 \n(38
.nr 38 \we.g. telnet. (See \f3SECURITY\f1)
.if \n(81<\n(38 .nr 81 \n(38
.81
.rm 81
.nr 38 1n
.nr 79 0
.nr 40 \n(79+(0*\n(38)
.nr 80 +\n(40
.nr 41 \n(80+(3*\n(38)
.nr 81 +\n(41
.nr TW \n(81
.if t .if \n(TW>\n(.li .tm Table at line 379 file http-gw.tbl is too wide - \n(TW units
.fc  
.nr #T 0-1
.nr #a 0-1
.eo
.de T#
.ds #d .d
.if \(ts\n(.z\(ts\(ts .ds #d nl
.mk ##
.nr ## -1v
.ls 1
.ls
..
.ec
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'Function\h'|\n(41u'Description
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u' \h'|\n(41u'
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'dir\h'|\n(41u'Fetching Gopher Menus
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'\h'|\n(41u'Getting a directory listing via FTP
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'\h'|\n(41u'Fetching an HTML document (This is being studied)
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u' \h'|\n(41u'
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'read\h'|\n(41u'Fetching a file of any type. 
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'\h'|\n(41u'HTML files are treated as \f3read\f1 even though 
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'\h'|\n(41u'they are also \f3dir\f1
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u' \h'|\n(41u'
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'write\h'|\n(41u'Putting a file of any type.
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'\h'|\n(41u'Needs \f3plus\f1 since only available to Gopher+ 
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'\h'|\n(41u'and HTTP/1.x
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u' \h'|\n(41u'
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'ftp\h'|\n(41u'Accessing an FTP server
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u' \h'|\n(41u'
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'plus\h'|\n(41u'Gopher+ operations
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'\h'|\n(41u'HTTP methods other than GET
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u' \h'|\n(41u'
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'wais\h'|\n(41u'WAIS index operations
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u' \h'|\n(41u'
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'exec\h'|\n(41u'Operations that require a program to be run, 
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u'\h'|\n(41u'e.g. telnet. (See \f3SECURITY\f1)
.ta \n(80u \n(81u 
.nr 31 \n(.f
.nr 35 1m
\&\h'|\n(40u' \h'|\n(41u'
.fc
.nr T. 1
.T# 1
.35
.TE
.if \n-(b.=0 .nr c. \n(.c-\n(d.-26
.LP
.SH SECURITY
There are a number of situations that the user needs to know about. The most
important of which is the way that certain functions are handled by the 
.B client, server,
and
.B proxy
programs. When the client wants to perform certain actions such as 
.B telnet
then the client program often runs the telnet command to perform the function.
If the client passes arguments to the program then there is a chance
that rogue commands could be executed as well as the intended one. 
Gopher requests to do FTP operations cause the server to run
the FTP program. Again there is the chance that 
the server could be tricked into
running rogue commands as well as the intended one.

Most client programs only know how to display a small number of data types and
they rely on external 
.B viewers
to handle the other data types. Again, there is a chance that client programs
can be tricked into running rogue commands as well as the intended ones.
' .SH AUTHENTICATION
' .PP
' If the user needs to authenticate to gain access, the proxy will build
' a response that will allow the user to enter a username. Currently this
' is done via a 
' .B wais
' enquiry. After the user has sent of the enquiry, the proxy will generate
' either a password or a challenge request also as a 
' .B wais
' enquiry. If the authorization succeeds, then the user is finally given the
' requested information. An authentication token will be inserted into the
' selectors(URL's) so that subsequent requests are allowed.
' .B The initial release only 
' .B has very simple hooks for this!
.SH INSTALLATION
.LP
To install
.B HTTP-GW
first place the executable in a system area, then modify
.B /etc/inetd.conf.
The TCP service port on which to install the Gopher/HTTP proxy
will depend on local site configuration. You would normally configure the
proxy to be on ports 70 and 80. 70 is the normal Gopher port and 80 is the
normal HTTP port. 
Once 
.B inetd.conf has been modified, 
.B restart or reload
.B inetd.
Verify installation by attempting a connection and
monitoring the system logs.
.LP
Typical configuration of the proxy in a firewall situation
involves rules to block all systems that are not in the
DNS from using the proxy, but to permit all systems on
the internal protected network to use the proxy. I.e.:
.na
.sp 1
http-gw: deny-hosts unknown
.br
http-gw: hosts 192.33.112.* 192.94.214.*
.ad
.sp 1
.SH FILES
.PD 0
.TP 20
.B /etc/inetd.conf
.B /etc/services
.B netperm-table
.SH SEE ALSO
.BR netperm-table (5)
.BR inetd (8)
.BR authd (8)
.BR ftp-gw (8)
.SH BUGS
