.TH XTSERV 6 "Oct 13, 1996"
.SH NAME
xtserv \- server for a synchronous multiplayer tetris
.SH SYNOPSIS
.B xtserv
[ -help ] [ -once ] [ -v ] [ -norestart ] [ -p \fIport\fR ]
.SH OPTIONS
.TP
.BR "-help"
Prints out a summary of the command-line options
.B xtserv
recognizes.
.TP
.BR "-once"
With this option,
.B xtserv
will exit after all clients have disconnected.
.TP
.BR "-v"
Sets verbose mode:
.B xtserv
will print information on clients connecting, disconnecting, starting
games, sending each other lines, losing, etc.
.TP
.BR "-norestart"
With this option,
.B xtserv
will not start a new game when all players but one have lost.  The
players will have to press the 'play' button themselves to start.
.TP
.BR "-p"
Specifies a port for xtserv to use.  The default is 19503.
.SH DESCRIPTION
.B xtserv
is the server for the synchronous multi-user version of Tetris,
.B xtris.

.B xtserv
listens for connections on a TCP port, keeps an internal list of
connected clients, and broadcasts information among clients to
manage starting the game, setting the level and mode, as well as
seeing each other's screens.

.B xtserv
is started automatically by
.B xtris,
with the option '-once', if
.B xtris
does not find an
.B xtserv
running on localhost, and no server host has been specified.

.B xtserv
will automatically restart a game when the one-but-last (or the only)
player has lost, unless started with the option -norestart.

.B xtserv
will also drop all bots when there are only bots left in the game.

The server can handle
clients exiting, being killed or losing the connection even in the
middle of a game.

Killing an
.B xtserv
will cause all connected clients to exit.  

.SH SEE ALSO
.BR xtris (6),
.BR xtbot (6)
.SH BUGS
None known; please report any bugs to the author.
.SH AUTHOR
.B xtserv 
was written by Roger Espel Llima <roger.espel.llima@pobox.com>. 

