#!/bin/sh
#
# this is how I generated the X type list.  This would have to be customized
# for various releases.
#
for file in /usr/X11R6/include/X11/*.h
do
	./typelist < $file
done | sort | uniq > x.types
