#!/bin/sh -
#
# $Id: switch-bsd,v 5.2.2.1 1992/02/09 15:11:45 jsp beta $
#
# Switch things to use BSD build scheme
# Assumes we are running in the top-level directory.
#
trap '' 2
if [ ! -d bsd/amd ]; then
	echo Not in top directory >&2
	exit 1
fi

if [ ! -d mk ]; then
	mkdir mk mk/config mk/amd mk/amq mk/mk-amd-map mk/fsinfo
fi

for i in . amd amq mk-amd-map fsinfo; do
	mv $i/Make* mk/$i/.
done
for i in amd/amd.8 amq/amq.8; do
	mv $i mk/$i
done

cp -rp bsd/* .
rm -f switch-bsd
