.TH WATCHDOG 8 "February 1996"
.UC 4
.SH NAME
watchdog \- a software watchdog daemon
.SH SYNOPSIS
.B watchdog
[
.I -i interval
[
.I -f
] [
.I -n file-name
] [
.I -l max load avg
] [
.I -v
] [
.I -s
] [
.I -b
] [
.I -d device-name
]
.br
.SH DESCRIPTION
Watchdog is a daemon that checks if your system is still working. If
programs in user space are not longer executed it will reboot the system.

The kernel provides /dev/watchdog, which when open must be written
to within a minute or the machine will reboot. Each write delays the reboot
time another minute. In the case of the software watchdog the ability to 
reboot will depend on the state of the machines and interrupts.

Watchdog can be stopped without causing a reboot if the device /dev/watchdog
is closed correctly, unless of course your kernel is compiled with the
CONFIG_WATCHDOG_NOWAYOUT option enabled.

Watchdog itself does several test to check the system:
.TP
Check whether the process table is full.
.TP
Check whether a given file is accessible.
.TP
Check whether the average work load exceeds  a predefined maximal value.

.LP
If any of these checks fail watchdog will cause a shutdown. Should any of
these tests last longer than one minute the machine will be rebooted, too.
.LP
Available command line options are the following:
.TP
-i interval
Set the interval between two writes to the softdog device. The kernel
drivers expects a write command every minute. Otherwise the system will be
rebooted. Default value is 10 seconds. An interval of more than a minute can
only be used with the -f option.
.TP
-l max load avg
Set the maximal allowed load average. Once this load average is reached the
system is rebooted. Default value is 12. Be careful not to this parameter
too low. To set a value less then the predefined minimal value of 2, you
have to use the -f option.

Note that this option sets the maximal 1 minute load average. the five resp.
fifteen minutes average is derived from this as 3/4 resp. 1/2 of it.
.TP
-f
Force the usage of the intervall given with -i or the maximal load average
given with -l.
.TP
-d device-name
Set the softdog devicename. Default is /dev/watchdog.
.TP
-n file-name
Set file name for file mode. Before sleeping <interval> seconds watchdog
tries to stat file <file-name>. An error returned by stat will
.I not 
cause a reboot. For a reboot the stat call has to last at least one
minute. This may happen if <file-name> is located on an NFS mounted
filesystem. If your system relies on an NFS mounted filesystem you might try
this option. However, in such a case the sync option may not work if the NFS
server is not answering.

.I This option is untested!

.TP
-v
Set verbose mode. Only implemented if compiled with SYSLOG feature. This
mode will log each write to the device in LOG_DAEMON with priority LOG_INFO.
This is useful if you want to see exactly when watchdog rebooted the system.
.TP
-s
Try to sync the filesystem every time the process is awake. Be aware that
the system is rebooted if for any reason syncing lasts longer than a minute.
.TP
-b
Soft-boot the system if an error occurs during the main loop, e.g. if the
file given with option -n is not accessible via the stat call.

.LP
.SH BUGS
None known so far.

File mode is not tested. If you have a system that makes a test possible,
please try and tell me, how it worked.

.LP
.SH AUTHORS
The original code is an example written by Alan Cox
<alan@lxorguk.ukuu.org.uk>, the author of the kernel driver. All
additions were written by Michael Meskes <meskes@debian.org>. Johnie Ingram
<johnie@netgod.net> had the idea of testing the load average.
.LP
.SH FILES
.nf
/dev/watchdog  The watchdog device
/var/run/watchdog.pid The PID of the running watchdog
.fi
