  /* these options are for GNU Pascal, included by toplev.c */
  "-fchar-escapes",
  "-fc-numbers",
  "-fshort-circuit",
  "-flazy-io",
  "-fstandard-pascal",
  "-fextended-pascal",
  "-fobject-pascal",
  "-fborland-pascal",
  "-fpascal-sc",
  "-fextended-syntax",
  "-flines",
  "-fdebug-gpi",
  "-fautomake",
  "-famtmpfile",
  "-fnested-comments",
  "-fsetlimit:",
  "-fgpc-main:",
