"vertical { "
"	height close <+inf-inf> "
"	horizontal { "
"		height close <+inf-inf> "
"		message "
"		height close <+inf-inf> "
"	} "
"	height close <+inf-inf> "
"	horizontal { "
"		height close <-inf> "
"		horizontal { "
"			vertical { "
"				0 <+inf> "
"				shellmessage "
"				0 <+inf> "
"			} "
"		} "
"		shellfield <+inf-inf*> "
"		height close <-inf> "
"	} "
"	(height close / 2) <+inf-inf> "
"	horizontal { "
"		height close <-inf> "
"		horizontal { "
"			vertical { "
"				0 <+inf> "
"				filemessage "
"				0 <+inf> "
"			} "
"			width shellmessage - width filemessage "
"		} "
"		filefield <+inf-inf*> "
"		height close <-inf> "
"	} "
"	(height close / 2) <+inf-inf> "
"	horizontal { "
"		height close <+inff-inff> "
"		vertical { "
"			artwin <+inf*> "
"			article <+inf*> "
"			subject <+inf*> "
"			thread <+inf*> "
"			subthread <+inf*> "
"			tagged <+inf*> "
"			0 <+inf> "
"		} "
"		height close <+inff-inff> "
"		vertical { "
"			bogusfrom <+inf*> "
"			bogussubj <+inf*> "
"			header <+inf*> "
"			body <+inf*> "
"			empty <+inf*> "
"			0 <+inf> "
"		} "
"		height close <+inff-inff> "
"	} "
"	height close <+inf> "
"	horizontal { "
"		height close <+inf-inf> "
"		ok "
"		height close <+inf-inf> "
"		choose "
"		height close <+inf-inf> "
"		close "
"		height close <+inf-inf> "
"	} "
"	height close <+inf-inf> "
"} ",
