"horizontal { "
"	2 "
"	vertical { "
"		2 "
"		toplayout <+inf-inf*+inf-inf>"
"		2 "
"		sash1 <+inf-inf*> "
"		2 "
"		message <+inf-inf*> "
"		2 "
"		sash2 <+inf-inf*> "
"		2 "
"		knapplayout <+inf-inf*> "
"		2 "
"		sash3 <+inf-inf*> "
"		textlayout <+inf-inf*+inff-inff> "
"	} "
"	2 "
"} ",
