.\" Process this file with
.\" groff -man -Tascii sgml2html.1
.\"
.TH SGML2HTML 1 "7 Jan 1996"
.SH NAME
sgml2html \- create HTML output from a SGML source file 
.SH SYNOPSIS
.B sgml2html [-L language] [-2] [-fat] [-img] [-l] [-style
.I s
.B ] [-t 
.I n
.B ] 
.IR file [.sgml]
.SH DESCRIPTION
.B sgml2html
converts a SGML source file to HTML output, using the
.BR sgmls (1)
parser, the
.BR sgmlsasp (1)
translator, and the
.BR html2html (1)
fixer. Output will appear in the top level file
.I file.html
and 
.I file-n.html
for each section, where 
.I file
is the name of the SGML source file and 
.I n
is the section name.
.SH OPTIONS
.IP "-L language"
Chooses alternate text to use for the hypertext links. "language" is a
file in $LINUXDOCLIB/rep/html in the format:
  PrevPage:    newvalue
  NextPage:    newvalue
  TOC:         newvalue

The default is "Previous", "Next", and "Table of Contents".
.IP -2
Splits files both at n. sections and n.m. subsections
.IP -fat
Uses DOS FAT .htm extensions instead of .html
.IP -img
Uses graphical buttons for previous and next links
.IP -l
Allows use of latin1 (ISO-8859-1) characters in the SGML source file,
default ASCII only
.IP "-style s"
Uses the mapping file $LINUXDOCLIB/lib/rep/html/<s>mapping
in addition to the default mapping file, for customizations
.IP "-t n"
Sets tabstops each <n> columns, default 8
.IP file
The SGML source file, named either 
.I file
or 
.I file.sgml
.SH FILES
Many files in $LINUXDOCLIB are used. 
.SH ENVIRONMENT
.IP LINUXDOCBIN
location of other executables that 
.B sgml2html
needs
.IP LINUXDOCLIB
location of library files that 
.B sgml2html
needs
.IP "Both variables are hardcoded into the script at install time."
.SH BUGS
None known.
.SH AUTHOR
Greg Hankins <greg.hankins@cc.gatech.edu>
.SH "SEE ALSO"
.BR sgml2info (1),
.BR sgml2latex (1), 
.BR sgml2lyx (1), 
.BR sgml2rtf (1), 
.BR sgml2txt (1),
.BR sgmlcheck (1).
