#!/bin/sh
#
# Script to format all manual pages in one or more directories into the
# dwww cache (/var/spool/dwww).
#
# Usage: $0 directory ...
# Example: $0 /usr/man/man1 /usr/local/man3
# Exampel: $0 `manpath -q | tr : ' '`
#
# Lars Wirzenius
# "@(#)dwww:$Id: dwww-format-man,v 1.1.1.1 1996/12/12 06:41:08 jim Exp $"
#

PATH="$PATH:/usr/sbin"

for i in "$@"
do
	find "$i" -type f |
	while read f
	do
		dwww-convert man "$f" > /dev/null
	done
done
