.TH DWWW-FORMAT-MAN 8
.SH NAME
dwww\-format\-man \- batch format manual pages for dwww
.SH SYNOPSIS
dwww-format-man
.IR directory ...
.SH DESCRIPTION
.B dwww-format-man
looks for manual pages in the directories named on the command line.
It formats each manual page, and puts the formatted version into the
dwww document cache.
System administrator's can run
.B dwww-format-man
if they want to make it faster to retrieve manual pages via dwww.
If
.B dwww-format-man
is not run, dwww will automatically manual pages not in its cache.
Long pages take a few moments to format,
but rarely so slow that it is worth running
.BR dwww-format-man .
.SH "SEE ALSO"
.B dwww(1) 
.SH AUTHOR
Lars Wirzenius (http://www.iki.fi/liw/mail-to-lasu.html).
