.TH REALPATH 1
.SH NAME
realpath \- return the canonicalized absolute pathname
.SH SYNOPSIS
.BI realpath " pathname " ...
.SH "DESCRIPTION"
.B realpath
converts each
.I pathname
argument to an absolute pathname, which has no
components that are symbolic links or the special
.B .
or
.B ..
directory entries.
(See
.BR realpath (2)
for more information.)
Each converted pathname is output to the standard output,
on its own line.
.SH "SEE ALSO"
.BR realpath (3)
.SH AUTHOR
Lars Wirzenius (liw@iki.fi), as part of the dwww package.
