.TH CDDA2WAV 1
.SH NAME
cdda2wav \- a sampling utility that dumps CD audio data into wav sound
files
.SH SYNOPSIS
.B cdda2wav
.RB [ -c
.IR chans ]
.RB [ -s ]
.RB [ -m ]
.RB [ -b
.IR bits ]
.RB [ -r
.IR rate ]
.RB [ -a
.IR divider ]
.RB [ -t
.IR track ]
.RB [ -i
.IR index ]
.RB [ -o
.IR offset ]
.RB [ -d
.IR duration ]
.RB [ -x ]
.RB [ -q ]
.RB [ -w ]
.RB [ -v ]
.RB [ -R ]
.RB [ -P ]
.RB [ -e ]
.RB [ -n
.IR sectors ]
.RB [ -N ]
.RB [ -B ]
.RB [ -D
.IR device ]
.RB [ -A
.IR auxdevice ]
.RB [ -I
.IR interface ]
.RB [ -O
.IR audiotype ]
.RB [ -M
.IR count ]
.RI [ audio.wav ]
.SH DESCRIPTION
.B cdda2wav
works with CDROM drives (see README for a list of drives) that are
capable of reading audio data digitally to the host
.RB ( CDDA ).
Other drives may have been added as well when you read this.
.SH OPTIONS
.TP
.BI \-D " device"
use
.B device
as CDROM drive.
.TP
.BI \-I " interface"
specify the interface for CDROM access:
.B generic_scsi
or
.BR cooked_ioctl .
.TP
.BI \-c " channels"
set
.B 1
for mono, or
.B 2
for stereo recording.
.TP
.B \-s
set to stereo recording.
.TP
.B \-m
set to mono recording.
.TP
.B \-x
set maximum (CD) quality.
.TP
.BI \-b " bits"
set bits per sample per channel:
.BR 8 ,
.B 12
or
.BR 16 .
.TP
.BI \-r " rate"
set rate in samples per second.  Possible values are listed with the
.BR -R
option.
.TP
.BI \-a " divider"
set rate to 44100Hz / divider.  Possible values are listed with the
.BR -R
option.
.TP
.B \-R
show a list of all sample rates and their dividers.
.TP
.B \-P
switch off overlap sampling.
.TP
.BI \-n " sectors"
read 
.I sectors
per request.
.TP
.BI \-t " track"
select start track.
.TP
.BI \-i " index"
select start index.
.TP
.BI \-o " offset"
start
.I offset
sectors behind start track (one sector equivalents 1/75 seconds).
.TP
.B \-O " audiotype"
can be 
.I wav
(for wav files) or
.I sun
(for sun PCM files) or
.I raw
(for headerless files).
.TP
.BI \-d " duration"
set recording time in seconds or
.B 0
for whole track.
.TP
.B \-B
copy each track into a seperate file.
.TP
.B \-w
wait for signal, then start recording.
.TP
.B \-e
copy audio data to sound device e.g.
.BR /dev/dsp .
.TP
.B \-v " level"
print verbose information about the CD.
.TP
.B \-N
don't write to file, just read (for debugging).
.TP
.B \-M " count"
enables calculation of MD-5 checksum for 'count' bytes from a beginning of a
track.
.TP
.B \-q
quiet operation, no screen output.
.TP
Defaults depend on the
.I Makefile
settings.
.SH "DISCUSSION"
.B cdda2wav
is able to read parts of an
.B audio
CD or
.B multimedia
CDROM (containing audio parts) directly digitally. These parts can be
written to a file, or to a sound device.
.PP
.B cdda2wav
stands for
.B CDDA
to
(where
.B CDDA
stands for compact disc digital audio and
.B WAV
is another sound sample format introduced by MSDOS Windows 3.1).  It
allows copying
.B CDDA
audio data from the CDROM drive into a file on your ram-, hard-, floppy-
or whatever-disk in the very common
.B WAV
format (notice that sampling has not to be done in realtime here, data
is read on request).
.PP
If your CDROM (not yet for SCSI drives) is on device
.B /dev/cdrom
and it is loaded with an audio CD, you may simply invoke
.B cdda2wav
and it will create the sound file
.B audio.wav
recording 16 seconds beginning with track 1 in stereo at 16 bit at 44100
Hz sample rate, if your file system has enough space free.  Otherwise
recording time will be limited. SCSI drives have to use different devices
(see file
.B README
for details).
.SH "HINTS ON OPTIONS"
.IP "Options"
Most of the options are used to control the format of the WAV file. In
the following text all of them are described.
.IP "Select Device"
.BI \-D " device"
select the CDROM drive device to be used.
It should correspond to the selected interface (see below).
.IP "Select Auxiliary device"
.BI \-A " auxdevice"
is necessary for SCSI drives only. It is the CDROM drive (SCSI) device (i.e.
.B /dev/sr0
) corresponding to the generic SCSI device (i.e.
.B /dev/sgd
). It has to match.
.IP "Select Interface"
.BI \-I " interface"
selects the CDROM drive interface. For SCSI drives use generic_scsi
(cooked_ioctl is not yet available in the kernel):
.B generic_scsi
and
.BR cooked_ioctl .
The first uses the generic SCSI interface, the latter uses the ioctl of
the CDROM driver. The latter variant works only when the kernel driver supports
.B CDDA
reading. This has to match the selected CDROM device (see above).
.IP "Enable echo to soundcard"
.B \-e
copies audio data to the sound card while recording, so you hear it nearly
simultanously. The soundcard gets the same data that is recorded. This
is time critical, so it works best with the
.B \-q
option.  To use
.B cdda2wav
as a pseudo CD player without recording in a file you could use
.B "cdda2wav \-q \-e \-t2 \-d0 \-n"
to play the whole second track.
.IP "Select mono or stereo recording"
.B \-m
or
.B "\-c 1"
selects mono recording (both stereo channels are mixed)
.B \-s
or
.B "\-c 2"
selects stereo recording (doubles file size)
.IP "Select maximum quality"
.B \-x
will set stereo, 16 bits per sample at 44.1 KHz (full CD quality).  Note
that other format options given later do change this setting.
.IP "Select sample quality"
.B "\-b 8"
specifies 8 bit (1 Byte) for each sample in each channel;
.B "\-b 12"
specifies 12 bit (2 Byte) for each sample in each channel;
.B "\-b 16"
specifies 16 bit (2 Byte) for each sample in each channel (Ensure that
your sample player or sound card is capable of playing 12-bit or 16-bit
samples). Selecting 12 or 16 bits doubles file size.  12-bit samples are
aligned to 16-bit samples, so they waste some disk space.
.IP "Select sample rate"
.BI \-r " samplerate"
selects a sample rate.
.I samplerate
can be in a range between 44100 and 900. Option
.B \-R
lists all available rates.
.IP "Select sample rate divider"
.BI \-a " divider"
selects a sample rate divider.
.I divider
can be minimally 1 and maximally 50.5 and everything between in steps of 0.5.
Option
.B \-R
lists all available rates.
.IP
To make the sound smoother at lower sampling rates,
.B cdda2wav
sums over
.I n
samples (where
.I n
is the specific dividend). So for 22050 Hertz output we have to sum over
2 samples, for 900 Hertz we have to sum over 49 samples.  This cancels
higher frequencies. Standard sector size of an audio CD (ignoring
additional information) is 2352 Bytes. In order to finish summing
for an output sample at sector boundaries the rates above have to be
choosen.  Arbitrary sampling rates in high quality would require some
interpolation scheme, which needs much more sophisticated programming.
.IP "List a table of all sampling rates"
.BI \-R
shows a list of all sample rates and their dividers. Dividers can range
from 1 to 50.5 in steps of 0.5.
.IP "Select start track"
.BI \-t " n"
select one of the tracks displayed in the table of contents.  This sets
the track where recording begins, but recording can advance through the
following tracks as well (depending on recording time).
.IP "Select start index"
.BI \-i " n"
select the index to start recording with.  Indices other than 1 will
invoke the index scanner, which will take some time to find the correct
start position. An offset may be given additionally (see below)..
.IP "Set recording time"
.B \-d " n"
set recording time to
.I n
seconds or set recording time for whole track if
.I n
is zero.
.IP
Recording time is defined as the time the generated sample will play (at
the defined sample rate). Since it's related to the amount of generated
samples, it's not the time of the sampling process itself (which can be
less or more).  It's neither strictly coupled with the time information on
the audio CD (shown by your hifi CD player).
Differences can occur by the usage of the
.B \-o
option (see below). Notice that recording time will be shortened, unless
enough disk space exists. Recording can be aborted at anytime by
pressing the break character (signal QUIT).
.IP "Record a complete audio CD in one go in different files"
.B \-B
copies each track into a seperate file. A base name can be given. File names
have an appended track number and an extension corresponding to the audio
format. To record all audio tracks of a CD, use a sufficient high duration
(i.e. -d99999).
.IP "Set start sector offset"
.BI \-o " sectors"
increments start sector of the track by
.IR sectors .
By this option you are able to skip a certain amount at the beginning of
a track so you can pick exactly the part you want. Each sector runs for 1/75
seconds, so you have very fine control. If your offset is so high that
it would not fit into the current track, a warning message is issued
and the offset is ignored.  Recording time is not reduced.  (To skip
introductory quiet passages automagically, use the
.B \-w
option see below.)
.IP "Wait for signal option"
.B \-w
Turning on this option will suppress all silent output at startup,
reducing possibly file size.
.B cdda2wav
will watch for any signal in the output signal and switches on writing
to file.
.IP "Set audio format"
.B \-O " audiotype"
can be 
.I wav
(for wav files) or
.I sun
(for sun PCM files) or
.I raw
(for headerless files).
.IP "Enable MD5 checksums"
.B \-M " count"
enables calculation of MD-5 checksum for 'count' bytes from the beginning of a
track. This was introduced for quick comparisons of tracks.
.IP "Do linear reading of sectors"
.B \-P
switches off overlap sampling, which would read certain sectors twice.
This option is nice on fast hardware or errorfree (perfect) cdrom drives.
.IP "Set the transfer size"
.B \-n " sectors"
will set the transfer size to the specified sectors per request.
.IP "Verbose option"
.B \-v " level"
prints more information. A binary mask allows selection of different
information.
.sp
.B "0"
keep quiet
.sp
.B "1"
display the table of contents
.sp
.B "2"
display a summary
.sp
.B "4"
invoke the index scanner and display start positions of indices
.sp
.B "8"
retrieve and display a media catalog number
.sp
.B "16"
retrieve and display international standard recording codes
.sp
.B "32"
display track start positions in absolute sector notation
.sp
To combine several requests just add the numbers and enter the sum as argument.
.IP "The table of contents"
The display will show the table of contents with number of tracks and
total time (displayed in
.IR mm : ss . hh
format,
.IR mm =minutes,
.IR ss =seconds,
.IR hh "=rounded 1/100 seconds)."
The following list displays track number and track time for each entry.
The summary gives a line per track describing the type of the track.
.sp
.ce 1
.B "track preemphasis copypermitted tracktype chans subQchan"
.sp
The
.B track
column holds the track number.
.B preemphasis
shows if that track has been given a non linear frequency response.
.B "copy-permitted"
indicates if this track is free of copyrights.
.B "tracktype"
can be data or audio. On multimedia CDs both of them should be
present.
.B "channels"
is defined for audio tracks only. There can be two or four channels.
.B "sub-Q-channel"
indicates the type of additional information present in the
sub-Q-channel.  This can be a position, a media catalog number or an
international standard recording code.
.IP "No file output"
.B \-N
this debugging option switches off writing to a file.
.IP "Quiet option"
.B \-q
suppress all screen output except error messages. Further it avoids
any sub q channel requests for position reports in the recording
display. That reduces cpu time resources and allows feeding a soundcard
with audio data on the fly.
.SH "HINTS ON USAGE"
Don't create samples you cannot read. First check your sample player
software and sound card hardware. I experienced problems with very low
sample rates (stereo <= 1575 Hz, mono <= 3675 Hz) when trying to play
them with standard WAV players for sound blaster (may be they are not
legal in
.B WAV
format). Certain CD-Writers insist on audio samples in a swapped,
bigendian format. Sox can be used to do swapping with the '-x' option.
.PP
Cdda2wav uses overlap sampling on default. This reduces jitter errors
that occur on interruptions. It slows down performance, too. If your
hardware is fast enough to run cdda2wav uninterrupted, you will gain
speed when switching overlap sampling off with the
.B \-P
option. Further fine tuning can be done with the
.B \-n " sectors"
option. You can specify how much sectors should be requested in one go.
.PP
Cdda2wav supports
.B pipes
now. Use a filename of
.B \-
to let cdda2wav output its samples to standard output.
.PP
Conversion to other sound formats can be done using the
.B sox
program package.
.PP
If you really want to sample more than one track in one go, this is
currently possible with the
.B \-B
option. When recording time exceeds the track limit a new file will
be opened for the next track.
.SH WARNING
.B IMPORTANT:
it is prohibited to sell copies of copyrighted material by noncopyright
holders. This program may not be used to circumvent copyrights.
.SH BUGS
A kernel bug (version < 1.1.20) prevented successful operation of mode
select commands.
.sp
Performance may not be optimal on slower systems.
.sp
The index scanner may give timeouts.
.sp
This man page is outdated.
.SH ACKNOWLEDGEMENTS
Thanks goto Project MODE (http://www.mode.net/) and Fraunhofer Institut für
integrierte Schaltungen (FhG-IIS) (http://www.iis.fhg.de/) for financial
support.
Rammi has helped a lot with the debugging and showed a lot of stamina when
hearing 100 times the first 16 seconds of the first track of the Krupps CD.
.SH AUTHOR
Heiko Eissfeldt heiko@colossus.escape.de
.SH DATE
2 June 1996
