# LaTeX2HTML 96.1-h (September 30, 1996)
# Associate images original text with physical files.

$key = q/{displaymath}xymatrixAar[r]^far[dr]_f;g;SPMamp;Bar[d]^gar[dr]^g;h;SPMamp;Car[r]_h;SPMamp;D{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=233 HEIGHT=108 ALIGN=BOTTOM ALT="displaymath176" SRC="img9.gif">|; 
$key = q/{}smiley{}/;
$cached_env_img{$key} = q|<IMG WIDTH=18 HEIGHT=20 ALIGN=BOTTOM ALT="tex2html_wrap2796" SRC="img74.gif">|; 
$key = q/{}IMG_inline$xymatrix@1Aar[r]|f;SPMamp;B$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=16 ALIGN=BOTTOM ALT="tex2html_wrap2500" SRC="img10.gif">|; 
$key = q/{displaymath}IMGDEFcorner#1POS;SPMquot;box;SPMquot;+0;;SPMquot;box;SPMquot;+#1**@-?;SPMgt;*@;SPMgt;+1pc*hboxtt#1xy0.(-11,-6).(11,6)!C=;SPMquot;box;SPMquot;*frm.,;SPMquot;box;SPMquot;;;SPMquot;box;SPMquot;+L**@.,;SPMquot;box;SPMquot;+R**@.,;SPMquot;box;SPMquot;+D**@.,;SPMquot;box;SPMquot;+U**@.cornerLcornerRcornerDcornerUcornerDLcornerDRcornerULcornerURxy{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=244 HEIGHT=128 ALIGN=BOTTOM ALT="displaymath740" SRC="img50.gif">|; 
$key = q/{}IMG_inline$xymatrix@1Xar[r]^a_b;SPMamp;Y;SPMamp;Zar[l]^A_B$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=152 HEIGHT=32 ALIGN=BOTTOM ALT="tex2html_wrap2488" SRC="img6.gif">|; 
$key = q/{_inline}$t_2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=15 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline2540" SRC="img26.gif">|; 
$key = q/{_inline}$t_1${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=15 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline2538" SRC="img25.gif">|; 
$key = q/{displaymath}xymatrix@dr@C=1pcaar[r]ar@-;SPMgt;;SPMgt;[d];SPMamp;a'ar@.;SPMgt;;SPMgt;[d]bar@.;SPMgt;;SPMgt;[r];SPMamp;b'{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=206 HEIGHT=116 ALIGN=BOTTOM ALT="displaymath2752" SRC="img65.gif">|; 
$key = q/{_inline}$t_1<verb_mark>326<verb_mark>t_2<verb_mark>327<verb_mark>x<verb_mark>328<verb_mark>y<verb_mark>329<verb_mark>${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=103 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2798" SRC="img75.gif">|; 
$key = q/{displaymath}IMGSelectTipscmobjectmargin=1ptxygraph!0;(.77,-.77):0!~:@-|@;SPMgt;w(:[r(.6)]x_1,:[d]z:[r]y:[u(.6)]x_2:@_;SPMquot;x_1;SPMquot;(:@_;SPMquot;x_2;SPMquot;):;SPMquot;z;SPMquot;:@(;SPMquot;w;SPMquot;;;SPMquot;z;SPMquot;,;SPMquot;y;SPMquot;;;SPMquot;z;SPMquot;);SPMquot;z;SPMquot;:;SPMquot;x_2;SPMquot;){displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=224 HEIGHT=122 ALIGN=BOTTOM ALT="displaymath1246" SRC="img77.gif">|; 
$key = q/{displaymath}xymatrixA;SPMamp;*+[F]sum_i=n^mi^2;SPMamp;bullet;SPMamp;Dar[ul]{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=259 HEIGHT=103 ALIGN=BOTTOM ALT="displaymath73" SRC="img2.gif">|; 
$key = q/{}IMGSelectTipscmxygraph!0;r1.5pc:0[u]!vloop;SPMlt;(-.005)kholevcrossnegvunder-[]!ar@-@'p-(1,0)@++(-1,1)[ul]!vcap[3];SPMgt;khole[rrr]!ar@-@'p-(0,1)@+-(1,1){}/;
$cached_env_img{$key} = q|<IMG WIDTH=108 HEIGHT=116 ALIGN=BOTTOM ALT="tex2html_wrap2808" SRC="img79.gif">|; 
$key = q/{_inline}$<verb_mark>64<verb_mark>d_1<verb_mark>65<verb_mark>d_2<verb_mark>66<verb_mark>${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=76 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2512" SRC="img16.gif">|; 
$key = q/{}IMGxy*[F-,]hboxstrut~shaded~xy{}/;
$cached_env_img{$key} = q|<IMG WIDTH=76 HEIGHT=27 ALIGN=BOTTOM ALT="tex2html_wrap2566" SRC="img32.gif">|; 
$key = q/{}IMGxy*[F-]hboxstrut~frame~xy{}/;
$cached_env_img{$key} = q|<IMG WIDTH=63 HEIGHT=25 ALIGN=BOTTOM ALT="tex2html_wrap2558" SRC="img28.gif">|; 
$key = q/{}IMG_inline$SelectTipscmxymatrix@1Aar@-;SPMgt;;SPMgt;|[r];SPMamp;B$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap2726" SRC="img59.gif">|; 
$key = q/{_inline}$t'<verb_mark>204<verb_mark>t${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=31 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline2638" SRC="img46.gif">|; 
$key = q/{_inline}$xymatrix@1Aar[r]|-SelectTipscmobject@;SPMgt;;SPMgt;|;SPMgt;SelectTipseuobject@;SPMgt;;SPMamp;B${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline2728" SRC="img60.gif">|; 
$key = q/{}IMGxy*[F-:;SPMlt;3pt;SPMgt;]hboxstrut~rounded~xy{}/;
$cached_env_img{$key} = q|<IMG WIDTH=85 HEIGHT=25 ALIGN=BOTTOM ALT="tex2html_wrap2568" SRC="img33.gif">|; 
$key = q/{}IMG_inline$xymatrix@1Aar@;SPMlt;-2pt;SPMgt;`d[r]`[r][r]ar@;SPMlt;+2pt;SPMgt;`d[r]`[r][r];SPMamp;B$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=50 ALIGN=BOTTOM ALT="tex2html_wrap2716" SRC="img56.gif">|; 
$key = q/{_inline}$<verb_mark>211<verb_mark>D_x<verb_mark>212<verb_mark>D_y<verb_mark>213<verb_mark>${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2648" SRC="img48.gif">|; 
$key = q/{displaymath}newdir;SPMgt;*!-5pt@;SPMgt;xymatrixAar@;SPMgt;-;SPMgt;@;SPMlt;2pt;SPMgt;[r]ar@;SPMgt;-;SPMgt;@;SPMlt;-2pt;SPMgt;[r];SPMamp;B{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=195 HEIGHT=15 ALIGN=BOTTOM ALT="displaymath920" SRC="img58.gif">|; 
$key = q/{_inline}$xymatrix@1Aar@^[r]ar@^@;SPMlt;-1ex;SPMgt;[r];SPMamp;B${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2618" SRC="img43.gif">|; 
$key = q/{}IMGDEFDT#1#DTx#1DEFDTx#1#2Dx#1#2;SPMamp;xy-(4,0)*;(4,2)*+**?;SPMgt;*@#1#2**@#1.xyDEFDx#1#2hboxDEF1#2enspacettcodeof1indexcode#2DEFDarray#1let=crtabskip=2emplus1filminus.8emhaligntohsize;SPMamp;hfil_inline$##$_inlinetabskip=1em;SPMamp;_inline$##$_inlinehfiltabskip=2emplus1filcr#1crcrDarrayDT;SPMlt;;SPMamp;DT;SPMgt;;SPMamp;DTxDT;SPMlt;;SPMlt;;SPMamp;DT;SPMgt;;SPMgt;;SPMamp;DT+DT|;SPMlt;;SPMamp;DT;SPMgt;|;SPMamp;DT|DT|;SPMlt;;SPMlt;;SPMamp;DT;SPMgt;;SPMgt;|;SPMamp;DT||DT(;SPMamp;DT);SPMamp;DToDT;SPMamp;DT{}/;
$cached_env_img{$key} = q|<IMG WIDTH=386 HEIGHT=137 ALIGN=BOTTOM ALT="tex2html_wrap2594" SRC="img36.gif">|; 
$key = q/{displaymath}IMGxymatrix@!0;SPMamp;lambdaomegaar@-[rr]ar@-'[d][dd]save[].[dd].[ddrr].[rr]*[F.]frm=;SPMquot;back;SPMquot;restore;SPMamp;;SPMamp;lambdaCar@-[dd]lambda2ar@-[ur]ar@-[rr]ar@-[dd]save[].[ddrr]*[F.]frmar@.+UL;;SPMquot;back;SPMquot;+ULar@.+UR;;SPMquot;back;SPMquot;+URar@.+DL;;SPMquot;back;SPMquot;+DLar@.+DR;;SPMquot;back;SPMquot;+DRrestore;SPMamp;;SPMamp;lambdaP2ar@-[ur]ar@-[dd];SPMamp;lambdaunderlineomegaar@-'[r][rr];SPMamp;;SPMamp;lambdaPunderlineomegalambdatoar@-[rr]ar@-[ur];SPMamp;;SPMamp;lambdaPar@-[ur]{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=244 HEIGHT=171 ALIGN=BOTTOM ALT="displaymath2792" SRC="img73.gif">|; 
$key = q/{_inline}$bullet${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=8 HEIGHT=8 ALIGN=BOTTOM ALT="tex2html_wrap_inline2476" SRC="img5.gif">|; 
$key = q/{displaymath}xymatrix1ar[rr]^-1000000xar[dr]_(.2)2000x|![d];[rr]hole;SPMamp;;SPMamp;10000001000ar[r]_2xar[urr]_;SPMgt;;SPMgt;;SPMgt;;SPMgt;x^2;SPMamp;2000{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=284 HEIGHT=103 ALIGN=BOTTOM ALT="displaymath372" SRC="img27.gif">|; 
$key = q/{displaymath}xymatrixAar@-[dr];SPMamp;save[]+;SPMlt;3cm,0cm;SPMgt;*txt;SPMlt;8pc;SPMgt;Thisisaverybigcommentarybutitdoesnototherwiseaffectthediagram.ar[l]ar[d]restore;SPMamp;Bar@-[r];SPMamp;Car@-[r];SPMamp;D{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=334 HEIGHT=123 ALIGN=BOTTOM ALT="displaymath1007" SRC="img63.gif">|; 
$key = q/{}IMGxy*[F.]hboxstrut~dotted~xy{}/;
$cached_env_img{$key} = q|<IMG WIDTH=71 HEIGHT=26 ALIGN=BOTTOM ALT="tex2html_wrap2562" SRC="img30.gif">|; 
$key = q/{displaymath}xymatrixcircar`r[d]^a`[rr]^b`4pt[rr]^c`[rrr]^d`_dl[drrr]^e[drrr]^f;SPMamp;circ;SPMamp;circ;SPMamp;circcirc;SPMamp;circ;SPMamp;circ;SPMamp;circ{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=285 HEIGHT=84 ALIGN=BOTTOM ALT="displaymath857" SRC="img55.gif">|; 
$key = q/{}IMGDEFDT#1#DTx#1DEFDTx#1#2Dx#1#2;SPMamp;xy-(4,0)*;(4,2)*+**?;SPMgt;*@#1#2**@#1.xyDEFDx#1#2hboxDEF1#1#2enspacettcodeof1indexcode#1#2DEFDarray#1let=crtabskip=0ptplus1filhaligntohsize;SPMamp;hfil_inline$##$_inlinetabskip=1em;SPMamp;_inline$##$_inlinehfiltabskip=1emplus1filcr#1crcrbigskipDarrayDT|-;SPMamp;DT^|-;SPMamp;DT_|-;SPMamp;;SPMamp;DT|=;SPMamp;DT3|-DT*;SPMamp;DT^`;SPMamp;DT_`;SPMamp;;SPMamp;DT^';SPMamp;DT_'{}/;
$cached_env_img{$key} = q|<IMG WIDTH=428 HEIGHT=94 ALIGN=BOTTOM ALT="tex2html_wrap2602" SRC="img40.gif">|; 
$key = q/{displaymath}xymatrixbulletar@--[d]ar@=[dr]ar@-[r];SPMamp;bulletar@.[d]bullet;SPMamp;bulletar[l]{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=189 HEIGHT=76 ALIGN=BOTTOM ALT="displaymath138" SRC="img4.gif">|; 
$key = q/{}IMGSelectTipscmxygraph!0;r1.5pc:0!vover[u]!hcap[-2];SPMlt;;SPMlt;[d]!vover-[ruu]!hcap[2];SPMgt;;SPMlt;{}/;
$cached_env_img{$key} = q|<IMG WIDTH=112 HEIGHT=73 ALIGN=BOTTOM ALT="tex2html_wrap2806" SRC="img78.gif">|; 
$key = q/{}IMGxy*[F=]hboxstrut~double~xy{}/;
$cached_env_img{$key} = q|<IMG WIDTH=72 HEIGHT=25 ALIGN=BOTTOM ALT="tex2html_wrap2560" SRC="img29.gif">|; 
$key = q/{displaymath}xy*=;SPMlt;2pc;SPMgt;[o][F]=;SPMquot;c;SPMquot;,;SPMquot;c;SPMquot;;(-1,-1)**,p+3pc*+|dl|**@-?;SPMgt;*@;SPMgt;,;SPMquot;c;SPMquot;;(0,-1)**,p+3pc*+|d|**@-?;SPMgt;*@;SPMgt;,;SPMquot;c;SPMquot;;(1,-1)**,p+3pc*+|dr|**@-?;SPMgt;*@;SPMgt;,;SPMquot;c;SPMquot;;(1,0)**,p+3pc*+|r|**@-?;SPMgt;*@;SPMgt;,;SPMquot;c;SPMquot;;(1,1)**,p+3pc*+|ur|**@-?;SPMgt;*@;SPMgt;,;SPMquot;c;SPMquot;;(0,1)**,p+3pc*+|u|**@-?;SPMgt;*@;SPMgt;,;SPMquot;c;SPMquot;;(-1,1)**,p+3pc*+|ul|**@-?;SPMgt;*@;SPMgt;,;SPMquot;c;SPMquot;;(-1,0)**,p+3pc*+|l|**@-?;SPMgt;*@;SPMgt;xy{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=226 HEIGHT=155 ALIGN=BOTTOM ALT="displaymath241" SRC="img15.gif">|; 
$key = q/{displaymath}IMGxy*+A=;SPMquot;A;SPMquot;,+;SPMlt;1cm,1.5cm;SPMgt;*+B=;SPMquot;B;SPMquot;,+;SPMlt;2cm,0pt;SPMgt;*+C=;SPMquot;C;SPMquot;,+;SPMlt;1cm,-1.5cm;SPMgt;*+D=;SPMquot;D;SPMquot;,;SPMquot;A;SPMquot;;;SPMquot;B;SPMquot;,uppertwocell^alpha,;SPMquot;B;SPMquot;;;SPMquot;C;SPMquot;,twocell^zeta_xigamma,;SPMquot;C;SPMquot;;afterPOSdropcompositemap;SPMquot;D;SPMquot;POS;SPMquot;A;SPMquot;;afterPOSdroplowertwocell;SPMquot;D;SPMquot;xy{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=274 HEIGHT=154 ALIGN=BOTTOM ALT="displaymath1334" SRC="img81.gif">|; 
$key = q/{_inline}$d,t${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=21 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2688" SRC="img54.gif">|; 
$key = q/{}IMG_inline$xymatrix@1AtimesBtimesCtimesDar[r]^+;SPMamp;B$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=204 HEIGHT=22 ALIGN=BOTTOM ALT="tex2html_wrap2492" SRC="img8.gif">|; 
$key = q/{_inline}$<verb_mark>97<verb_mark>a<verb_mark>98<verb_mark>${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=25 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2530" SRC="img22.gif">|; 
$key = q/{_inline}$<verb_mark>67<verb_mark>d_2<verb_mark>68<verb_mark>d_1<verb_mark>69<verb_mark>${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=76 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline2514" SRC="img17.gif">|; 
$key = q/{_inline}$lambda2${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=20 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2790" SRC="img72.gif">|; 
$key = q/{_inline}$xymatrixAar@^@^;SPMlt;-_;SPMgt;[r]ar@_@*x*[r];SPMamp;B${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=90 HEIGHT=40 ALIGN=MIDDLE ALT="tex2html_wrap_inline2604" SRC="img41.gif">|; 
$key = q/{_inline}$<verb_mark>190<verb_mark>r<verb_mark>191<verb_mark>c<verb_mark>192<verb_mark>${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=42 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2622" SRC="img44.gif">|; 
$key = q/{displaymath}xymatrixAar[d]_far[r]^f;SPMamp;Bar[dl]|i_Bar[d]^gBar[r]_g;SPMamp;C{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=202 HEIGHT=107 ALIGN=BOTTOM ALT="displaymath208" SRC="img13.gif">|; 
$key = q/{}IMGSelectTipscmxygraph!0;r1.25pc:0!P5;SPMquot;a;SPMquot;~;SPMgt;!P10;SPMquot;b;SPMquot;~:(1.7487,0):~;SPMgt;!P20;SPMquot;c;SPMquot;~=-9~:(2.2,0):~;SPMgt;!xunderv~;SPMquot;b3;SPMquot;;SPMquot;b2;SPMquot;;SPMquot;a2;SPMquot;;SPMquot;a1;SPMquot;!xunderv~;SPMquot;b5;SPMquot;;SPMquot;b4;SPMquot;;SPMquot;a3;SPMquot;;SPMquot;a2;SPMquot;!xunderv~;SPMquot;b7;SPMquot;;SPMquot;b6;SPMquot;;SPMquot;a4;SPMquot;;SPMquot;a3;SPMquot;!xunderv~;SPMquot;b9;SPMquot;;SPMquot;b8;SPMquot;;SPMquot;a5;SPMquot;;SPMquot;a4;SPMquot;!xunderv~;SPMquot;b1;SPMquot;;SPMquot;b10;SPMquot;;SPMquot;a1;SPMquot;;SPMquot;a5;SPMquot;!vloop~;SPMquot;c3;SPMquot;;SPMquot;c2;SPMquot;;SPMquot;b2;SPMquot;;SPMquot;b1;SPMquot;;SPMlt;;SPMlt;!vloop~;SPMquot;c7;SPMquot;;SPMquot;c6;SPMquot;;SPMquot;b4;SPMquot;;SPMquot;b3;SPMquot;;SPMlt;;SPMlt;!vloop~;SPMquot;c11;SPMquot;;SPMquot;c10;SPMquot;;SPMquot;b6;SPMquot;;SPMquot;b5;SPMquot;;SPMlt;;SPMlt;!vloop~;SPMquot;c15;SPMquot;;SPMquot;c14;SPMquot;;SPMquot;b8;SPMquot;;SPMquot;b7;SPMquot;;SPMlt;;SPMlt;!vloop~;SPMquot;c19;SPMquot;;SPMquot;c18;SPMquot;;SPMquot;b10;SPMquot;;SPMquot;b9;SPMquot;;SPMlt;;SPMlt;{}/;
$cached_env_img{$key} = q|<IMG WIDTH=131 HEIGHT=128 ALIGN=BOTTOM ALT="tex2html_wrap2810" SRC="img80.gif">|; 
$key = q/{}IMG_inline$xymatrix@1Aar[r]^(.3)+;SPMamp;B$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=21 ALIGN=BOTTOM ALT="tex2html_wrap2552" SRC="img23.gif">|; 
$key = q/{displaymath}IMGDEFa#1*hboxDEFnext#1ttcodeofnext;SPMamp;Aar#1[rr];SPMamp;;SPMamp;Bxymatrix@R-1.8pc@C-1pca@;SPMlt;-;SPMgt;a@^;SPMlt;-;SPMgt;a@_;SPMlt;-;SPMgt;a@2;SPMlt;-;SPMgt;a@3;SPMlt;-;SPMgt;{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=252 HEIGHT=137 ALIGN=BOTTOM ALT="displaymath579" SRC="img38.gif">|; 
$key = q/{displaymath}xymatrixcircar@|--;SPMgt;'[dr]^a'[rr]+D*bullet^b[drrr]^c;SPMamp;circ;SPMamp;circ;SPMamp;circcirc;SPMamp;circ;SPMamp;circ;SPMamp;circ{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=258 HEIGHT=76 ALIGN=BOTTOM ALT="displaymath794" SRC="img52.gif">|; 
$key = q/{displaymath}IMGDEFa#1*hboxDEFnext#1ttcodeofnext;SPMamp;Aar#1[r];SPMamp;Bxymatrix@R-1.8pca@^(-;SPMgt;a@|-_;SPMgt;{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=268 HEIGHT=48 ALIGN=BOTTOM ALT="displaymath607" SRC="img39.gif">|; 
$key = q/{displaymath}xymatrix@R=1pc1,1;SPMamp;1,2;SPMamp;1,3;SPMamp;1,4;SPMamp;1,52,1;SPMamp;2,2;SPMamp;2,3;SPMamp;2,4;SPMamp;2,5save;SPMquot;1,2;SPMquot;.;SPMquot;2,4;SPMquot;*[F.]frmar;SPMquot;1,1;SPMquot;ar;SPMquot;2,1;SPMquot;ar;SPMquot;1,5;SPMquot;ar;SPMquot;2,5;SPMquot;restore{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=381 HEIGHT=83 ALIGN=BOTTOM ALT="displaymath1118" SRC="img69.gif">|; 
$key = q/{_inline}$D_x,D_y${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=60 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2650" SRC="img49.gif">|; 
$key = q/{}IMG_inline$xymatrix@1Aar[r]^;SPMlt;+;SPMamp;B$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=21 ALIGN=BOTTOM ALT="tex2html_wrap2546" SRC="img19.gif">|; 
$key = q/{_inline}$xymatrix@1Aar@*composite+*times[rr]^*+txtHighlabel;SPMamp;;SPMamp;B${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=134 HEIGHT=94 ALIGN=MIDDLE ALT="tex2html_wrap_inline2574" SRC="img35.gif">|; 
$key = q/{displaymath}xymatrixAB;SPMamp;Car@;SPMlt;1ex;SPMgt;[ul]ar@;SPMlt;1ex;SPMgt;[ul];[]{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=195 HEIGHT=89 ALIGN=BOTTOM ALT="displaymath707" SRC="img47.gif">|; 
$key = q/{displaymath}IMGxyr2pc:=;SPMquot;A;SPMquot;,+(.2,1.5)=;SPMquot;B;SPMquot;,;SPMquot;A;SPMquot;,xypolygon6~:(1,-.1):(0,.33)::~;SPMlt;;SPMgt;;;SPMquot;B;SPMquot;**@-xyqquadxyr2pc:xypolygon4;SPMquot;A;SPMquot;~:(0,.7)::,+(.7,1.1),xypolygon4;SPMquot;B;SPMquot;~:(.8,0):(0,.75)::,;SPMquot;A1;SPMquot;;;SPMquot;B1;SPMquot;**@.,;SPMquot;A2;SPMquot;;;SPMquot;B2;SPMquot;**@.,;SPMquot;A3;SPMquot;;;SPMquot;B3;SPMquot;**@.,;SPMquot;A4;SPMquot;;;SPMquot;B4;SPMquot;**@.xyqquadxyr2pc:xypolygon3;SPMquot;A;SPMquot;~:(0,.7)::,+(.7,1.1),xypolygon3;SPMquot;B;SPMquot;~:(-.85,0):(-.15,.8)::,;SPMquot;A1;SPMquot;PATH~=**@.';SPMquot;B2;SPMquot;';SPMquot;A3;SPMquot;';SPMquot;B1;SPMquot;';SPMquot;A2;SPMquot;';SPMquot;B3;SPMquot;';SPMquot;A1;SPMquot;xy{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=377 HEIGHT=98 ALIGN=BOTTOM ALT="displaymath1350" SRC="img82.gif">|; 
$key = q/{}IMG_inline$left(DEFobjectstylescriptstyleDEFlabelstylescriptstylevcenterxymatrix@-1.2pc@urAar[r]^a;SPMamp;Bar[d]^bA'ar[u]^a';SPMamp;B'ar[l]^b'right)$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=124 HEIGHT=95 ALIGN=BOTTOM ALT="tex2html_wrap2758" SRC="img66.gif">|; 
$key = q/{_inline}$xymatrixAar[r]^a=;SPMquot;a;SPMquot;;SPMamp;Bar[r]^b=;SPMquot;b;SPMquot;;SPMamp;Car@^;SPMquot;a;SPMquot;;;SPMquot;b;SPMquot;${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=166 HEIGHT=48 ALIGN=MIDDLE ALT="tex2html_wrap_inline2764" SRC="img68.gif">|; 
$key = q/{}IMGxy*[F--]hboxstrut~dashed~xy{}/;
$cached_env_img{$key} = q|<IMG WIDTH=74 HEIGHT=26 ALIGN=BOTTOM ALT="tex2html_wrap2564" SRC="img31.gif">|; 
$key = q/{displaymath}xymatrix*=0bulletar@^[dr]!U|1ar@^[drr]!U|2ar@^[drrr]!U|3;SPMamp;*+[F]txtx;SPMamp;*+[F]txtxx;SPMamp;*+[F]txtxxx{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=260 HEIGHT=117 ALIGN=BOTTOM ALT="displaymath986" SRC="img62.gif">|; 
$key = q/{displaymath}xymatrixg1Aar[r];SPMamp;Bar[d];SPMamp;g2A'ar[r];SPMamp;B'ar[d]Car[u];SPMamp;Dar[l];SPMamp;C'ar[u];SPMamp;D'ar[l]ar@.;SPMgt;;SPMquot;g1;SPMquot;;;SPMquot;1,4;SPMquot;ar@--;SPMgt;;SPMquot;2,1;SPMquot;;;SPMquot;g2;SPMquot;{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=284 HEIGHT=103 ALIGN=BOTTOM ALT="displaymath1127" SRC="img70.gif">|; 
$key = q/{_inline}$newdir|;SPMgt;!4.5pt@|*:(1,-.2)@^;SPMgt;*:(1,+.2)@_;SPMgt;xymatrixAar@=|;SPMgt;[r];SPMamp;B${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=90 HEIGHT=21 ALIGN=MIDDLE ALT="tex2html_wrap_inline2718" SRC="img57.gif">|; 
$key = q/{_inline}$smashxymatrix@1Aar[r]^*+[o][F-]x;SPMamp;B${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=32 ALIGN=BOTTOM ALT="tex2html_wrap_inline2570" SRC="img34.gif">|; 
$key = q/{}IMG_inline$xymatrix@1Aar[r]^;SPMgt;;SPMgt;+;SPMamp;B$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=21 ALIGN=BOTTOM ALT="tex2html_wrap2550" SRC="img21.gif">|; 
$key = q/{displaymath}IMGDEFst#1hboxlower1exrlapkern1pcxy*+r2ptar@#1,;SPMlt;1pc,-1.8pc;SPMgt;*xy|@#1|st=;SPMgt;quadst.;SPMgt;quadst:;SPMgt;quadst~;SPMgt;quadst--;SPMgt;quadst-quadst{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=462 HEIGHT=66 ALIGN=BOTTOM ALT="displaymath121" SRC="img3.gif">|; 
$key = q/{}IMG_inline$xymatrix@1Aar[r]^;SPMlt;(0)+;SPMamp;B$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=21 ALIGN=BOTTOM ALT="tex2html_wrap2554" SRC="img24.gif">|; 
$key = q/{displaymath}xymatrix*txtAverylongandstupidprogramar[rr]^-txtweirdarrow;SPMamp;;SPMamp;*txt;SPMlt;2pc;SPMgt;Com-pli-catedCode{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=356 HEIGHT=82 ALIGN=BOTTOM ALT="displaymath977" SRC="img61.gif">|; 
$key = q/{displaymath}IMGxy*xybox0;;SPMlt;1.5pc,1.28mm;SPMgt;:;SPMlt;.41pc,1.12pc;SPMgt;::,0,croplattice-35-55-1.34.5-3.44.4=;SPMquot;L;SPMquot;,;SPMquot;L;SPMquot;+Lar;SPMquot;L;SPMquot;+!R*+!Lsigma^(1),;SPMquot;L;SPMquot;+Dar;SPMquot;L;SPMquot;+!U*+!Dsigma^(2)xy{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=273 HEIGHT=234 ALIGN=BOTTOM ALT="displaymath1368" SRC="img83.gif">|; 
$key = q/{_inline}$lambdaomega${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=23 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2788" SRC="img71.gif">|; 
$key = q/{displaymath}xymatrixAar@;SPMlt;1ex;SPMgt;[dr]^a_.;SPMamp;Bar@;SPMlt;1ex;SPMgt;[ul]^bar@;SPMlt;1ex;SPMgt;[r]^c;SPMamp;Car@;SPMlt;1ex;SPMgt;[l]^d_.{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=233 HEIGHT=107 ALIGN=BOTTOM ALT="displaymath662" SRC="img42.gif">|; 
$key = q/{displaymath}xymatrixar@[dr]|=Aar[d]ar[r];SPMamp;Bar[d]Bar[r];SPMamp;C{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=195 HEIGHT=89 ALIGN=BOTTOM ALT="displaymath199" SRC="img12.gif">|; 
$key = q/{displaymath}xymatrixxar@(ul,dl)[]|idar@^[rr]|f;SPMamp;;SPMamp;f(x)ar@^[ll]|f^-1{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=253 HEIGHT=38 ALIGN=BOTTOM ALT="displaymath289" SRC="img18.gif">|; 
$key = q/{displaymath}xymatrixUar@_[ddr]_yar@^[drr]^xar@.;SPMgt;[dr]|-(x,y);SPMamp;Xtimes_ZYar[d]^qar[r]_p;SPMamp;Xar[d]_f;SPMamp;Yar[r]^g;SPMamp;Z{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=261 HEIGHT=164 ALIGN=BOTTOM ALT="displaymath20" SRC="img1.gif">|; 
$key = q/{_inline}$<verb_mark>200<verb_mark>r<verb_mark>201<verb_mark>c<verb_mark>202<verb_mark>${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=45 HEIGHT=27 ALIGN=MIDDLE ALT="tex2html_wrap_inline2630" SRC="img45.gif">|; 
$key = q/{displaymath}entrymodifiers=++[o][F-]SelectTipscmxymatrix@-1pc*txtstartar[r];SPMamp;0ar@(r,u)[]^bar[r]_a;SPMamp;1ar[r]^bar@(r,d)[]_a;SPMamp;2ar[r]^bar`dr_l[l]`_ur[l]_a[l];SPMamp;*++[o][F=]3ar`ur^l[lll]`^dr[lll]^b[lll]ar`dr_l[ll]`_ur[ll][ll]{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=287 HEIGHT=94 ALIGN=BOTTOM ALT="displaymath1080" SRC="img67.gif">|; 
$key = q/{}IMGDEFDC#1#DCx#1DEFDCx#1#2Dx#1#2;SPMamp;xy*+;(12,4)*+**@#1#2xyDEFDx#1#2hboxDEF1#2enspacettcodeof1indexcode#2DEFDarray#1let=crtabskip=2emplus1filhaligntohsize;SPMamp;hfil_inline$##$_inlinetabskip=1em;SPMamp;_inline$##$_inlinehfiltabskip=2emplus1fil#1crcrDarrayDC-;SPMamp;DC--DC~;SPMamp;DC~~DC.{}/;
$cached_env_img{$key} = q|<IMG WIDTH=302 HEIGHT=95 ALIGN=BOTTOM ALT="tex2html_wrap2596" SRC="img37.gif">|; 
$key = q/{displaymath}IMGDEFa#1*hboxDEF1#1enspacettcodeof1;SPMamp;Aar#1[r];SPMamp;Bxymatrix@R-1.4pca@^a@_a@_1pc{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=258 HEIGHT=118 ALIGN=BOTTOM ALT="displaymath223" SRC="img14.gif">|; 
$key = q/{displaymath}IMGxy0;r5pc:*@*=;SPMquot;p;SPMquot;,*+!DRp;p+(.5,-.5)*@*=;SPMquot;c;SPMquot;,*+!ULc**@-,;SPMquot;c;SPMquot;,ellipse;SPMlt;15pt;SPMgt;_,=:a(45)=,ellipse;SPMlt;;SPMgt;__,=:a(30)-,ellipse(1,.4).,ellipse(1,.4)_,=:a(120)--,ellipse(,.75).,ellipse(,.75)_,^,^-xy{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=270 HEIGHT=160 ALIGN=BOTTOM ALT="displaymath1386" SRC="img84.gif">|; 
$key = q/{displaymath}xymatrix@!0;SPMamp;lambdaomegaar@-[rr]ar@-'[d][dd];SPMamp;;SPMamp;lambdaCar@-[dd]lambda2ar@-[ur]ar@-[rr]ar@-[dd];SPMamp;;SPMamp;lambdaP2ar@-[ur]ar@-[dd];SPMamp;lambdaunderlineomegaar@-'[r][rr];SPMamp;;SPMamp;lambdaPunderlineomegalambdatoar@-[rr]ar@-[ur];SPMamp;;SPMamp;lambdaPar@-[ur]{displaymath}/;
$cached_env_img{$key} = q|<IMG WIDTH=239 HEIGHT=159 ALIGN=BOTTOM ALT="displaymath812" SRC="img53.gif">|; 
$key = q/{}IMG_inline$xymatrix@1AtimesBtimesCtimesDar[r]^-+;SPMamp;B$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=204 HEIGHT=22 ALIGN=BOTTOM ALT="tex2html_wrap2490" SRC="img7.gif">|; 
$key = q/{}IMG_inline$xymatrix@1@=0pt@M=0ptA;SPMamp;BC;SPMamp;D$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=31 HEIGHT=36 ALIGN=BOTTOM ALT="tex2html_wrap2750" SRC="img64.gif">|; 
$key = q/{_inline}$<verb_mark>330<verb_mark>t_1<verb_mark>331<verb_mark>t_2<verb_mark>332<verb_mark>x<verb_mark>333<verb_mark>y<verb_mark>334<verb_mark>${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=125 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline2800" SRC="img76.gif">|; 
$key = q/{_inline}$alpha${_inline}/;
$cached_env_img{$key} = q|<IMG WIDTH=12 HEIGHT=10 ALIGN=BOTTOM ALT="tex2html_wrap_inline2656" SRC="img51.gif">|; 
$key = q/{}IMG_inline$xymatrix@1Aar[r]^;SPMgt;+;SPMamp;B$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=21 ALIGN=BOTTOM ALT="tex2html_wrap2548" SRC="img20.gif">|; 
$key = q/{}IMG_inline$xymatrix@1Aar[r]|hole;SPMamp;B$_inline{}/;
$cached_env_img{$key} = q|<IMG WIDTH=82 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap2502" SRC="img11.gif">|; 

1;

