/* THIS FILE IS AUTOMATICALLY GENERATED */
char *BuildSystem= "Linux valour 1.3.77 #1 Sun Mar 24 13:14:02 GMT 1996 i486";
char *BuildDate= "Tue Apr 16 15:40:52 BST 1996";
char *BuildUser= "uid=1000(and1000) gid=1000(and1000) groups=1000(and1000),25(floppy),40(src),101(tcpdump),102(console),103(modula3),104(archim),105(armgnu),106(java),107(ftpadmin),108(rfc)";
