'\" t
.\" Copyright 1993-1995 Daniel Quinlan (quinlan@yggdrasil.com)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\"
.\" Slightly rearranged, aeb, 950713
.\"
.\" Traduction 20/10/1996 par Christophe Blaess (ccb@club-internet.fr)
.\"
.TH ISO_8859_1 7 "20 Octobre 1996" Linux "Manuel de l'administrateur Linux"
.nh
.SH NOM
iso_8859_1 \- Le jeu de caracteres ISO 8859-1 en octal, decimal et hexadecimal.
.SH DESCRIPTION
Le standard ISO 8859 inclut plusieures extensions au jeu de caracteres ASCII
(ISO 646-IRV).  Le jeu le plus important est ISO 8859-1, l'alphabet
Latin numero 1, largement implemente, et qui est devenu un standard
de-facto remplacant le standard ASCII.
.P
Le standard ISO 8859-1 supporte les langages suivants : Afrikaans, Allemand,
Anglais, Basque, Catalan, Danois,  Ecossais, Espagnol, Faeroese, Finois, 
Francais, Gaelique, Hollandais, Islandais, Irlandais, Italien, Norvegien, 
Portugais, et Suedois.
.P
Notez que le jeu de caracteres ISO 8859-1 correspond aux 256 premiers
caracteres du standard ISO 10646 (Unicode).
.SS "Alaphabet ISO 8859"
l'ensemble complet d'alphabets 8859 inclut :
.P
.TS
l l.
ISO 8859-1	Langues ouest-europeennes (Latin-1)
ISO 8859-2	Langues est-europeennes   (Latin-2)
ISO 8859-3	Sud-Est europeens et diverses langues (Latin-3)
ISO 8859-4	Scandinavie/Baltique (Latin-4)
ISO 8859-5	Latin/Cyrillique
ISO 8859-6	Latin/Arabe
ISO 8859-7	Latin/Grec
ISO 8859-8	Latin/Hebreu
ISO 8859-9	Latin-1 modifie pour le Turque  (Latin-5)
ISO 8859-10	Langages Lappon/Nordique/Eskimo (Latin-6)
.TE
.SS "Caracteres ISO 8859-1"
La table suivante presente les caracteres du jeu ISO 8859 Latin-1, imprimables
et non listes dans la page de manuel
.BR ascii (7).

.TS
l l l c lp-1.
Oct	Dec	Hex	Car	Description
_
240	160	A0	 	ESPACE INSECABLE
241	161	A1	¡	POINT D'EXCLAMATION INVERSE
242	162	A2	¢	SYMBOLE CENT
243	163	A3	£	SYMBOLE LIVRE
244	164	A4	¤	SYMBOLE MONETAIRE
245	165	A5	¥	SYMBOLE YEN
246	166	A6	¦	BARRE INTERROMPUE
247	167	A7	§	PARAGRAPHE
250	168	A8	¨	TREMA
251	169	A9	©	SYMBOLE COPYRIGHT
252	170	AA	ª	FEMININE ORDINAL INDICATOR
253	171	AB	«	GUILLEMET GAUCHE
254	172	AC	¬	SYMBOLE NEGATION
255	173	AD	­	TIRET
256	174	AE	®	SYMBOLE REGISTERED
257	175	AF	¯	MACRON
260	176	B0	°	DEGRE
261	177	B1	±	SYMBOLE PLUS OU MOINS
262	178	B2	²	PUISSANCE DEUX
263	179	B3	³	PUISSANCE TROIS
264	180	B4	´	ACCENT AIGU
265	181	B5	µ	SYMBOLE MICRON
266	182	B6	¶	PILCROW SIGN
267	183	B7	·	POINT CENTRAL
270	184	B8	¸	CEDILLE
271	185	B9	¹	PUISSANCE UN
272	186	BA	º	MASCULINE ORDINAL INDICATOR
273	187	BB	»	GUILLEMET DROIT
274	188	BC	¼	UN QUART
275	189	BD	½	UN DEMI
276	190	BE	¾	TROIS QUARTS
277	191	BF	¿	POINT D'INTERROGATION INVERSE
300	192	C0	À	A MAJUSCULE ACCENT GRAVE
301	193	C1	Á	A MAJUSCULE ACCENT AIGU
302	194	C2	Â	A MAJUSCULE ACCENT CIRCONFLEXE
303	195	C3	Ã	A MAJUSCULE TILDE
304	196	C4	Ä	A MAJUSCULE TREMA
305	197	C5	Å	A MAJUSCULE AVEC CERCLE
306	198	C6	Æ	LIAISON A\-E MAJUSCULES
307	199	C7	Ç	C CEDILLE MAJUSCULE
310	200	C8	È	E MAJUSCULE ACCENT GRAVE
311	201	C9	É	E MAJUSCULE ACCENT AIGU
312	202	CA	Ê	E MAJUSCULE ACCENT CIRCONFLEXE
313	203	CB	Ë	E MAJUSCULE TREMA
314	204	CC	Ì	I MAJUSCULE ACCENT GRAVE
315	205	CD	Í	I MAJUSCULE ACCENT AIGU
316	206	CE	Î	I MAJUSCULE CIRCONFLEXE
317	207	CF	Ï	I MAJUSCULE TREMA
320	208	D0	Ð	LATIN CAPITAL LETTER ETH
321	209	D1	Ñ	N MAJUSCULE TILDE
322	210	D2	Ò	O MAJUSCULE ACCENT GRAVE
323	211	D3	Ó	O MAJUSCULE ACCENT AIGU
324	212	D4	Ô	O MAJUSCULE ACCENT CIRCONFLEXE
325	213	D5	Õ	O MAJUSCULE TILDE
326	214	D6	Ö	O MAJUSCULE TREMA
327	215	D7	×	SYMBOLE MULTIPLICATION
330	216	D8	Ø	O MAJUSCULE BARRE
331	217	D9	Ù	U MAJUSCULE ACCENT GRAVE
332	218	DA	Ú	U MAJUSCULE ACCENT AIGU
333	219	DB	Û	U MAJUSCULE ACCENT CIRCONFLEXE
334	220	DC	Ü	U MAJUSCULE TREMA
335	221	DD	Ý	Y MAJUSCULE ACCENT AIGU
336	222	DE	Þ	LATIN CAPITAL LETTER THORN
337	223	DF	ß	SYMBOLE DOUBLE S
340	224	E0	à	A MINUSCULE ACCENT GRAVE
341	225	E1	á	A MINUSCULE ACCENT AIGU
342	226	E2	â	A MINUSCULE ACCENT CIRCONFLEXE
343	227	E3	ã	A MINUSCULE TILDE
344	228	E4	ä	A MINUSCULE TREMA
345	229	E5	å	A MINUSCULE AVEC CERCLE
346	230	E6	æ	LIAISON A\-E MINUSCULES
347	231	E7	ç	C CEDILLE MINUSCULE
350	232	E8	è	E MINUSCULE ACCENT GRAVE
351	233	E9	é	E MINUSCULE ACCENT AIGU
352	234	EA	ê	E MINUSCULE ACCENT CIRCONFLEXE
353	235	EB	ë	E MINUSCULE TREMA
354	236	EC	ì	I MINUSCULE ACCENT GRAVE
355	237	ED	í	I MINUSCULE ACCENT AIGU
356	238	EE	î	I MINUSCULE ACCENT CIRCONFLEXE
357	239	EF	ï	I MINUSCULE TREMA
360	240	F0	ð	LATIN SMALL LETTER ETH
361	241	F1	ñ	N MINUSCULE TILDE
362	242	F2	ò	O MINUSCULE ACCENT GRAVE
363	243	F3	ó	O MINUSCULE ACCENT AIGU
364	244	F4	ô	O MINUSCULE ACCENT CIRCONFLEXE
365	245	F5	õ	O MINUSCULE TILDE
366	246	F6	ö	O MINUSCULE TREMA
367	247	F7	÷	SYMBOLE DIVISION
370	248	F8	ø	O MINUSCULE BARRE
371	249	F9	ù	U MINUSCULE ACCENT GRAVE
372	250	FA	ú	U MINUSCULE ACCENT AIGU
373	251	FB	û	U MINUSCULE ACCENT CIRCONFLEXE
374	252	FC	ü	U MINUSCULE TREMA
375	253	FD	ý	Y MINUSCULE ACCENT GRAVE
376	254	FE	þ	LATIN SMALL LETTER THORN
377	255	FF	ÿ	Y MINUSCULE TREMA
.TE

[NDT] Je ne connais pas le nom des symboles 170, 186, 208, 222, 240 et 254.

.SH "VOIR AUSSI"
.BR ascii (7)
