.\" $Id: rlprrc.5,v 1.3 1996/11/17 08:34:05 meem Exp $
.TH rlprrc 5 "1996/10/11" "special files" "UNIX Reference Manual"
.SH NAME
rlprrc \- remote printing resource file
.SH DESCRIPTION
The \fBrlprrc\fP configuration file is consulted by \fBrlpr\fP(1) to
resolve a printqueue or a hostname. It can be used to either lookup a
printqueue (printer) for a given host, or a host for a given
printqueue.
.PP
Initially, \fBrlpr\fP(1) looks for the file \fI.rlprrc\fP in the
user's home directory.  If that is not found, the system-wide
\fI/etc/rlprrc\fP is consulted.  If neither are found, \fBrlpr\fP
fails.
.PP
There is one entry per line \- each line has the format:
.PP
\fBhostname: printer1 printer2 ... printerN\fP
.PP
which indicates that host \fBhostname\fP has printers \fBprinter1
printer2 ... printerN\fP available.  In the case where \fBrlpr\fP(1)
knows the host to print to but does not know which printer to use on
that host, the first one (\fBprinter1\fP here) will be used.
.PP
In the case where \fBrlpr\fP(1) knows the printqueue (printer) to
print to but does not know what host has that queue, the last host
which has the specified printqueue is used.  If this behavior is not
acceptable, you can force a certain host to always be used for a
certain printqueue by putting a \fB!\fP after the prinqueue name.
.PP
for example, an \fB.rlprrc\fP file containing:
.ta \w'1234567'u
.nf

	foo.baz.org: litho laserjet4! 
	foo.bar.org: laserjet4 lineprinter

.fi
.PP
will always resolve the printqueue \fBlaserjet4\fP to
\fBfoo.baz.org\fP no matter what other hosts have a printqueue named
\fBlaserjet4\fP.
.PP
The \fBrlprrc\fP file is only consulted in situations where a
printqueue or hostname needs to be resolved.  \fBIt is provided only for
convenience and is not required.\fP
.SH SEE ALSO
\fBrlpr\fP(1), \fBrlprd\fP(8)
.SH AUTHOR
meem <meem@gnu.ai.mit.edu>
