.\" $Id: rlpr.1,v 1.10 1996/11/17 08:10:55 meem Exp $
.TH rlpr 1 "1996/11/17" "printing tools -- rlpr 1.40" "UNIX Reference Manual"
.SH NAME
rlpr \- remote off line print
.SH SYNOPSIS
\fBrlpr\fP [\fB-H\fPprinthost] [\fB-P\fPprinter] [\fB-X\fPproxyhost]
[\fB-#\fPcopies] [\fB-C\fPclass] [\fB-J\fPjob] [\fB-T\fPtitle] [\fB-U\fPuser]
[\fB-i\fP[indent]] [\fB-w\fPwidth] [\fB-1234cdfghlmnopqrstvWV\fP]
[\fB--tmpdir\fP=dir]
[\fB--port\fP=port]
[\fB--verbose\fP]
[\fB--debug\fP]
[file ...]
.SH DESCRIPTION
\fBrlpr\fP uses tcp/ip to send print jobs to lpd servers anywhere on
a network.  Unlike lpr, it does not require that the remote printers
be explicitly known to the local system (traditionally through
\fI/etc/printcap\fP), and thus is considerably more flexible and
requires less administration.
.PP
\fBrlpr\fP can be used anywhere a traditional \fBlpr\fP might be used,
and is backwards compatible with traditional BSD \fBlpr\fP.
.PP
\fBrlpr\fP can be installed and used in two different ways:
.PP
1. Ideally, if the \fBrlpr\fP client can be installed setuid root,
then \fBrlpr\fP can interact directly with other \fBlpd\fP's on the
network.  See \fBexamples\fP below.
.PP
2. If \fBrlpr\fP cannot be installed setuid root (in cases where one
is not the administrator on the machine one needs to print from) then
\fBrlpr\fP can be used in conjunction with an \fBrlprd\fP proxy
agent. See the \fPconfiguring a proxy\fP and \fB examples\fP sections below
for details.
.SH MOTIVATION
Traditional Berkeley \fBlpr\fP has one major drawback: the mortal user
cannot \fBlpr\fP to a printer which is not listed explicitly in the
\fI/etc/printcap\fP file.
.PP		
This is especially annoying in scenarios where there is a central UNIX
server which many users (using their own desktop computers) connect to
in order to do their daily work; If those users wish to print files
from the central server to their personal machines (assuming they had
a local \fBlpd\fP), they \fIcannot do this\fP without the central
server's \fI/etc/printcap\fP being edited to contain the host and
printer of each user on the network \- this scales horribly.
.SH OPTIONS
.PP
.SS Environment/Setup
.TP
.I      \-\-debug
print gobs of debugging information
.TP
.I \-H, \-\-printhost=host
select the host to print to (used with \fI-P\fP).
.TP
.I \-P, \-\-printer=printername, \-\-queue=printername
select the printer to print to (used with \fI-H\fP).
.TP
.I      \-\-port=number
select an alternate port (instead of 7290) to connect to, if using
rlprd.  usually not needed.
.TP
.I \-X, \-\-proxy=proxyhost, \-\-proxyhost=proxyhost
select the proxy host to use.
.TP
.I \-\-tmpdir=tmpdir
use tmpdir for temporary files (by default, \fB/tmp\fP is used)
.TP
.I \-V, \-\-version
print version and exit.
.PP
.fi
\fBNOTE:\fP instead of constantly specifying these parameters,
one can set up defaults through either environment variables 
or \fBrlprrc\fP configuration files.  For information on personal
or system-wide \fBrlprrc\fP files, see \fBrlprrc\fP(5).
.SS Behavior
.TP
.I \-#, \-\-copies=copies
print \fIcopies\fP copies of each document \- use sparingly,
\fBprinters aren't copiers\fP.
.TP
.I \-m, \-\-mail
send mail upon completion.
.TP
.I \-r, \-\-remove
remove file after printing.
.TP
.I \-s
.br
ignored (provided for compatibility).
.TP
.I \-q, \-\-quiet, \-\-silent
quiet mode \- stay quiet (except for fatal errors).
.TP
.I \-\-verbose
verbose mode \- on by default unless \fBrlpr\fP is invoked as \fBlpr\fP.
.TP
.I \-W, \-\-windows
"Windows" mode \- for printing multiple files to a
windows-based \fBlpd\fP.
.fi
.SS Document Content
.ta \w'1234'u
.nf
\fI\-1\fP	print data using \fBtroff\fP(1) R (times roman) font.
\fI\-2\fP	print data using \fBtroff\fP(1) I (times italic) font.
\fI\-3\fP	print data using \fBtroff\fP(1) B (times bold) font.
\fI\-4\fP	print data using \fBtroff\fP(1) S (special) font.
\fI\-c\fP	assume data has been produced by \fBcifplot\fP(1).
\fI\-d\fP	assume data has been produced by \fBtex\fP(1).
\fI\-f\fP	filter data assuming the start of each line has
	a \fIfortran\fP carriage control character.
\fI\-g\fP	assume data has been produced by the BSD standard
	plot library.
\fI\-l\fP	treat control characters as regular characters.
\fI\-n\fP	assume data has been produced by \fBditroff\fP.
\fI\-o\fP	assume data is \fIpostscript\fP.
\fI\-p\fP	print data using \fBpr\fP(1).
\fI\-t\fP	assume data has been produced by \fBtroff\fP(1).
\fI\-v\fP	assume the data contains a raster image.
.fi
.SS Document Format
.TP
.I \-i, \-\-indent=[cols]
indent output by \fIcols\fP columns (8 by default).
.TP
.I \-h, \-\-no-burst
do not print burst (banner) page.
.TP
.I \-w, \-\-width=width
use \fIwidth\fP for page width when using \fBpr\fP(1).
.TP
.I \-C, \-\-class=class
use \fIclass\fP for the class name on burst page instead of
the local system name.
.TP
.I \-J,  \-\-job=jobname
use \fIjobname\fP for the job name on burst page instead of
the first filename in the job.
.TP
.I \-T, \-\-title=title
use \fItitle\fP for the title when using \fBpr\fP(1)
instead of the current filename.
.TP
.I \-U, \-\-user=username
use \fIusername\fP for the user name on burst page instead
of the actual username.
.fi
.br
.SH "CONFIGURING A PROXY"
In situations where the \fBrlpr\fP client cannot be installed setuid
root, \fBrlpr\fP cannot directly talk to an \fBlpd\fP because
\fBlpd\fP requires that print requests come from privileged
ports. Unfortunately, \fBrlpr\fP cannot "come from a privileged port"
without having superuser status.
.br
\fBThe privileged port requirement is part of RFC 1179.\fP
.PP
If you or someone you know has root access to a machine on the
network, you can use a \fBproxy\fP, known as \fBrlprd\fP to get around
this architectural wart.
.PP
\fBrlprd\fP works by taking \fBlpd\fP requests on a non-privileged port,
mapping them to a privileged port, and sending them out to the real
\fBlpd\fP. The proxy and the lpd \fBneed not be on the same
machine\fP. 
.PP
In the scenario provided in the motivation, if each user had root
access on his own machine, it would be optimal for the user to start
\fBrlprd\fP up on his own machine, in which case the proxy and the
printhost are the same machine.  The user would additionally have to
make sure his own machine was listed in his local
\fI/etc/hosts.lpd\fP so that his \fBlpd\fP would accept connections
from his \fBrlprd\fP.
.PP
However, if the machine the user wants to print to is not running
unix (but is running an \fBlpd\fP) (i.e. Windows, WinNT, etc) -- Then
that user can configure his \fBlpd\fP to accept connections from
an \fBrlprd\fP running somewhere on the network, and use that
\fBrlprd\fP as a proxy for \fBrlpr\fP.
.PP
For more on this mess, see \fBrlprd\fP(8).
.SH EXAMPLES
.TP
WITHOUT A PROXY  (rlpr is setuid root)
.PP
sun% \fBrlpr --printhost=foo.bar.org --printer=hp4l foo.c\fP
.PP
prints \fBfoo.c\fP to the printer \fBhp4l\fP on the host
\fBfoo.bar.org\fP (assuming foo.bar.org has been
configured to accept print requests from host \fBsun\fP in its
\fI/etc/hosts.lpd\fP).
.PP
sun% \fBwho | rlpr --printhost=foo.bar.org --printer=hp4l\fP
.PP
prints the output of \fBwho\fP(1) to the printer \fBhp4l\fP on the
host \fBfoo.bar.org\fP.
.TP
WITH A PROXY  (rlpr is a normal program)
.PP
sun% \fBrlpr -Xfoo.bar.org -Hfoo.bar.org -Php4l foo.c\fP
.PP
prints \fBfoo.c\fP to the printer \fBhp4l\fP on the host
\fBfoo.bar.org\fP using \fBfoo.bar.org\fP as a proxyhost. Under this
configuration, foo.bar.org needs to be configured to accept print
requests from the proxy (itself) and \fBnot from sun\fP. In situations
where the proxy and the printhost are not the same machine, this can
lead to some security holes due to the original lameness of berkeley
\fBlpd\fP's host-based security.
.PP
\fBNOTE:\fP if a proxyhost isn't specified anywhere, \fBrlpr\fP
assumes one isn't necessary.
.SH "ENVIRONMENT VARIABLES"
The following environment variables are used by \fBrlpr\fP:
.TP
.B RLPR_PRINTHOST
Specifies the default host to print to.
.TP
\fBPRINTER\fP or \fBLPDEST\fP
Specifies a default printer (printqueue) to use.
.br
First \fBPRINTER\fP is consulted, then \fBLPDEST\fP.
.TP
\fBRLPR_PROXYHOST\fP or \fBRLPR_PROXY\fP
Specifies a proxy host to use, if necessary.
.br
First \fBRLPR_PROXYHOST\fP is consulted, then \fBRLPR_PROXY\fP.
.TP
.B TMPDIR
.br
If \fBTMPDIR\fP is set, it is used for temporary files.  By default, 
\fB/tmp\fP is used.
.PP
.SH FILES
.nf
.ta \w'123456789012345678'u
$HOME/.rlprrc	Printer/Host database
$TMPDIR/cf*	Temporary control files on local machine
$TMPDIR/df*	Temporary data file for jobs from stdin
/var/spool/*/cf*	Temporary control files on printhost
/var/spool/*/df*	Temporary data files on printhost
/etc/hosts.lpd	Host-based security on printhost
/etc/passwd	Personal identification
/etc/rlprrc	System-wide Printer/Host database
.fi
.SH "SEE ALSO"
\fBrlprd\fP(8), \fBrlprrc\fP(5), \fBlpr\fP(1)
.SH AUTHOR
meem <meem@gnu.ai.mit.edu>
.SH "BUGS / LIMITATIONS"
Some evil applications have \fBlpr\fP hardcoded into them.
