#!/bin/bash

set -e

if [ -x /usr/X11R6/bin/mkfontdir ]; then

  path=/usr/X11R6/lib/X11/fonts

  for i in 75dpi 100dpi misc; do
    if [ -d $path/$i ]; then
      echo "Making font directory $path/$i..."
      /usr/X11R6/bin/mkfontdir $path/$i
    fi
  done

fi

