.TH KNEWS 1 "1996"
.SH NAME
tcp_relay \- a tcp relay
.SH SYNOPSIS
.B tcp_relay
-p port [-s] -h host ... remotehost[:port]
.SH DESCRIPTION
For more details, read the source.
.SH OPTIONS
.B -p port
.RS
The port tcp_relay will listen for connections on.
.RE
.B -s
.RS
If this option is given, only a single connection at a time will
be handled.  Otherwise tcp_relay will fork a new copy of itself
for each incomming connection and go on to accept new connections.
.RE
.B -h host
.RS
Connections from this host will be allowed.  Several of these
may be supplied.
.RE
.SH AUTHOR
This software is Copyright 1996 by Karl-Johan Johnsson
<su95-kjo@nada.kth.se>.

Permission is hereby granted to copy, reproduce, redistribute or otherwise
use this software as long as: there is no monetary profit gained
specifically from the use or reproduction of this software, it is not
sold, rented, traded or otherwise marketed, and this copyright notice is
included prominently in any copy made. 

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. ANY USE OF THIS
SOFTWARE IS AT THE USERS OWN RISK.
