.TH TKDIFF 1 "1996/05/14 08:33:12"

.SH NAME 
tkdiff \- A graphical "diff" utility.

.SH SYNOPSIS 
.B tkdiff <file1> <file2>
to compare two files.

.B tkdiff <file>
to compare <file> with the most recent version checked into RCS or
CVS (if a CVS directory is present, uses CVS; otherwise, RCS is assumed).

.B tkdiff -r <file>
to compare <file> with the most recent version checked into RCS.

.B tkdiff -r<rev> <file>
to compare <file> with RCS revision <rev> of <file>.

.B tkdiff -r<rev> -r <file>
to compare revision <rev> of <file> with the most recent version
checked into RCS.

.B tkdiff -r<rev1> -r<rev2> <file>
to compare RCS revisions <rev1> and <rev2> of <file>.

.B tkdiff -C <file>
to compare <file> with the most recent version checked into CVS.

.B tkdiff -C<rev> <file>
to compare <file> with CVS revision <rev> of <file>.

.B tkdiff -C<rev> -C <file>
to compare revision <rev> of <file> with the most recent version
checked into CVS.

.B tkdiff -C<rev1> -C<rev2> <file>
to compare CVS revisions <rev1> and <rev2> of <file>.

.SH DESCRIPTION
A graphical "diff" utility.  Online help is available by hitting
the "help" button.

.SH AUTHOR
John Klassa <klassa@ivc.com>
