FILE entry.obj
FILE error.obj
FILE expand.obj
FILE key.obj
FILE main.obj
FILE macros.obj
FILE names.obj
FILE parse.obj
FILE print.obj
FILE pxfile.obj
FILE record.obj
FILE rewrite.obj
FILE rsc.obj
FILE s_parse.obj
FILE symbols.obj
FILE stack.obj
FILE sbuffer.obj
FILE tex_aux.obj
FILE tex_read.obj
FILE type.obj
FILE wordlist.obj
FILE regex.obj
