#! /bin/sh

# A script to be called to run all the other configuring scripts manually.

scripts/Configure-makefile
scripts/Configure-os.h
scripts/Configure-os.c
scripts/Configure-config.h

# End of Configure
