.TH lifeconv 6 
.SH NAME
lifeconv - convert old life patterns to 2.0 format
.SH SYNTAX
.B lifeconv [-PARp]
.SH DESCRIPTION
.NXR "lifeconv"
.PN lifeconv
is a format-conversiontool for
.BR xlife (6)
pattern files.  For information on the pattern file format, see its
manual page.
.P
A leading -[RAPp] argument forces the conversion format. Otherwise
it uses the following rules:

1) If the image won't fit in a 1000x876 screen, leave it alone (thus,
very large patterns like the breeder are left in #A format).

2) Otherwise, convert it to whichever of `P' or `R' format takes up less
disk space. Offsets are generated in the header so that the hot spot is
at the center of the bounding rectangle.

Option `p' converts from old P format to new P format.  In old P format,
the y offset at which a line was to be loaded was its absolute line number.
In the new format, it's the line number relative to the #P control line (if
the #P is the first line in the save file the two coincide).

All #-constructs other than #A, #R and #I are passed through without change.

With no file arguments, lifeconv acts as a filter.  If given file arguments,
the files will be converted to the new format in place.
.SH RESTRICTIONS
.P
None.

.SH AUTHOR
Eric S. Raymond <esr@snark.thyrsus.com>

.SH SEE ALSO   
xlife(6)
