.TH nslook 1L "Oct 93" "Handmade"
.SH NAME
nslook \- lookup hostnames and ip addresses
.SH SYNOPSIS
.B nslook 
.I hostname

.B nslook
.I ip_address
.SH DESCRIPTION
.B nslook
converts hostnames to IP-addresses and IP-addresses to hostnames.
The argument can be a list of hostnames and IP-addresses.
.SH SEE ALSO
nslookup(1), scotty(1)
.SH BUGS
We'll see.
.SH AUTHORS
schoenw@ibr.cs.tu-bs.de (Kaept'n Koerg)
