.TH rpcprobe 1L "Oct 93" "Handmade"
.SH NAME
rpcprobe \- list and probe the RPC services on a host
.SH SYNOPSIS
.B rpcprobe 
.I hostname
.SH DESCRIPTION
.B rpcprobe
retrieves the list of registered RPC services for
.I hostname
and tries to call procedure 0. This procedure normally simply does
nothing and could be used to ping a RPC service.
.B rpcprobe
lists all registered services and reports whether a response was
received.
.SH SEE ALSO
rpcinfo(8), portmap(8), scotty(1)
.SH BUGS
We'll see.
.SH AUTHORS
schoenw@ibr.cs.tu-bs.de (Kaept'n Koerg)
