.TH rstat 1L "Oct 93" "Handmade"
.SH NAME
rstat \- show the status of a remote host
.SH SYNOPSIS
.B rstat 
.I hostname
.I interval
.I [iterations]
.SH DESCRIPTION
.B rstat
displays the remote system status of host
.I hostname.
The status information is obtained with the rstat(3) RPC call.
The status information will be updated every
.I interval
seconds. If 
.I iterations
is given, the statistics are repeated 
.I iterations
times.
.SH SEE ALSO
rstat(3), scotty(1)
.SH BUGS
We'll see.
.SH AUTHORS
schoenw@ibr.cs.tu-bs.de (Kaept'n Koerg)
