.TH traceroute 8L "Oct 93" "Handmade"
.SH NAME
traceroute \- trace a route to a host
.SH SYNOPSIS
.B traceroute
[
-m
.I max_ttl
]
[
-w
.I time
]
.I hostname
.SH DESCRIPTION
.B traceroute
tracks a route to
.I hostname
by sending UDP packets to unused ports with a varying time to live
field in the IP header. This one is a simple reimplementation of the
original traceroute written by Van Jacobson based on scotty(1).
.SH OPTIONS
.TP
.BI "-m " max_ttl
Sets the maximal time to live to 
.I max_ttl.
The default is 30.
.TP
.BI "-w " time
Set the timeout time to 
.I time
seconds.
.SH SEE ALSO
scotty(1)
.SH AUTHORS
schoenw@ibr.cs.tu-bs.de
