.\" Personal
.TH SENDMSG 1
.UC L

.SH NAME
sendmsg - send a message via Internet

.SH SYNOPSIS
.B sendmsg
[
.B \-vmM
]
.BI user[@host]

.SH DESCRIPTION
.I sendmsg
sends a one line text message to the terminal of the specified recipient.
.PP
On the receiving site there must be a SAFT-server
(Simple Asynchronous File Transfer) installed, like the
.I sendfiled
and the recipients terminal must be writeable.

.BI user
can be an sendfile or elm alias.

.SH OPTIONS
.TP 8
.TP
.B -v
Verbose mode: show SAFT protocol messages
.TP
.B -m
Receive messages only on this tty. This is the default.
.TP
.B -M
Allow receiving messages on other ttys.
   
.SH EXAMPLES
.I sendmsg neg@linux.rus.uni-stuttgart.de
.br
message:
.I how about lunch?

.SH FILES
.TP 6
.B /usr/local/etc/nosendfile
Users which are not allowed to receive files or messages (set by root).
.TP 
.B /var/spool/sendfile/$LOGNAME/config/restrictions
List of addresses from where you don't want messages or files. The format
is: 

.ES
   user@host [mfb]
.EE

m stands for messages, f for files and b for both. Wildcards * and ? are
allowed. Examples:

.ES
   gates@microsoft.com b
   *aol.com m
.EE

.TP 
.B /var/spool/sendfile/$LOGNAME/config/aliases
The sendfile alias file. Format: 

.ES
   alias address
.EE

Example:

.ES
   chief grmblfz@bigvax.somewhere.net
.EE

.SH SEE ALSO
sendfile(1)

.SH AUTHOR
Ulli Horlacher  -  framstag@rus.uni-stuttgart.de
