#! /bin/sh
# touchlock - update lock(s)

# =()<. ${NEWSCONFIG-@<NEWSCONFIG>@}>()=
. ${NEWSCONFIG-/etc/news/bin/config}

PATH=$NEWSCTL/bin:$NEWSBIN:$NEWSPATH ; export PATH
umask $NEWSUMASK

status=0
for lname
do
	case "$lname" in
	*/*)	lock="$lname"	;;
	*)	lock="$NEWSCTL/$lname"	;;
	esac
	
	if test ! -f "$lock"
	then
		echo "$0: cannot find \`$lock'" >&2
		status=1
	else
		touch "$lock" || status=1
	fi
done
exit $status
