/* "mgt" Copyright (c) 1991 Shodan  */

/* Short help strings.  Don't make any of these longer than the longest one
 * already present */

char *helpStr[] =
{
   "Quit mgt",
   "Move forward",
   "Move backward",
   "Next node",
   "Previous node",
   "End of the current variation",
   "Beginning of file",
   "Next comment",
   "Previous comment",
   "Next variation branch",
   "Last variation branch",
   "Jump to a specific node number",
   "Write Smart-Go file",
   "Set black stone",
   "Set white stone",
   "Make variation",
   "Cut tree into buffer",
   "Add letter",
   "Add mark",
   "Load new file",
   "Paste buffer in",
   "Edit comment",
   "Delete current node",
   "Name the current node",
   "Score the game",
   "Pass move",
   "Other player's turn (permanent)",
   "Toggle stone",
   "Reverse through files",
   "Forward through files",
   "Redraw screen",
   "Toggle save format",
   "Toggle tutor mode",
   "Save screen image",
   "Show game info",
   "Make a move",
   "Cursor down left",
   "Cursor down",
   "Cursor down right",
   "Cursor left",
   "Cursor right",
   "Cursor up left",
   "Cursor up",
   "Cursor up right",
   "___last command marker___"};
