.TH MGT2SHORT 6  "26 February 1993"
.SH NAME
mgt2short - converts Smart-Go files to the short format.
.SH SYNOPSIS
.B mgt2short files
.SH DESCRIPTION
.B Mgt2short
converts Smart-Go files to the short format by 
invoking 
.B mgt
on each file and instructing mgt to save the file in the short
format.  This means that any data in the files which mgt does not
recognize will be lost.  
.SH AUTHOR
Adrian Mariano (adrian@bsdserver.ucsf.edu)

