$header "static char *abort_message[]"
M_ABORT_M1		"L'option -a fait arrêter Checker ici. Bye.\n"

$header "static char* help_message[]"
M_HELP_M1		"Vous pouvez donner des options à Checker par la variable d'environnement CHECKEROPTS\n"
M_HELP_M2		"Les options sont:\n"
M_HELP_M3		"-s --silent          N'affiche pas le message de début.\n"
M_HELP_M4		"-q --quiet           idem.\n"
M_HELP_M5		"-a --abort           Arrêt immédiat.\n"
M_HELP_M6		"-h --help            Affiche ce message.\n"
$literal "#ifdef CHKR_SAVESTACK"
M_HELP_M7		"-n --nosymtab        N'utilise pas la table des symbols.\n"
$literal "#endif"
M_HELP_M8		"-o=file --output=file  Redirige les message de Checker dans `file'.\n"
M_HELP_M9		"-i=file --image=file Spécifie le fichier image (Checker le trouve pour vous)\n"
$literal "#ifdef CHKR_PROFILE"
M_HELP_M10		"-p --profile         Affiche des informations de profile.\n"
$literal "#endif"
M_HELP_M11		"-d=xx --disable=xxx  Supprime les message pour l'adresse.\n"
M_HELP_M12		"-S --stop            Arrêt avant main().\n"
M_HELP_M13		"-D=a --detector=a    Récupere les mietes à la fin.\n"
M_HELP_M14		"-m=a  --malloc0=a    Change le comportement de malloc(0).\n"
M_HELP_M15		"-v    --verbose      Verbose.\n"
M_HELP_M16		"-u=end --inuse=end   Affiche les blocs non libérés à la fin.\n"
M_HELP_M17		" --Wsignal=sig       Message quand `sig' est reçu.\n"
M_HELP_M18		" --Wno-signal=sig    Pas de message quand `sig' est reçu.\n"
M_HELP_M19		" --aged-queue=n      Taille de la queue des blocs agés.\n"
M_HELP_M20		" --leak-size-threshold=n Taille minimum d'un trou pour être affiché.\n"
M_HELP_M21		" --bytes-per-state=n Nombre d'octets par élément de bitmap.\n"
M_HELP_M22		" --no-signals        Supprime le gestionnaire de signaux.\n"
M_HELP_M23		" --Wsbrk --Wno-sbrk  Emet un message si sbrk() est appelé.\n"
M_HELP_M24		"-A --Wmemalign       Emet un message si l'appel n'est pas conventionel.\n"
M_HELP_M25		"-t --trace           Trace les appels à malloc, free...\n"
M_HELP_M26		"-w --weak-check-copy Copie les bitmaps pour memcpy, bcopy, memmove\n"
M_HELP_M0		"\n"

$header "static char* init_message[]"
$literal "#if !defined(SIMCHECKER) && !defined(GCCCHECKER)"
M_COPY_M1		"Ce programme a été compilé avec `checkergcc' ou `checkerg++'.\n"
$literal "#endif"
M_COPY_M2		"Checker est un détecteur d'accès à la mémoire.\n"
M_COPY_M3		"Checker est distribué dans l'espoir d'être utile,\n"
M_COPY_M4		"cependant SANS AUCUNE GARANTIE; même sans la garantie implicite de\n"
M_COPY_M5		"COMMERCIALISATION ou d'aptitude à un but particulier. Voir la GNU\n"
M_COPY_M6		"General Public License pour plus de détails.\n"
M_COPY_M7		"Pour plus d'informations, mettre CHECKEROPTS à `--help'\n"
$end

$literal "#ifdef NEED_CHKR_LD_OPTIONS"
$header "static char* link_with_other_message[]"
M_L_W_O_M1		"Attention: cet éxécutable contient des fichiers non compilés avec Checker.\n"
M_L_W_O_M2		" Checker va seulement tester les violations des limites dans le tas.\n"
M_L_W_O_M3		"\n"
$end
$literal "#endif"
