\input texinfo
@c -*-texinfo-*-
@c %**start of header
@setfilename guile-user.info
@settitle Guile User Manual
@c %**end of header

@include version.texi

@c I combine the variable and function indices
@syncodeindex vr fn

@c @iftex
@c @cropmarks
@c @end iftex

@dircategory Guile -- GNU extension language
@direntry
* guile-user: (guile-user).                     The Guile User Manual.
@end direntry

@setchapternewpage on

@ifinfo
Guile User Manual
Copyright (C) 1996 Free Software Foundation

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).
@end ignore

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the Free Software Foundation.
@end ifinfo

@titlepage
@sp 10
@comment The title is printed in a large font.
@title Guile User Manual
@subtitle For use with Guile @value{VERSION}
@subtitle Last updated @value{UPDATED}
@author Mark Galassi
@author Los Alamos National Laboratory
@author @email{rosalia@@nis.lanl.gov}

@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@vskip 0pt plus 1filll
Copyright @copyright{} 1996 Free Software Foundation

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by Free Software Foundation.
@end titlepage

@c @smallbook
@finalout
@headings double

@ifinfo
@node Top, Introduction - what is Guile, (dir), (dir)
@top The Guile User Manual
@end ifinfo

@menu
* Introduction - what is Guile::  
* How to start up Guile - a quick tour::  
* Using Guile::                 
* Guile in a library - using libguile.a::  
* Some other features of Guile::  
* Where to find more Guile/Scheme resources::  
* Concept Index::               
* Procedure and Variable Index::  

 --- The Detailed Node Listing ---

Introduction - what is Guile

* What are scripting and extension languages::  
* History of Guile and its motivations::  
* How to characterize Guile::   
* Roadmap for the User Manual::  

How to start up Guile - a quick tour

* Invoking Guile::              
* Guile as a basic Scheme interpreter::  

Using Guile

* Using Guile to write Guile programs::  

Guile in a library - using libguile.a

* Two world views::             
* What is libguile -- high and low level::  
* How to get started with libguile::  
* More interesting programming with libguile::  
* Further examples::            

More interesting programming with libguile

* learn1.c::                    
* c_builtins.h::                
* c_builtins.c::                
* What learn1 is doing::        
* Compiling and running learn1::

Some other features of Guile

* Modules in Guile::
* The Guile interface to Posix::  
* Threads in Guile::            
* Guile exceptions - catch and throw::  
* Regular expression support::  

Modules in Guile

* Getting started with modules::
* Interfaces to Scheme packages::

Threads in Guile

* What are threads::            
* Configuring Guile to use threads::  
* Examples of Scheme threads::  
* Dynamic roots::               

Where to find more Guile/Scheme resources

* Online resources::            
* Books and papers::            
* Other documents shipped with Guile::  
@end menu

@include intro.texi
@c @include install.texi
@include startup.texi
@include using-guile.texi
@include libguile.texi
@c @include tk.texi
@include other.texi
@c @include i18n.texi
@include more-resources.texi
@c @include install-probs.texi

@include cindex.texi
@include pi.texi

@contents

@bye
