@c \input texinfo
@c -*-texinfo-*-
@c %**start of header
@setfilename guile_user.info
@settitle Guile User Manual
@c %**end of header

@node What is missing in this manual, Concept Index, Bug reports and hackarounds for various guile releases, Top
@appendix What is missing in this manual

I feel that a few things have not been treated here; either they were
missing in the outline, or I don't know much about them.  I would like
to add them eventually.

@strong{Ggl, mesa and glut:} Guile has an interface to SGI's Open GL
library, using the free GL clone "mesa".  This also works with the glut
toolkit.  There is no documentation; I will have to study the code.

@strong{ctax:} Ctax is a C-like syntax for scheme, provided as one of
the plugin modules for Guile.  It would be nice to show examples of
ctax, and examples of how to switch from one language to another as you
fancy.

@strong{threads:} Threads are as trendy as applets, and are used in the
applet formalism of Guile.  What is the interface to threads from C and
from scheme?
