#!/bin/sh -e
#
# Debian package preinst
# Version 1.2
#
# Robert Leslie <rob@mars.org>

case "$1" in
    install)
    ;;

    upgrade)
	start-stop-daemon --stop --quiet --oknodo  \
	    --pidfile /var/run/sendmail.pid  \
	    --exec /usr/sbin/sendmail 2>/dev/null || true
    ;;

    abort-upgrade)
    ;;

    *)
	echo "preinst called with unknown argument \`$1'" >&2
	exit 0
    ;;
esac
