	{"ABS",	K_ABS	},
	{"ACOS",	K_ACOS	},
	{"ASIN",	K_ASIN	},
	{"ATAN",	K_ATAN	},
	{"ATAN2",	K_ATAN2	},
	{"AVG",	K_AVG	},
	{"CEIL",	K_CEIL	},
	{"COS",	K_COS	},
	{"COUNT",	K_COUNT	},
	{"DTR",	K_DTR	},
	{"ERROR",	K_ERROR	},
	{"EXP",	K_EXP	},
	{"FABS",	K_FABS	},
	{"FIXED",	K_FIXED	},
	{"FLOOR",	K_FLOOR	},
	{"HYPOT",	K_HYPOT	},
	{"IF",	K_IF	},
	{"INVALID",	K_INVALID	},
	{"LN",	K_LN	},
	{"LOG",	K_LOG	},
	{"MAX",	K_MAX	},
	{"MIN",	K_MIN	},
	{"PI",	K_PI	},
	{"POW",	K_POW	},
	{"PROD",	K_PROD	},
	{"RND",	K_RND	},
	{"ROUND",	K_ROUND	},
	{"RTD",	K_RTD	},
	{"SIN",	K_SIN	},
	{"SQRT",	K_SQRT	},
	{"STDDEV",	K_STDDEV	},
	{"SUM",	K_SUM	},
	{"TAN",	K_TAN	},
	{"FV",	K_FV	/* @fv(e1,e2,e3) computes the future value */	},
	{"IRR",	K_IRR	/* @irr(range)	 computes the internal rate of return */	},
	{"PMT",	K_PMT	},
	{"PV",	K_PV	},
	{"HOUR",	K_HOUR	/* @hour(e)	number of hours since midnight: 0 to 23 */	},
	{"MINUTE",	K_MINUTE	/* @minute(e)	the number of minutes past the hour: 0 to 59 */	},
	{"SECOND",	K_SECOND	/* @second(e)	the number of seconds past the minute: 0-59 */	},
	{"MONTH",	K_MONTH	/* @month(e)	Return the month: 1 (Jan) to 12 (Dec) */	},
	{"DAY",	K_DAY	/* @day(e)	Return the day of the month: 1 to 31 */	},
	{"YEAR",	K_YEAR	/* @year(e)	Return the year.  Valid years begin with 1970*/	},
	{"DATE",	K_DATE	/* @date(e)	Convert the time in seconds to a date */	},
	{"DTS",	K_DTS	/* @dts(m,d,y)	Return m/d/y encoded in seconds since 1970 */	},
	{"NOW",	K_NOW	/* @now		Return the time encoded in seconds since 1970*/	},
	{"TTS",	K_TTS	/* @tts(h,m,s)	Return h:m:s encoded in seconds since midnight*/	},
	{"FMT",	K_FMT	/* @fmt(se,e)	Convert a number to a string using sprintf(3)*/	},
	{"STON",	K_STON	/* @ston(se)	Convert string expr se to a numeric */	},
	{"SUBSTR",	K_SUBSTR	},
	{"UPPER",	K_UPPER	},
	{"LOWER",	K_LOWER	},
	{"CAPITAL",	K_CAPITAL	},
	{"EQS",	K_EQS	},
	{"EXT",	K_EXT	},
	{"NVAL",	K_NVAL	},
	{"SVAL",	K_SVAL	},
	{"LOOKUP",	K_LOOKUP	},
	{"HLOOKUP",	K_HLOOKUP	},
	{"VLOOKUP",	K_VLOOKUP	},
	{"INDEX",	K_INDEX	},
	{"STINDEX",	K_STINDEX	},
	{"AUTO",	K_AUTO	},
	{"AUTOCALC",	K_AUTOCALC	},
	{"BYROWS",	K_BYROWS	},
	{"BYCOLS",	K_BYCOLS	},
	{"ITERATIONS",	K_ITERATIONS	},
	{"NUMERIC",	K_NUMERIC	},
	{"PRESCALE",	K_PRESCALE	},
	{"EXTFUN",	K_EXTFUN	},
	{"CELLCUR",	K_CELLCUR	},
	{"TOPROW",	K_TOPROW	},
	{"TBLSTYLE",	K_TBLSTYLE	},
	{"TBL",	K_TBL	},
	{"LATEX",	K_LATEX	},
	{"SLATEX",	K_SLATEX	},
	{"TEX",	K_TEX	},
	{"FRAME",	K_FRAME	},
	{"RNDINFINITY",	K_RNDINFINITY	},
	{"MYROW",	K_MYROW	},
	{"MYCOL",	K_MYCOL	},
	{"COLTOA",	K_COLTOA	},
	{"CRACTION",	K_CRACTION	},
	{"CRROW",	K_CRROW	},
	{"CRCOL",	K_CRCOL	},
	{"ROWLIMIT",	K_ROWLIMIT	},
	{"COLLIMIT",	K_COLLIMIT	},
	{"NUMITER",	K_NUMITER	},
	{"MATRIX_ADD",	K_MATRIX_ADD	},
	{"MATRIX_SUB",	K_MATRIX_SUB	},
	{"MATRIX_INV",	K_MATRIX_INV	},
	{"MATRIX_MULT",	K_MATRIX_MULT	},
	{"MATRIX_TRANS",	K_MATRIX_TRANS	},
	{"GRAPH",	K_GRAPH	},
