# This file is provided as an example for those who don't want to
# use /etc/init.d/nrprobenet start (this deamon will probe the local 
# net for cards, and create a /etc/bootpdtab file with up-to-date entries
# in it. (see manual page nrprobenet)
# 
# /etc/bootptab: database for bootp server (/usr/sbin/bootpd)
#
# Blank lines and lines beginning with '#' are ignored.
#
# Legend:	(see bootptab.5)
#	first field -- hostname (not indented)
#	bf -- bootfile
#	bs -- bootfile size in 512-octet blocks
#	cs -- cookie servers
#	df -- dump file name
#	dn -- domain name
#	ds -- domain name servers
#	ef -- extension file
#	gw -- gateways
#	ha -- hardware address
#	hd -- home directory for bootfiles
#	hn -- host name set for client
#	ht -- hardware type
#	im -- impress servers
#	ip -- host IP address
#	lg -- log servers
#	lp -- LPR servers
#	ns -- IEN-116 name servers
#	ra -- reply address
#	rl -- resource location protocol servers
#	rp -- root path
#	sa -- boot server address
#	sm -- subnet mask
#	sw -- swap server
#	tc -- template host (points to similar host entry)
#	td -- TFTP directory
#	to -- time offset (seconds)
#	ts -- time servers
#	vm -- vendor magic number
#	Tn -- generic option tag n
#
# Be careful about including backslashes where they're needed.  Weird (bad)
# things can happen when a backslash is omitted where one is intended.
# Also, note that generic option data must be either a string or a
# sequence of bytes where each byte is a two-digit hex value.
#
#
# .nrdefault will be used for all table enries generated by nrprobenet
# It may be good to add a gateway (gw) here
# My entry reads:
#  .nrdefault::gw=rulgate:
.nrdefault::

rulgmz.LeidenUniv.nl:ha=00.A0.24.B7.72.E6:tc=.nrdefault
rulgma.LeidenUniv.nl:ha=02.60.8C.A3.2C.74:tc=.nrdefault
rulgmb.LeidenUniv.nl:ha=00.20.AF.F2.8F.80:tc=.nrdefault
rulgmx.LeidenUniv.nl:ha=00.A0.24.B8.5D.B6:tc=.nrdefault
rulgms.LeidenUniv.nl:ha=00.A0.24.B7.72.E0:tc=.nrdefault
rulkmd.LeidenUniv.nl:ha=00.A0.24.B7.72.D5:tc=.nrdefault
rulkmc.LeidenUniv.nl:ha=02.60.8C.0B.E9.97:tc=.nrdefault
rulkmm.LeidenUniv.nl:ha=02.60.8C.2A.EE.1A:tc=.nrdefault
rulkmo.LeidenUniv.nl:ha=00.60.8C.81.F3.75:tc=.nrdefault
rulkmp.LeidenUniv.nl:ha=00.60.8C.81.F3.64:tc=.nrdefault
ruladm.LeidenUniv.nl:ha=08.00.09.7A.18.9A:tc=.nrdefault
rulkmq.LeidenUniv.nl:ha=00.60.8C.81.F3.74:tc=.nrdefault
rulgmt.LeidenUniv.nl:ha=02.60.8C.46.A4.54:tc=.nrdefault
rulgmu.LeidenUniv.nl:ha=00.A0.24.B7.72.E1:tc=.nrdefault
rulgmd.LeidenUniv.nl:ha=02.60.8C.3B.AE.63:tc=.nrdefault
rulgmv.LeidenUniv.nl:ha=02.60.8C.46.3B.1C:tc=.nrdefault
rulgmw.LeidenUniv.nl:ha=00.A0.24.B8.5E.00:tc=.nrdefault
kolpc1.LeidenUniv.nl:ha=00.60.97.1E.4A.E2:tc=.nrdefault
kolpc3.LeidenUniv.nl:ha=00.60.97.1E.4A.C2:tc=.nrdefault
kolpc16.LeidenUniv.nl:ha=00.60.97.1E.4B.59:tc=.nrdefault
kolpc17LeidenUniv.nl:ha=00.60.97.1E.4B.FB:tc=.nrdefault
rulgmr.LeidenUniv.nl:ha=00.A0.24.B7.72.D8:tc=.nrdefault
rulgmp.LeidenUniv.nl:ha=02.60.8C.46.5C.4A:tc=.nrdefault
rulgml.LeidenUniv.nl:ha=00.A0.24.EC.40.8F:tc=.nrdefault
rulgmf.LeidenUniv.nl:ha=00.A0.24.24.9B.E5:tc=.nrdefault
rulgmm.LeidenUniv.nl:ha=02.60.8C.9C.0D.F4:tc=.nrdefault
rulgmn.LeidenUniv.nl:ha=02.60.8C.9D.D0.B8:tc=.nrdefault
rulgmo.LeidenUniv.nl:ha=02.60.8C.9D.DB.2A:tc=.nrdefault
rulgmg.LeidenUniv.nl:ha=02.60.8C.A3.44.76:tc=.nrdefault
qv3dale.LeidenUniv.nl:ha=00.A0.24.2C.D5.BE:tc=.nrdefault
qv3goofy.LeidenUniv.nl:ha=00.A0.24.55.A5.09:tc=.nrdefault
qv3daisy.LeidenUniv.nl:ha=00.20.AF.05.08.77:tc=.nrdefault
rulkmr.LeidenUniv.nl:ha=00.60.8C.81.F3.56:tc=.nrdefault
rulkms.LeidenUniv.nl:ha=00.60.8C.81.F3.73:tc=.nrdefault
rulkmw.LeidenUniv.nl:ha=00.20.AF.03.BE.A6:tc=.nrdefault
rulgmi.leidenuniv.nl:ha=02.60.8C.A3.35.FA:tc=.nrdefault
rulvsb.LeidenUniv.nl:ha=00.20.AF.4B.36.C0:tc=.nrdefault
rulvsc.LeidenUniv.nl:ha=00.20.AF.4A.EF.1B:tc=.nrdefault
rulvsd.LeidenUniv.nl:ha=00.A0.24.24.9B.D1:tc=.nrdefault
rulvse.LeidenUniv.nl:ha=02.60.8C.A3.2C.6F:tc=.nrdefault
rulvsf.LeidenUniv.nl:ha=00.A0.24.24.9C.1F:tc=.nrdefault
rulvsg.LeidenUniv.nl:ha=00.A0.24.2C.C6.3D:tc=.nrdefault
rulvsh.LeidenUniv.nl:ha=00.A0.24.2C.D5.AF:tc=.nrdefault
rulvsi.LeidenUniv.nl:ha=00.A0.24.2C.C6.42:tc=.nrdefault
rulvsj.LeidenUniv.nl:ha=00.A0.24.2C.C6.E9:tc=.nrdefault
rulgmj.LeidenUniv.nl:ha=00.A0.24.B8.5D.48:tc=.nrdefault
rulvsk.LeidenUniv.nl:ha=00.A0.24.55.A5.E6:tc=.nrdefault
rulvsl.LeidenUniv.nl:ha=00.A0.24.55.A5.2B:tc=.nrdefault
rulvsm.LeidenUniv.nl:ha=02.60.8C.A3.49.B0:tc=.nrdefault
rulvsn.LeidenUniv.nl:ha=00.A0.24.54.C8.A3:tc=.nrdefault
rulvso.LeidenUniv.nl:ha=00.A0.24.24.9C.33:tc=.nrdefault
rulvsp.LeidenUniv.nl:ha=08.00.2B.0A.EB.A9:tc=.nrdefault
rulvst.LeidenUniv.nl:ha=00.A0.24.B7.72.FB:tc=.nrdefault
rulgmk.LeidenUniv.nl:ha=00.A0.24.B7.72.E2:tc=.nrdefault
eatest1.LeidenUniv.nl:ha=02.60.8C.3A.35.C5:tc=.nrdefault
eatest3.LeidenUniv.nl:ha=00.A0.24.46.A9.E2:tc=.nrdefault
kristal.LeidenUniv.nl:ha=00.A0.24.53.B6.FA:tc=.nrdefault
rulsur.LeidenUniv.nl:ha=AA.00.04.00.20.70:tc=.nrdefault
rulgmc.LeidenUniv.nl:ha=00.A0.24.EC.3F.E5:tc=.nrdefault
qv3chip.LeidenUniv.nl:ha=00.A0.24.52.1D.C6:tc=.nrdefault
ilcolor.LeidenUniv.nl:ha=00.60.B0.03.0C.72:tc=.nrdefault
132.229.1.203:ha=00.A0.24.EC.17.CF:tc=.nrdefault
rulcma.LeidenUniv.nl:ha=00.A0.24.B8.5E.0A:tc=.nrdefault
qv3wicky.LeidenUniv.nl:ha=02.60.8C.A7.1A.27:tc=.nrdefault
qv3scrooge.LeidenUniv.nl:ha=02.60.8C.A2.DB.4C:tc=.nrdefault
crikol.LeidenUniv.nl:ha=08.00.90.03.E3.43:tc=.nrdefault
rulcme.LeidenUniv.nl:ha=00.A0.24.B8.5E.06:tc=.nrdefault
rulkmb.LeidenUniv.nl:ha=02.60.8C.0D.46.56:tc=.nrdefault
rulkmu.LeidenUniv.nl:ha=00.20.AF.05.06.E4:tc=.nrdefault
qv3hewey.LeidenUniv.nl:ha=00.20.AF.03.BE.B5:tc=.nrdefault
qv3mickey.LeidenUniv.nl:ha=00.20.AF.03.BE.AE:tc=.nrdefault
rulkma.LeidenUniv.nl:ha=00.A0.24.B8.5C.79:tc=.nrdefault
rulkml.LeidenUniv.nl:ha=02.60.8C.2A.1D.60:tc=.nrdefault
rulkmk.LeidenUniv.nl:ha=02.60.8C.92.65.55:tc=.nrdefault
rulkmj.LeidenUniv.nl:ha=02.60.8C.3B.0F.BD:tc=.nrdefault
rulkmi.LeidenUniv.nl:ha=00.A0.24.B7.72.CC:tc=.nrdefault
rulkmf.LeidenUniv.nl:ha=02.60.8C.3A.1D.B3:tc=.nrdefault
rulcmf.LeidenUniv.nl:ha=00.A0.24.B8.5D.B9:tc=.nrdefault
rulcmg.LeidenUniv.nl:ha=00.A0.24.B8.5C.98:tc=.nrdefault
rulcmk.LeidenUniv.nl:ha=00.A0.24.B8.5D.F3:tc=.nrdefault
rulfjk.Leidenuniv.nl:ha=00.A0.24.B8.5D.1F:tc=.nrdefault
rulcmn.LeidenUniv.nl:ha=00.A0.24.B7.72.DF:tc=.nrdefault
rulcmo.LeidenUniv.nl:ha=00.A0.24.B8.5E.2A:tc=.nrdefault
rulcmp.LeidenUniv.nl:ha=00.A0.24.B8.5E.29:tc=.nrdefault
rulcmq.LeidenUniv.nl:ha=00.A0.24.B7.72.C8:tc=.nrdefault
ilpc2.leidenuniv.nl:ha=02.60.8C.3B.69.98:tc=.nrdefault
rulcmr.LeidenUniv.nl:ha=00.A0.24.B8.5D.47:tc=.nrdefault
rulcms.LeidenUniv.nl:ha=00.A0.24.B8.5C.7B:tc=.nrdefault
rulcmu.LeidenUniv.nl:ha=02.60.8C.3C.47.E5:tc=.nrdefault
rulcmv.LeidenUniv.nl:ha=00.A0.24.B8.5C.23:tc=.nrdefault
rulcmy.LeidenUniv.nl:ha=00.A0.24.B8.5D.57:tc=.nrdefault
rulcmz.LeidenUniv.nl:ha=02.60.8C.2A.23.0B:tc=.nrdefault
rulkmt.LeidenUniv.nl:ha=00.20.AF.05.06.EA:tc=.nrdefault
rulvsa.LeidenUniv.nl:ha=00.20.AF.4B.36.79:tc=.nrdefault
bmdw.LeidenUniv.nl:ha=00.80.5F.FC.CE.EB:tc=.nrdefault
rulilpc1.LeidenUniv.nl:ha=00.A0.24.EC.40.A0:tc=.nrdefault
yassu.LeidenUniv.nl:ha=02.60.8C.3B.9E.2D:tc=.nrdefault
rulgmy.LeidenUniv.nl:ha=02.60.8C.41.D1.52:tc=.nrdefault
