"Files*doubleClickTime:		300",
"Files*updateInterval:		10000",
"Files.initGeometry:			400x350",
"Files.file window.Geometry:	400x350",
"Files*MenuButton*cursor:		hand2",
"Files*Command*cursor:			hand2",
"Files*SimpleMenu*cursor:		hand2",
"Files*Toggle*cursor:			hand2",
"Files*background:				grey",
"Files*Text*background:				white",
"Files*viewport.icon box*Toggle.foreground:	red",
"Files*viewport.icon box*Toggle.shadowWidth: 	0",
"Files*viewport.icon box*Command.shadowWidth: 	0",
"Files*chmod.form.Form.Command.highlightThickness:0",
"Files*boldFont:			-*-lucidatypewriter-bold-r-*-*-14-*",
"Files*iconFont:			-*-lucidatypewriter-medium-r-*-*-12-*",
"Files*buttonFont:		-*-lucida-*-r-*-*-12-*",
"Files*menuFont:			-*-lucida-*-r-*-*-12-*",
"Files*labelFont:		-*-lucida-*-r-*-*-12-*",
"Files*statusFont:		-*-lucida-*-r-*-*-12-*",
"Files*cellFont:			-*-lucidatypewriter-medium-r-*-*-14-*",
"Files*appIconWidth: 72",
"Files*appIconHeight: 60",
"Files*fileIconWidth: 48",
"Files*fileIconHeight: 40",
"Files*treeIconWidth: 48",
"Files*treeIconHeight: 32",
"Files*confirmDeletes: 		true",
"Files*confirmDeleteFolder: 	true",
"Files*confirmCopies: 		true",
"Files*confirmMoves: 		true",
"Files*confirmOverwrite:		false",
"Files*confirmQuit:		true",
"Files*echoActions:			false",
"Files*showOwner: 		true",
"Files*showDate: 		false",
"Files*showPermissions: 		false",
"Files*showLength: 		true",
"Files*initialDisplayType:	 	Icons",
"Files*defaultDisplayType: 		Icons",
"Files*defaultSortType: 		SortByName",
"Files*defaultEditor: 		exec editor",
"Files*defaultViewer: 		exec editor",
"Files*defaultTerm: 		exec xterm",
"Files*Command.cursor: hand2",
"Files*MenuButton.cursor: hand2",
"Files*viewport.forceBars: true",
"Files*popup form*bitmap.borderWidth : 0",
"Files*popup form*label.borderWidth : 0",
"Files*button box.orientation: horizontal",
"Files*button box.borderWidth: 0",
"Files*viewport.borderWidth: 0",
"Files*viewport.icon box*Label.borderWidth : 0",
"Files*viewport.icon box.Command.borderWidth : 0",
"Files*viewport.icon box.Form.borderWidth : 0",
"Files*viewport.icon box*Toggle.borderWidth : 1",
"Files*chmod*Label.borderWidth : 0",
"Files*info*Label.borderWidth : 0",
"Files*error*Label.borderWidth : 0",
"Files*confirm*Label.borderWidth : 0",
"Files*Text*translations : #override \\n <Key>Return: no-op() \\n <Key>Linefeed : no-op() \\n Ctrl<Key>J : no-op() \\n",
