.TH verse 1L "Bible Verse" "DEBIAN" \" -*- nroff -*-
.SH NAME
verse \- Displays a daily devotional verse from scripture
.SH SYNOPSIS
\fBverse\fP
.SH DESCRIPTION
Displays a verse taken from the database in
.B /usr/lib/daily.verse
that is specific for the current date.
.SH INTEGRATION
If you invoke
.B verse
from /etc/profile then the daily devotional verse will appear on each
login for each user. Alternatively you could put the invocation of
.B verse
into the .profile of a user and have each user choose if he wants to use
verse or not.
.PP
Note that you will run into trouble if you have dialin users whose scripts
call pppd and put the verse call into /etc/profile. The output might confuse
the ppp programs.
.SH AUTHOR (of the verse program not the database)
Christoph Lameter <clameter@debian.org>
