#!/usr/bin/perl
$prt=0;
while(<>) {
    if ($_ =~ /Number/) {
	$prt=1;
    } else {
	if (($prt==1) && ($_ =~ /Block/)) {
	    $prt=0;
	    print " ";
	} else {		
	    if ($prt==1) {	
		print $_;	
	    }}		       
    }
}
