load_lib mike-g++.exp
prebase

set src_code member.C

set not_compiler_output "sorry|:30:"
set compiler_output ".*`int Y::X::\\* Y::X::foo\\(\\)'.*
.*`int Y::X::\\* foo\\(\\)'.*
.*`int Y::X::\\* \\(\\* foo2\\(\\)\\)\\(\\)'.*
.*`int \\(Y::X::\\* bar2\\(\\)\\)\\(\\)'.*
.*`int Y::X::\\* \\(Y::X::\\* foo3\\(\\)\\)\\(\\)'.*"

set groups {passed member-pointers error-reporting}

postbase $src_code $run $groups
