load_lib mike-g++.exp
prebase

set src_code report.C
set compiler_output "`int foo\\(int = \\(\\*\\*bar\\)\\(s\\)\\)'.*
.*`doowop<foo\\(int\\)>'.*
.*`int foo2\\(int \\(\\*\\)\\(int\\) = foo\\(int\\)\\)'.*
.*`const int \\* \\(\\*const \\* baz\\(class X::Y\\)\\)\\(\\)'.*
.*`static int ninny\\(\\)::A::ninny2\\(\\)'.*
.*`badoo<'\\\\001'>'.*
.*`int darg\\(char X::\\*\\)'"

set groups {passed error-reporting}

postbase $src_code $run $groups
