.TH spell 1
.SH NAME
spell \- List misspelled words in stream or files
.SH SYNOPSIS
.B spell
.I [file...]
.SH DESCRIPTION
.PP
Returns a sorted list of words from the input files (if present) or stdin
which fail to match entries in the ispell dictionary.
.SH FILES
.nf
.I /usr/lib/ispell/default.hash
.I $HOME/.ispell_words
.fi
.SH "SEE ALSO"
.BR ispell (1),
.BR spell (1),
.BR spellword (1)
.RS
.LP
.nf
.ft R
.ad
.fi
.RE
.LP
