#-----------------------------------------------------------------------------
#                               EXAMPLES  Makefile
#-----------------------------------------------------------------------------
#
# Intructions to Add a new example
#
#   1. Update the variable LIST_EXEC with the new target (executable name).
#      Do not include any extensions; instead append $e to this name.
#
#   2. Add a new entry in the dependencies with the following format :
#       name_exec_DEP= {list of .o files needed to build the executable -
#         use $o as the extension instead of .o or .obj}
#       name_exec$e : name_exec.$o $(name_exec_DEP)
#-----------------------------------------------------------------------------

# Put here the final target of each test case.
# it can be a '.o' file if the test is just a compilation one
# otherwise it is the final executable
LIST_COMPILE_ONLY =
LIST_EXEC = hello$e text_io_example$e use_of_import$e tgef$e tef$e \
 demo1$e demo2$e test_cl$e

#-----------------------------------------------------------------------------
# Dependencies

hello_DEP=
hello$e : hello.$o $(hello_DEP)

demo1_DEP=
demo1$e : demo1.$o  instr.$o $(demo1_DEP)

demo2_DEP=
demo2$e : demo2.$o instr.$o instr-child.$o $(demo2_DEP)

use_of_import_DEP = imported_function.$o
use_of_import$e : use_of_import.$o $(use_of_import_DEP)

text_io_example_DEP =
text_io_example$e : text_io_example.$o $(text_io_example_DEP)

tgef_DEP =
tgef$e : tgef.$o $(tgef_DEP)

tef_DEP =
tef$e : tef.$o $(tef_DEP)

ex6_main_DEP = ex6.$o
ex6_main.$o : ex6_main.adb ex6_if.ads
ex6_if.$o : ex6_if.ads ex6_if.adb

test_cl_DEP =
test_cl: test_cl.o
test_cl.o: test_cl.adb
