.\" cgiscriptsconfig.8, Copyright (C) 1996, Yves Arrouye <arrouye@debian.org>
.TH APACHECONFIG 8 "9 September 1996" "Debian/Linux" "Linux Administrator's Manual"
.SH NAME
.B cgiscriptsconfig
\- install or remove CGI scripts
.SH SYNOPSIS
.B cgiscriptsconfig
[
.B \-\-force
]
[
.B \-\-overwrite
]
[
.B \-\-symlinks
]
[
.BI \-\-cgidir " directory"
]
.br
.B cgiscriptsconfig
.B \-\-remove
.SH DESCRIPTION
.B cgiscriptsconfig
installs or removes Common Gateway Interface scripts to a location where
a Web server can access them.
.SH OPTIONS
.TP
.B \-\-force
Force interactive asking of the directory where the scripts will be
installed.
.TP
.B \-\-overwrite
Overwrite existing files.
.TP
.B \-\-symlinks
Create symbolic links instead of copying the scripts.
.TP
.BI \-\-cgidir " directory"
Install the scripts in the specified
.IR directory .
.TP
.BI \-\-remove
Remove the installed scripts.
.SH CAVEATS AND BUGS
At the moment,
.B cgiscriptsconfig
only recognizes the configuration files of the Apache server.
.SH AUTHOR
Yves Arrouye <arrouye@debian.org>

