$header "static char *abort_message[]"
M_ABORT_M1		"Checker aborted by the -a option."

$header "static char* help_message[]"
M_HELP_M1		"Checker reads options from the environment variable CHECKEROPTS\n"
M_HELP_M2		"Options are:\n"
M_HELP_M3		"-s --silent          Do not print the welcome message.\n"
M_HELP_M4		"-q --quiet           Same as --silent.\n"
M_HELP_M5		"-a --abort           Abort on startup.\n"
M_HELP_M6		"-h --help            Print this message.\n"
$literal "#ifdef CHKR_SAVESTACK"
M_HELP_M7		"-n --nosymtab        Do not use symbol table.\n"
$literal "#endif"
M_HELP_M8		"-o=file --output=file  Redirect Checker's output to `file'.\n"
M_HELP_M9		"-i=file --image=file Set the image file (Checker finds it for you)\n"
$literal "#ifdef CHKR_PROFILE"
M_HELP_M10		"-p --profile         Display profile information.\n"
$literal "#endif"
M_HELP_M11		"-d=xx --disable=xxx  Disable an address or a range of addresses.\n"
M_HELP_M12		"-S --stop            Stop just before main.\n"
M_HELP_M13		"-D=end --detector=end    Do leak detection at the end of the program.\n"
M_HELP_M14		"-m=a  --malloc0=a    Set the behavior of malloc(0).\n"
M_HELP_M15		"-v    --verbose      Verbose.\n"
M_HELP_M16		"-u=end --inuse=end   Do inuse at the end.\n"
M_HELP_M17		" -Wsignal=sig        Emit a warning when `sig' is received.\n"
M_HELP_M18		" -Wno-signal=sig     Do not emit a warning when `sig' is received.\n"
M_HELP_M19		" --aged-queue=n      Set the size of the aged block queue.\n"
M_HELP_M20		" --leak-size-threshold=n Minimum size of a leak to be displayed.\n"
M_HELP_M21		" --bytes-per-state=n Number of bytes handled by a bitmap state.\n"
M_HELP_M22		" --no-signals        Disable the signal manager.\n"
M_HELP_M23		" --Wsbrk --Wno-sbrk  Emit a warning if sbrk() is called.\n"
M_HELP_M24		"-A --Wmemalign       Emit a warning if the aligment arg isn't a power of 2.\n"
M_HELP_M25		"-t --trace           Trace calls to malloc, free...\n"
M_HELP_M26		"-w --weak-check-copy Only copy the bitmap for memcpy, memmove, bcopy\n"
M_HELP_M0		"\n"

$header "static char* init_message[]"
$literal "#if !defined(SIMCHECKER) && !defined(GCCCHECKER)"
M_COPY_M1		"This program has been compiled with `checkergcc' or `checkerg++'.\n"
$literal "#endif"
M_COPY_M2		"Checker is a memory access detector.\n"
M_COPY_M3		"Checker is distributed in the hope that it will be useful,\n"
M_COPY_M4		"but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
M_COPY_M5		"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n"
M_COPY_M6		"General Public License for more details.\n"
M_COPY_M7		"For more information, set CHECKEROPTS to `--help'\n"
$end

$literal "#ifdef NEED_CHKR_LD_OPTIONS"
$header "static char* link_with_other_message[]"
M_L_W_O_M1		"Warning: this program contains functions not compiled with Checker.\n"
M_L_W_O_M2		" Therefore Checker will only check bounds violation in the heap.\n"
M_L_W_O_M3		"\n"
$end
$literal "#endif"
