.TH TERMTEST 1
.SH NAME
termtest \- debugging tool for 
.IR term
.SH SYNOPSIS
.B "termtest "
[\-1 <program>] [\-2 <program>] [-local <options>] [--remote <options>]
[<options>]
.SH DESCRIPTION
You should perform two sets of tests before you ever try to run
.IR term
itself.
The
.IR termtest
program lets you 
exercise 
.IR term
and its clients locally by starting two
.IR term
daemons on the same system.
.IR Termtest
when run, establishes two connected instances of 
.IR term 
on the local system so you may see if they and the clients work.  
To avoid problems with other programs also called 'termtest' you should 
run
.IR termtest 
from the source directory of 
.IR term
by typing
.PP
\ \ \ setenv TERMMODE 0
.PP
.PP
\ \ \ ./termtest \ \-n \ on
.PP
.IR Termtest
opens the files 'local.log' and 'remote.log' in the local directory to
record the stderr output of the two term daemons.
Options on the command line of
.B termtest
are passed on to both of them.
If you need to debug you can use 
.B \-d 64
or even
.B \-d 2112.
Familiarity with the sources is essential if you use debugging.
The termrc file is used to set the parameters of both daemons.
You can specify a different term daemon (e.g. an old one that is
already installed on your system) as the 'remote' by giving the
option 
.B \-2 program
as the first option for test. Similarly, you can use a
different 'local' term daemon with the 
.B \-1 
option.
.PP
Once 
.IR termtest
is running you should be able to use the clients from any shell:
.PP
\ \ \ trsh
.PP
give you a 'remote' shell.  You may need to type 'reset ^J' to reset
the tty of the new shell (that's Cntl-J).
.PP
\ \ \ trsh -s who
.PP
will run the who command 'remotely' to list the current users.
.PP
\ \ \ tupload -fvv <filename> ... /tmp
.PP
will copy the listed files into the /tmp directory and provide CPS statistics.
.PP
\ \ \ tredir 4000 23
.PP
will map port 4000 to 23 and put itself in the background.  Then, typing
.PP
\ \ \ telnet 0 4000
.PP
should give you a login prompt that works.
If you're running X, you should be able to use 
.IR txconn
to establish a new display (screen) that maps to the existing screen.
.PP
Be sure to run 
.IR ./termtest
on both the local and remote systems,
particularly if the systems use different architectures.
.SH BUGS
.SH SEE ALSO
.IR term (1),
.IR termrc (1),
.IR term_setup (1),
.IR term_clients (1),
.IR termtest (1),
.IR linecheck (1).
.SH AUTHOR
Michael O'Reilly, michael@iinet.com.au, original author
.br
Bill C. Riemers, bcr@physics.purdue.edu, current developer

