.TH TERM_SETUP 1
.SH NAME
linecheck, termtest \- debugging tools for term
B
.SH SYNOPSIS
.B linecheck 
[ escape ... ] < /dev/tty?? >/dev/tty??
.PP
.B termtest
[-1\ <program>] [-2\ <program>] [--local\ <option>]
[--remote\ <option>] [<options>]
.SH DESCRIPTION
You should perform two sets of tests before you ever try to run
.IR term
itself.
The
.IR linecheck
program performs a first-order test of the transparency of the link.
The
.IR termtest
program lets you 
exercise 
.IR term
and its clients locally by starting two
.IR term
daemons on the same system.
.SH SEE ALSO
.IR term (1),
.IR termrc (1),
.IR term_setup (1),
.IR term_clients (1),
.IR termtest (1),
.IR linecheck (1).
.SH AUTHOR
Michael O'Reilly, michael@iinet.com.au, original author
.br
Bill C. Riemers, bcr@physics.purdue.edu, current developer

