# Test the dg.exp driver.
# This is a testsuite tester tester.  As such we *want* to test things like
# expected failure handling.  But expected failures must continually be
# monitored and so in the normal case we create unnecessary work.  So only
# run these tests if DG_TEST is defined to "yes".

global DG_TEST
if { ![info exists DG_TEST] || "$DG_TEST" != "yes" } {
    return
}

# Load support procs.
load_lib gcc-dg.exp

# Initialize harness.
dg-init

# Main loop.
dg-runtest [lsort [glob -nocomplain $srcdir/$subdir/dg-*.c]] "" ""

# All done.
dg-finish
