.TH SNNTP 1 local "redistributable"
.DA 27 June 1994
.SH NAME
snntp, snntpsend \- transmit netnews via NNTP simply
.SH SYNOPSIS
.B snntp
[
.B \-v
]
site
.br
.B snntpsend
[
site ...
]
.SH DESCRIPTION
.I Snntp
sends articles
named on standard input
(in C News
.RB ` n '
format)
to internet
.I site
via the NNTP protocol.
Any input lines corresponding to articles that
cannot be sent are copied to standard output.
The
.B v
option causes
.I snntp
to chatter on standard error.
.PP
.I Snntpsend
is more commonly invoked;
it expects to find batch files for sites in
.B /usr/spool/nntp
and sends news to each named
.I site
.RB ( *.*
if none).
.SH FILES
/usr/spool/out.nntp	nntp batch files
.SH SEE ALSO
.IR newssys (5),
.IR relaynews (8),
.IR snntpd (8)
.br
Internet RFC 977 \- NNTP
.SH DIAGNOSTICS
.I Snntp
exits with status 0
in the normal case,
with batch entries for any unsent messages on standard output;
status 1
in the event that no articles were sent,
in which case standard output can be ignored;
any other status indicates a disastrous error.
.SH HISTORY
Written by Geoff Collyer
as a companion to
.IR snntpd (8).
.SH BUGS
NNTP is
.I not
the last word in news transmission protocols.
.PP
The silly CRLF convention used by NNTP is a nuisance.
